### ISSUE TITLE
MakRCNN implementation with multiple classes

### ISSUE THREAD

**Issue by aakashkodes** [matterport/Mask_RCNN#1006]
My json file looks like this.
{"Circle1.jpg36854":{"fileref":"","size":36854,"filename":"Circle1.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_{"Circle1.jpg36854":{"fileref":"","size":36854,"filename":"Circle1.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_poinx":[539,600,655,700,712,716,710,696,681,630,577,524,486,460,452,453,466,478,492,519,539],"all_points_y":[287,280,303,345,385,417,450,482,509,539,548,537,507,460,418,395,352,332,315,299,287]},"region_attributes":{"class_ids":"Circle"}}}},"Circle2.jpg36075":{"fileref":"","size":36075,"filename":"Circle2.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[485,528,557,594,625,699,734,733,725,697,636,571,532,497,469,449,442,442,460,485],"all_points_y":[308,280,273,270,276,318,394,423,462,512,554,560,550,530,506,473,432,368,337,308]},"region_attributes":{"class_ids":"Circle"}}}},"Circle3.jpg36206":{"fileref":"","size":36206,"filename":"Circle3.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[454,487,527,578,627,665,694,723,736,739,717,682,641,591,550,509,484,443,427,433,454],"all_points_y":[327,291,267,257,263,278,299,336,382,441,497,536,559,568,567,550,531,490,438,362,327]},"region_attributes":{"class_ids":"Circle"}}}},"Circle4.jpg36748":{"fileref":"","size":36748,"filename":"Circle4.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[444,472,508,554,588,617,652,700,733,754,747,727,688,628,562,490,447,417,414,432,444],"all_points_y":[322,285,266,249,248,247,256,290,328,396,460,506,549,577,582,557,513,457,391,339,322]},"region_attributes":{"class_ids":"Circle"}}}},"Circle5.jpg37021":{"fileref":"","size":37021,"filename":"Circle5.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[413,436,460,481,505,533,559,586,633,672,701,749,769,755,720,658,597,521,479,433,414,405,405,413],"all_points_y":[359,307,283,265,252,242,236,235,239,256,274,330,428,480,538,576,593,584,560,518,469,425,378,359]},"region_attributes":{"class_ids":"Circle"}}}},"Circle6.jpg37335":{"fileref":"","size":37335,"filename":"Circle6.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[450,504,567,632,688,736,776,775,756,698,640,585,514,452,418,394,388,415,439,450],"all_points_y":[277,237,222,229,247,290,374,456,513,571,598,608,596,561,521,458,394,318,288,277]},"region_attributes":{"class_ids":"Circle"}}}},"Circle7.jpg37619":{"fileref":"","size":37619,"filename":"Circle7.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[404,463,536,642,711,761,798,755,692,622,550,479,419,383,381,395,404],"all_points_y":[317,249,212,214,252,310,416,534,587,615,619,592,542,459,375,332,317]},"region_attributes":{"class_ids":"Circle"}}}},"Circle8.jpg37791":{"fileref":"","size":37791,"filename":"Circle8.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[389,417,440,470,525,590,648,741,790,800,792,732,686,619,555,475,430,399,375,369,377,389],"all_points_y":[320,278,254,231,206,199,208,249,348,402,494,571,604,626,628,604,567,525,471,415,347,320]},"region_attributes":{"class_ids":"Circle"}}}},"Circle9.jpg37931":{"fileref":"","size":37931,"filename":"Circle9.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[426,475,513,551,592,641,685,721,761,788,808,810,795,729,701,650,611,524,462,427,388,361,358,374,406,426],"all_points_y":[251,215,198,190,186,195,210,233,272,312,375,436,512,594,610,632,642,637,609,581,530,462,391,314,272,251]},"region_attributes":{"class_ids":"Circle"}}}},"Circle10.jpg38455":{"fileref":"","size":38455,"filename":"Circle10.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[378,408,433,464,494,539,608,660,717,791,827,815,775,690,602,522,427,357,344,356,378],"all_points_y":[295,253,230,210,195,179,177,189,211,290,387,486,566,630,653,650,605,501,408,338,295]},"region_attributes":{"class_ids":"Circle"}}}},"D2Rectangle1.jpg33355":{"fileref":"","size":33355,"filename":"D2Rectangle1.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[484,487,589,589,484],"all_points_y":[371,542,543,367,371]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[510,511,685,682,510],"all_points_y":[274,383,383,276,274]},"region_attributes":{"class_ids":"Rectangle"}}}},"D2Rectangle2.jpg33318":{"fileref":"","size":33318,"filename":"D2Rectangle2.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[481,479,593,592,481],"all_points_y":[369,557,558,369,369]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[504,506,690,689,504],"all_points_y":[267,385,383,267,267]},"region_attributes":{"class_ids":"Rectangle"}}}},"D2Rectangle3.jpg35098":{"fileref":"","size":35098,"filename":"D2Rectangle3.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[476,476,599,598,476],"all_points_y":[374,566,566,369,374]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[498,500,697,699,498],"all_points_y":[255,387,385,256,255]},"region_attributes":{"class_ids":"Rectangle"}}}},"D2Rectangle4.jpg34855":{"fileref":"","size":34855,"filename":"D2Rectangle4.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[469,469,604,604,469],"all_points_y":[371,582,582,366,371]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[492,493,704,706,492],"all_points_y":[242,385,385,241,242]},"region_attributes":{"class_ids":"Rectangle"}}}},"D2Rectangle5.jpg35080":{"fileref":"","size":35080,"filename":"D2Rectangle5.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[464,464,610,609,464],"all_points_y":[369,591,592,371,369]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[488,487,709,708,488],"all_points_y":[232,385,384,229,232]},"region_attributes":{"class_ids":"Rectangle"}}}},"D2Rectangle6.jpg35980":{"fileref":"","size":35980,"filename":"D2Rectangle6.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[455,456,619,618,455],"all_points_y":[369,609,606,367,369]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[479,480,716,714,479],"all_points_y":[221,384,382,218,221]},"region_attributes":{"class_ids":"Rectangle"}}}},"D2Rectangle7.jpg36202":{"fileref":"","size":36202,"filename":"D2Rectangle7.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[451,452,625,624,451],"all_points_y":[370,614,614,371,370]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[473,475,720,717,473],"all_points_y":[207,383,383,207,207]},"region_attributes":{"class_ids":"Rectangle"}}}},"D2Rectangle8.jpg36269":{"fileref":"","size":36269,"filename":"D2Rectangle8.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[444,445,638,635,444],"all_points_y":[374,630,629,366,374]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[465,468,730,729,465],"all_points_y":[194,390,387,195,194]},"region_attributes":{"class_ids":"Rectangle"}}}},"D2Rectangle9.jpg36416":{"fileref":"","size":36416,"filename":"D2Rectangle9.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[439,439,634,637,439],"all_points_y":[372,637,639,368,372]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[463,464,732,731,463],"all_points_y":[187,385,382,184,187]},"region_attributes":{"class_ids":"Rectangle"}}}},"DRectangle1.jpg34920":{"fileref":"","size":34920,"filename":"DRectangle1.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[429,429,637,635,429],"all_points_y":[407,520,517,400,407]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[622,626,742,742,622],"all_points_y":[309,500,501,306,309]},"region_attributes":{"class_ids":"Rectangle"}}}},"DRectangle2.jpg35769":{"fileref":"","size":35769,"filename":"DRectangle2.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[415,415,635,636,415],"all_points_y":[402,526,527,398,402]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[624,623,755,756,624],"all_points_y":[302,509,507,297,302]},"region_attributes":{"class_ids":"Rectangle"}}}},"DRectangle3.jpg35946":{"fileref":"","size":35946,"filename":"DRectangle3.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[400,398,637,636,400],"all_points_y":[401,535,535,395,401]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[628,630,771,770,628],"all_points_y":[292,518,519,286,292]},"region_attributes":{"class_ids":"Rectangle"}}}},"DRectangle4.jpg36317":{"fileref":"","size":36317,"filename":"DRectangle4.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[386,386,647,643,386],"all_points_y":[391,541,540,387,391]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[627,629,785,786,627],"all_points_y":[280,523,522,279,280]},"region_attributes":{"class_ids":"Rectangle"}}}},"DRectangle5.jpg36283":{"fileref":"","size":36283,"filename":"DRectangle5.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[374,375,642,641,374],"all_points_y":[392,549,549,389,392]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[629,631,800,797,629],"all_points_y":[272,535,532,272,272]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle1.jpg33807":{"fileref":"","size":33807,"filename":"Rectangle1.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[508,510,639,638,508],"all_points_y":[315,406,405,312,315]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle2.jpg34547":{"fileref":"","size":34547,"filename":"Rectangle2.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[499,499,650,648,499],"all_points_y":[305,420,418,301,305]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle3.jpg34210":{"fileref":"","size":34210,"filename":"Rectangle3.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[487,486,659,658,487],"all_points_y":[298,431,430,293,298]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle4.jpg34496":{"fileref":"","size":34496,"filename":"Rectangle4.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[478,477,676,672,478],"all_points_y":[288,443,440,283,288]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle5.jpg34201":{"fileref":"","size":34201,"filename":"Rectangle5.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[468,468,677,677,468],"all_points_y":[277,450,449,272,277]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle6.jpg35177":{"fileref":"","size":35177,"filename":"Rectangle6.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[459,461,688,687,459],"all_points_y":[264,457,459,261,264]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle30.jpg33247":{"fileref":"","size":33247,"filename":"Rectangle30.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[468,469,675,676,468],"all_points_y":[209,510,510,212,209]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle31.jpg33932":{"fileref":"","size":33932,"filename":"Rectangle31.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[464,464,683,684,464],"all_points_y":[208,513,514,209,208]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle32.jpg33456":{"fileref":"","size":33456,"filename":"Rectangle32.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[458,456,689,687,458],"all_points_y":[204,519,518,201,204]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle33.jpg34054":{"fileref":"","size":34054,"filename":"Rectangle33.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[450,449,694,693,450],"all_points_y":[198,522,524,197,198]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle34.jpg33632":{"fileref":"","size":33632,"filename":"Rectangle34.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[447,446,701,703,447],"all_points_y":[197,525,526,194,197]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle35.jpg34133":{"fileref":"","size":34133,"filename":"Rectangle35.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[439,440,709,706,439],"all_points_y":[189,529,528,188,189]},"region_attributes":{"class_ids":"Rectangle"}}}},"Rectangle36.jpg33902":{"fileref":"","size":33902,"filename":"Rectangle36.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[434,433,713,712,434],"all_points_y":[184,536,534,182,184]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircle1.jpg36599":{"fileref":"","size":36599,"filename":"RectangleCircle1.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[494,466,441,419,400,387,417,460,496,534,557,581,601,605,593,574,558,525,494],"all_points_y":[346,353,365,380,415,459,529,555,561,554,539,518,484,460,428,393,364,348,346]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[489,487,782,780,489],"all_points_y":[267,460,458,263,267]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircle2.jpg36706":{"fileref":"","size":36706,"filename":"RectangleCircle2.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[487,457,428,403,390,377,382,395,411,490,542,571,602,613,614,605,583,569,545,503,487],"all_points_y":[336,343,355,376,404,432,488,519,543,572,566,543,515,479,457,431,400,374,355,339,336]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[487,491,790,789,487],"all_points_y":[255,463,459,250,255]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircle3.jpg37551":{"fileref":"","size":37551,"filename":"RectangleCircle3.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[487,442,407,372,368,384,402,422,458,491,544,580,608,619,618,616,604,589,538,516,487],"all_points_y":[326,337,361,407,478,518,541,559,574,577,574,549,514,481,453,440,411,384,341,328,326]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[484,485,805,804,484],"all_points_y":[247,464,464,243,247]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircle4.jpg37814":{"fileref":"","size":37814,"filename":"RectangleCircle4.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[482,418,390,369,358,357,393,439,474,549,581,628,627,603,583,556,531,498,477,482],"all_points_y":[320,342,363,397,440,495,552,577,592,579,556,493,452,397,373,351,334,321,319,320]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[482,487,814,812,482],"all_points_y":[241,458,459,241,241]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircle5.jpg37836":{"fileref":"","size":37836,"filename":"RectangleCircle5.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[486,453,407,390,358,343,353,389,486,543,582,620,631,632,617,607,585,564,546,501,486],"all_points_y":[311,318,337,351,391,441,509,568,606,590,563,521,479,447,412,392,369,346,331,313,311]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[483,484,825,826,483],"all_points_y":[227,458,459,230,227]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircle6.jpg38168":{"fileref":"","size":38168,"filename":"RectangleCircle6.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[479,429,394,369,342,334,337,384,484,568,602,627,636,637,621,592,568,530,493,479],"all_points_y":[303,314,331,358,398,443,514,578,615,586,557,514,478,452,412,374,344,321,306,303]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[479,481,836,836,479],"all_points_y":[216,466,463,221,216]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircleCenter1.jpg38298":{"fileref":"","size":38298,"filename":"RectangleCircleCenter1.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[401,402,772,768,401],"all_points_y":[289,544,544,289,289]},"region_attributes":{"class_ids":"Rectangle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[543,514,503,502,520,537,572,624,665,672,627,574,543],"all_points_y":[337,366,393,435,467,484,498,492,456,378,333,325,337]},"region_attributes":{"class_ids":"Circle"}}}},"RectangleCircleCenter2.jpg37762":{"fileref":"","size":37762,"filename":"RectangleCircleCenter2.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[553,515,506,504,524,538,566,593,642,663,670,678,666,628,585,548,553],"all_points_y":[331,360,391,435,469,481,493,498,483,455,440,410,360,326,317,335,331]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[397,399,772,774,397],"all_points_y":[282,542,540,281,282]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircleCenter3.jpg38358":{"fileref":"","size":38358,"filename":"RectangleCircleCenter3.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[532,507,503,539,603,655,683,675,621,560,532],"all_points_y":[336,382,436,484,499,477,427,359,315,320,336]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[395,396,773,773,395],"all_points_y":[283,544,545,279,283]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircleCenter4.jpg37947":{"fileref":"","size":37947,"filename":"RectangleCircleCenter4.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[560,519,510,505,516,534,557,584,633,656,679,690,668,640,604,560],"all_points_y":[316,353,378,416,449,470,485,494,486,472,444,390,341,324,310,316]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[391,392,779,779,391],"all_points_y":[275,550,548,275,275]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircleCenter5.jpg38447":{"fileref":"","size":38447,"filename":"RectangleCircleCenter5.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[590,546,515,504,509,518,556,601,630,673,686,698,678,664,623,590],"all_points_y":[307,318,356,393,421,455,483,492,492,462,432,391,346,323,310,307]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[386,387,785,784,386],"all_points_y":[269,555,553,267,269]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircleCenter6.jpg37823":{"fileref":"","size":37823,"filename":"RectangleCircleCenter6.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[562,532,513,506,512,534,569,614,641,664,682,695,696,669,627,597,562],"all_points_y":[307,329,360,388,436,466,486,491,482,464,446,417,362,319,299,299,307]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[384,385,789,788,384],"all_points_y":[266,558,556,265,266]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircleCenter14.jpg40658":{"fileref":"","size":40658,"filename":"RectangleCircleCenter14.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[491,464,451,457,475,511,553,633,688,766,809,804,792,763,717,653,607,561,515,491],"all_points_y":[275,325,373,430,489,530,555,571,560,513,431,363,309,270,231,214,214,225,250,275]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[357,358,813,810,357],"all_points_y":[263,616,612,260,263]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircleCenter15.jpg40470":{"fileref":"","size":40470,"filename":"RectangleCircleCenter15.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[527,480,456,445,454,486,539,604,655,696,741,795,820,800,770,736,691,628,563,527],"all_points_y":[237,282,333,378,455,512,555,573,575,564,545,484,398,321,270,239,215,205,216,237]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[353,355,815,811,353],"all_points_y":[261,624,624,266,261]},"region_attributes":{"class_ids":"Rectangle"}}}},"RectangleCircleCenter16.jpg40433":{"fileref":"","size":40433,"filename":"RectangleCircleCenter16.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"polygon","all_points_x":[469,444,440,455,483,562,609,639,685,728,766,821,824,803,762,716,671,632,565,489,469],"all_points_y":[286,349,418,471,519,572,580,583,580,559,531,444,381,305,238,210,199,194,202,251,286]},"region_attributes":{"class_ids":"Circle"}},"1":{"shape_attributes":{"name":"polygon","all_points_x":[345,346,821,817,345],"all_points_y":[261,628,626,258,261]},"region_attributes":{"class_ids":"Rectangle"}}}}}

My load function and load mask are as follows.

class BalloonDataset(utils.Dataset):

    def load_balloon(self, dataset_dir, subset):
        """Load a subset of the Balloon dataset.
        dataset_dir: Root directory of the dataset.
        subset: Subset to load: train or val
        """
        # Add classes. We have only one class to add.
        self.add_class("balloon", 1, "Circle")
        self.add_class("balloon", 2, "Rectangle")

        # Train or validation dataset?
        assert subset in ["train", "val"]
        dataset_dir = os.path.join(dataset_dir, subset)

        # Load annotations
        # VGG Image Annotator saves each image in the form:
        # { 'filename': '28503151_5b5b7ec140_b.jpg',
        #   'regions': {
        #       '0': {
        #           'region_attributes': {},
        #           'shape_attributes': {
        #               'all_points_x': [...],
        #               'all_points_y': [...],
        #               'name': 'polygon'}},
        #       ... more regions ...
        #   },
        #   'size': 100202
        # }
        # We mostly care about the x and y coordinates of each region
        annotations = json.load(open(os.path.join(dataset_dir, "via_region_data.json")))
        annotations = list(annotations.values())  # don't need the dict keys

        # The VIA tool saves images in the JSON even if they don't have any
        # annotations. Skip unannotated images.
        annotations = [a for a in annotations if a['regions']]

        # Add images
        for a in annotations:
            # Get the x, y coordinaets of points of the polygons that make up
            # the outline of each object instance. There are stores in the
            # shape_attributes (see json format above)
            polygons = [r['shape_attributes'] for r in a['regions'].values()]
            objects = [s['region_attributes'] for s in a['regions'].values()]
            print(objects)
            
            num_ids = [int(n['class_ids']) for n in objects]  
            
            # load_mask() needs the image size to convert polygons to masks.
            # Unfortunately, VIA doesn't include it in JSON, so we must read
            # the image. This is only managable since the dataset is tiny.
            image_path = os.path.join(dataset_dir, a['filename'])
            image = skimage.io.imread(image_path)
            height, width = image.shape[:2]

            self.add_image(
                "balloon",
                image_id=a['filename'],  # use file name as a unique image id
                path=image_path,
                width=width, height=height,
                polygons=polygons,
                num_ids=num_ids)

    def load_mask(self, image_id):
        """Generate instance masks for an image.
       Returns:
        masks: A bool array of shape [height, width, instance count] with
            one mask per instance.
        class_ids: a 1D array of class IDs of the instance masks.
        """
        # If not a balloon dataset image, delegate to parent class.
        info = self.image_info[image_id]
        if info["source"] != "balloon":
            return super(self.__class__, self).load_mask(image_id)
        num_ids = info['num_ids']
        # Convert polygons to a bitmap mask of shape
        # [height, width, instance_count]
        
        mask = np.zeros([info["height"], info["width"], len(info["polygons"])],
                        dtype=np.uint8)
        for i, p in enumerate(info["polygons"]):
            # Get indexes of pixels inside the polygon and set them to 1
            rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
            mask[rr, cc, i] = 1

        # Return mask, and array of class IDs of each instance. Since we have
        # one class ID only, we return an array of 1s
        num_ids = np.array(num_ids, dtype=np.int32)
        return mask, num_ids

    def image_reference(self, image_id):
        """Return the path of the image."""
        info = self.image_info[image_id]
        if info["source"] == "balloon":
            return info["path"]
        else:
            super(self.__class__, self).image_reference(image_id)

Error message:
Loading weights  C:\Windows\System32\Mask_RCNN\mask_rcnn_coco.h5
2018-10-04 15:59:41.117001: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-10-04 15:59:41.373850: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.392
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.29GiB
2018-10-04 15:59:41.381220: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
[{'class_ids': 'Circle'}]
Traceback (most recent call last):
  File "balloon.py", line 366, in <module>
    train(model)
  File "balloon.py", line 185, in train
    dataset_train.load_balloon(args.dataset, "train")
  File "balloon.py", line 128, in load_balloon
    num_ids = [int(n['class_ids']) for n in objects]
  File "balloon.py", line 128, in <listcomp>
    num_ids = [int(n['class_ids']) for n in objects]
ValueError: invalid literal for int() with base 10: 'Circle'

I am new to MaskRCNN. How do i solve this?

**Comment by aakashkodes** [comment]
@waspinator Can you please help look into this?

**Comment by aakashkodes** [comment]
@AliceDinh. Hi . I tried the code that you had mentioned.
But i am running into an error.
Can you please look into it.
I have two classes named Circle and Rectangle.
It loos like this
![image](https://user-images.githubusercontent.com/41433168/46483884-f4579f00-c7f8-11e8-893b-90a4ad20b9a2.png)
My json file is mentioned in the question.
Can you tell me where I went wrong?

**Comment by aakashkodes** [comment]
Hi @AliceDinh  Thanks for your reply. I corrected it.
But still getting the same error.
I have made a presentation about the error. Please have a look at it and help me to solve this error.
[MaskRCNN.pptx](https://github.com/matterport/Mask_RCNN/files/2453079/MaskRCNN.pptx)

**Comment by acv-anvt** [comment]
Sorry @aakashkodes, please don't use anythings related to  "new to MaskRCNN". Please take a look how to train your own data.
In your error, 100% it make from you missing label for one object or wrong value of label. It just python code.

**Comment by aakashkodes** [comment]
@acv-anvt  maybe I should have put it this way. I am very new to machine learning and programming. I am a design engineer with no prior experience in python and very little experience in programming. 
So, if you cant help to solve it. No issues.
So please dont try to put down others by saying its just python code.

**Comment by Akash481** [comment]
Well, the error is because of adding class in VGG. In my case, while annotation I used class name in place of the class number. Remove the class name and replace it with a class number. In your case replace rectangle with 1 and circle with 2 while annotating in VGG.
I hope it helps!
