### ISSUE TITLE
How to set mask color?

### ISSUE THREAD

**Issue by monjurulkarim** [matterport/Mask_RCNN#1012]
Hi,
How can I set different color for different class? For example, I want all the cars to have same color, and all lamposts have same color but different from cars color.

**Comment by fastlater** [comment]
Next time, check old issues before open a new one. It was discussed before in #895

**Comment by 404hasbeenfound** [comment]
excuse me, I cannot find the method to run my video, do you know how to run my video in this code? Thanks!

**Comment by monjurulkarim** [comment]
In the 'visualize.py' file find the mask block and add the following code:
        # Mask
        mask = masks[:, :, i]
        if show_mask:
            if label == 'classname1':
                masked_image = apply_mask(masked_image,mask, [1.0, 0.0, 0.5454545454545459],alpha=0.5)
            elif label == 'classname2':
                masked_image = apply_mask(masked_image,mask, [1.0, 0.5454545454545454, 0.0],alpha=0.5)
=====================================================
