### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by 123liluky** [matterport/Mask_RCNN#102]
When I train net on 35kval images, StopIteration happens in the 295th step  of 6th epcho, like below.
295/1000 [=======>......................] - ETA: 11:56 - loss: 1.3895 - rpn_class_loss: 0.0333 - 
rpn_bbox_loss: 0.5186 - mrcnn_class_loss: 0.3381 - mrcnn_bbox_loss: 0.2326 - mrcnn_mask_loss: 0.2669
Traceback (most recent call last):
File "coco.py", line 397, in <module>  layers='heads')
File "D:\work\code\matterportMask_RCNN\Mask_RCNN-master\model.py", line 2183,in train
  **fit_kwargs
File "G:\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
  return func(*args, **kwargs)
File "G:\Anaconda3\lib\site-packages\keras\engine\training.py", line 2083, in fit_generator
  generator_output = next(output_generator)
StopIteration
I can't figur out what happened, can you help me? Changes I made in config.py BATCH_SIZE=1,IMAGE_MAX_DIM=512,IMAGE_MIN_DIM=400.

**Comment by waleedka** [comment]
I see a `StopIteration` error being raise. That seems to indicate that the data generator is failing for some reason. Maybe you have images missing in your dataset, or any other issue loading the data. 

Use the `inspect_data` notebook and verify that the data generator loads images correctly. Specifically, there is a block of commented out code that calls next() on the data generator repeatedly a lot of times to verify it's working. Try to run it on the entire dataset and verify that all images can be loaded successfully. 

Also, make sure you get the latest version of the code from github.

**Comment by 123liluky** [comment]
I have several other questions: 
1. When I try to train on 35k val images, I just remove “dataset_train.load_coco(args.dataset, "train")” in coco.py. Must I do some other changes?
2. When I set IMAGE_MAX_DIM=512,IMAGE_MIN_DIM=400 in config.py, I also set RPN_ANCHOR_SCALES = (16, 32, 64, 128, 256). Are there other parameters closely related to INPUT IMAGE SIZE?
Thank you!

**Comment by waleedka** [comment]
Yes. That's the mean pixel for the COCO dataset.

**Comment by jmtatsch** [comment]
@123liluky @waleedka those are the imagenet means not the coco means

**Comment by 123liluky** [comment]
@jmtatsch Thank you! If those means imagenet means, I needn't change them when training on my own gray medical images, right?

**Comment by jmtatsch** [comment]
@123liluky Transferring learned weights from color to gray is nontrivial. Nevertheless using (a slice of) the color weights for initialization is probably better than random initialization.

If you start training with imagenet weights, remember those are most useful if the input data is as similiar to the data the initial model was trained with. In the imagenet case the data is often demeaned by substracting [123.7, 116.8, 103.9] and sometimes rescaled with the standard deviation. Make sure your gray images are also at least zero mean.

**Comment by waleedka** [comment]
@jmtatsch You're right, they're the Imagenet mean. Corrected. Thanks!
