### ISSUE TITLE
Dataset Requirements

### ISSUE THREAD

**Issue by rbrth** [matterport/Mask_RCNN#103]
Hello,

I would like to try this great implementation out on my own dataset and was wondering what the requirements for such a set are.

My set contains only a per-pixel class segmentation as ground truth, hence not instance bounding boxes or instance segmentations.

Would this mask-rcnn implementation be able to cope? 

Best,
Ruud

**Comment by zhang-qiang-github** [comment]
refer to: https://github.com/matterport/Mask_RCNN/issues/54

**Comment by rbrth** [comment]
@zhang-qiang-github Thank you for the link. Indeed I also found that one, but it remains unclear whether the masks should be instances as well, or that you can also use one mask per class per image. 

For example, as can be seen here: https://imgur.com/a/qliNT

**Comment by zhang-qiang-github** [comment]
Actually, I also want to know whether the training label must be the per-pixel segmentation result?

I have some object detection results (one rectangle for one object). I also want to whether I can use those label to train mask rcnn. I am also waiting the answer.

Qiang

**Comment by waleedka** [comment]
@rbrth Good question. I think what you're describing is semantic segmentation (as opposed to instance segmentation). You try to distinguish between classes but don't care to distinguish between instances of the same class. There are different types of models specifically designed for semantic segmentation, and my guess is that they might work better for that purpose. I think this model would work as well, but might not give you the best accuracy compared to a semantic segmentation model.

@zhang-qiang-github I think Issue https://github.com/matterport/Mask_RCNN/issues/110 answers your question. In short, you can create fake rectangular masks. And, also, I am planning to work on an update that makes it easier to train with bounding boxes only.

**Comment by paulcx** [comment]
@waleedka Do you mean for example training own dataset with coordinates rather than mask annotation? It is easy to gather or annotate the image with bounding boxes I guess.

**Comment by waleedka** [comment]
@paulcx Yes, I'm hoping to find time to add an option to skip the mask branch if it's not needed. That would be useful in cases where you only care to find the bounding box of an object and don't really need pixel-level masks.

**Comment by bkvie** [comment]
@waleedka  Why not just use faster r-cnn then?

**Comment by waleedka** [comment]
@bkvie You can use Faster RCNN if you don't need masks. And that's what I suggested in Issue #110 that I linked above.

**Comment by sunbin1205** [comment]
@waleedka This question has been bothering me for a long time. I hope to get your reply!
I need to make a building dataset, and in order to be accurate, my dataset must be marked with segmentation. But now I don't know exactly how to reorganize the dataset, especially the tag file? I see other people asking questions that mention modifying a function, but I still don't understand. Can you give me a detailed steps? Including the exact location of the function that needs to be modified? Looking forward to your reply!

**Comment by vesapupovci** [comment]
@waleedka Is it possible to only use the mask branch of Mask-RCNN? I don't need to generate bounding boxes, labels or confidence scores. I only need the masks.
