### ISSUE TITLE
how to use two graphics card for inference? i had try  many methods...

### ISSUE THREAD

**Issue by jesen8** [matterport/Mask_RCNN#1030]
First, i try to modify this 

![image](https://user-images.githubusercontent.com/33971685/46999757-25b95e80-d159-11e8-875e-38d9789f5351.png)

then, i commented this line of code

![image](https://user-images.githubusercontent.com/33971685/46999839-63b68280-d159-11e8-94f3-782f7cdb8e16.png)

so,modify this code 
![image](https://user-images.githubusercontent.com/33971685/46999884-80eb5100-d159-11e8-9cdd-7e404367563f.png)

last 
![image](https://user-images.githubusercontent.com/33971685/46999917-99f40200-d159-11e8-9383-78c688d83b7c.png)

but ,then i run this detect code ,the error occurred 

![image](https://user-images.githubusercontent.com/33971685/47000664-51d5df00-d15b-11e8-97dd-d18f115c0834.png)

the error occurred in this code

![image](https://user-images.githubusercontent.com/33971685/47000175-47671580-d15a-11e8-8f21-034fdd3f6cbb.png)

when i try to use some other method ,also failed, i need your help please ,thanks very mach

**Comment by jesen8** [comment]
@waleedka Hi,waleedka, i need your help ,thanks very much

**Comment by dcyoung** [comment]
See #958 
You might be using an incompatible version of keras. Alternatively you may be able to modify the parallel model class to avoid changing dependencies.

**Comment by Ujang24** [comment]
You can try to use something like this. This is when you have 2 GPU installed. 
`CUDA_VISIBLE_DEVICES=0,1 python3 balloon.py ... ... ... ...`

**Comment by jesen8** [comment]
> 
> 
> You can try to use something like this. This is when you have 2 GPU installed.
> `CUDA_VISIBLE_DEVICES=0,1 python3 balloon.py ... ... ... ...`

oh,i'm sorry for you ,please give me more detail tutorials,thanks.

**Comment by keineahnung2345** [comment]
Try reinstalling your keras version to 2.1.3. Take a look of this issue: https://github.com/matterport/Mask_RCNN/issues/958.
