### ISSUE TITLE
Tensorboard losses ALWAYS start from same point, even after loading last weights

### ISSUE THREAD

**Issue by Everac** [matterport/Mask_RCNN#1031]
Hello, 

I've trained the model multiple times on my own image dataset.

The first time I trained it from scratch. Next, I stopped the model and then I trained it again using the last trained weights (I used the method find_last from the class MaskRCNN). 
After that, I have stopped the training and restarted multiple times, always using the last trained weights. 

I displayed all event files I obtained in Tensorboard. What called my attention was the fact that all loss curves start from the same point.

Intuitively, I'd expect the curves to start at different points because each curve calculates the initial loss with with the (optimized) weights from the preceding training. So normally I would expect to see that each new curve starts in a lower lever that the previous one.

Clearly this is not happening.

Could anyone explain me why is that?

By the way, I use SGD optimizer and I have a batch size of 1 image. 

![losses](https://user-images.githubusercontent.com/20886563/47015383-19c79f80-d14d-11e8-9454-a351b28065cb.png)

**Comment by fastlater** [comment]
I had a similar problem before. Sometimes I restarted my training and training starting point came back to epoch 0. What I did was to type the exact name of the weights I want to start with.
python nucleus.py train --dataset=./datasets/nucleus --subset=train --weights=./logs/nucleus20181016T0000/mask_rcnn_nucleus_XXXX.h5

Before I was using last but since I started to type the path by myself, training continue where it should be.

**Comment by Everac** [comment]
Solved it! Thanks!

**Comment by ash1995** [comment]
I'm facing the same problem despite specifying the full path of the weights I want to start with.
`python3 sate.py train --dataset=/datasets/satellite --model=/logs/sate20190124T1353/mask_rcnn_sate_0039.h5`

I initially ran the training process till the 70th epoch but restarted from epoch 39.

![tb](https://user-images.githubusercontent.com/32295036/51799885-8835f680-2240-11e9-801a-4b8eb27237a6.png)

Would you happen to know how to resolve this?
