### ISSUE TITLE
On Paperspace, the kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by ryohei1540** [matterport/Mask_RCNN#1042]
I got an error message "The kernel appears to have died. It will restart automatically" on Paperspace, when I ran the first cell of "demo.ipynb".

This message would appear when "from mrcnn import utils" is called.

I will really appreciate it if you could tell me how to address this problem.

**Comment by keineahnung2345** [comment]
What version of tensorflow do you use? Maybe changing to TF1.9 will solve the problem.
