### ISSUE TITLE
 Predict problem on multi gpu (Input to reshape is a tensor with 24000 values, but the requested has 48000)

### ISSUE THREAD

**Issue by kawa23** [matterport/Mask_RCNN#1044]
I try to  predict with  GPU_COUNT = 2, but got the issue:

<img width="1120" alt="screen shot 2018-10-20 at 8 38 15 pm" src="https://user-images.githubusercontent.com/39022504/47255773-9093ce00-d4a8-11e8-95a8-6a7f475f2a28.png">

`keras.__version__ = 2.1.5`  and  `tf.__version__=1.7.0`  and my config was:

```
config.BATCH_SIZE = 4
config.IMAGES_PER_GPU = 2
config.GPU_COUNT = 2 
```

And it worked fine with single gpu like that:

```
config.BATCH_SIZE = 2
config.IMAGES_PER_GPU = 2
config.GPU_COUNT = 1 
```

**Comment by Tachyu** [comment]
same problem :(

**Comment by kawa23** [comment]
> same problem :(

I  thought it cause by `DetectionLayer output reshape` , 

see here:
[https://github.com/matterport/Mask_RCNN/pull/1082](url)

hope this solve your problem
