### ISSUE TITLE
import pycocotools._mask as _mask  has some  problem

### ISSUE THREAD

**Issue by WManYang** [matterport/Mask_RCNN#105]
Thank you for your generous work on implementing Mask R-CNN.
when I run
 # Train a new model starting from pre-trained COCO weights
    python3 coco.py train --dataset=/path/to/coco/ --model=coco
there is something wrong look like this: 
Traceback (most recent call last):
  File "coco.py", line 40, in <module>
    from pycocotools.coco import COCO
  File "/mnt/Mask_RCNN-master/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/mnt/Mask_RCNN-master/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: dynamic module does not define init function (PyInit__mask)

thank you very much.

**Comment by waleedka** [comment]
This seems like an issue in pycocotools. Maybe try removing it and installing it again. Verify that you installed it for Python3 (their default is Python2.7) and verify that you have Cython installed.

**Comment by WManYang** [comment]
thank you very much! According to your suggestion,this problem is solved now.
