### ISSUE TITLE
Want to train for Linemod dataset with masks in png format, any instructions?

### ISSUE THREAD

**Issue by zq1995012** [matterport/Mask_RCNN#1055]
The Linemod dataset has mask (binary images) images available but no bounding boxes or corresponding JSON file. I want to train the Mask RCNN on it but not sure how to properly modify the dataset. Is there any instruction to do this?

Any help is appreciated.

**Comment by fastlater** [comment]
@zq1995012  If you have the masks (1 instance per mask image better) and the raw image, you can train the model using a load mask function similar to the function used to load the nucleus dataset.

**Comment by zq1995012** [comment]
Thanks, mate!

**Comment by vijaysamula** [comment]
@zq1995012 Hi, I am also using Linemod dataset and I too have the same problem with MASK RCNN. Can you please share your code or the way you have changed the code to use .png mask.
