### ISSUE TITLE
In config.py, the value of STEPS_PER_EPOCH cannot be modified.

### ISSUE THREAD

**Issue by linquanxu** [matterport/Mask_RCNN#1068]
hi，matterport.
When i train a model with coco.py, i want to modify STEPS_PER_EPOCH=100, IMAGE_MAX_DIM=800 in config.py. However, these values have not changed. 
BTW, print() in model.py can't print the log.

The command is as follows:
python3 coco.py --dataset=/home/xulinquan/data/other_data/coco/ --logs=../../logs train --year=2017 --model=../../mask_rcnn_coco_0149.h5

the logs:
![qq 20181025175131](https://user-images.githubusercontent.com/16631303/47492052-bb05d280-d87e-11e8-923b-a0d230b3523d.png)

how to fix it?

**Comment by Ujang24** [comment]
Open coco.py in your editor. 
You will see these line of code:
```
class CocoConfig(Config):
    """Configuration for training on MS COCO.
    Derives from the base Config class and overrides values specific
    to the COCO dataset.
    """
    # Give the configuration a recognizable name
    NAME = "coco"

    # We use a GPU with 12GB memory, which can fit two images.
    # Adjust down if you use a smaller GPU.
    IMAGES_PER_GPU = 2

    # Uncomment to train on 8 GPUs (default is 1)
    # GPU_COUNT = 8

    # Number of classes (including background)
    NUM_CLASSES = 1 + 80  # COCO has 80 classes
```
Add these lines:

```
# Number of training steps per epoch
    STEPS_PER_EPOCH = 20  #Change the number as you want
```

**Comment by linquanxu** [comment]
Thank you, I have fixed this issue.

**Comment by linquanxu** [comment]
@Ujang24 I didn't run 'python3 setup.py install' when model.py was modified.
