### ISSUE TITLE
Can we train the network using a large batch size on single GPU?

### ISSUE THREAD

**Issue by tangjiuqi097** [matterport/Mask_RCNN#1069]
For the limit of GPU, I can only train the network using a small batch size. And because of it, I get lower performance. 

So, can we train the network using a large batch size on single GPU?

For example, if our GPU can only handle only one image, can we accumulate the gradients for 16 steps and then update the trainable parameters, so as to equivalent to the batch size of 16?

I am not sure if it is reasonable, and I do not know how to implement it. Can you give me some helps?

**Comment by rangermbh** [comment]
A 12GB GPU can typically handle 2 images of 1024x1024px, so the batch_size is set to 2. If you use a smaller image(eg. 256*256*3 ), you should use the highest number that your GPU can handle for best performance.
