### ISSUE TITLE
IMAGE_SHAPE: How to set the MIN and MAX image dimensions?

### ISSUE THREAD

**Issue by Everac** [matterport/Mask_RCNN#1077]
Hi everyone, 
I would appreciate if you could help me with my problem:

I have a dataset of 1280*800 images. Currently, I trained the model without modifying the IMAGE_MIN_DIM and the IMAGE_MAX_DIM parameters from the basic config.py script, so basically :

        - My original images have dimensions:
                                  -- MIN_SIZE_ORIGINAL_DIM: 800
                                  -- MAX_SIZE_ORIGINAL_DIM: 1280
        
       - Mask R-CNN used the model parameters: 
                                 -- IMAGE_MIN_DIM = 800
                                 -- IMAGE_MAX_DIM = 1024

After the training, I tested my weights in inference mode and I could not get masks and images in their original size. Instead, I got 1024*1024 images with zero-padding at the highest and lowest sides of the images. I understand this is normal since Mask R-CNN uses square images (from what I understood from the paper). 

I have two questions: 

1.- In inference mode, is there a way to obtain images, masks and bboxes in its original 1280*800 size ?  
 
and

2.-  Should I retrain the model, but modifying the config.py parameters to the original dimensions of my images?   
                                                                        -- IMAGE_MIN_DIM = 800
                                                                        -- IMAGE_MAX_DIM = 1280

Thank you in advance for your time.

**Comment by harshgrovr** [comment]
@Everac where do we set size if inference image?

**Comment by luna9722** [comment]
hello @Everac, please if you figured out the answer, can you please enlighten me ?

**Comment by uknwho** [comment]
hi all, would really appreciate the answer to this question. Thanks in advance
