### ISSUE TITLE
Project on object's relative location detection

### ISSUE THREAD

**Issue by monjurulkarim** [matterport/Mask_RCNN#1079]
I am trying to detect whether an object is in its right location or not?
For example, there is a table in an image and a pen on the table. I want to detect whether the pen is on the table or not?
May be I have to check whether the bounding box of pen is inside the bounding box of table or not.
Can anyone help, how can I do this?

**Comment by fastlater** [comment]
Get the outputs of mask rcnn, understand their meaning and write your logic in the post inference part.

**Comment by fastlater** [comment]
@monjurulkarim check the sample codes and the visualize.py script
