### ISSUE TITLE
Follows nucleus style to train, but keep getting error in resize mask function from utils.py

### ISSUE THREAD

**Issue by zq1995012** [matterport/Mask_RCNN#1083]
I have a dataset that has original images and masks, so I followed the nucleus sample style to write my own train script. Both original images and masks have the shape of [480,640,3]. When I start training, it keeps reporting error:
`ERROR:root:Error processing image {'id': '000895.jpg', 'source': 'ape', 'path': 'S:\\project\\LINEMOD\\ape\\JPEGImages\\000895.jpg', 'width': 640, 'height': 480}
Traceback (most recent call last):
  File "S:\anaconda\envs\research\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "S:\anaconda\envs\research\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1220, in load_image_gt
    mask = utils.resize_mask(mask, scale, padding, crop)
  File "S:\anaconda\envs\research\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\utils.py", line 506, in resize_mask
    mask = scipy.ndimage.zoom(mask, zoom=[scale, scale, 1], order=0)
  File "S:\anaconda\envs\research\lib\site-packages\scipy\ndimage\interpolation.py", line 573, in zoom
    zoom = _ni_support._normalize_sequence(zoom, input.ndim)
  File "S:\anaconda\envs\research\lib\site-packages\scipy\ndimage\_ni_support.py", line 65, in _normalize_sequence
    raise RuntimeError(err)
RuntimeError: sequence argument must have length equal to input rank
image_id is this: 000598.jpg
mask_dir is this: S:\project\LINEMOD\ape\mask
masks has 1 items
mask's shape is (480, 640, 3, 1)
ERROR:root:Error processing image {'id': '000598.jpg', 'source': 'ape', 'path': 'S:\\project\\LINEMOD\\ape\\JPEGImages\\000598.jpg', 'width': 640, 'height': 480}
Traceback (most recent call last):
  File "S:\anaconda\envs\research\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "S:\anaconda\envs\research\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1220, in load_image_gt
    mask = utils.resize_mask(mask, scale, padding, crop)
  File "S:\anaconda\envs\research\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\utils.py", line 506, in resize_mask
    mask = scipy.ndimage.zoom(mask, zoom=[scale, scale, 1], order=0)
  File "S:\anaconda\envs\research\lib\site-packages\scipy\ndimage\interpolation.py", line 573, in zoom
    zoom = _ni_support._normalize_sequence(zoom, input.ndim)
  File "S:\anaconda\envs\research\lib\site-packages\scipy\ndimage\_ni_support.py", line 65, in _normalize_sequence`

And here is my dataset code. 
`class ApeDataset(utils.Dataset):

    def load_ape(self, dataset_dir, subset):
        """Load a subset of the Balloon dataset.
        dataset_dir: Root directory of the dataset.
        subset: Subset to load: train or val
        """
        # Add classes. We have only one class to add.
        self.add_class("ape", 1, "ape")

        # Train or validation dataset?
        assert subset in ["train", "val"]
        if subset == "train":
            file = "train.txt"
        else:
            file = "test.txt"
        file_path = os.path.join(dataset_dir, file)
        image_ids = []
        with open(file_path, 'r') as f:
            for line in f.readlines():
                temp = line.split("/")
                image_ids.append(temp[3].strip())
        image_dir = "JPEGImages"
        dataset_dir = os.path.join(dataset_dir, image_dir)
        

       # Add images
        for image_id in image_ids:
            image_path = os.path.join(dataset_dir, image_id)
            image = skimage.io.imread(image_path)
            height, width = image.shape[:2]
            print("images shape is :{}".format(image.shape))
            self.add_image(
                "ape",
                image_id=image_id,
                path=image_path,
                width=width, height=height)
     

    def load_mask(self, image_id):
        """Generate instance masks for an image.
       Returns:
        masks: A bool array of shape [height, width, instance count] with
            one mask per instance.
        class_ids: a 1D array of class IDs of the instance masks.
        """
        # If not a balloon dataset image, delegate to parent class.
        info = self.image_info[image_id]
        # Get mask directory from image path
        mask_dir = os.path.join(os.path.dirname(os.path.dirname(info['path'])), "mask")
        # print("image_id is this: {}".format(info['id']))
        # print("mask_dir is this: {}".format(mask_dir))
        # Read mask files from .png image
        mask = []
        for f in next(os.walk(mask_dir))[2]:
            if f.endswith(".png"):
                file_name_temp = f.split(".")
                file_name_temp = file_name_temp[0]
                file_name_temp = file_name_temp+".jpg"
                # print("file_name_temp is this: {}".format(file_name_temp))
                if file_name_temp == info['id'][2:]:
                    m = skimage.io.imread(os.path.join(mask_dir, f)).astype(np.bool)
                    mask.append(m)
        # print("masks has {} items".format(len(mask)))
        mask = np.stack(mask, axis=-1)
        # print("mask's shape is {}".format(mask.shape))

        # Return mask, and array of class IDs of each instance. Since we have
        # one class ID, we return an array of ones
        return mask, np.ones([mask.shape[-1]], dtype=np.int32)

    def image_reference(self, image_id):
        """Return the path of the image."""
        info = self.image_info[image_id]
        if info["source"] == "ape":
            return info["path"]
        else:
            super(self.__class__, self).image_reference(image_id)`
Any help is aprreciated.

**Comment by zq1995012** [comment]
Found the problem is the shape of mask.

**Comment by koukouzasg** [comment]
Could you be more specific on what was the problem with the shape of mash and what you changed in order to make it work again? @zq1995012

**Comment by ChaoLi977** [comment]
I met the same problem and I change the channel number of mask file from 3 to 1, it works. 
So I think the "shape of mask" means  the channel number of mask.
