### ISSUE TITLE
How do I get the mean pixel?

### ISSUE THREAD

**Issue by simhue** [matterport/Mask_RCNN#1090]
It's unclear to me how to get the mean pixel. Do I have to iterate over every image in my training/validation set to calculate the mean pixel?

**Comment by fastlater** [comment]
Yes, you should iterate over every image. However, the improvement using the mean is not guaranteed. At least, based on my own experience using mask rcnn.

**Comment by simhue** [comment]
Alright, thanks for the answer.

**Comment by Altimis** [comment]
Hey guys, I have a question please. Do we need to change the default value of MEAN_PIXEL by the actual mean pixel of our images ? Thank you.
