### ISSUE TITLE
Where does the target normalization happen, if it happens!

### ISSUE THREAD

**Issue by DecentMakeover** [matterport/Mask_RCNN#1099]
My target values are not in the range [0 1] 

Below is a simple sanity check 

`path = '/home/archimedes/Mask_RCNN/datasets/aadhar/stage1_train/'
for folders in os.listdir(path):
    image = np.array(Image.open(get_mask_path(path, folders)))
    values_range = np.unique(image)
    print(values_range)
    break`

The output of the above script is,
`[    0 65535]`

but when i run the training file it somehow normalizes, i'm not able to figure out if there is a normalizing function which it calls, please help me here, because my loss is going to NAN and im thinking this has something to do with it.

![screenshot from 2018-11-02 16-12-17](https://user-images.githubusercontent.com/25679895/47910896-33d9df80-deba-11e8-89fa-29f9743834c6.png)

Thanks in advance

**Comment by keineahnung2345** [comment]
Could you please paste the code generating the output of "this if unique of labels [0 1]"?

**Comment by DecentMakeover** [comment]
Hi @keineahnung2345  

I have fixed the issue, the problem was 

This line `m = skimage.io.imread(os.path.join(mask_dir, f)).astype(np.bool)` , will convert the array into [True False]

To this line i was doing a `.astype(np.int)` operation and printing the unique values, which will give me [0 1]

I made the required changes, Thank you for your time, and let me know if you need more clarifications
