### ISSUE TITLE
How to evaluate on a new image?

### ISSUE THREAD

**Issue by Tetsujinfr** [matterport/Mask_RCNN#11]
Hi
first thanks for sharing this great repo.

Now I tried the jupiter notebook but got an error on the first cell (not sure why):
```
File "coco.py", line 339
    config.print()
               ^
SyntaxError: invalid syntax
```
then I did comment the line given it is just a print but then  I got a ton of more errors;

So back to the command line, but I get the same error...

can you please help to fix or give the steps to properly evaluate on a new image (not COCO data)?

thanks for your help.
Tets

**Comment by waleedka** [comment]
The syntax error is odd. Are you using Python 3? If not, try it on Python 3 and see if that solves the issue.

**Comment by Tetsujinfr** [comment]
Ohoh, right, I use pythom 2.7 ...
Ok so I am up for another container with P3 install. 
Not sure I will mess around with python3 but thanks for your help.

**Comment by waleedka** [comment]
In the README file there is a link to a container that we've tested with.

**Comment by Tetsujinfr** [comment]
Oh nice. Buy does it support GPU/Cuda or just use CPU?
Tets

**Comment by waleedka** [comment]
I'm afraid that docker image doesn't support GPUs. I use it to verify that the setup works and isolate code issues from environment issues.
