### ISSUE TITLE
Question about the target_class_ids dimensions

### ISSUE THREAD

**Issue by 491734045** [matterport/Mask_RCNN#1109]
Hi,
  The comment of the output variable: target_class_ids in "class DetectionTargetLayer()" is as below:
           target_class_ids: [batch, TRAIN_ROIS_PER_IMAGE]. Integer class IDs.

  While, the sub-function: compute_output_shape(self, input_shape) defines the output variable: target_class_ids as below, which is not consistent with the comment.
          (None, 1),  # class_ids

  According to my understanding, the comment is right. Do you have any idea?

**Comment by keineahnung2345** [comment]
The commit https://github.com/matterport/Mask_RCNN/commit/5bd10d73305f9645cfe1bcc5f800b2de25b24bd8 in July already fixed it, please check if you are using the newest Mask RCNN.

**Comment by 491734045** [comment]
@keineahnung2345 
Thanks for your reply! I have been used the old version.
