### ISSUE TITLE
parameter setting

### ISSUE THREAD

**Issue by 123liluky** [matterport/Mask_RCNN#111]
I am wondering why TRAIN_ROIS_PER_IMAGE affects GPU memory to be used a lot? And what's the difference or corelation between POST_NMS_ROIS_TRAINING and TRAIN_ROIS_PER_IMAGE?
Thanks a lot!

**Comment by waleedka** [comment]
POST_NMS_ROIS_TRAINING is the number of ROIs generated by the RPN network. Out of those, we pick a subset of TRAIN_ROIS_PER_IMAGE to use to train the 2nd stage classifier. 

Think of TRAIN_ROIS_PER_IMAGE as the batch size for the 2nd stage. The larger it is, the more memory you need.
