### ISSUE TITLE
demo.ipynb TensorFlow binary was not compiled to use: AVX2 FMA

### ISSUE THREAD

**Issue by pshankinclarke** [matterport/Mask_RCNN#1113]
Hi I am currently attempting to run the demo using the instructions from "demo.ipynb."  I named the demo code "demo.py." When I run the code (i.e. python3 demo.py) I receive the following error : 

**I tensorflow/core/platform/cpu_feature_guard.cc:141].Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA .** 

How can one fix this problem?

**Comment by mejihero** [comment]
Same issue when I train a new model through the pre-train model:python3 samples/coco/coco.py train --dataset=/path/to/coco/ --model=coco

**Comment by pshankinclarke** [comment]
Doesn't seem to be a bottleneck for the program running after all
