### ISSUE TITLE
Only detect non-overlapping objects

### ISSUE THREAD

**Issue by kutoga** [matterport/Mask_RCNN#1128]
I like to specify that the model should only identify / return non-overlapping instances.

I did not find any configuration setting for this nor an easy way to change the model code.

Maybe someone can give me a hint how this can be achieved?

Thank you very much

**Comment by kutoga** [comment]
Thanks, I'll try that:)!

**Comment by kutoga** [comment]
I actually already used a floating point number, because the previous value was also a floating point.

Thanks:)!

**Comment by eyildiz-ugoe** [comment]
`config.DETECTION_NMS_THRESHOLD` doesn't have anything to do with overlapping and non-overlapping segments. Setting this 0.0 or to another value does not prevent masks from overlapping.
