### ISSUE TITLE
added classes don't show in detection

### ISSUE THREAD

**Issue by bat3a** [matterport/Mask_RCNN#1138]
hi
i added the classes as noted, and I'm training from zero on all layers, but it doesn't show all classes as noted in the database, instead it pick a random class and classifies all masks with it ?!

![err](https://user-images.githubusercontent.com/1135060/48997342-49a89080-f158-11e8-9cdf-284515944c24.jpg)

the classes are:
        self.add_class("foods", 1, "banana")
        self.add_class("foods", 2, "onions")
        self.add_class("foods", 3, "figs")
        self.add_class("foods", 4, "pear")
        self.add_class("foods", 5, "rice")
        self.add_class("foods", 8, "lemon")
        self.add_class("foods", 9, "pringles")
        self.add_class("foods", 11, "tomate")

**Comment by bat3a** [comment]
duplicate issue exists #372

**Comment by QT85** [comment]
@bat3a Have you solved this problem? if so, can you share your code?
