### ISSUE TITLE
A question about training on my own dataset that has only one class

### ISSUE THREAD

**Issue by vincent341** [matterport/Mask_RCNN#114]
@waleedka  Thanks very much for your great work. I am using your code to train mask rcnn on my own dataset that has only one class, say 'basketball' and background. Is it right to train using only images with 'basketball' instead using background images? Really appreciate your kind help.

**Comment by waleedka** [comment]
Generally you'd want to give both, positive and negative examples for training. However, since this is an object detection/instance segmentation network, then the patches of the image that don't contain a basketball are background, so that should suffice.
