### ISSUE TITLE
loss is Nan,while the other 5 loss is not nan

### ISSUE THREAD

**Issue by lkj1114889770** [matterport/Mask_RCNN#1162]
9/500 [..............................] - ETA: 43:03 - loss: nan - rpn_class_loss: 0.4798 - rpn_bbox_loss: 0.5489 - mrcnn_class_loss: 1.1758 - mrcnn_bbox_loss: 0.4309 - mrcnn_mask_loss: 0.2511
As descreibe below, the total loss=nan, however the other 5 loss is not.  I can't figure out why. Can someone help?

**Comment by lijianaiml** [comment]
@lkj1114889770 
hi,looks like you'v solve it,so what's the porblem?

**Comment by lkj1114889770** [comment]
@lijianaiml Actually I don't know why, I just change the version of Keras to 2.1.5 as my previous machine
