### ISSUE TITLE
How to change the density of color of masks formed

### ISSUE THREAD

**Issue by padmaksha18** [matterport/Mask_RCNN#1185]
HI, I am using the matterport code for an use case where i am generating masks to blur personal details in images like faces, car no plate etc. The masks generated are very transparent and hence nothing gets blurred actually. I tried changing the code in visualize.py for each of the brightness and saturation values.
def random_colors(N, bright=True):
"""
Generate random colors.
To get visually distinct colors, generate them in HSV space then
convert to RGB.
"""
brightness = 1.0 if bright else 0.7
hsv = [(i / N, 1, brightness) for i in range(N)]
colors = list(map(lambda c: colorsys.hsv_to_rgb(*c), hsv))
random.shuffle(colors)
return colors

But if i change the brightness to 0 or 1 , it either becomes dark or white but the density of color donot change. How can i achieve a complete opaque color, kindly advice. Many thanks in advance.

**Comment by stygian2a** [comment]
You are looking at the wrong function.Just under this one is :
def apply_mask(image, mask, color, alpha=0.5):
    """Apply the given mask to the image.
    """
    for c in range(3):
        image[:, :, c] = np.where(mask == 1,
                                  image[:, :, c] *
                                  (1 - alpha) + alpha * color[c] * 255,
                                  image[:, :, c])
return image

That's it! just choose an alpha of 1 when you call this function !

**Comment by padmaksha18** [comment]
HI Stygian, Many thanks for your reply and it works exactly how i need it to be. Can you please explain me in short if possible how this function works actually and what this value of "alpha" is meant to be. Many thanks again!!

**Comment by padmaksha18** [comment]
Thanks a lot again!!
