### ISSUE TITLE
Calling Mask_RCNN using Python subprocess.call(): ModuleNotFoundError: No module named 'mrcnn'

### ISSUE THREAD

**Issue by eyildiz-ugoe** [matterport/Mask_RCNN#1188]
I have the following piece of code in Python 2.7 (and that my `PYTHONPATH` is set to 2.7 too):

```
# run the detection code using a different python environment
python3 = '/usr/bin/python3'
execution_dir = '/path/to/dir'
command = [python3, execution_dir + "prediction.py", "-i " + "/tmp/input_image.png"]
subprocess.check_call(command, env={'PYTHONPATH': '/usr/local/lib/python3.6/dist-packages'})
```

which I want to use to externally invoke mask_rcnn prediction function by using the Python 3 in my `PYTHONPATH`.  This technique isn't anything new, and it works really fine with other programs that I have. However, with Mask_RCNN I face the famous error of: 

```
    from mrcnn.config import Config
ModuleNotFoundError: No module named 'mrcnn'
```

which is probably happening because of module/package issues of Python. 

Can someone tell me how to wrap Mask_RCNN in a way that one can simply call it externally?

**Comment by eyildiz-ugoe** [comment]
One had to add the project path to the PYTHONPATH. Solved.

**Comment by nickleeh** [comment]
> One had to add the project path to the PYTHONPATH. Solved.

I met the same problem, can you explain why and how to add project path to PYTHONPATH? Thanks.

**Comment by nataliameira** [comment]
@nickleeh @eyildiz-ugoe I met the same problem, can you explain why and how to add project path to PYTHONPATH? Thanks.
