### ISSUE TITLE
[Discussion] Mask shape

### ISSUE THREAD

**Issue by PavlosMelissinos** [matterport/Mask_RCNN#119]
This is not really an issue. Furthermore, I know this is not an official implementation and that neither of you is the author of the Mask R-CNN paper but I think I prefer to have a public discussion about this instead of correspond with the authors. So here goes...

Any ideas why the final output (mrcnn_mask) includes every class in it, resulting in a shape of `(None, 100, 28, 28, 81)`? Technically each of the 100 detections corresponds to a single object and the class probabilities for each detection are already known. Does this really give any noteworthy advantage compared to a simpler solution like a binary value for fg/bg (conditioned on the detected class) shaped `(None, 100, 28, 28)` and is it worth the additional memory requirements?

Thanks in advance

**Comment by ppwwyyxx** [comment]
```
Class-Specific vs. Class-Agnostic Masks: Our default in-
stantiation predicts class-specific masks, i.e., one m×m
mask per class. Interestingly, Mask R-CNN with class-
agnostic masks (i.e., predicting a single m×m output re-
gardless of class) is nearly as effective: it has 29.7 mask AP
vs. 30.3 for the class-specific counterpart on ResNet-50-C4.
This further highlights the division of labor in our approach
which largely decouples classification and segmentation.
```

**Comment by PavlosMelissinos** [comment]
Well duh... *facepalm* It's been a while since I read the paper and I didn't remember that, thanks.
