### ISSUE TITLE
Adding LSTM to P2-P5

### ISSUE THREAD

**Issue by eselkin** [matterport/Mask_RCNN#1223]
Similar to #342 

I want to add a LSTM to the model for each pyramidal layer of the FPN's outputs. I'm training and predicting on video where the objects are in enclosed spaces and the medium is video so the sequences preceding the current step are related to the previous several.

However, when I add the layers to the P2,P3,P4,P5 in the form of:
```
PX=KL.LSTM(10, input_shape=PX.output.shape, output_shape=PX.output.shape, hidden=100, return_sequences=True, name="fpn_pX_lstm")(PX)
```
I get no change to the graph on tensorboard for the model. It still shows the last conv2d layer fpn_pX as the last layer.

Is the graph dependent on the initial coco trained weights or is this LSTM not getting added to the graph?
<img width="886" alt="screen shot 2019-01-11 at 8 33 51 pm" src="https://user-images.githubusercontent.com/5606931/51069262-3c4c4600-15e0-11e9-9d8e-5f07363e009c.png">

**Comment by mariocorradetti** [comment]
Hi, have you been able to implement this modified version of Mask R-CNN? I was searching for something similar but i can not find anything that can be implemented ""easily"" on Colab. Thank you in advance
