### ISSUE TITLE
Can model used in actual project?

### ISSUE THREAD

**Issue by shaoyang0409** [matterport/Mask_RCNN#123]
Hi ,
I'm a newer, using mask-rcnn for testing recently,  first of all, thank you for your contribution!
My final purpose is running it in andriod application, but I run it for a pitcure with a few time, it is obviously not feasible.

questions;
1. Can model used in actual project? If can, and how about that?(sketchy)
2. What are the special requirements for hardware?

Thank you!

**Comment by waleedka** [comment]
This model is not intended for mobile devices because it's fairly heavy. Theoretically, you could run it on a mobile device, but you'll likely need to make big changes.
