### ISSUE TITLE
How to save output coordinates after inference?

### ISSUE THREAD

**Issue by monjurulkarim** [matterport/Mask_RCNN#1247]
Hi,
I want to save the coordinates of every objects detected after the inference in a COCO style json file. So, that it can be used for further training. 
May be I have to save the contours=find_contours() from visualize.py file. But how can I save in a json file like COCO style? Can anybody help?

**Comment by monjurulkarim** [comment]
figured out.

**Comment by 12rics** [comment]
@monjurulkarim Hi. Can you plz share how you did it?

**Comment by monjurulkarim** [comment]
@12rics 
In the visualize.py file you can find the display_instances functions. There is 'contours' variable which has the coordinates of the contours of every detected objects in an array. Save the x and y  (1st two elements of the array) coordinates of that array in two different lists. 
Then, write these two lists in a CSV file.

**Comment by 12rics** [comment]
@monjurulkarim Thank you!

**Comment by andreasalamanos** [comment]
> @12rics
> In the visualize.py file you can find the display_instances functions. There is 'contours' variable which has the coordinates of the contours of every detected objects in an array. Save the x and y (1st two elements of the array) coordinates of that array in two different lists.
> Then, write these two lists in a CSV file.

the `verts` is  [y, x] or am I mistaken?

**Comment by monjurulkarim** [comment]
@rasputin1917 yes, you are right.

**Comment by st162053** [comment]
Hi are you ablte to save the coordinates of the polygon mask that way?

**Comment by monjurulkarim** [comment]
@st162053 
Yes.
https://github.com/matterport/Mask_RCNN/issues/1247#issuecomment-458636260
