### ISSUE TITLE
How should I apply this model  to object location (bbox regression only) problems?

### ISSUE THREAD

**Issue by JackLee396** [matterport/Mask_RCNN#125]
Really impressive work! 
I've read the code in coco.py and train_shapes.ipynb, these examples are all doing on  datasets containing masks. How should I apply this model  to object location (bbox regression only) problems? What the format should my own datasets use? 
Thanks a lot!

**Comment by waleedka** [comment]
I think the discussion in issue https://github.com/matterport/Mask_RCNN/issues/110 answers your question.
