### ISSUE TITLE
Installation instructions 1. and 2. needs swap in readme.md

### ISSUE THREAD

**Issue by saiabinesh** [matterport/Mask_RCNN#1255]
I think it's pretty obvious to people but still deserves attention. Since,
1. should be. "Clone repository". Then
2. should be "Install requirements". 

![image](https://user-images.githubusercontent.com/12128767/51742397-8b3eb480-2091-11e9-998d-bb676a54b247.png)

**Comment by waleedka** [comment]
Thanks for the note. Fixed by https://github.com/matterport/Mask_RCNN/pull/1267
