### ISSUE TITLE
Bug in build_rpn_targets ?

### ISSUE THREAD

**Issue by jnd77** [matterport/Mask_RCNN#1274]
When looking at:
https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L1543-L1550

we use `ix` as index to assign to rpn_bbox.
Since during the rpn bbox loss computation, we use the indices of the anchors where rpn_match is 1, I believe it should be `rpn_bbox[i]`, not `rpn_bbox[ix]`.

That might explain the issue reported here:
https://github.com/matterport/Mask_RCNN/issues/1243

@waleedka @keineahnung2345 you might want to have a look as it would mean the box part of the RPN is not being trained at all ...

**Comment by ericj974** [comment]
After looking at the code, I came to the same conclusion. Thanks @jnd77 for raising the matter.

**Comment by keineahnung2345** [comment]
Have you noticed that the `rpn_bbox` in `build_rpn_targets` becomes `target_bbox` in `rpn_bbox_loss_graph`? And the `rpn_bbox` in `rpn_bbox_loss_graph` is the output of RPN model?

**Comment by jnd77** [comment]
Ha yes you are completely right ... Thanks for clarifying !

But it made me notice another strange thing:

`rpn_class_loss_graph` is computed over all anchors, when the paper states it should be on the mini-batch size.

`rpn_bbox_loss_graph` is computed over only mini-batch size boxes, when paper states it should be computed over all of them.

**Comment by keineahnung2345** [comment]
Are you talking about the paper of Faster R-CNN?

**Comment by jnd77** [comment]
Yes I do.

**Comment by jnd77** [comment]
Regarding the issue with the RPN losses, I refer to an earlier issue I had forgotten about:
https://github.com/matterport/Mask_RCNN/issues/824

And will close this one.
