### ISSUE TITLE
KeyError during training with my own dataset

### ISSUE THREAD

**Issue by cvKDean** [matterport/Mask_RCNN#1294]
Good day, I am trying to follow the [Color Splash Example](https://github.com/matterport/Mask_RCNN/tree/master/samples/balloon) via this [blog post](https://engineering.matterport.com/splash-of-color-instance-segmentation-with-mask-r-cnn-and-tensorflow-7c761e238b46) where I used my own class, which detects roofs in the image. I just replaced the `balloon` class with `roof` so the configuration has only 2 classes (including the background). I annotated my own images using VIA v.2.0.5. However during training, I am getting the following error:

`Epoch 1/30
ERROR:root:Error processing image {'id': '0030_0040.png', 'source': 'roof', 'path': 'roxas-mask-rcnn/val/0030_0040.png', 'width': 255, 'height': 260, 'polygons': [{'name': 'polygon', 'all_points_x': [7, 42, 90, 14, 1, 1, 19], 'all_points_y': [107, 89, 175, 213, 186, 144, 135]}, {'name': 'polygon', 'all_points_x': [185, 231, 253, 254, 220], 'all_points_y': [142, 117, 157, 183, 202]}, {'name': 'polygon', 'all_points_x': [82, 119, 135, 92], 'all_points_y': [220, 202, 226, 250]}]}
Traceback (most recent call last):
  File "/home/deankarlo/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/deankarlo/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1275, in load_image_gt
    source_class_ids = dataset.source_class_ids[dataset.image_info[image_id]["source"]]
KeyError: 'roof'`

Why is it looking for a key named `roof`? Is it supposed to look for `source` instead? Any help is appreciated. Thank you!

**Comment by cvKDean** [comment]
Solved. The problem is just a misnaming of the class. Specifically:

```
class RoofDataset(utils.Dataset):

    def load_roof(self, dataset_dir, subset):
        """Load a subset of the Roof dataset.
        dataset_dir: Root directory of the dataset.
        subset: Subset to load: train or val
        """
        # Add classes. We have only one class to add.
        self.add_class("roof", 1, "roof") #this line has a mistake, class is misnamed
```
Thank you.

**Comment by pedrosouzax** [comment]
Thanks a lot cvKDean!

**Comment by serpel2007** [comment]
Hai everyone,
I need help on training custom dataset in google colab using Mask RCNN. As a trial, I just save a few JPEG images from google earth and annotated them using VGG Image Annotation too. When I attempt to train I am getting the following error:
TypeError                                 Traceback (most recent call last)

<ipython-input-14-9d3046b5d0d4> in <module>()
----> 1 train(model)

2 frames

<ipython-input-10-09df886ea42d> in <listcomp>(.0)
     47             # the outline of each object instance. There are stores in the
     48             # shape_attributes (see json format above)
---> 49             polygons = [r['shape_attributes'] for r in a['regions']]
     50             objects = [s['region_attributes']['name'] for s in a['regions']]
     51             print("objects:",objects)

TypeError: string indices must be integers

can someone explain and help provide solution

**Comment by mahdi-darvish** [comment]
I have solved this issue by changing class names,
I previously had : 
def load_data(self, image_ids, form, image_group):
        self.add_class('dataset', 1, 'pumpkins')

then I changed it to: 
 self.add_class('pumpkins', 1, 'pumpkins')
and apparently it sloved the issue.

Thank you, @cvKDean, for opening this discussion.

**Comment by Akbarkhan87** [comment]
![Capture](https://user-images.githubusercontent.com/80898953/116971366-08831600-acec-11eb-9a8e-21425499c95c.PNG)
 Can somebody help me in the above code. Because I have prepared the datasets that is different from ShanghaiTech part A and B.

**Comment by Akbarkhan87** [comment]
@cvKDean can you please help me

**Comment by nataliameira** [comment]
> Hai everyone,
> I need help on training custom dataset in google colab using Mask RCNN. As a trial, I just save a few JPEG images from google earth and annotated them using VGG Image Annotation too. When I attempt to train I am getting the following error:
> TypeError Traceback (most recent call last)
> 
> in ()
> ----> 1 train(model)
> 
> 2 frames
> 
> in (.0)
> 47 # the outline of each object instance. There are stores in the
> 48 # shape_attributes (see json format above)
> ---> 49 polygons = [r['shape_attributes'] for r in a['regions']]
> 50 objects = [s['region_attributes']['name'] for s in a['regions']]
> 51 print("objects:",objects)
> 
> TypeError: string indices must be integers
> 
> can someone explain and help provide solution

@serpel2007 Did you manage to solve this problem? Can you help me?
