### ISSUE TITLE
tensorflow.python.framework.errors_impl.ResourceExhaustedError

### ISSUE THREAD

**Issue by QiuSYang** [matterport/Mask_RCNN#1308]
I trained until the third step appeared tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[200,14,14,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc.
How do I inherit config.py parameters?

**Comment by Zhang-O** [comment]
？？？, have you solved your problem?  could you kindly tell us your solution?
