### ISSUE TITLE
mask prediction and bbox prediction

### ISSUE THREAD

**Issue by 123liluky** [matterport/Mask_RCNN#131]
Hi! I have doubts that mask prediction and bbox prediction are done in paralle in Figure3 in paper while mask prediction is followed by bbox prediction in the code, right?

**Comment by waleedka** [comment]
During training, the prediction of bounding boxes and masks are done in parallel. But in classification, the mask prediction is done *after* the bounding box prediction in order to get the mask on the refined bounding box.
