### ISSUE TITLE
Question: How to plot precision-recall curve for validation dataset

### ISSUE THREAD

**Issue by eoghanmull** [matterport/Mask_RCNN#1325]
Hi all,

I am currently trying to plot the precision-recall curve for my validation dataset @ 0.5 iou_threshold.

The utils.compute_ap() function is ideal to get the precision-recall curve for one image along with visualize.plot_precision_recall().

However it is not clear how to plot prediction-recall for multiple images.

The precision and recall arrays are both 4 elements each which is confusing, i thought they would be each a single value.

![image](https://user-images.githubusercontent.com/6501586/53998555-0c30a780-4138-11e9-8b78-2bff90dfb56f.png)

Precision is the first array, Recall is the second as returned by compute_ap()

My inital thought was to make a larger array of precisons and recalls from each image and then plot this array. 

~~However since precison and recall are not singular values this has confused me somewhat.~~
Edit: The middle 2 indexes of the array are the values of 2 different classes.

Hope someone can provide some clarity on this!

**Comment by ApoorvaOjha** [comment]
> Hi all,
> 
> I am currently trying to plot the precision-recall curve for my validation dataset @ 0.5 iou_threshold.
> 
> The utils.compute_ap() function is ideal to get the precision-recall curve for one image along with visualize.plot_precision_recall().
> 
> However it is not clear how to plot prediction-recall for multiple images.
> 
> The precision and recall arrays are both 4 elements each which is confusing, i thought they would be each a single value.
> 
> ![image](https://user-images.githubusercontent.com/6501586/53998555-0c30a780-4138-11e9-8b78-2bff90dfb56f.png)
> 
> Precision is the first array, Recall is the second as returned by compute_ap()
> 
> My inital thought was to make a larger array of precisons and recalls from each image and then plot this array.
> 
> ~However since precison and recall are not singular values this has confused me somewhat.~
> Edit: The middle 2 indexes of the array are the values of 2 different classes.
> 
> Hope someone can provide some clarity on this!

Hey did you find the solution for plotting precision recall graph for multiple images? Please convey the same to me.
