### ISSUE TITLE
Is STEPS_PER_EPOCH=1000 sufficent to coco dataset?

### ISSUE THREAD

**Issue by yiyang186** [matterport/Mask_RCNN#1333]
In the file of sample/coco/coco.py, the sample do not modify STEPS_PER_EPOCH, so that STEPS_PER_EPOCH = 1000. Is it sufficent to coco dataset? Shall I set STEPS_PER_EPOCH = num_samples_coco / IMAGES_PER_GPU / GPU_COUNT?

**Comment by AsRain** [comment]
Hello! I have the same concern. Because I find that if I increase `gpu_count`  1 to 2, the training time for every epoch stays the same(but two gpus are working).
The default setting is `gpu_count=1`.
So I wonder whether I should decrease `STEP_PER_EPOCH` to `1000/2 = 500`

**Comment by yeshenlin** [comment]
> Hello! I have the same concern. Because I find that if I increase `gpu_count` 1 to 2, the training time for every epoch stays the same(but two gpus are working).
> The default setting is `gpu_count=1`.
> So I wonder whether I should decrease `STEP_PER_EPOCH` to `1000/2 = 500`

I also wonder that @AsRain

**Comment by chAwater** [comment]
@yiyang186 @AsRain @yeshenlin 

I think the answer is yes, according to https://github.com/matterport/Mask_RCNN/issues/708#issuecomment-423711203 and #550 or https://github.com/keras-team/keras/issues/10164
