### ISSUE TITLE
Annotations in xml convert to json?

### ISSUE THREAD

**Issue by adions025** [matterport/Mask_RCNN#1344]
Hello, 
I would like to know if someone has been able to train using an xml annotation file, or if someone has converted xml to json.
Can someone show me an example how to use the load_() function if I change my xml file to json?
I made some annotations with VIA tool and it was correct, but I would really like to use the xml annotations as they are done and it takes a long time to start over.
I would appreciate it.

**Comment by xiongshuai520** [comment]
Hi，guys，do you handle it?or someone else can give a answer in this page?thanks a lot

**Comment by adions025** [comment]
Hello, finally I have converted the xml file to json creating a false mask in the form of polygon from the coordinates of the rectangle but does not contribute anything new for you training.

**Comment by adions025** [comment]
https://github.com/adions025/XMLtoJson_Mask_RCNN
