### ISSUE TITLE
How to speed up inference?

### ISSUE THREAD

**Issue by davidb1** [matterport/Mask_RCNN#1349]
It's taking around 4 seconds to infer a picture of about 1000X500 using 1080TI. 
Are there any obvious ways I'm missing to speed up the inference? Exporting a frozen model? 

Another question - would retraining the model for grayscale only improve the inference time?

**Comment by zhouyuangan** [comment]
Keep watching this issue. I need help, too.

**Comment by davidb1** [comment]
@zhouyuangan check that you're using your gpu and not your cpu. That was the issue for me at least.
