### ISSUE TITLE
Mask IoU ?

### ISSUE THREAD

**Issue by wenjianhugit** [matterport/Mask_RCNN#135]
Hi,

First of all, thank you for this fantastic implementation about Mask R-CNN !

Just a quick question, which function calculates the Mask IoU ? I checked compute_ap in utils.py, but it seems not the function I am looking for. I believe this function is required to calculate segmentation AP.

Many thanks !

**Comment by waleedka** [comment]
That's implemented in the pycocotools library and is only called for evaluation. Check this line in `coco.py`:
```
cocoEval.evaluate()
```
