### ISSUE TITLE
Mean Average Precision For Each Classes

### ISSUE THREAD

**Issue by PhanDuc** [matterport/Mask_RCNN#1371]
Hi, I'm curious how to calculate the mAPs for each class? 
I'm checking the function `compute_ap` but it calculated mean average precision of total dataset.

**Comment by monjurulkarim** [comment]
hi, how did you solve this?

**Comment by yy9568** [comment]
@PhanDuc

**Comment by jay61439476** [comment]
@PhanDuc hello  did you solve this?

**Comment by PhanDuc** [comment]
@monjurulkarim , @jay61439476 , please check my script for evaluation. I hope it might help!

https://gist.github.com/PhanDuc/abf8bf5a8eed78cc03e4df9b1f1a276c
