### ISSUE TITLE
Failed to visualize Mask_RCNN model with plot_model from keras.utils

### ISSUE THREAD

**Issue by oibook13** [matterport/Mask_RCNN#138]
This is a good implementation for Mask_RCNN. Thanks for that. To intuitive understand MaskRCNN, I tried to visualize the model's architecture. However, I failed. 

The details are as follows:
In coco.py
```python
...
from keras.utils import plot_model  # I add this for visualizing the model
...
    if args.command == "train":
        model = modellib.MaskRCNN(mode="training", config=config,
                                  model_dir=args.logs)
    else:
        model = modellib.MaskRCNN(mode="inference", config=config,
                                  model_dir=args.logs)
    plot_model(model, to_file='model.png') # visualize the model
...
```

And I got this error
```python
Traceback (most recent call last):
  File "mycoco.py", line 366, in <module>
    plot_model(model, to_file='model.png')
  File "/home/luoyan/anaconda3/lib/python3.5/site-packages/keras/utils/vis_utils.py", line 131, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "/home/luoyan/anaconda3/lib/python3.5/site-packages/keras/utils/vis_utils.py", line 62, in model_to_dot
    layers = model.layers
AttributeError: 'MaskRCNN' object has no attribute 'layers'
```

I know MaskRCNN defines its weights using callable object, like x = KL.Activation('relu')(x). In this way, model doesn't have layers member. But I think there should be a way to visualize the model. Any ideas? Thanks.

**Comment by waleedka** [comment]
I haven't used `plot_model` so I'm not sure if it'll work. I'm curious to know, and it would be great if you contribute it back through a PR if it does. 

Based on the error, I think you might be passing the MaskRCNN object rather than the Keras M object. Note that MaskRCNN is a custom class, and inside that class the `keras_model` property holds a reference to the Keras model.

**Comment by oibook13** [comment]
@waleedka you are right, I passed MaskRCNN object instead of keras_model object, which would cause this problem. Here I have some updates:

If I use 
```python
from keras.utils import plot_model
plot_model(model.keras_model, to_file='model.png')  # now, here I pass keras_model
```
It will save model.png for me, but the png is a blank file.

if I use iPython to visualize
```python
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
SVG(model_to_dot(model.keras_model).create(prog='dot', format='svg'))
```
It succeeded. The graph is as follows
![image](https://user-images.githubusercontent.com/492839/34016580-10d2a57e-e0e8-11e7-83eb-f31476b29e84.png)

Although, it is tricky to save the svg (from dot) to pdf, at least I can see the workflow. Hence, I will close this issue.

**Comment by chenhoushuang** [comment]
> @waleedka you are right, I passed MaskRCNN object instead of keras_model object, which would cause this problem. Here I have some updates:
> 
> If I use
> 
> ```python
> from keras.utils import plot_model
> plot_model(model.keras_model, to_file='model.png')  # now, here I pass keras_model
> ```
> 
> It will save model.png for me, but the png is a blank file.
> 
> if I use iPython to visualize
> 
> ```python
> from IPython.display import SVG
> from keras.utils.vis_utils import model_to_dot
> SVG(model_to_dot(model.keras_model).create(prog='dot', format='svg'))
> ```
> 
> It succeeded. The graph is as follows
> ![image](https://user-images.githubusercontent.com/492839/34016580-10d2a57e-e0e8-11e7-83eb-f31476b29e84.png)
> 
> Although, it is tricky to save the svg (from dot) to pdf, at least I can see the workflow. Hence, I will close this issue.

    # Create model
    if args.command == "train":
        model = modellib.MaskRCNN(mode="training", config=config,
                                  model_dir=args.logs)
    else:
        model = modellib.MaskRCNN(mode="inference", config=config,
                                  model_dir=args.logs)

    # Select weights file to load
    if args.model.lower() == "coco":
        model_path = COCO_MODEL_PATH
    elif args.model.lower() == "last":
        # Find last trained weights
        model_path = model.find_last()
    elif args.model.lower() == "imagenet":
        # Start from ImageNet trained weights
        model_path = model.get_imagenet_weights()
    else:
        model_path = args.model

    # Load weights
    print("Loading weights ", model_path)
    model.load_weights(model_path, by_name=True)
    
    # print model
    from keras.utils import plot_model
    plot_model(model.keras_model,to_file='model.png')

print model after load weights will be OK instead of a blank file
