### ISSUE TITLE
Windows machine crashed when using mask-rcnn

### ISSUE THREAD

**Issue by itachi1232gg** [matterport/Mask_RCNN#1383]
I trained a mask-rcnn model on a Linux machine with a 1080TI, everything went smoothly.  For some purpose, I deployed the model on a Windows machine with 32GB RAM and a 1080Ti GPU to do some instance segmentation, it keeps restarting the windows machine.  Anyone knows the reason?

**Comment by 759420184** [comment]
Sometimes my machine restarts. I changed the IMAGES_PER_GPU = 2 to 1,in the config.py file,it can solve my problem, I hope it will help you.

**Comment by itachi1232gg** [comment]
@759420184 Thanks a lot.  It's possibly caused by my power supply or hardware overheat. I solved my problem by changing another Windows machine to run the code :-)
