### ISSUE TITLE
How to visualize my result when trained with grayscale images (display_instances in visualize.py)

### ISSUE THREAD

**Issue by thepate94227** [matterport/Mask_RCNN#1390]
Hey everyone,

i just trained my Mask R-CNN with grayscale images. 
Now i want to visualize my result. When i use my code, which i used for rgb images, i get an error in visualize.py in the apply_mask function, because the dimensions aren't the same. 
For visualization i used parts of waspinators code:
https://github.com/waspinator/deep-learning-explorer/blob/master/mask-rcnn/notebooks/mask_rcnn.ipynb

The function which i use and which cause the problem is display_instances in visualize.py.

This is the apply_mask function where the error occure:
```
def apply_mask(image, mask, color, alpha=0.5):
    """Apply the given mask to the image.
    """
    for c in range(3):
        image[:, :, c] = np.where(mask == 1,
                                  image[:, :, c] *
                                  (1 - alpha) + alpha * color[c] * 255,
                                  image[:, :, c])
    return image

Traceback (most recent call last):
  File "loadKnotG.py", line 171, in <module>
    dataset_train.class_names, figsize=(8, 8))
  File "visualize.py", line 154, in display_instances
    masked_image = apply_mask(masked_image, mask, color)
  File "visualize.py", line 79, in apply_mask
    image[:, :, c] *
IndexError: index 1 is out of bounds for axis 2 with size 1
```

My images have the shape (w,d,1) because they are grayscale. For this i edited the load_image function in utils.py like i supposed to do according to the wiki here.

Does somebody know how i can visualize my results?

In apply_mask i tried to avoid the problem by first delete the last dimension, so i can convert the image in rgb:

```
image = np.squeeze(image, axis=2)
image = skimage.color.gray2rgb(image)
```

But then i get this error:

```
Traceback (most recent call last):
  File "loadKnotG.py", line 171, in <module>
    dataset_train.class_names, figsize=(8, 8))
  File "visualize.py", line 169, in display_instances
    masked_image = apply_mask(masked_image, mask, color)
  File "visualize.py", line 93, in apply_mask
    image[:, :, c] *
IndexError: too many indices for array
```

**Comment by hwh-hit** [comment]
I have tried to changed the func apply_mask(3->1),the IndexError: index 1 is out of bounds for axis 2 with size 1 disappeared,but doesn't work. so i changed my test.py(for detection),before visualisation,i read the image again and use ＂skimage.color.gray2rgb(image)＂，i works for me,but to be honest,the grayscale images does't save much time for me ,it still 100ms around.

**Comment by thepate94227** [comment]
> I have tried to changed the func apply_mask(3->1),the IndexError: index 1 is out of bounds for axis 2 with size 1 disappeared,but doesn't work. so i changed my test.py(for detection),before visualisation,i read the image again and use ＂skimage.color.gray2rgb(image)＂，i works for me,but to be honest,the grayscale images does't save much time for me ,it still 100ms around.

Thank you for your answer. Yes, i already thought about convert the image to rgb, but i thought that maybe there is another way...
In my case i want to use grayscale images, because i don't want my NN to use the color information.

**Comment by OterLabb** [comment]
I got it working with greyscale images by changing  `for c in range(3):` to  `for c in range(0):`

And reading the image with:
`img = skimage.io.imread(image_path)
img_arr = img[..., np.newaxis]`
