### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools._mask

### ISSUE THREAD

**Issue by nijatmursali** [matterport/Mask_RCNN#1392]
I have installed pycocotools with "pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI", however when I try to implement **python model_main.py** it gives me error of 
                   **ModuleNotFoundError: No module named 'pycocotools._mask'**

I have also tried

git clone https://github.com/cocodataset/cocoapi
cd PythonAPI
python setup.py build_ext install

It gives error:

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

I have installed C++ tools. 

I have installed the pycocotools with cocoapi. Any kinds of help appreciated.

**Comment by mehdiselbi** [comment]
same problem here :'(

**Comment by nijatmursali** [comment]
I solved the issue by just using Anaconda.

**Comment by mehdiselbi** [comment]
i'm using anaconda too!  can you explain more please ?!

**Comment by olaurendin** [comment]
You may find this tutorial useful :
https://www.youtube.com/watch?v=2TikTv6PWDw

**Comment by mehdiselbi** [comment]
thanks i'll try to do it 
@olaurendin

**Comment by ghost** [comment]
the same problem :(

**Comment by Espade** [comment]
solved the problem by "sudo pip install cython"
then do make command

**Comment by nijatmursali** [comment]
Lads, 

The problem was because of Window 10 that couldn't see the path variable for C++, however, I have included that one as well. 

As I have mentioned earlier, the problem has been solved using Anaconda and doing 

`pip install pycocotools`

and then installing cocoAPI from the link I have provided. 

I hope this one helps. Good luck.

**Comment by amit-code** [comment]
You can replace extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'] with extra_compile_args={'gcc': ['/Qstd=c99']} in /coco/pycocotools/setup.py.

And then run again python setup.py build_ext install
