### ISSUE TITLE
Changing config parameters during the training

### ISSUE THREAD

**Issue by pesekon2** [matterport/Mask_RCNN#142]
Hi, 

I am trying to train the network on my own data, but I have a problem - my GPU fails (resource exhausted) when training 3+ layers on the image size which is still okay for the 4+ layers. 

Is it possible to change config parameters during the process? Between 3+ and 4+ trainings? 

I have tried something like  
`CocoConfig.IMAGE_MAX_DIM = 704`  
`CocoConfig.IMAGE_MIN_DIM = 700`

It didn't work. Neither did
`model.config.IMAGE_MAX_DIM = 704`  
`model.config.IMAGE_MIN_DIM = 700`

I still got the error message saying that tensor [None, 1024, 1024, 3] was expected. 

Thank you.

**Comment by waleedka** [comment]
Don't change attributes of the config object. Change attributes of the Config class. 

See how CocoConfig sub-classes Config and overrides some attributes. You need to do the same and create a new config class, otherwise your changes are not taking effect.

**Comment by pesekon2** [comment]
Okay, maybe that was my problem. With `CocoConfig.IMAGE_MAX_DIM = 704` I meant exactly overriding the attributes, but I did try just that. Not creating new class. 

However, is it okay to initialize new class after 4+ training just for the 3+ training? Is it okay for weights to continue the training with different image size?

**Comment by waleedka** [comment]
Let me make sure I understand the question: you want to train the model with layers 4+ and then save it, and then re-create the model with a smaller image size and load the previous weights and continue the training with layers 3+. Is that accurate?

I think that might not be a great idea. When you change the image size, you likely have to change the anchor sizes as well. So now you have a new model with different input and different anchor sizes, so it will learn different features. I don't think that would give you good results. 

Try to train with the same config that you'd use for inferencing. If your images are similar in nature to COCO images (i.e. natural pictures) then you probably don't need to train the first 3 layers anyway. Just do 4+. On the other hand, if your images are very different (e.g. medical x-rays) then you'd need to train earlier layers as well.

**Comment by pesekon2** [comment]
> you want to train the model with layers 4+ and then save it, and then re-create the model with a smaller image size and load the previous weights and continue the training with layers 3+. Is that accurate?

Yes, that was what I tried to do.  
My images are satellite images and I was still getting wrong results. Now I know why (it came to my mind after few weeks of work, I should ask earlier). The original images are 6000x6000 so I wanted to use as big image size as possible, but now I see that I should use the same size during the whole training process. 
Okay, I will try to train it again from the beginning with fixed image size to the one that is acceptable by layers 3+. Then I can try it with bigger image and without 3+ layers. 

Thank you for the help, I think that this was the critical moment in my process.

**Comment by waleedka** [comment]
Sounds good. And check this other project. It extends this repo to work on satellite images.

https://github.com/jremillard/images-to-osm
