### ISSUE TITLE
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,2) and requested shape (2,2)

### ISSUE THREAD

**Issue by davidb1** [matterport/Mask_RCNN#1435]
Getting this error on some images, any ideas?

 coming from: 
molded_images, image_metas, windows = self.mold_inputs(images)
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,2) and requested shape (2,2)

**Comment by davidb1** [comment]
Make sure the image isn't grayscale and convert to RGB it if it is (like in utils, load_image function)

**Comment by xiongshuai520** [comment]
thanks,it worked for me

**Comment by nooriahmed** [comment]
> Make sure the image isn't grayscale and convert to RGB it if it is (like in utils, load_image function)

I am facing the same issue, would you please give a little brief description.i could not get your point. I am using grayscale images. I shall be grateful. regards

**Comment by davidb1** [comment]
I got this error when I was using (what I found out was) a grayscale image.
MaskRCNN doesn't work by default with grayscale and my model wasn't trained to work with grayscale so I needed to convert the image to RGB before inputing it for inference.

**Comment by nooriahmed** [comment]
> I got this error when I was using (what I found out was) a grayscale image.
> MaskRCNN doesn't work by default with grayscale and my model wasn't trained to work with grayscale so I needed to convert the image to RGB before inputing it for inference.

Thank you very much for the kind response

**Comment by buaacarzp** [comment]
hi, its my honer to meet the same question with you , but i have trouble in the test model, please help me , my qq is 510695983

**Comment by superabhijha2000** [comment]
operands could not be broadcast together with remapped shapes [original->remapped]: (3,2) and requested shape (2,2)

**Comment by superabhijha2000** [comment]
my code is working when i pass it by gray scale it give the same error ---- operands could not be broadcast together with remapped shapes [original->remapped]: (3,2) and requested shape (2,2)

**Comment by bharath5673** [comment]
grayscale 2 rgb worked for me...  #custom_mrcnn

**Comment by Genius-farmer** [comment]
Dear All,

I'm facing this error.

"ValueError: len(output_shape) cannot be smaller than the image dimensions"

is there any solution for this?

Please assist with this posting

[https://github.com/matterport/Mask_RCNN/issues/2534](url)

**Comment by pudari2007** [comment]
> grayscale 2 rgb worked for me... #custom_mrcnn

Thank you it worked for me but we should use syntax like this eg.
backtorgb = cv2. cvtColor(gray,cv2. COLOR_GRAY2RGB)

**Comment by GT84** [comment]
Hy,

I know this is already closed for some time and there might be some forks or repos in here that are more up to date. 
But for me this was the first and also the best implementation (I used) and so I am still using this repository as starting point.

I'm currently working on a project explicitly analysing grayscale images, so I did not want to change grayscale to RGB.
I tried to debug, until ending up ``keras.engine`` methods. As a result, some methods from ``keras.engine``, that are used here, require 3 dims in shape. By default, some (or the most) grayscale images will appear with 2 dims.

So the (3,2) that does not map to (2,2) is simply a nested padding list ([``mrcnn.utils.py``](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/utils.py) Lines [458](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/utils.py#L458), [479](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/utils.py#L479)), hardcoded for a 3-dimensional image/array.
Rearranging this code will lead to other/further issues which finally appear inside of ``keras.engine``.

Therefore, my solution is to just reshape every incomming image (not mask) without changing values and image size,
as it will happen as soon as we switch to RGB or any other colored format:

```python
>>> image.shape
(512, 1024)
>>> image = image.reshape((*image.shape, 1))
>>> image.shape
(512, 1024, 1)
```

By default this should be attached in the [``load_image()``](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/utils.py#L355) method of your [``Dataset``](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/utils.py#L239) and also before you pass
any image into [``detect()``](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/model.py#L2482) of your [``MaskRCNN``](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/model.py#L1820) instance.

This worked for me without any problems. Maybe this helps someone who is still working with this.

> **Additionally**:
> [``IMAGE_CHANNEL_COUNT = 1``](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/config.py#L137) must be adopted in the [Config](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/config.py).
> Some adoptions in ``visualize.py`` if you want to use included plotting methods
