### ISSUE TITLE
SyntaxError when running demo.ipynb using jupyter notebook

### ISSUE THREAD

**Issue by knwng** [matterport/Mask_RCNN#144]
Hi, I ran demo.ipynb using jupyter notebook and got error as following:
  File "coco.py", line 340
    config.print()
                ^
SyntaxError: invalid syntax

**Comment by jmtatsch** [comment]
@knwng  Please try to check out the current version of the repository, try again and report back.

**Comment by knwng** [comment]
Thanks for reply, I finally find out it's a problem caused by improper python environment. I'll close this issue

**Comment by Raj7kumar7** [comment]
@knwng Can you tell me what changes you made ?I am getting the same error
