### ISSUE TITLE
train on own dataset using mask_rcnn_coco.h5 as initial weight 

### ISSUE THREAD

**Issue by tracychen69** [matterport/Mask_RCNN#145]
Hi @waleedka, 

Thanks for the impressive work.

I want to train the model using my own dataset (only two classes) with the weight you trained on COCO as initial weight (mask_rcnn_coco.h5). Basically, I added following code:

exclude_list = {'mrcnn_bbox_fc', 'mrcnn_mask_deconv', 'mrcnn_class_logits', 'mrcnn_mask'}
model.load_weights(model_path, by_name=True, exclude=exclude_list)

Is this correct, or should I add more layers into the "exclude_list". Thanks.

**Comment by waleedka** [comment]
Check the train_shapes notebook. It does something similar to what you're doing, and it has the list of the layers you need to exclude.

**Comment by pesekon2** [comment]
Hi,  
and what if we trained our own model with excluded layers and then we would like to continue the training with `model=last`? Should we again exclude those layers, or should we use them in this case?

**Comment by waleedka** [comment]
No, you only exclude the layers the first time you load the COCO weights. After that you load all the layers. Your code should treat `model=coco` as a special case that excludes incompatible layers.

**Comment by pesekon2** [comment]
I thought that, but wasn't sure. Thanks.

**Comment by sunbin1205** [comment]
@pesekon2 How do you make your own data set? I need to make a data set for a building. Can you give me a hand?
