### ISSUE TITLE
error train own dataset TypeError: string indices must be integers

### ISSUE THREAD

**Issue by wilsonhermar** [matterport/Mask_RCNN#1452]
Good day.
I am training my own dataset.
I use via 2.0.5
When I train, I get the error
File "samples/bottles/bottle.py", line 381, in 
train(model)
File "samples/bottles/bottle.py", line 203, in train
dataset_val.load_bottle(args.dataset, "val")
File "samples/bottles/bottle.py", line 128, in load_bottle
polygons = [r['shape_attributes'] for r in a['regions']]
File "samples/bottles/bottle.py", line 128, in 
polygons = [r['shape_attributes'] for r in a['regions']]
TypeError: string indices must be integers

PLEASE HELP!!!!!

My code is :

def load_bottle(self, dataset_dir, subset):
"""Load a subset of the Balloon dataset.
dataset_dir: Root directory of the dataset.
subset: Subset to load: train or val
"""
# Add classes. We have only one class to add.
self.add_class("bottle", 1, "PET")
self.add_class("bottle", 2, "COLOR HDPE")
self.add_class("bottle", 3, "WHITE HDPE")

    # Train or validation dataset?
    assert subset in ["train", "val"]
    dataset_dir = os.path.join(dataset_dir, subset)

    # Load annotations
    # VGG Image Annotator (up to version 1.6) saves each image in the form:
    # { 'filename': '28503151_5b5b7ec140_b.jpg',
    #   'regions': {
    #       '0': {
    #           'region_attributes': {},
    #           'shape_attributes': {
    #               'all_points_x': [...],
    #               'all_points_y': [...],
    #               'name': 'polygon'}},
    #       ... more regions ...
    #   },
    #   'size': 100202
    # }
    # We mostly care about the x and y coordinates of each region
    # Note: In VIA 2.0, regions was changed from a dict to a list.
    annotations = json.load(open(os.path.join(dataset_dir, "via_region_data.json")))
    annotations = list(annotations.values())  # don't need the dict keys

    # The VIA tool saves images in the JSON even if they don't have any
    # annotations. Skip unannotated images.
    annotations = [a for a in annotations if a['regions']]

    # Add images
    for a in annotations:
        # Get the x, y coordinaets of points of the polygons that make up
        # the outline of each object instance. These are stores in the
        # shape_attributes (see json format above)
        # The if condition is needed to support VIA versions 1.x and 2.x.
        #if type(a['regions']) is dict:
        polygons = [r['shape_attributes'] for r in a['regions']]
        names = [r['region_attributes'] for r in a['regions']]
        
        #else:
        #polygons = [r['shape_attributes'] for r in a['regions']] 

        # load_mask() needs the image size to convert polygons to masks.
        # Unfortunately, VIA doesn't include it in JSON, so we must read
        # the image. This is only managable since the dataset is tiny.
        image_path = os.path.join(dataset_dir, a['filename'])
        image = skimage.io.imread(image_path)
        height, width = image.shape[:2]

        self.add_image(
            "bottle",
            image_id=a['filename'],  # use file name as a unique image id
            path=image_path,
            width=width, height=height,
            polygons=polygons,
            names=names)

def load_mask(self, image_id):
    """Generate instance masks for an image.
   Returns:
    masks: A bool array of shape [height, width, instance count] with
        one mask per instance.
    class_ids: a 1D array of class IDs of the instance masks.
    """
    # If not a balloon dataset image, delegate to parent class.
    image_info = self.image_info[image_id]
    if image_info["source"] != "bottle":
        return super(self.__class__, self).load_mask(image_id)
    
    # Convert polygons to a bitmap mask of shape
    # [height, width, instance_count]
    info = self.image_info[image_id]
    class_names = info["names"]
    mask = np.zeros([info["height"], info["width"], len(info["polygons"])],
                    dtype=np.uint8)
    for i, p in enumerate(info["polygons"]):
        # Get indexes of pixels inside the polygon and set them to 1
        rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
        mask[rr, cc, i] = 1
    class_ids = np.zeros([len(info["polygons"])])

    for i, p in enumerate(class_names):
        if p['class'] == 'PET':
            class_ids[i] = 1
        elif p['class'] == 'COLOR HDPE':
            class_ids[i] = 2
        elif p['class'] == 'WHITE HDPE':
            class_ids[i] = 3
    class_ids = class_ids.astype(int)
    # Return mask, and array of class IDs of each instance. Since we have
    # one class ID only, we return an array of 1s
    return mask.astype(np.bool), class_ids

def image_reference(self, image_id):
    """Return the path of the image."""
    info = self.image_info[image_id]
    if info["source"] == "bottle":
        return info["path"]
    else:
        super(self.__class__, self).image_reference(image_id)

**Comment by wilsonhermar** [comment]
Good day.
I am training my own dataset. 
I use via 2.0.5
When I train, I get the error
  File "samples/bottles/bottle.py", line 381, in <module>
    train(model)
  File "samples/bottles/bottle.py", line 203, in train
    dataset_val.load_bottle(args.dataset, "val")
  File "samples/bottles/bottle.py", line 128, in load_bottle
    polygons = [r['shape_attributes'] for r in a['regions']]
  File "samples/bottles/bottle.py", line 128, in <listcomp>
    polygons = [r['shape_attributes'] for r in a['regions']]
TypeError: string indices must be integers


PLEASE HELP!!!!!

 My code is :

def load_bottle(self, dataset_dir, subset):
        """Load a subset of the Balloon dataset.
        dataset_dir: Root directory of the dataset.
        subset: Subset to load: train or val
        """
        # Add classes. We have only one class to add.
        self.add_class("bottle", 1, "PET")
        self.add_class("bottle", 2, "COLOR HDPE")
        self.add_class("bottle", 3, "WHITE HDPE")

        # Train or validation dataset?
        assert subset in ["train", "val"]
        dataset_dir = os.path.join(dataset_dir, subset)

        # Load annotations
        # VGG Image Annotator (up to version 1.6) saves each image in the form:
        # { 'filename': '28503151_5b5b7ec140_b.jpg',
        #   'regions': {
        #       '0': {
        #           'region_attributes': {},
        #           'shape_attributes': {
        #               'all_points_x': [...],
        #               'all_points_y': [...],
        #               'name': 'polygon'}},
        #       ... more regions ...
        #   },
        #   'size': 100202
        # }
        # We mostly care about the x and y coordinates of each region
        # Note: In VIA 2.0, regions was changed from a dict to a list.
        annotations = json.load(open(os.path.join(dataset_dir, "via_region_data.json")))
        annotations = list(annotations.values())  # don't need the dict keys

        # The VIA tool saves images in the JSON even if they don't have any
        # annotations. Skip unannotated images.
        annotations = [a for a in annotations if a['regions']]

        # Add images
        for a in annotations:
            # Get the x, y coordinaets of points of the polygons that make up
            # the outline of each object instance. These are stores in the
            # shape_attributes (see json format above)
            # The if condition is needed to support VIA versions 1.x and 2.x.
            #if type(a['regions']) is dict:
            polygons = [r['shape_attributes'] for r in a['regions']]
            names = [r['region_attributes'] for r in a['regions']]
            
            #else:
            #polygons = [r['shape_attributes'] for r in a['regions']] 

            # load_mask() needs the image size to convert polygons to masks.
            # Unfortunately, VIA doesn't include it in JSON, so we must read
            # the image. This is only managable since the dataset is tiny.
            image_path = os.path.join(dataset_dir, a['filename'])
            image = skimage.io.imread(image_path)
            height, width = image.shape[:2]

            self.add_image(
                "bottle",
                image_id=a['filename'],  # use file name as a unique image id
                path=image_path,
                width=width, height=height,
                polygons=polygons,
                names=names)

    def load_mask(self, image_id):
        """Generate instance masks for an image.
       Returns:
        masks: A bool array of shape [height, width, instance count] with
            one mask per instance.
        class_ids: a 1D array of class IDs of the instance masks.
        """
        # If not a balloon dataset image, delegate to parent class.
        image_info = self.image_info[image_id]
        if image_info["source"] != "bottle":
            return super(self.__class__, self).load_mask(image_id)
        
        # Convert polygons to a bitmap mask of shape
        # [height, width, instance_count]
        info = self.image_info[image_id]
        class_names = info["names"]
        mask = np.zeros([info["height"], info["width"], len(info["polygons"])],
                        dtype=np.uint8)
        for i, p in enumerate(info["polygons"]):
            # Get indexes of pixels inside the polygon and set them to 1
            rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
            mask[rr, cc, i] = 1
        class_ids = np.zeros([len(info["polygons"])])

        for i, p in enumerate(class_names):
            if p['class'] == 'PET':
                class_ids[i] = 1
            elif p['class'] == 'COLOR HDPE':
                class_ids[i] = 2
            elif p['class'] == 'WHITE HDPE':
                class_ids[i] = 3
        class_ids = class_ids.astype(int)
        # Return mask, and array of class IDs of each instance. Since we have
        # one class ID only, we return an array of 1s
        return mask.astype(np.bool), class_ids

    def image_reference(self, image_id):
        """Return the path of the image."""
        info = self.image_info[image_id]
        if info["source"] == "bottle":
            return info["path"]
        else:
            super(self.__class__, self).image_reference(image_id)

**Comment by myBestLove** [comment]
maybe you should change to
polygons = [r['shape_attributes'] for r in a['regions'].values()]
 names = [r['region_attributes'] for r in a['regions'].values()]

**Comment by wilsonhermar** [comment]
myBestLove, thanks but it is not possible because version 2.0.5 VIA are lists and not dictionaries.

**Comment by wilsonhermar** [comment]
It worked

**Comment by nyck33** [comment]
@wilsonhermar  can you describe what worked?  I'm getting the same error in a similar situation.

**Comment by nataliameira** [comment]
I have the same problem. Has anyone managed to solve this?

**Comment by sruthisentil** [comment]
> I have the same problem. Has anyone managed to solve this?

Did you ever fix this issue?

**Comment by nataliameira** [comment]
Hello @sruthisentil 

Yes, I corrected. I don't remember exactly how I solved this specific error. I did my training with the balloon example for several classes. I had to edit a part of the file to work for multiple classes. And then, my model worked.

**Comment by gSayak** [comment]
@nataliameira @sruthisentil @nyck33... did any of u solve this issue? am having the same issue and the above code isn't solving it for me
