### ISSUE TITLE
Changes made to model.py are not reflecting in the demo.ipynb

### ISSUE THREAD

**Issue by VellalaVineethKumar** [matterport/Mask_RCNN#1479]
I wanted to extract the features from the mask-RCNN model.Hence i changed the model.py as to return the features from the masked region.
I referred this code to make the changes.
[https://gist.github.com/kielnino/3965d905a921abbe29a7c89af5ba1114]
Now this model.py file return features along with boxes, class_ids, scores, full_masks 
in line no: 2483
Now in the after running the jupyter notebook demop.ipynb file when i try to print the results i the features are not being displayed when i print(results).

Do i need to build things again after changing the model.py file? or is there any mistake im doing?

Please help!.

**Comment by naruto-raj** [comment]
yes you have build and at the same time remove the previous build files to get changes working

**Comment by remindchobits** [comment]
I just ran 

python setup.py install

after each time I made changes in files and it works fine, hope that helps

**Comment by VellalaVineethKumar** [comment]
@remindchobits That really worked! Thanks, Dude :-)
