### ISSUE TITLE
Mask bounds

### ISSUE THREAD

**Issue by ThomHordijk** [matterport/Mask_RCNN#1494]
Hello I am using the code to detect objects and I need to deduct the center of the object. Using the bounding box gives a decent approximation but i have found that from time to time the box leaps away from the masks to side. The mask are more consistent so I am attempting to use the data used to give the mask its border. I have not been able to single out this data, would you be able to tell me if it is at all possible to retrieve the mask in x,y coordinates? How would i go about doing this?

**Comment by andreasalamanos** [comment]
Did you solve it?
 I will give it a try and I will send back

**Comment by andreasalamanos** [comment]
Hi @ThomHordijk,

my solution is this one:
```
def get_mask_center(mask):
        mask_centers=[]
        for nmask in range(mask.shape[2]):
            tr_area=np.argwhere(mask[:,:,nmask]==True)
            x_max=tr_area.max(axis=0)[0]
            x_min=tr_area.min(axis=0)[0]
            y_max=tr_area.max(axis=0)[1]
            y_min=tr_area.min(axis=0)[1]

            x_center=x_min+(x_max-x_min)/2
            y_center=y_min+(y_max-y_min)/2
            mask_centers.append([x_center, y_center])
    return np.asarray(mask_centers)
```

Call it with: ` mask_centers=get_mask_center(r['masks'])`

Definitely there is another better solution, but for my coding level at least it works

**Comment by ThomHordijk** [comment]
Hi @rasputin1917,

Thank you for taking the time to look into a solution for.
I should probably have closed the issue when found our own solution.
We managed to solve the issue by calculating the threshold with cv2.threshold, from that we calculate the contours, cv2.findContours. Using these the moments of the mask can be derived, cv2.moments. 
The represent for instance the outer values of the mask. 

Never the less thank you for going through the effort. And once again, I am sorry for not having closed the issue when it was solved.

**Comment by andreasalamanos** [comment]
> Hi @rasputin1917,
> 
> Thank you for taking the time to look into a solution for.
> I should probably have closed the issue when found our own solution.
> We managed to solve the issue by calculating the threshold with cv2.threshold, from that we calculate the contours, cv2.findContours. Using these the moments of the mask can be derived, cv2.moments.
> The represent for instance the outer values of the mask.
> 
> Never the less thank you for going through the effort. And once again, I am sorry for not having closed the issue when it was solved.

@ThomHordijk,

can you share your code?
