### ISSUE TITLE
How to deal with Polygons having some points outside the image

### ISSUE THREAD

**Issue by AyushP123** [matterport/Mask_RCNN#1514]
Hi,
      For a few images, our polygon annotation points have gone beyond the height and width of the image. We were getting 'index out of bounds' error for these images, for which we clipped the x and y co-ordinate of the polygons. However this has led to the network loss becoming nan. How should we proceed ahead without ignoring the polygons whose points lie outside the image.

**Comment by freezurbern** [comment]
While I have not had this issue myself, I would make sure the polygons are shaped correctly after the clipping process. Perhaps adding a pixel of buffer from the edge of the image would also help? This sounds similar to the point made here: 
> Note: we add 1 pixel of padding in each direction because the contours module doesn't handle cases where pixels bleed to the edge of the image
- http://www.immersivelimit.com/create-coco-annotations-from-scratch

While that is not the same as your problem, it seems worth a shot.
