### ISSUE TITLE
How to use GPU training when there is only one GPU？

### ISSUE THREAD

**Issue by chenyanyin** [matterport/Mask_RCNN#1516]
In config.py,
Uncomment to train on 8 GPUs (default is 1)
GPU_COUNT = 1
but just only one GPU, how to training with GPU?

**Comment by monk678** [comment]
Did you solve the problem?

**Comment by chenyanyin** [comment]
Using tensorflow-gpu is ok

**Comment by chenyanyin** [comment]
> Did you solve the problem?

Using tensorflow-gpu is ok

**Comment by chenyanyin** [comment]
> Did you solve the problem?

Using tensorflow-gpu is ok
