### ISSUE TITLE
coco eval accuracy is low

### ISSUE THREAD

**Issue by hao522** [matterport/Mask_RCNN#152]
I ran the evaluation on minival 5K based v2 model you provided, the mask AP is 0.233, which seems a bit low compared to the original paper, is this a normal number?

**Comment by waleedka** [comment]
The minival evaluation results are listed on the [Releases page](https://github.com/matterport/Mask_RCNN/releases). Please verify that you're doing the test correctly. And if you're certain, please provide more details on how you're running the test.

**Comment by hao522** [comment]
yes, I tested on COCO2014 minival several times, the detection AP is 0.260 and the segmentation AP is 0.233. My environment is tensorflow 1.4, python 2.7, with 3 GTX1080 GPUs.

**Comment by waleedka** [comment]
Can you try on Python 3? There is a small chance it might make a difference due to differences in how Python 2.7 and Python 3 handle divisions with multiple data types.

**Comment by hao522** [comment]
Yeah, I managed to get the same result on Python3, seems that the different versions of Python caused the problem, thx

**Comment by waleedka** [comment]
Good to know. Thanks for reporting back.
