### ISSUE TITLE
Bounding Box Coordinates starting pixel

### ISSUE THREAD

**Issue by andreasalamanos** [matterport/Mask_RCNN#1528]
Hi all,
I was wondering from which pixel point of the image does the bounding box coordinate start??

I mean if my r["rois"] is lets say  [113,  84 , 117 , 93] (x1,y1,x2,y2). Which corner is the one that I start counting 113 pixels on x-axis and 84 on y-axis, in order to find the starting pixel of my bounding box?

How can I reverse the bounding box results in order to reverse the output 90 degrees counter-clockwise??

thanks

--

**Comment by MathiasKahlen** [comment]
Apparently rois are (y1, x1, y2, x2) and x increases from left to right and y increases from top to bottom. So if x is 0 it is in the left side and if y is 0 then its in the top. The other two coordinates (y2, x2) are the opposite corner of the (y1, x1). So (y1, x1) must be the upper left corner of the box.
