### ISSUE TITLE
Unable to override the load_mask() function    

### ISSUE THREAD

**Issue by tanpreet97** [matterport/Mask_RCNN#1532]
I am using Mask_RCNN to localize the damaged region in the car. I have annotated my images using the VIA tool as used in the balloons example. Therefore, I used the same load_mask() function used in the balloon.py file but on running the inspect_data.ipynb file, I am being shown the error:

WARNING:root:You are using the default load_mask(), maybe you need to define your own one.
My load_mask() function is unable to override the parent function.
So, please help.

**Comment by 1chimaruGin** [comment]
Have you fixed it? I'm facing same error.

**Comment by Abdiflame** [comment]
Hello, I was facing the same problem. I solved it by re-adjusting the indentation of the code. Try to check out the class KangarooDataset(Dataset): functions indentation :)
