### ISSUE TITLE
re.error: nothing to repeat at position 0 

### ISSUE THREAD

**Issue by HAMZARaouia** [matterport/Mask_RCNN#1537]
![image](https://user-images.githubusercontent.com/37270416/58787798-d8f09e00-85ea-11e9-91f8-0ead0313ef09.png)

**Any ideas on how to fix this ?**
@waleedka @moorage @PavlosMelissinos @haeric @rymalia 
Thank you

**Comment by aferjani** [comment]
Same error here. Anyone managed to solve it?

**Comment by johnny-brav0** [comment]
Did you find a solution, if yes please share, I'm having a similar issue. Thanks:)
