### ISSUE TITLE
Model does not train from 'last'

### ISSUE THREAD

**Issue by dsouzinator** [matterport/Mask_RCNN#1546]
I am trying to train my model from 'last'. I have previously trained my model 'heads', now i wish to train 'all'. My code is similar to [#362](https://github.com/matterport/Mask_RCNN/issues/362) 
I trained my 'heads' first using the initialization code similar to #362
followed by
`model.train(dataset_train,dataset_val,
                learning_rate=config.LEARNING_RATE,
                epochs=30,
                layers='heads')`

A while later in another file, I trained 'all' layers using the same initial code followed by 
`model.train(dataset_train,dataset_val,
                learning_rate=config.LEARNING_RATE,
                epochs=30,
                layers='all')`
I also set `init_with = "last"`.

OUTPUT
 
.
.
.
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)

This model structure is the output. After this execution finishes without any error.
Training doesn't take place. Nor is a new weights file saved.
My code file is linked [here](https://github.com/dsouzinator/melanoma-MaskRcnn/blob/master/maskrcnn.py)

**Comment by genausz** [comment]
you can replace your second stage epochs parameters to 60, because the epochs here means the final epoch of your whole trainning process.

```
model.train(dataset_train,dataset_val,
                learning_rate=config.LEARNING_RATE,
                epochs=60,
                layers='all')
```

**Comment by dsouzinator** [comment]
Thank you, that makes sense. Checked it out, works perfectly.
