### ISSUE TITLE
[{'rois': array([], shape=(0, 4), dtype=int32), 'class': array([], dtype=int32), 'scores': array([], dtype=float32), 'mask': array([], shape=(426, 640, 0), dtype=float64)}]

### ISSUE THREAD

**Issue by buaacarzp** [matterport/Mask_RCNN#1558]
this result is right? I use the coco's net of  maskrcnn_coco.h5   and turn it to .pb file  and use the image in the file of the images ,but the output is ```[{'rois': array([], shape=(0, 4), dtype=int32), 'class': array([], dtype=int32), 'scores': array([], dtype=float32), 'mask': array([], shape=(426, 640, 0), dtype=float64)}]```, why it is not print the values of the 'rois','class','scores'  and print the None value ?

**Comment by 121649982** [comment]
have you solved the problem?can you tell me how to convert the .h5 to pb?I'm working for this too

**Comment by angyee** [comment]
i am getting results like this, but how to display the result of image?

[{'rois': array([[244, 287, 590, 721],
[216, 737, 426, 925]], dtype=int32), 'class': array([1, 1], dtype=int32), 'scores': array([0.9834276 , 0.76979005], dtype=float32), 'mask': array([[[False, False],
[False, False],
[False, False],
...,
[False, False],
[False, False],
[False, False]],

[[False, False],
[False, False],
[False, False],
...,
[False, False],
[False, False],
[False, False]],

[[False, False],
[False, False],
[False, False],
...,
[False, False],
[False, False],
[False, False]],

...,

[[False, False],
[False, False],
[False, False],
...,
[False, False],
[False, False],
[False, False]],

[[False, False],
[False, False],
[False, False],
...,
[False, False],
[False, False],
[False, False]],

[[False, False],
[False, False],
[False, False],
...,
[False, False],
[False, False],
[False, False]]])}]
