### ISSUE TITLE
instance segmentation for person

### ISSUE THREAD

**Issue by GittersYang** [matterport/Mask_RCNN#1563]
I want to get the instance of people.
How can I do to train coco for one class(person)?

**Comment by genausz** [comment]
in samples/coco/coco.py, you can found the code in line 94-106 as bellow:
```
class CocoDataset(utils.Dataset):
    def load_coco(self, dataset_dir, subset, year=DEFAULT_DATASET_YEAR, class_ids=None,
                  class_map=None, return_coco=False, auto_download=False):
        """Load a subset of the COCO dataset.
        # other comments
        class_ids: If provided, only loads images that have the given classes.
        """
```
you can provide the id of class(people) to the *class_ids* , such that you can train a model only for class(person).

**Comment by GittersYang** [comment]
Do you mean to do this?：class_ids=people  
Or something else?

**Comment by genausz** [comment]
> Do you mean to do this?：class_ids=people
> Or something else?

No, you should set a dict of classes's ids to class_ids.
As in coco dataset,
```
class_names = ['BG', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', ...] 
```
you should set class_ids = [1].

**Comment by GittersYang** [comment]
ok, thank you for the timely reply.
