### ISSUE TITLE
What does the mask shape need to be for multiple classes?

### ISSUE THREAD

**Issue by satrya-sabeni** [matterport/Mask_RCNN#1565]
Hi,

I want to train a model on 5 classes, I don't exactly know in which shape to return my mask from the `load_mask()` function. Currently my mask shape looks like this:

`mask.shape`
(1080, 1618, 5)

where every pixel/3rd dimension is mapped to a 5 long array that corresponds to one of the 5 classes.
```
[1,0,0,0,0]:1, #1 Class A
[0,1,0,0,0]:2, #2 Class B
[0,0,1,0,0]:3, #3 Class C
[0,0,0,1,0]:4, #4 Class D
[0,0,0,0,1]:5  #5 Class E
```
In my `class_ids` I put an array with the classes that are found in that image, like:
`array([1, 2, 3])`
 
With this format I'm able to visualise it with `visualize.display_top_masks(image, mask, class_ids, dataset_train.class_names)`, which seems to be correct (I don't have instances, that's why every object is the same colour).

![Image](https://i.ibb.co/684bXYh/download.png)

However when I train I get the error:
```
File "/.../Mask_RCNN-master/mrcnn/model.py", line 1265, in load_image_gt
    class_ids = class_ids[_idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 5
```
This for example is an image that contains objects that belong to 3 classes of the 5. So I'm guessing the 3rd dimension of `mask` always needs to be as long as the `class_ids`. But can anyone tell what exactly I need to be putting in these 2 variables?

**Comment by satrya-sabeni** [comment]
Got it a while ago but for anyone who has the same problem, per `mask` image the array should be formatted like this: [H, W, binary array with as length the amount of objects the image has(without background)]. The `class_ids` is the same length as the binary array in the `mask` with each item representing the class_id that corresponds to that item.

For example:
mask array: 
```
[[0, 0, 1, 0], #class 3
[1, 0, 0, 0], #class 1
[0, 0, 0, 1]] #class 4
```
clasd_ids: `[1, 2, 3, 4]`

The length depends on the objects found in the mask, so this is not fixed for all masks.

**Comment by jasdal365** [comment]
@satrya-sabeni Could you please share your code?

**Comment by satrya-sabeni** [comment]
> @satrya-sabeni Could you please share your code?

I don't have it anymore unfortunately
