### ISSUE TITLE
Post-processing for Improvement in masks

### ISSUE THREAD

**Issue by itsrrworld** [matterport/Mask_RCNN#1577]
I am working on building footprint detection with the use of Mask_RCNN. I have completed the training process and testing with different images. Now my doubt is how to perform post-processing step to improve the quality of masks. 

Something like shown in below image
![Capture](https://user-images.githubusercontent.com/25461059/59961979-cf2ccd00-94fc-11e9-8e01-5b295fe3b415.PNG)

Can anyone help me with this? Thanks in advance😁

**Comment by berylyellow** [comment]
the same question to me，do not know how to do post-processing

**Comment by itsrrworld** [comment]
I have sorted it out. You can play with some of the operations available at [skimage.morphology](https://scikit-image.org/docs/dev/api/skimage.morphology.html), [skimage.measure](https://scikit-image.org/docs/dev/api/skimage.measure.html) or [skimage.filters](https://scikit-image.org/docs/dev/api/skimage.filters.html) like erosion, dilation, binary_fill_holes etc. Or you can also use CV2 morphological operations instead of skimage.
