### ISSUE TITLE
No module named request?

### ISSUE THREAD

**Issue by majie19930819** [matterport/Mask_RCNN#158]
when I run the demo.ipynb in juptyer notebook, the error is  "No module named request" when import import urllib.request in coco.py

**Comment by LightGal** [comment]
Me too.

[And they say urllib.request has been deprecated.](https://stackoverflow.com/questions/36781105/import-urllib-request-importerror-no-module-named-request)

I am trying to solve.

**Comment by LightGal** [comment]
python3 is ok

**Comment by waleedka** [comment]
Since Python3 is okay then I'll close this issue. This repo is currently targeted to Python 3. However, if someone provides a PR that ensures it works for both 2.7 and 3+ then I'll merge it.
