### ISSUE TITLE
time cost on predicting single image is 3s

### ISSUE THREAD

**Issue by Stuartqin** [matterport/Mask_RCNN#1605]
The prediction is made according to Mask_RCNN/samples/demo.ipynb. I iterated the part of 'model.detect([image], verbose=1)' using the same picture and used time.time() to test the time cost on single iteration.  I found that it took around 3s to predict single image no matter it is the first or second iteration. Is there any way to reduce the prediction time? 
I used 'nvidia-smi -l 1'  to monitor the GPU(Tesla P100), and found no running processes. The memory-usage is also 0MiB/16276MiB. Is there anything wrong with my config?

**Comment by karthik9319** [comment]
Hi, @Stuartqin I see you closed this issue. Even I'm facing this issue were you able to solve it? If so can you tell me how did you do it?
