### ISSUE TITLE
train on coco dataset with limited categories we need

### ISSUE THREAD

**Issue by mrzw** [matterport/Mask_RCNN#161]
Hi @waleedka ,
Thanks for the impressive work.
I want to train the limited categories of coco other than the all 80 categories with the weight you trained on COCO as initial weight (mask_rcnn_coco.h5), what should I do?

**Comment by hao522** [comment]
same question

**Comment by BugaDM** [comment]
Inside the Dataset class defined in COCO.py, the load_coco function has a parameter called class_ids: if provided, only loads images that have the given classes. Then, you just have to identify de IDs of the classes you want to train, send that parameter and train the model using the code inside COCO.py.

**Comment by waleedka** [comment]
As @BugaDM mentioned. And see the similar thread in #104

**Comment by Ekta246** [comment]
> Inside the Dataset class defined in COCO.py, the load_coco function has a parameter called class_ids: if provided, only loads images that have the given classes. Then, you just have to identify de IDs of the classes you want to train, send that parameter and train the model using the code inside COCO.py.

Thanks for the explanation. I have one more question what if I wanted to add one more custom category class(which I have converted into coco format annotations) to the existing limited coco category classes
