### ISSUE TITLE
Display instance segmentation from the balloon sample?

### ISSUE THREAD

**Issue by kientruccapa** [matterport/Mask_RCNN#1619]
Hi there,
How to visualize instance segmentation from the balloon sample?
thanks!

**Comment by KellyChenTue** [comment]
Hello, are you trying balloon.py ? The result is saved in your working directory.

**Comment by hoangcuongbk80** [comment]
Hi,

Run balloon_inference.py from [here](https://github.com/hoangcuongbk80/Object-RPE/tree/master/Mask_RCNN/samples/balloon) and you should get masks visualized as the following:

![result](https://user-images.githubusercontent.com/10355081/60948172-99585880-a2f2-11e9-91b1-6a8136632c74.png)

**Comment by kientruccapa** [comment]
@hoangcuongbk80  It works! Great, thank bro.
@KellyChenTue The image saved is a splash image, not masks.
