### ISSUE TITLE
Multi-gpu inference error 

### ISSUE THREAD

**Issue by DecentMakeover** [matterport/Mask_RCNN#1634]
@waleedka 

while using the demo,ipynb , when i run the inference using 2 GPU's it works fine , but when i scale that to 4GPUS i get

    InvalidArgumentError: Input to reshape is a tensor with 600 values, but the requested shape has 4800 
    [[{{node tower_0_4/mask_rcnn/mrcnn_detection/Reshape_1}} = Reshape[T=DT_FLOAT, 
    Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"] 
    (tower_0_4/mask_rcnn/mrcnn_detection/packed, 
    tower_0_4/mask_rcnn/mrcnn_detection/Reshape_1/shape)]] 

Any ideas?
Thanks

**Comment by chAwater** [comment]
I think PR #1082 will fix it.

**Comment by DecentMakeover** [comment]
@chAwater  My guess is PR #1082 only works for 2GPUS's but i am yet to test it out, so let me check and  ill revert.Thanks for your time.

**Comment by chAwater** [comment]
OK, looking forward to your result. I only have two GPUs and this PR works. 
I think (blurry) that I saw some other developer's comments or PRs about 4 or 8 GPUs, maybe you can try some other multi-GPU related PRs.

**Comment by DecentMakeover** [comment]
sure, i should post something by tonight.

**Comment by DecentMakeover** [comment]
@chAwater the changes work , i am able to run this on 5,6,7,8 GPU'S.

thanks for your help!

**Comment by chAwater** [comment]
Great! Good to know!
