### ISSUE TITLE
What is heads and 3+ 4+ layers while training

### ISSUE THREAD

**Issue by yerzhik** [matterport/Mask_RCNN#1637]
While finetuning what would be the best layers to select? But usually you would want to train lower layers (if top layer is input): assuming that higher levels learnt some general features, and you want to fine tune lower layers with some additional specific samples. 
Which of those is lower: heads, 3+, 4+ maybe something else?

**Comment by adityashrm21** [comment]
You can get an idea of the stages here: https://engmrk.com/residual-networks-resnets/

Also, `head` means the last layers as mentioned in the docstring:

```layers: Allows selecting wich layers to train. It can be:
            - A regular expression to match layer names to train
            - One of these predefined values:
              heads: The RPN, classifier and mask heads of the network
              all: All the layers
              3+: Train Resnet stage 3 and up
              4+: Train Resnet stage 4 and up
              5+: Train Resnet stage 5 and up```

**Comment by yerzhik** [comment]
Thank you so much!
