### ISSUE TITLE
How to display subset of classes during inference?

### ISSUE THREAD

**Issue by kHarshit** [matterport/Mask_RCNN#1666]
I want to display a subset of the coco classes during inference on an image e.g. if I want to display cars *(class id: 3 as per `demo.ipynb`)* or persons *(class id: 1)* only, what changes should I make in `visualize.py` ([`display_instances()`](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/visualize.py#L83) function)?

**Comment by kHarshit** [comment]
Solved it!

No need to modify any function in `visualize.py`, simply remove the unwanted class outputs from `model.detect` during inference. 

e.g. 
```
results = model.detect([image], verbose=1)

# Visualize results
# for first image (as we're providing single image only)
r = results[0]
```
Remove values from r['rois'], r['class_ids'], r['masks'], and r['scores'] corresponding to unwanted class in r['class_ids'].

**Comment by sebo361** [comment]
Hi @kHarshit can you please share your code for only displaying a subset of classes? thx

**Comment by kHarshit** [comment]
@sebo313 Say, I only want to display people (corresponding to `label 1` in COCO):

```
results = model.detect([image], verbose=1)

# Visualize results
# for first image (as we're providing single image only)
r = results[0]
# print(r)  # dictionary of np arrays

# get indices corresponding to unwanted classes
indices_to_remove = np.where(r['class_ids'] != 1)
print(indices_to_remove)

# remove corresponding entries from `r`
new_class_ids = np.delete(r['class_ids'], indices_to_remove, axis=0)
new_rois = np.delete(r['rois'], indices_to_remove, axis=0)
new_scores = np.delete(r['scores'], indices_to_remove, axis=0)
new_masks = np.delete(r['masks'], indices_to_remove, axis=2)

visualize.display_instances(image, new_rois, new_masks, new_class_ids, 
                            class_names, new_scores)
```

**Comment by sebo361** [comment]
awesome thanks @kHarshit!
