### ISSUE TITLE
Google Colab installation ModuleNotFoundError

### ISSUE THREAD

**Issue by jeremytandjung** [matterport/Mask_RCNN#1673]
Hello, 

I'm trying to use this module in Google Colab.
So I successfully installed the module with the following commands.

` !git clone https://github.com/matterport/Mask_RCNN.git`
`!pip install -r 'Mask_RCNN/requirements.txt' `
`!cd Mask_RCNN ; python setup.py install`

Then `!pip show mask-rcnn` works, but when I tried to import mrcnn it said 'No Module Found'
![image](https://user-images.githubusercontent.com/35509768/62275370-a4387180-b3f6-11e9-81bb-e6a3159c8916.png)

Can someone help me out with this problem? Thank you so much.

**Comment by akrsrivastava** [comment]
I also face this error on Colab. I restart the kernel and reinstall mrcnn to fix this.

**Comment by Benito2204** [comment]
@ jeremyimmanuel 

I need your help on running MaskRCNN in colab.

If you don't mind, can you provide your email ID?

Thanks

**Comment by marwazaa** [comment]
@jeremyimmanuel 
I also find this error No module named 'mrcnn' in colab, please can you help me.
Thanks

**Comment by jeremytandjung** [comment]
@marwazaa i think i fixed it by restarting the kernel and just reinstalling the module. That was a year ago so I don't remember how I fixed it. Sorry.

**Comment by atpshivakumar** [comment]
%cd Mask_RCNN/
!python3 setup.py install

Try above lines before running the main code to get rid of module not found error for mrcnn

**Comment by fahiers** [comment]
> %cd Mask_RCNN/ !python3 setup.py install
> 
> Try above lines before running the main code to get rid of module not found error for mrcnn

TY MENNN !!!
