### ISSUE TITLE
scratch

### ISSUE THREAD

**Issue by mjjackey** [matterport/Mask_RCNN#1684]
I want to change the backbone from ResNet to ResNeXt, so I can't directly use the pre-trained model, how can I train from scratch? Thank you!

**Comment by Amrimn** [comment]
@mjjackey did yo know how to train from scratch?

**Comment by mjjackey** [comment]
> @mjjackey did yo know how to train from scratch?

To train a model from scratch, just don't call model.load_weights() after creating the model object.

**Comment by hoangphucITJP** [comment]
Hi @mjjackey . Did you implement ResNeXt backbone?

**Comment by mjjackey** [comment]
> 
> 
> Hi @mjjackey . Did you implement ResNeXt backbone?
Hi, I intended to do it, but, finally, I didn't do it.
