### ISSUE TITLE
Bounding box in terms of original image dimesnion

### ISSUE THREAD

**Issue by akrsrivastava** [matterport/Mask_RCNN#1698]
My original image is of shape 892 X 643 and the predicted bounding box is for the resized image 1024 X 1024. How do I get the bounding box for the original image?
If it is not possible, then do I need to train with IMAGE_RESIZE ="none" ?

**Comment by harshgrovr** [comment]
@akrsrivastava

When we specify IMAGE_MAX_DIM = 1024, does it mean that all the images, masks and bounding box will be normalized according to this size?

**Comment by akrsrivastava** [comment]
Turns out that the predictions are actually in the scale of the original image, not the resized image. @harshgrovr Internally during training / predictions the calculations happen as per the Image_max_dim but the predictions are generated in the scale of the original image.
