### ISSUE TITLE
Debug on Keras

### ISSUE THREAD

**Issue by hao522** [matterport/Mask_RCNN#172]
How could I debug this model, say if I would like to get some intermediate values in PyramidROIAlign() func, seems like there's no sess.run(some_node) in the training process in keras

**Comment by waleedka** [comment]
See the ```inspect_model``` notebook. It displays intermediate values at different levels. If you need to dig deeper, you'd need to dive further into Keras.

**Comment by hao522** [comment]
got it, thx
