### ISSUE TITLE
Caculate Precision Recall and Ground Truth for the whole dataset

### ISSUE THREAD

**Issue by quanghuy0497** [matterport/Mask_RCNN#1722]
Hello, as far as I know, there are functions `plot_overlaps` and `plot_precision_recall` from `visualize.py` that support us draw precision-recall curve and grid of ground truth objects, but only for each image.
But now I have a dataset just for testing, and I want to draw precision-recall curve and grid of ground truth of this whole testing dataset for evaluated. So, is there anybody could help me with that problem?
Here is my code to calculate mAP for this whole dataset
```python
dataset_test = object.CustomDataset()
dataset_test.load_custom(custom_DIR, "test")
dataset_test.prepare()
APs = []
np.random.shuffle(dataset_test.image_ids)
for image_id in dataset_test.image_ids:
   image, image_meta, gt_class_id, gt_bbox, gt_mask =\
       modellib.load_image_gt(dataset_test, config,
                              image_id, use_mini_mask=False)
   molded_images = np.expand_dims(modellib.mold_image(image, config), 0)
   results = model.detect([image], verbose=0)
   r = results[0]
   AP, precisions, recalls, overlaps =\
       utils.compute_ap(gt_bbox, gt_class_id, gt_mask,
                        r["rois"], r["class_ids"], r["scores"], r['masks'])
   APs.append(AP)
print("mAP: ", np.mean(APs) * 100, "%")
```

**Comment by AndreiBaraian** [comment]
How did you manage to calculate the precision/recall curve for the whole dataset?

**Comment by timofurrer** [comment]
@quanghuy0497 do you mind clarifying how you solved it?

**Comment by ApoorvaOjha** [comment]
> How did you manage to calculate the precision/recall curve for the whole dataset?

did you find out how to do it?
