### ISSUE TITLE
Training with empty images

### ISSUE THREAD

**Issue by ghost** [matterport/Mask_RCNN#1729]
Hello everybody,

I am working on an instance segmentation task with very few objects that can be placed in a box. I've already trained a model which works fine in most cases. However I get the problem of wrong object detections in an empty box/image.

To adress this problem I want to retrain the model with some additional empty box images to adapt the model to this particular case.

However as far as I dug into the issue, the training procedure does not consider images with no annotation attached to it. The following lines are an extract of an .json annotation file I use. As you can see the first image has an "annotation" attached to it whereas the second doesn't. Thus the second image will not be considered during training.

Does anyone know how to use the code of this repo to train image samples that do not contain an object? Can I make it work by changing the annotation file or do I need to change the code? If I have to change the code how deep do I have to go into the details of the training process?
I'd appreciate any solution or usefull comment adressing this problem. Thank you!

{"images": [{"id": 1, "file_name": "Train001520.tif", "width": 768, "height": 576, "date_captured": "2019-07-12 19:49:23.068417", "license": 1, "coco_url": "", "flickr_url": ""}, {"id": 2, "file_name": "Train001521.tif", "width": 768, "height": 576, "date_captured": "2019-07-12 19:49:23.068417", "license": 1, "coco_url": "", "flickr_url": ""}], "annotations": [{"id": 1, "image_id": 1, "category_id": 1, "iscrowd": 0, "area": 28630, "bbox": [240.0, 115.0, 315.0, 334.0], "segmentation": [[338.0, %... AND SO ON%  438.5, 286.0, 448.5]], "width": 768, "height": 576}], "categories": [{"supercategory": "banana", "id": 1, "name": "banana"}]}

**Comment by jvendrig** [comment]
There's been many similar questions. E.g. https://github.com/matterport/Mask_RCNN/issues/757
I've seen one pull request only: https://github.com/matterport/Mask_RCNN/pull/1088
