### ISSUE TITLE
pycocotolls install on the windows platform

### ISSUE THREAD

**Issue by hhuhhu** [matterport/Mask_RCNN#173]
can't install it on the windows, anybody have success?
when i excute "python setup.py build_ext install", it reports "error D8021： invalid parameter/Wno-cpp"

**Comment by philferriere** [comment]
@hhuhhu, try the instructions [here](https://github.com/philferriere/cocoapi):
- Install the [Visual C++ 2015 Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)
- Run `pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI`

Let me know if you still have issues after that. Good luck!

**Comment by hhuhhu** [comment]
i download vs2017 build tools and run that code, it didn't report the previous issue, but there's new issue occurred."Can't find file io.h".

**Comment by hhuhhu** [comment]
i uninstall vs2017 and install vs2015 build tools as what you say, not it worked.Thank you

**Comment by farzadzare** [comment]
i install 2015 build tools as what you say but now it works
