### ISSUE TITLE
What is the meaning of BACKBONE_STRIDES?

### ISSUE THREAD

**Issue by Mabinogiysk** [matterport/Mask_RCNN#175]
Is BACKBONE_STRIDES the feature map size in each stage?
If I change the image size from 128\*128 to 512\*512, should I change the value of BACKBONE_STRIDES?
Thanks!

**Comment by waleedka** [comment]
The backbone stride is the stride of each layer of the backbone network relative to the input image. For example, the C2 layer of the pyramid has a stride of 4, meaning that it's dimensions are 1/4 of the dimensions of the input image (i.e. if the input image is 1024x1024 the C2 size is 256x256). 

Changing the input image size doesn't affect the backbone stride.

**Comment by John1231983** [comment]
@waleedka : What is BACKBONE_STRIDES value when I use resnet50 model, instead of 101? Because your document said that 
>The strides of each layer of the FPN Pyramid. These values
    are based on a Resnet101 backbone.
    BACKBONE_STRIDES = [4, 8, 16, 32, 64]

**Comment by waleedka** [comment]
Resnet50 has the same strides as Resnet101
