### ISSUE TITLE
Can we use this Mask_RCNN model for Classification?

### ISSUE THREAD

**Issue by Akhiladdh** [matterport/Mask_RCNN#1751]
Is it possible to customize and use Mask-RCNN model on Classification dataset?
Dataset format: Image and corresponding class.

**Comment by Hunain-Gillani** [comment]
Please elaborate on what you mean by classification dataset?

**Comment by Akhiladdh** [comment]
I want to check if I can use this model for [MURA](https://stanfordmlgroup.github.io/competitions/mura/) dataset.

**Comment by Hunain-Gillani** [comment]
Mask RCNN is typically used for instance segmentation, and it masks the instance/object in the image. If you think you can work with it, then Mask RCNN will work for MURA dataset.

**Comment by Akhiladdh** [comment]
My Input Data will not have masks,. So, I am not sure if I can customize this Model.

**Comment by Hunain-Gillani** [comment]
Well, you could manually annotate images, and compose masks. But If you don't want that, then mask rcnn is not for you.

**Comment by Akhiladdh** [comment]
Thank you!
