### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Elephmoon** [matterport/Mask_RCNN#1759]
when trying to learn from the train_shapes file, the error 'Model' object has no attribute 'metrics_tensors'. How to handle this?

![Снимок экрана от 2019-09-22 21-49-08](https://user-images.githubusercontent.com/16652418/65392914-083a3f00-dd83-11e9-98bf-01545e5c2fab.png)

**Comment by Elephmoon** [comment]
has reinstalled all the dependencies and has been corrected

**Comment by gethubwy** [comment]
hi,bro,I didn't understand how to handle this problem,Can you be more specific?

**Comment by Elephmoon** [comment]
Hey. As far as I remember, I just reinstalled all the dependencies through conda, and that helped.
