### ISSUE TITLE
How I can Train Mask-RCNN

### ISSUE THREAD

**Issue by matiqul** [matterport/Mask_RCNN#176]
Can anyone tell me how I can set the path to train Mask-RCNN :
parser = argparse.ArgumentParser(
description='Train Mask R-CNN on MS COCO.')
parser.add_argument('-command',
metavar='train',
help="'train' or 'evaluate' on MS COCO")
parser.add_argument('-model',
metavar='COCO_DIR',
help='Directory of the MS-COCO dataset')
parser.add_argument('-dataset',
metavar='COCO_DIR/mask_rcnn_coco.h5',
help="Path to weights .h5 file or 'coco'")
args = parser.parse_args()
print("Command: ", args.command)
print("Model: ", args.model)
print("Dataset: ", args.dataset)

It outputs : Command : None
Model : None
Dataset: None

**Comment by hlthu** [comment]
please see the header of the file `coco.py`.

**Comment by matiqul** [comment]
Thanks I have solved this problem....
