### ISSUE TITLE
Getting the result of the prediction inference on large images

### ISSUE THREAD

**Issue by Amrimn** [matterport/Mask_RCNN#1762]
I am using maskrcnn for  the detection of oil slicks on the sea surface using radar images
In fact, I trained Maskrcnn on a dataset of SAR images(tif).  Everything works fine for the training. However, I have some issues to run the prediction on big images. When I give as input small images (2000,2000), it works. However, when I try bigger sized  images, for instance, (8000 ,5000), it generates the error below: 
Resource exhausted: OOM when allocating tensor with shape[1,64,7264,7264] .Kind regards
I am trying to solve this by dividing the images into crops and running the prediction on every crop,  then reconstructing the whole result of the image. The problem is that I don't know how to reconstruct the hole result:
for each crop I get the dictionary of the below arrays.
The dict contains -masks: [H, W, N] instance binary masks.
-rois: [N, (y1, x1, y2, x2)] detection bounding boxes
-class_ids: [N] int class IDs
-scores: [N] float probability scores for the class IDs
I manage to reconstruct the mask as I know the position of the crop in the big image. 
However, for the rest of the dictionary elements, I can't figure out how to group them properly in one array each with respect to the original large image. 
Could you please give me more insight on the above issues? I thank you a lot in advance for your collaboration.

**Comment by RituYadav92** [comment]
Hi,
Are you using just the radar sensor data or you are fusing radar with RGB images?

**Comment by Amrimn** [comment]
Hello,

I'am using only large radar images (8000 * 8000). In fact, to predict these
big images, I crop them into small crops, but that still takes a lot of
memory.
Are you using large images for prediction? If so, can you tell me how you
treat them?

Thanks in advance.
Emna


Le mer. 2 oct. 2019 à 16:42, RituYadav92 <notifications@github.com> a
écrit :

**Comment by Amrimn** [comment]
@RituYadav92 
I'm using only large radar images (~8000 * 8000). In fact, to predict these big images, I crop them into small crops, I get the result for each crops. Then I group the results properly with respect to the original large image. But that still takes a lot of memory and a lot time. 
Do you have an idea how to deal with large images in this case?
Thanks in advance.

**Comment by RituYadav92** [comment]
Hi, 
I am using RGB images and RADAR points combined.  RGB images are normal size not as big as yours. Can you provide 1 or 2 sample radar image which you are referring here?

**Comment by Amrimn** [comment]
@RituYadav92 Ni i can't it's a private data sorry
