### ISSUE TITLE
In tensorflow 2.0 , tf.placeholder cannot be used. 

### ISSUE THREAD

**Issue by ayushmankumar7** [matterport/Mask_RCNN#1792]

**Comment by akrsrivastava** [comment]
Getting similar issue with tf.log

**Comment by daniel-dennis** [comment]
I got this issue too, perhaps requirements.txt on line 7 should be changed from``` tensorflow>=1.3.0``` to ```tensorflow==1.3.0```?

Edit: I've got the demo to work by using ```tensorflow==1.15```

**Comment by akrsrivastava** [comment]
Right now I have added 
`import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()`

as per [this instruction on TF homepage](https://www.tensorflow.org/guide/migrate) .

Not sure whats the best way though.

**Comment by ayushmankumar7** [comment]
I tired the same. There were still some issues. 
Anyway, i followed the instructions by the Owner. 
It worked fine.

**Comment by akrsrivastava** [comment]
@ayushmankumar7 Can you let me know where are the owner's instructions. Thanks!
