### ISSUE TITLE
Can't use my own generated Annotation Mask JSON format in VIA or any annotation tools

### ISSUE THREAD

**Issue by jzrlza** [matterport/Mask_RCNN#1793]
Good morning! I would tell you that there's an inconsistency in JSON annotation formatting from various tools. I tried to load your JSON sample from balloon dataset, but it said the file is corrupt, even it is readable by this project, and I found out that your JSON annotation format parsing does not support current VIA custom generated JSON file from anywhere because of different values and formatting. 

You need to solve this problem, make sure this project supports JSON annotation from any sources. Your formatting might be outdated.

I will appreciate your concerns that I can't train my own model right now due to image annotation problems.

**Comment by LesiChou** [comment]
So am I！But I rewrite the function of loading annotaions, and it works.

**Comment by josephofiowa** [comment]
@jzrlza Are you attempting to use the balloon dataset or something custom? I can help reproduce - joseph@roboflow.ai
