### ISSUE TITLE
Resnet Architecture

### ISSUE THREAD

**Issue by Erwin-fy** [matterport/Mask_RCNN#184]
Thanks for your sharing, and I have a question about Resnet Architecture. 
In Caffe prototxt, the conv_block is behind of the identity_block, which is different from your codes, so  could this affect the results?

**Comment by philferriere** [comment]
Which Caffe prototxt specifically are you referring to, @Erwin-fy? There is already a [discussion thread](https://github.com/matterport/Mask_RCNN/issues/117) on the Resnet architecture used here.  Does it answer your concerns?

**Comment by Erwin-fy** [comment]
Yes, thank you!!
