### ISSUE TITLE
How much GPU memory is needed to train on MS COCO dataset

### ISSUE THREAD

**Issue by XupingZHENG** [matterport/Mask_RCNN#186]
I tried to train on MS COCO dataset, using the command provided in the readme
python3 coco.py train --dataset=/path/to/coco/ --model=imagenet
failed due to insufficient GPU memory, so I wonder how much is GPU memory is needed to run the above command, without changing the default training setup.

**Comment by waleedka** [comment]
You need a 12GB GPU to use the default settings.
