### ISSUE TITLE
Confusion Matrix for Mask-RCNN

### ISSUE THREAD

**Issue by Hunain-Gillani** [matterport/Mask_RCNN#1860]
I'm trying to print the confusion matrix in the model.py file via 

```
Y_pred = model.predict_generator(val_generator, self.VALIDATION_STEPS)
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
print(confusion_matrix(validation_generator.classes, y_pred))
```

code taken from [this](https://gist.github.com/RyanAkilos/3808c17f79e77c4117de35aa68447045)

an exception i raised stating that zero dimension numpy array cannot be concatenated. 

Thanks.

**Comment by qaixerabbas** [comment]
I am trying to do the same. i.e. confusion matrix printing.
but still struggling

**Comment by gautamchitnis** [comment]
@Hunain-G did you resolve this? Please provide details if possible.

**Comment by nandita96** [comment]
@gautamchitnis @Hunain-G , have you able to solve it? please tell how you resolve it ?
