### ISSUE TITLE
In compute_ap, precisions array should be float type

### ISSUE THREAD

**Issue by mangalbhaskar** [matterport/Mask_RCNN#1879]
In [compute_ap](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/utils.py#L715), precisions array should be float type like as done for calculating recalls. Currently, it either gives array of 1 or 0 hence it affects the calculation of mAP.
Original:
```python
  # Compute precision and recall at each prediction box step
    precisions = np.cumsum(pred_match > -1) / (np.arange(len(pred_match)) + 1)
    recalls = np.cumsum(pred_match > -1).astype(np.float32) / len(gt_match)
```
Proposed change for the precision calculation
```python
  # Compute precision and recall at each prediction box step
    precisions = np.cumsum(pred_match > -1).astype(np.float32) / (np.arange(len(pred_match)) + 1)
```

**Comment by Dayan-Zhanchi** [comment]
On an unrelated note, do you know what task the AP is calculated over in the compute_ap method? Is it calculating the AP for mask or bb? Or a combination of both tasks?

**Comment by mangalbhaskar** [comment]
> On an unrelated note, do you know what task the AP is calculated over in the compute_ap method? Is it calculating the AP for mask or bb? Or a combination of both tasks?

It is calculating AP for mask, [see here](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/utils.py#L682)

Additionally, i am planning to provide a switch to use bbox; and compare how AP for mask varies wrt  bbox.

If you need to calculate AP for bbox, refer compute_recall where overlap for bbox is used, [see here](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/utils.py#L786)

Closing this issue as seems like even after changing the precision to float, it did not alter the AP value; would need to look deeper!

**Comment by panamantis** [comment]
Oh my, all my mAPs where 0.0 or 1.0.  Indeed, this needs to be a float.  I'll have to figure out how to request a code change (or do it myself).
