### ISSUE TITLE
[help] convert PNG segmentation masks to right format

### ISSUE THREAD

**Issue by hasibzunair** [matterport/Mask_RCNN#1880]
How can I convert segmentation masks stored as PNG images in order to train it on Mask R-CNN for both multi-class segmentation and instance segmentation? Each of the mask consists of N different kinds of pixel annotations. There are no other annotations such as XML/JSON or polygon formats for this. Below I have attached the instance and class annotations. 

Class map:
![classmap](https://user-images.githubusercontent.com/33185386/69490080-67cecc80-0e50-11ea-8709-d7fc758f201b.png)

Instance map:

![instancemap](https://user-images.githubusercontent.com/33185386/69490081-68676300-0e50-11ea-8ee0-46d048bd114b.png)

Looking for suggestions. Thanks.

**Comment by rakehsaleem** [comment]
Hello, I have been facing similar issue so have you found any solution to the problem on how to use PNG annotations in mask R-CNN. I am also finding the solution but have no success so far!!

**Comment by hasibzunair** [comment]
Unfortunately not. I ended up using another approach for this problem. Maybe it can be of help to you.

https://github.com/hasibzunair/MoNuSAC-ISBI-2020

**Comment by rakehsaleem** [comment]
Thank you for your answer and quick response. I will definitely follow your link and see if that helps me !!
