### ISSUE TITLE
How to train a model from scratch?

### ISSUE THREAD

**Issue by JackLee396** [matterport/Mask_RCNN#189]
I want to modified the structure of the backbone of resnet, so I can't load the pretrained coco model directly. Could you give me some advice on how to train a different backbone model utilizing the pretrained model or training from scratch? Thank you!

**Comment by John1231983** [comment]
@JackLee396 : Have you find the solution? I also want to train my model from scratch but I did not know which script could I run?

**Comment by mjjackey** [comment]
@JackLee396 @John1231983 
The same question, how to train a new backbone from scratch?
