### ISSUE TITLE
for detecting small object , I add C1 featuremap into the model ,now the mrcnn loss is lower ,but the rpn loss is very high,what else should i modify? 

### ISSUE THREAD

**Issue by ChienWong** [matterport/Mask_RCNN#1890]
Now ,I have modify the resnet graph, C1.shape is [512,512,3],  added  C1 and  Upsampled P2 ,and adapted the box size to different feature map,but they are all belong to mrcnn branch,
about the rpn branch, i can not modify anything,
who can teach me how to do it?

**Comment by ChienWong** [comment]
OK, I get it

**Comment by suresh-s** [comment]
I am facing the same issue.  How do you solve it?
