### ISSUE TITLE
Training get stuck at random epochs and random steps

### ISSUE THREAD

**Issue by jqx37** [matterport/Mask_RCNN#1899]
Dear all,
My training gets stuck at random epochs/steps when using GPU training. Sometimes the training would go through without problems, and sometimes it can't. Most of the time, when I re-install Tensorflow 1.15 the training can be continued for 16 - 20 epochs before it hangs. I tried to set "use_multiprocessing=False or True", "workers=1 or 0", ResNet50 and ResNet101. The image size is 1024 by 1024, also tried reducing the ROIs from 200 to 50, none of these methods helped. I have no problem when using CPU to train the model, but it takes too long.
My GPU is Quadra M1000M, which has 4GB VRAM. CUDA 10, Tensorflow 1.15, Keras 2.3.1, Python 3.6.6. My OS is Windows 7 Pro 64 Bits.
I am wondering if this problem is caused by the small VRAM?
Thanks.

**Comment by marcfielding1** [comment]
Yeah so I had this on an NVIDIA GTX 1070 - it just froze my entire OS, multiprocessing and reducing the batch size to one solved it for me.

**Comment by jqx37** [comment]
@marcfielding1 I changed the worker number to 1, and the ROIs from 200 to 50. Now it can go for around 30 epochs, and then it will get stuck. Interestingly, I used to be able to do 10 - 20 epochs when ROI = 200. It seems like a memory and multi-threading issue to me. I really do not know what to do to fix this.

**Comment by jqx37** [comment]
Anybody has luck on using a high-end GPU training the model? What would be the recommended minimum VRAM size? Thanks.

**Comment by jqx37** [comment]
Problem found. It seems to be the TF and Keras version issue. I created a new Python 3.6 environment, then installed TF==1.13.1, and Keras==2.1.3 and the rest of the required libs. "use_multiprocessing=False", "workers=0", Now the program can train models without stuck at random steps. No idea why. Also, a 4GB VRAM is enough to train the ResNet101 backbone with a batch size=1 image. ROI can be even set to 200.

**Comment by soufianemns** [comment]
Dear jqx37 ,
can you provide us with the code that you have modified,"use_multiprocessing=False or True", "workers=1 or 0", ResNet50 and ResNet101" !

**Comment by jqx37** [comment]
@soufianemns 
1. I commented out the following lines in model.py, function def train()
#        if os.name == 'nt':
#            workers = 0
#        else:
#            workers = multiprocessing.cpu_count()
2. self.keras_model.fit_generator(
            train_generator,
            initial_epoch=self.epoch,
            epochs=epochs,
            steps_per_epoch=self.config.STEPS_PER_EPOCH,
            callbacks=callbacks,
            validation_data=val_generator,
            validation_steps=self.config.VALIDATION_STEPS,
            max_queue_size=100,
            workers=0, #workers, --> instead of "workers", I used 0
            use_multiprocessing=False,
        )
3. Be careful with your Tensorflow, and Keras versions.
TF==1.13.1, and Keras==2.1.3 works for me. So far, I am not sure if NumPy and other libs' version matters too much. My solution may not be the cleanest one, but I hope this can help you a bit. If you have any questions, please feel free to leave me a note. Thanks.

**Comment by SarfarazHabib** [comment]
Hi Guys, I am having same problem on tensorflow2, Can you guys please help..

**Comment by aadi-mishra** [comment]
I am having the same issue as well with TF2, my first phase of training succeeded smoothly but It's stuck during the second phase of training.
