### ISSUE TITLE
Wings, limbs and holes

### ISSUE THREAD

**Issue by pannous** [matterport/Mask_RCNN#19]
The model seems to have problems with wings, limbs and holes. Is there theoretical awareness of this and proposed countermeasures?

**Comment by bhack** [comment]
Do you have any visual sample of this issues?

**Comment by pannous** [comment]
the missing holes can be seen right on the main page:
![image](https://user-images.githubusercontent.com/516118/33068403-77383d40-ceb1-11e7-8221-4796070afeef.png)

pictures of giraffes and airplanes will follow

**Comment by waleedka** [comment]
It depends on the training data. 

http://cocodataset.org/#explore?id=162827

**Comment by pannous** [comment]
I see. can this be trained on Moving Images? moving objects give away their shape.
