### ISSUE TITLE
Downloading mask_rcnn_coco.h5 -- Network Failure / Forbidden

### ISSUE THREAD

**Issue by backspace131** [matterport/Mask_RCNN#1906]
Is there any I can do to download these weights? Or any alternative links? I tried downloading this for 3 hours already in any devices and in different network. Is this still open? Please help, thanks.

**Comment by vijaygill** [comment]
1. Open the link https://github.com/matterport/Mask_RCNN/releases/tag/v2.0
2. Scroll down to "Assets" and expand it.
3. download the file mask_rcnn_coco.h5.
4. Place it in the desired directory where the code is trying to download it.

Keep this file safe somewhere and just copy it before you begin training / inferring.

The code tries to download the file if it is not present in the desired location. Manually copying it there prevents the download.

**Comment by backspace131** [comment]
> 1. Open the link https://github.com/matterport/Mask_RCNN/releases/tag/v2.0
> 2. Scroll down to "Assets" and expand it.
> 3. download the file mask_rcnn_coco.h5.
> 4. Place it in the desired directory where the code is trying to download it.
> 
> Keep this file safe somewhere and just copy it before you begin training / inferring.
> 
> The code tries to download the file if it is not present in the desired location. Manually copying it there prevents the download.

Thanks a bunch!
