### ISSUE TITLE
Assertion Error in demo.ipynb

### ISSUE THREAD

**Issue by backspace131** [matterport/Mask_RCNN#1908]
I downloaded everything as recommended in mask rcnn but this error keep popping up.

![error1](https://user-images.githubusercontent.com/58779365/70676810-5ac33180-1cc8-11ea-95da-741d0b4714fb.JPG)

And also this one,

![error2](https://user-images.githubusercontent.com/58779365/70676827-6ca4d480-1cc8-11ea-9f70-9f1a4ede5968.JPG)

I haven`t touch the code yet and felt quite lost. Thanks for the advice!

**Comment by rakehsaleem** [comment]
Could you provide the information about the packages you have been using? 

tensroflow=?
keras=?
python  .... etc etc

**Comment by backspace131** [comment]
> Could you provide the information about the packages you have been using?
> 
> tensroflow=?
> keras=?
> python .... etc etc

Oh, I dont have imgaug but thanks for the response!
