### ISSUE TITLE
Memory Issue Running Demo on Nvidia Jetson TX1

### ISSUE THREAD

**Issue by kaisark** [matterport/Mask_RCNN#191]
I am running into memory issues running the demo notebook on Nvidia Jetson TX1 (4GB RAM). I switched to Resnet50 (model.py) and played around with IMAGE_MIN_DIM and IMAGE_MAX_DIM (config.py), but am still running into resource issues. What is the minimum amount of RAM required to run Mask_RCNN???

Error:
InternalError: TopKOp: Could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to sort input, temp_storage_bytes: 1279, status: too many resources requested for launch
	 [[Node: roi_align_mask/TopKV2 = TopKV2[T=DT_INT32, sorted=true, _device="/job:localhost/replica:0/task:0/gpu:0"](roi_align_mask/add_1/_2419, roi_align_mask/strided_slice_7)]]
	 \[\[Node: mrcnn_mask/Reshape_1/_2441 = _Recv\[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3174_mrcnn_mask/Reshape_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by dhkwon1122** [comment]
I also have same problem, did you solve this?

**Comment by waleedka** [comment]
This is a fairly big model. It's optimized for accuracy rather than lightness or speed. I've had it run on 8GB of video memory, but I haven't tried to run it on less memory. I think 4GB is too small for this type of model.
