### ISSUE TITLE
Is anyone using USE_MINI_MASK = False? Training crashes if I do.

### ISSUE THREAD

**Issue by vijaygill** [matterport/Mask_RCNN#1919]
I am trying to use full size masks and training crashes with following error

"expected input_gt_masks to have shape" (I forgot to save the shape size).

Also my IMAGE_MIN_DIM is 256 and IMAGE_MAX_DIM is 384

Thanks.

**Comment by aashokvardhan** [comment]
It might just be a memory issue.Try setting USE_MINI_MASK = True and slowly increase the min_mask shape (28, 28)-->(56, 56), you should find the threshold mask where you get this exception.Also try reducing the batch size.

**Comment by vijaygill** [comment]
> It might just be a memory issue.Try setting USE_MINI_MASK = True and slowly increase the min_mask shape (28, 28)-->(56, 56), you should find the threshold mask where you get this exception.Also try reducing the batch size.

Thanks @aashokvardhan. I did that exactly (there's one training session going on as I write this post). I upped the mini_mask_size to (56,56) and set USE_MINI_MASK=True. Training has slowed down a bit though.

**Comment by vijaygill** [comment]
Closing this ticket and sticking to size (56, 56).
