### ISSUE TITLE
uint8 vs uint16

### ISSUE THREAD

**Issue by saskra** [matterport/Mask_RCNN#1920]
I have 16 bit images - will this be a problem when using your code (with transfer learning from coco)? Should I convert them to 8 bit while loading them or is the architecture capable of handling those as well?

**Comment by oriolorra** [comment]
Hi,

Have you investigated about it?

Thanks,

**Comment by saskra** [comment]
I tested both and the results were bad, but I have not checked yet whether the 16 bit are causing the problem or something else.

**Comment by oriolorra** [comment]
Okay, thanks!
