### ISSUE TITLE
ValueError: Error when checking input: expected input_image to have 4 dimensions, but got array with shape (3, 512, 512)

### ISSUE THREAD

**Issue by saskra** [matterport/Mask_RCNN#1923]
```shell
ValueError: Error when checking input: expected input_image to have 4 dimensions, but got array with shape (3, 512, 512)
```
I get this error message when I train using the Nucleus example on my own greyscale images following these adaptions: https://github.com/matterport/Mask_RCNN/wiki#training-with-rgb-d-or-grayscale-images

Any suggestions?

**Comment by aashokvardhan** [comment]
Shouldn't the channel count be 1 ??

Did you update your load_image function to read the image as 4 channels??

1) Change IMAGE_CHANNEL_COUNT =1 in config.py
2) Change MEAN_PIXEL = np.array([123])
3) Update the load_image functions in utils:
def load_image_path(self, image_path):
       image = skimage.io.imread(image_path, as_gray=True)*255
       image = np.expand_dims(image, axis=-1).astype(np.unit8)
       return image

**Comment by saskra** [comment]
I had done the first two but number 3 helped, thanks a lot!

**Comment by taroko-mooncake** [comment]
Changing load_image to the above still only gives me three channels [H,W,C]
Did you add another dimension at the start to make [N,H,W,C] ?
