### ISSUE TITLE
Inference time steadily increases (GPU)

### ISSUE THREAD

**Issue by NellTrico** [matterport/Mask_RCNN#1925]
EDIT: I figured it out, it was my fault in some other part of the code, my bad! Closing.

Hello,

I have successfully trained a network to make some predictions. My problem is that the inference time seems to steadily increase over time (continuously running inferences over a day, at 2 inferences/s).
I have observed this behavior on several machines, running the same program. On one of them I started a process yesterday, which was running at 100-150 ms /inference, and after a day (specifically, 170 K inferences) it is running at 150-200ms.

My inference architecture is as follows:

My model is kept within a class, which owns a  tensorflow graph `self.graph = tf.Graph()`
```
with self.graph.as_default():
    [...]
    self.model = mrcnn.model.MaskRCNN(mode='inference',
                                       config=inference_config,
                                       model_dir=MODEL_DIR)
    [...]
```

My model lives in the same class, and is used when prompted with something like this:

```
with self.graph.as_default():
    [...]
    results = self.model.detect([img_arr], verbose=0)
```

I have been profiling memory, using suggestions found here: https://github.com/tensorflow/tensorflow/issues/10408, and did not notice any leak.

Did I do something obviously wrong here?
Has this behaviour been observed by anyone before?

**Comment by monjurulkarim** [comment]
@NellTrico Hi, how did you solve this? I am facing the same problem.

**Comment by NellTrico** [comment]
@monjurulkarim I figured out that it was an unrelated error in my code. I was creating virtual memory blocks that I was not freeing, making the leak harder to detect. Since then I fixed that, ran MRCNN inference code without any visible leak continuously, at the same frequency (~170k inferences a day) for over a week without any issue.
