### ISSUE TITLE
Kernel died as I run demo.ipynb

### ISSUE THREAD

**Issue by backspace131** [matterport/Mask_RCNN#1926]
I run on jupyter notebook and during the process, the image output didn`t load and the kernel just died. Here is the trace in conda prompt:

![error3](https://user-images.githubusercontent.com/58779365/71102416-6e542800-21f3-11ea-9244-6e2a37c27cf4.JPG)

I am using python3.6.9, cuda9.0, cudNN9.0 for windows 10. Thanks for the advice!

**Comment by YatinAdityaT** [comment]
@backspace131  did you solve this error?
