### ISSUE TITLE
KeyError: 'object' when trying to train multiple classes

### ISSUE THREAD

**Issue by SriRamGovardhanam** [matterport/Mask_RCNN#1929]
i wanted to train multiple classes with json file exported by new VIA annotator, but i am stuck at this error
[{'name': 'bottle', 'type': 'unknown', 'image_quality': {'good': True, 'frontal': True, 'good_illumination': True}}]
Traceback (most recent call last):
  File "final2.py", line 367, in <module>
    train(model)
  File "final2.py", line 188, in train
    dataset_train.load_custom(args.dataset, "train")
  File "final2.py", line 126, in load_custom
    num_ids = [int(n['object']) for n in objects]
  File "final2.py", line 126, in <listcomp>
    num_ids = [int(n['object']) for n in objects]
KeyError: 'object'

and here is my equivalent load_mask()

def load_custom(self, dataset_dir, subset):
        """Load a subset of the bottle dataset.
        dataset_dir: Root directory of the dataset.
        subset: Subset to load: train or val
        """
        # Add classes. We have only one class to add.
        self.add_class("object", 1, "bottle")
        self.add_class("object", 2, "glass")
        self.add_class("object", 3, "paper")
        self.add_class("object", 4, "trash")

        # Train or validation dataset?
        assert subset in ["train", "val"]
        dataset_dir = os.path.join(dataset_dir, subset)

        # Load annotations
        # VGG Image Annotator saves each image in the form:
        # { 'filename': '28503151_5b5b7ec140_b.jpg',
        #   'regions': {
        #       '0': {
        #           'region_attributes': {},
        #           'shape_attributes': {
        #               'all_points_x': [...],
        #               'all_points_y': [...],
        #               'name': 'polygon'}},
        #       ... more regions ...
        #   },
        #   'size': 100202
        # }
        # We mostly care about the x and y coordinates of each region
        annotations1 = json.load(open(os.path.join(dataset_dir, "via_region_data.json")))
        # print(annotations1)
        annotations = list(annotations1.values())  # don't need the dict keys

        # The VIA tool saves images in the JSON even if they don't have any
        # annotations. Skip unannotated images.
        annotations = [a for a in annotations if a['regions']]

        # Add images
        for a in annotations:
            # print(a)
            # Get the x, y coordinaets of points of the polygons that make up
            # the outline of each object instance. There are stores in the
            # shape_attributes (see json format above)
            polygons = [r['shape_attributes'] for r in a['regions']] 
            objects = [s['region_attributes'] for s in a['regions']]
            print(objects)
            num_ids = [int(n['object']) for n in objects]
            # load_mask() needs the image size to convert polygons to masks.
            # Unfortunately, VIA doesn't include it in JSON, so we must read
            # the image. This is only managable since the dataset is tiny.
            print("numids",num_ids)
            image_path = os.path.join(dataset_dir, a['filename'])
            image = skimage.io.imread(image_path)
            height, width = image.shape[:2]

            self.add_image(
                "object",  ## for a single class just add the name here
                image_id=a['filename'],  # use file name as a unique image id
                path=image_path,
                width=width, height=height,
                polygons=polygons,
                num_ids=num_ids)

    def load_mask(self, image_id):
        """Generate instance masks for an image.
       Returns:
        masks: A bool array of shape [height, width, instance count] with
            one mask per instance.
        class_ids: a 1D array of class IDs of the instance masks.
        """
        # If not a bottle dataset image, delegate to parent class.
        image_info = self.image_info[image_id]
        if image_info["source"] != "object":
            return super(self.__class__, self).load_mask(image_id)

        # Convert polygons to a bitmap mask of shape
        # [height, width, instance_count]
        info = self.image_info[image_id]
        if info["source"] != "object":
            return super(self.__class__, self).load_mask(image_id)
        num_ids = info['num_ids']
        mask = np.zeros([info["height"], info["width"], len(info["polygons"])],
                        dtype=np.uint8)
        for i, p in enumerate(info["polygons"]):
            # Get indexes of pixels inside the polygon and set them to 1
        	rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])

        	mask[rr, cc, i] = 1

        # Return mask, and array of class IDs of each instance. Since we have
        # one class ID only, we return an array of 1s
        # Map class names to class IDs.
        num_ids = np.array(num_ids, dtype=np.int32)
        return mask, num_ids

    def image_reference(self, image_id):
        """Return the path of the image."""
        info = self.image_info[image_id]
        if info["source"] == "object":
            return info["path"]
        else:
            super(self.__class__, self).image_reference(image_id)

please help me out!

**Comment by aashokvardhan** [comment]
To my knowledge the objects list don't contain a dictionaries with key called 'object'.Ideally the objects should look similar to [{'Event' : '2'}, {'Event' : '1'}].Replace 'object' with 'Event'.

num_ids = [int(n['Event']) for n in objects]

**Comment by SriRamGovardhanam** [comment]
hey, thanks that you replied ... Replacing 'object' with 'Event' doesnt helps me, since this time KeyError:Event 
somehow i sorted things out and finally its working

**Comment by thanawat-hub** [comment]
can you tell about your sorted things out ? I'm stuck same your problem. I run on colab pls help
