### ISSUE TITLE
How to keep background-class detection?

### ISSUE THREAD

**Issue by hoangphucITJP** [matterport/Mask_RCNN#1935]
As I know, the final detections do not include background class detection.

I tried to change this line (https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L716):
```
keep = tf.where(class_ids > 0)[:, 0]
```
to
```
keep = tf.where(class_ids >= 0)[:, 0]
```
But it results no detections when run predict

Any idea of how to keep background-class detection?

**Comment by gaowq2017** [comment]
As we all know, Mask RCNN is instance segmentation!

**Comment by hoangphucITJP** [comment]
> As we all know, Mask RCNN is instance segmentation!

I mean that I want to get the negative ROIs after classifier head. But nevermind, I figured it out

**Comment by lydiakienbaum** [comment]
I have the same question as @hoangphucITJP . How to extract the ROI or the mask of the background for a color analysis?
