### ISSUE TITLE
Using train-shapes notebook with higher resolution runs into error

### ISSUE THREAD

**Issue by Heavy02011** [matterport/Mask_RCNN#194]
I'm using https://github.com/matterport/Mask_RCNN/blob/master/train_shapes.ipynb with the following modification for resolution for creating generic images like

    class ShapesConfig(Config):
       ...
       IMAGES_PER_GPU = 1 #8

       ...

       # Use small images for faster training. Set the limits of the small side
       # the large side, and that determines the image shape.
       IMAGE_MIN_DIM = 256
       IMAGE_MAX_DIM = 512

       # Use smaller anchors because our image and objects are small
       RPN_ANCHOR_SCALES = (32, 64, 128, 256, 512)  # anchor side in pixels
       ...

and get the following error during training

    ERROR:root:Error processing image {'source': 'shapes', 'path': None, 'shapes': [('circle', (29, 31, 44), (169, 63, 88)), ('triangle', (84, 87, 146), (34, 191, 29)), ('square', (251, 147, 186), (78, 236, 120)), ('circle', (208, 46, 20), (368, 136, 112))], 'height': 512, 'width': 512, 'id': 146, 'bg_color': array([ 37, 247, 114])}

Any ideas what I'm overlooking?

**Comment by waleedka** [comment]
You listed the first part of the error, but not the rest. If you're still getting this error, please provide the full stack trace and I'll try to track it.

**Comment by Heavy02011** [comment]
Great your update fixes the error. Thank you very much!
