### ISSUE TITLE
Low values for precision and recall with 4 classes

### ISSUE THREAD

**Issue by giuordy** [matterport/Mask_RCNN#1951]
Hi, i trained the model with only 4 classes and BG. The detection is good but the evaluation results are very low. Precision and recall values are between 0.001 and 0.15 and i don't understand why. I used pretrained coco weights to start training on the following classes: person, car, dining table and chair.  Can someone help me?

**Comment by giuordy** [comment]
Solved. I didn't set CatIds parameter in "evaluate_coco".

**Comment by nabeelkhalid92** [comment]
@giuordy how did you set CatIds parameter?

**Comment by nataliameira** [comment]
@giuordy  how do you did that?
