### ISSUE TITLE
Mask_RCNN compatible with RTX 2080 Ti ?

### ISSUE THREAD

**Issue by Chakib-Belafdil** [matterport/Mask_RCNN#1952]
After having managed to make my code work on a Quadro K6000 and a GTX 1060 I am trying to make my code work on RTX 2080 Ti.

Are there any people here who have managed to make it work with an RTX 2080 Ti ?

**Comment by jyothir07** [comment]
I made it work but too slow. Average GPU utilisation is 5%

**Comment by Chakib-Belafdil** [comment]
What is your python environment configuration ?

Mine is a conda environment with:
Python 3.7
tensorflow-gpu 1.14.0 (which installed all the DLL needed so I can't tell which CUDA or cuDNN version it is)
keras 2.2.5

**Comment by jyothir07** [comment]
> What is your python environment configuration ?
> 
> Mine is a conda environment with:
> Python 3.7
> tensorflow-gpu 1.14.0 (which installed all the DLL needed so I can't tell which CUDA or cuDNN version it is)
> keras 2.2.5

@chakib-belafdil Could u please explain the procedure, confirm the GPU model and the obtained GPU utilisation also..

**Comment by Chakib-Belafdil** [comment]
Here the procedure that made it work on my Windows 10 PC with a RTX 2080 Ti:
https://docdro.id/uEhggPa 

And the environment file (change the extension .txt to .yml):
https://docdro.id/Xy2KLWb

Hope it will work on your PCs too
