### ISSUE TITLE
IMAGE_RESIZE_MODE & IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 257

### ISSUE THREAD

**Issue by jasdal365** [matterport/Mask_RCNN#1954]
Hi, I trained my MaskRCNN and everything seems fine, until I changed 
`IMAGE_RESIZE_MODE = "none "`  in config.py
After that and also for the RESIZE_MODE "square" I got the error: 

`ERROR:root:Error processing image {'id': 'Picture.jpg_47096', 'source': 'form', 'path': 'Picture.jpg', 'width': 2048, 'height': 1536, 'polygons': [{'name': 'polygon', 'all_points_x': [764, 769, 1480, 1451, 764], 'all_points_y': [857, 952, 1139, 1006, 857]}], '_class': 'firstclass'}
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1673, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1238, in load_image_gt
    class_ids = class_ids[_idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 257
`

If I got two masks of the same class in one picture, I got the error with

`IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 258`

The Parameter class_ids is 1D, _idx has the dimension 257. 
The function load_mask is returning the mask with [h,w,no of instances] as said in other issues. For this problem I couldn't find a solution yet, I also checked all related issues here.
Please help, I'm suffering for many days at that error...

**Comment by jasdal365** [comment]
My Code is: 

```
def load_mask(self, image_id):
        image_info = self.image_info[image_id]
        if image_info["source"] != "form":
            return super(self.__class__, self).load_mask(image_id)

        info = self.image_info[image_id]
        mask = np.zeros([info["height"], info["width"], len(info["polygons"])], dtype=np.uint8)
        for i, p in enumerate(info["polygons"]):
            rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
            mask[rr, cc, i] = 1

        cl = image_info['_class']
        class_ids = np.array([self.class_names.index(cl)] * len(mask[0, 0]))
        return mask.astype(np.bool), class_ids.astype(np.int32)

```

Changing parameters in MINI_MASK or MULTIPROCESSING doesn't work

**Comment by jasdal365** [comment]
The Problem is solved. It wasn't about the code, the installed packages got wrong versions. Here's my setup: 
CUDA 10 
tensorflow 1.14.0
tensorflow-gpu 1.14.0
keras 2.2.3

**Comment by mgarnett21** [comment]
can't sovle my problem , but thanks

**Comment by Siddharth1698** [comment]
I got this error but turned out that during annotation I gave a name to label but not the same name in the code for the specific class. When I corrected that I got rid of the error.
