### ISSUE TITLE
Load Validation Dataset -- File not found

### ISSUE THREAD

**Issue by backspace131** [matterport/Mask_RCNN#1956]
I`m having a problem about this: 

![filenotfound](https://user-images.githubusercontent.com/58779365/72523126-195f0c80-389a-11ea-9164-7649512775e5.JPG)

I train my own dataset based on instructions and samples in the balloon.

I already check the paths and everything and still doesn`t work. Any suggestions?

**Comment by Chakib-Belafdil** [comment]
Did you checked if you have the via_region_data.json file in the directory pointed out ?
