### ISSUE TITLE
Apply_mask issue

### ISSUE THREAD

**Issue by everysens-mounsif-hanafi** [matterport/Mask_RCNN#1967]
Hi everyone,
If someone can explain what's wrong with this:
ValueError: **operands could not be broadcast together with shapes (56,56) (640,640) (640,640)** 
in this function:
def apply_mask(image, mask, color, alpha=0.5):
    """Apply the given mask to the image.
    """
    for c in range(3):
        image[:, :, c] = np.where(mask == 1,
                                  image[:, :, c] *
                                  (1 - alpha) + alpha * color[c] * 255,
                                  image[:, :, c])

    return image
They have the same shape , i tried to find a hint , but found nothing.

If someone could help, i would be grateful

**Comment by truongtd6285** [comment]
Did you change something in the visualize.py, if not, may be your input to that function was incorrect. The mask and masked_image must have the same size.

**Comment by everysens-mounsif-hanafi** [comment]
I used mask instead of mini_mask. Thank you for your assist.
Its fixed now

**Comment by maskrcnnuser** [comment]
@everysens-mounsif-hanafi - I am getting the same error. Could you please help me how you solved it?

ValueError                                Traceback (most recent call last)
<ipython-input-11-46f0a2fee53f> in <module>
----> 1 visualize.display_instances(image, bbox, mask, class_ids, dataset.class_names)

visualize.py in display_instances(image, boxes, masks, class_ids, class_names, scores, title, figsize, ax, show_mask, show_bbox, colors, captions)
    150         mask = masks[:, :, i]
    151         if show_mask:
--> 152             masked_image = apply_mask(masked_image, mask, color)
    153 
    154         # Mask Polygon

visualize.py in apply_mask(image, mask, color, alpha)
     77                                   image[:, :, c] *
     78                                   (1 - alpha) + alpha * color[c] * 255,
---> 79                                   image[:, :, c])
     80     return image
     81 

<__array_function__ internals> in where(*args, **kwargs)

ValueError: operands could not be broadcast together with shapes (56,56) (1024,1024) (1024,1024)

**Comment by maskrcnnuser** [comment]
I am using Mask_RCNN that works on TF2. I deleted use_mini_mask=TRUE argument from load_image_gt (based on suggestion here --> https://github.com/matterport/Mask_RCNN/issues/2111)

**Comment by maskrcnnuser** [comment]
And I am using Windows based implementation - branch of --> https://github.com/akTwelve/Mask_RCNN

**Comment by huitudou** [comment]
class InferenceConfig(ShapesConfig):
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1
    USE_MINI_MASK = False

我通过在InferenceConfig中增加USE_MINI_MASK = False来解决这个问题
