### ISSUE TITLE
How to save masked objects in a saparate file ?

### ISSUE THREAD

**Issue by Mididou** [matterport/Mask_RCNN#1980]
Hello Everyone , i have this masked objects : 

![image](https://user-images.githubusercontent.com/48514563/73162504-37283f00-40ee-11ea-9ddc-3bdf974a3fd3.png)

And i want to save every masked object separatly as a jpg photo in a different file , i.e , in my output file i want to have for exemple : 

![image](https://user-images.githubusercontent.com/48514563/73162604-72c30900-40ee-11ea-8c0a-9248624f1e72.png)

and all the other objects.

Any suggestion on how to execute that would be super appreciated , thank you.

**Comment by truongtd6285** [comment]
You can get the masks from detected results. Then you can extract the boxes around those masks
```
mask = results[0]['masks']
bbox = utils.extract_bboxes(mask)
```
with boxes and masks, you can save masked objects to files.

**Comment by Mididou** [comment]
Thank you for the contribution @truongtd6285 , but the thing is , if i do that , i'll get this :  

![image](https://user-images.githubusercontent.com/48514563/73441809-e154d080-4353-11ea-8529-6dc904249415.png)

instead of that :  

![image](https://user-images.githubusercontent.com/48514563/73441840-f16cb000-4353-11ea-8393-4b633e3a8c7b.png)
 
and i'm using segmentation on purpose , because i need to overlook certain parts in my images , that's why i need only the masks.

**Comment by truongtd6285** [comment]
Just do something likes this:
```
mask = results[0]['masks']
bbox = utils.extract_bboxes(mask)
img_cropped = img[bbox[i][0]:bbox[i][2], bbox[i][1]:bbox[i][3]]
mask_cropped = mask[:,:,i][bbox[i][0]:bbox[i][2], bbox[i][1]:bbox[i][3]]
mask_applied = cv2.bitwise_and(img_cropped, img_cropped, mask = croped_mask)
```

**Comment by Mididou** [comment]
Thank you .
So , i finally managed to get the segmented objects as i wanted by adding this pice of code :  

      `i = 0
       mask = r["masks"]
       for i in range(mask.shape[2]):
	     image = cv2.imread(args["image"])
	     image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
 	     image = imutils.resize(image, width=1150)

	     for j in range(image.shape[2]):

		   image[:,:,j] = image[:,:,j] * mask[:,:,i]

	   # cv2.figure(figsize=(8,8))
	   # cv2.imshow("Output", image)
	   # cv2.waitKey()
	   filename = "Output/segment_%d.jpg"%i
	   cv2.imwrite(filename,image)
	    i+=1`

The only problem , is that i get the segmented parts with the mask colors and not the original colors : 

![image](https://user-images.githubusercontent.com/48514563/73547986-5271b200-4440-11ea-9d74-a11b52b0fe10.png)

Any idea on how to solve that ? , thank you.

**Comment by truongtd6285** [comment]
It is just because Opencv loads and process images in BGR channel, but your image was converted to RGB channel. So you can remove this line `image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)` or you can keep it but should convert back image from RGB2BGR before saving it.

**Comment by Mididou** [comment]
indeed !!!! , lack of concentration 👍  , thank's again @truongtd6285  , issue resolved .

**Comment by sarathsrk** [comment]
> Thank you .
> So , i finally managed to get the segmented objects as i wanted by adding this pice of code :
> 
> ```
>   `i = 0
>    mask = r["masks"]
>    for i in range(mask.shape[2]):
>      image = cv2.imread(args["image"])
>      image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
>      image = imutils.resize(image, width=1150)
> 
>      for j in range(image.shape[2]):
> 
> 	   image[:,:,j] = image[:,:,j] * mask[:,:,i]
> 
>    # cv2.figure(figsize=(8,8))
>    # cv2.imshow("Output", image)
>    # cv2.waitKey()
>    filename = "Output/segment_%d.jpg"%i
>    cv2.imwrite(filename,image)
>     i+=1`
> ```
> 
> The only problem , is that i get the segmented parts with the mask colors and not the original colors :
> 
> ![image](https://user-images.githubusercontent.com/48514563/73547986-5271b200-4440-11ea-9d74-a11b52b0fe10.png)
> 
> Any idea on how to solve that ? , thank you.

Can you please share full code? It would be really helpful if you send it to sarath0993@gmail.com

**Comment by sarathsrk** [comment]
Because I'm getting this error **IndexError: index 13 is out of bounds for axis 2 with size 13**

**Comment by shahik** [comment]
**Refined Code**
    
    image = skimage.io.imread(os.path.join('/content/real_test/','0004.JPG'))
    results = model.detect([image], verbose=1)
    r = results[0]

    mask = r['masks']
    import cv2,imutils
    for i in range(mask.shape[2]): 
      img=image
      img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  
      for j in range(image.shape[2]):
        img[:,:,j] = img[:,:,j] * mask[:,:,i]
  
      filename = "/content/segment_%d.jpg"%i
      cv2.imwrite(filename,img)
