### ISSUE TITLE
Got trouble with <<AttributeError: 'module' object has no attribute 'fullmatch'>>

### ISSUE THREAD

**Issue by LifeBeyondExpectations** [matterport/Mask_RCNN#199]
I just solved this problem so let me share the solution.

First the error comment is below.

> Traceback (most recent call last):
>   File "coco.py", line 493, in <module>
>     layers='heads')
>   File "/home/jaesungchoe/Dropbox/0_iDeaFactory/Mask_RCNN/model.py", line 2189, in train
>     self.set_trainable(layers)
>   File "/home/jaesungchoe/Dropbox/0_iDeaFactory/Mask_RCNN/model.py", line 2093, in set_trainable
>     trainable = bool(re.fullmatch(layer_regex, layer.name))
> AttributeError: 'module' object has no attribute 'fullmatch'

I am not sure but there is a problem with <<python - re.fullmatch(..)>> but not with <<python3 - re.fullmatch(..)>>
( Since I cannot solve the problem with _Py_ZeroStruct #196 , I run the code in python2.7 not python3.x )

You just can change <<re.fullmatch(..) >> into <<re.match(..) >> 
For me, now it works well.

**Comment by saqib1707** [comment]
I don't think this is a solution :-1: The issue #196  still is open
