### ISSUE TITLE
Averaging severals weights saved in h5 files

### ISSUE THREAD

**Issue by suchiz** [matterport/Mask_RCNN#1994]
Hi there, 

I did a K-Fold cross validation to get the best model out of my dataset. So each fold got me some weights saved into an h5 file. I now want to average the weights of my 3 best models (I know it might generate a bad result but still want to try).

So I tried to open the .h5 files with the h5py library to make an average of them but that's a total mess and got lost.

Does anybody tried to do the same or have some tips ?

Thank you very much !

**Comment by yoya93** [comment]
@suchiz hello could you average the models obtained in the cross validation ???

**Comment by suchiz** [comment]
Hi @yoya93, unfortunately I could'nt. I've looked at Keras issues instead of here and found some interesting comments. Some has made me change my mind about averaging weights.

**Comment by yoya93** [comment]
@suchiz  Ok, thank you very much for the information
