### ISSUE TITLE
how i fix the bug?

### ISSUE THREAD

**Issue by Sivaaaa** [matterport/Mask_RCNN#2035]
AttributeError: module 'tensorflow' has no attribute 'Summary'

**Comment by 1chimaruGin** [comment]
@Sivaaaa What your tensorflow version?

**Comment by Sivaaaa** [comment]
> @Sivaaaa What your tensorflow version?

yes i got it,tensorflow version is a problem and i downgrade my tensorflow version it worked
thankyou @1chimaruGin
