### ISSUE TITLE
Use 1 class from COCO and add 2 new classes

### ISSUE THREAD

**Issue by Siddikulus** [matterport/Mask_RCNN#2036]
I have to implement object detection for three classes i.e. 'Person', 'Road' and 'Tyre'. The person class is already trained on the COCO dataset.

How do I use the weights of this already trained 'Person' class and my 2 new classes together to detect the objects? 

My annotation file is only annotated for 'Tyre' and 'Road', do I have to completely ceate a new dataset with the 'Person' class annotated aswell?

Thanks

**Comment by dhirajpatnaik16297** [comment]
Hey there,
Same is the case with me. I want to have some classes of coco and add some other so how should i proceed to train. Shall i train from scratch? or shall i proceed from annotating again all the classes i want? What shall i do?

I am using VIA 2.0.9 to annotate for the extra classes.
Please help me out.

**Comment by Siddikulus** [comment]
Hey there @dhirajpatnaik16297. I've resolved the issue, what you really need to do is annotate a set of images with all the classes (the one present in coco + the new classes) and retrain the model (can be all the layers or just the heads)

**Comment by yiyichun** [comment]
Hi, @Siddikulus:
How to create .json file ? (the one present in coco + the new classes)
1. How to filter  the classes of "person" from coco "instances_train2014.json"?
2.How to merge .json with only "person" from coco and .json of new classes?
The above is my idea, is this correct ?
thanks ~

**Comment by Siddikulus** [comment]
Hey @yiyichun,
I have a repository related to object detection [here](https://github.com/Siddikulus/Construction-Safety-Equipment-Detection). It has the source code for Object Detection using Mask-RCNN on custom classes and a link to a tutorial I followed for setting up my dataset.

1. I think you can download the annotations for just a particular class from COCO ('Person' in your case).
2. I used 'Labelme' for this, you could follow the link attached in my repository for this.
