### ISSUE TITLE
train_shapes - AttributeError: module 'tensorflow' has no attribute 'random_shuffle'

### ISSUE THREAD

**Issue by akansha9j** [matterport/Mask_RCNN#2063]
<img width="1178" alt="Screen Shot 2020-03-23 at 12 22 30 PM" src="https://user-images.githubusercontent.com/19935580/77355096-156bc280-6d01-11ea-8394-a7d4b9b8e2d3.png">

I downgraded my tensorflow version to 2.0 but I am still seeing this error while running train_shapes notebook.

**Comment by akansha9j** [comment]
Not needed now

**Comment by hci-mkim** [comment]
how could you solved this problem??

**Comment by akansha9j** [comment]
Earlier I was trying to follow the instructions given in the MatterPort github which resulted in a lot of errors. But then I found this blog - https://www.analyticsvidhya.com/blog/2019/07/computer-vision-implementing-mask-r-cnn-image-segmentation/ . I think they have eventually found out which version works for everything. Following this blog I could run the model notebooks without any errors. Hope it helps you too!

**Comment by adafranca** [comment]
"tensorflow==1.15.0" worked to me
