### ISSUE TITLE
Train Mask RCNN from scratch

### ISSUE THREAD

**Issue by ojoaobrito** [matterport/Mask_RCNN#2064]
Just a quick question, I want to train this implementation of Mask RCNN from **scratch** (i.e. **without using the COCO or Imagenet weights**). How can I do that?

**Comment by brahimharounhassan** [comment]
> Just a quick question, I want to train this implementation of Mask RCNN from **scratch** (i.e. **without using the COCO or Imagenet weights**). How can I do that?

I would also like, it can help us a lot as a student.

J'aimerais aussi, cela peut nous aider beaucoup en tant qu'étudiant.

**Comment by sadmam** [comment]
This would in fact be great to know.

**Comment by JotaCoves** [comment]
Are you asking how start with random weights?
If is this, if you comment the line where model.load_weights() do that.

> Just a quick question, I want to train this implementation of Mask RCNN from **scratch** (i.e. **without using the COCO or Imagenet weights**). How can I do that?

Are you asking how start with random weights?
If is this, if you comment the line where model.load_weights() do that.

**Comment by brahimharounhassan** [comment]
> Are you asking how start with random weights?
> If is this, if you comment the line where model.load_weights() do that.
> 
> > Just a quick question, I want to train this implementation of Mask RCNN from **scratch** (i.e. **without using the COCO or Imagenet weights**). How can I do that?
> 
> Are you asking how start with random weights?
> If is this, if you comment the line where model.load_weights() do that.

I think the question was, how start training based on our own datasets, like a bunch of specifics images (annotated of cours ) without using a pre-trained dataset or any kind of external weights. First, generating our .h5 file (weights) and use it for our needs. 
Sorry for my english if isn't clear. ( French speaker )

**Comment by satishhiremath** [comment]
I think we can train MRCNN from scratch. I tried by making train "all" layers while training. But we need a huge amount of train data to get better results as network is too deep.
As there is always a space to learn, looking forward to knowing if my understanding is correct.

**Comment by ojoaobrito** [comment]
> Are you asking how start with random weights?
> If is this, if you comment the line where model.load_weights() do that.
> 
> > Just a quick question, I want to train this implementation of Mask RCNN from **scratch** (i.e. **without using the COCO or Imagenet weights**). How can I do that?
> 
> Are you asking how start with random weights?
> If is this, if you comment the line where model.load_weights() do that.

That did the trick! Thank you very much! @JotaCoves
