### ISSUE TITLE
COCO evaluation result : segmentation result does not come up 

### ISSUE THREAD

**Issue by LifeBeyondExpectations** [matterport/Mask_RCNN#207]
Before giving a question, thank you for all of you who spent time on this big project.

I have two questions.
1. For me, evaluation results of segmentation does not come up. Let me upload a screenshot after type ..
`python3 coco.py evaluate --dataset=... --model=weight/mask_rcnn_coco.h5 --year=2017 `
![maskrcnn_eval](https://user-images.githubusercontent.com/32631453/35113067-8ef26ed4-fcc3-11e7-8231-7f11e158b389.png)

2. I check the result with the paper[[url](https://arxiv.org/pdf/1703.06870.pdf)] but those are ... very different. I am not sure how do I treat this problem. ... 
![maskrcnn_detection_result](https://user-images.githubusercontent.com/32631453/35113184-ece96632-fcc3-11e7-86bd-1d87c62a6288.png)

**Comment by LifeBeyondExpectations** [comment]
I fount the solution for number one(how to evaluate segmentation)

- original code
`print("Running COCO evaluation on {} images.".format(args.limit))
 evaluate_coco(model, dataset_val, coco, "bbox", limit=int(args.limit))`
 
- add this line 
`evaluate_coco(model, dataset_val, coco, "segm", limit=int(args.limit))`

- final code
`print("Running COCO evaluation on {} images.".format(args.limit))
 evaluate_coco(model, dataset_val, coco, "bbox", limit=int(args.limit))
 evaluate_coco(model, dataset_val, coco, "segm", limit=int(args.limit))`

**Comment by swordfish23** [comment]
@LifeBeyondExpectations
@TrueCactus
@waleedka 
#207 #1466 #2109 

During evaluation I'm getting an error. Could you help me solving this? I'm using custom annotated data with custom classes.

```
dataset_train.image_info = dataset_train.image_info[:-val_samples]
dataset_val.image_info = dataset_train.image_info[-val_samples:]

dataset_train.prepare()
dataset_val.prepare()
```

With this I'm able to train my model and doing predictions. Training data is split into train and test. 'C:/data/training_dataset_coco_12_classes/annotations.json' contains all training datasets generated with lableme2coco.py.

```
dataset_all = COCO(annotation_file='C:/data/training_dataset_coco_12_classes/annotations.json')
coco.evaluate_coco(model=model_inference,
                   dataset=dataset_val, coco=dataset_all,
                   eval_type="bbox",
                   limit=int(50))
coco.evaluate_coco(model=model_inference,
                   dataset=dataset_val, coco=dataset_all,
                   eval_type="segm",
                   limit=int(50))
```
The last snippet results in this error message. Any idea what's wrong? What is coco=XX expecting?

```
Traceback (most recent call last):
  File "C:\TF2\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-43-fbbd30a0bfb1>", line 4, in <module>
    limit=int(50))
  File "C:\TF2\akTwelve_Mask_RCNN\samples\coco\coco.py", line 376, in evaluate_coco
    r["masks"].astype(np.uint8))
  File "C:\TF2\akTwelve_Mask_RCNN\samples\coco\coco.py", line 333, in build_coco_results
    "category_id": dataset.get_source_class_id(class_id, "coco"),
  File "C:\TF2\akTwelve_Mask_RCNN\mrcnn\utils.py", line 341, in get_source_class_id
    assert info['source'] == source
AssertionError
```

Many thanks in advance!
