### ISSUE TITLE
COCO minival split

### ISSUE THREAD

**Issue by Jannick-v** [matterport/Mask_RCNN#21]
Just a quick question: where can I find the minival set you used in to train with the coco dataset?
Currently I used a minival (5k images) set from here: 
https://dl.dropboxusercontent.com/s/o43o90bna78omob/instances_minival2014.json.zip?dl=0
and the remaining 35K are in the following file:
https://dl.dropboxusercontent.com/s/s3tw5zcg7395368/instances_valminusminival2014.json.zip?dl=0

awesome work by the way!

**Comment by bennyguo** [comment]
I have the same question, and I think it should be put into README like in [https://github.com/rbgirshick/py-faster-rcnn/blob/master/data/README.md](url)

> Annotations for the 5k image 'minival' subset of COCO val2014 that I like to use can be found at https://dl.dropboxusercontent.com/s/o43o90bna78omob/instances_minival2014.json.zip?dl=0. Annotations for COCO val2014 (set) minus minival (~35k images) can be found at https://dl.dropboxusercontent.com/s/s3tw5zcg7395368/instances_valminusminival2014.json.zip?dl=0.

**Comment by waleedka** [comment]
Yes, you got the right files. I updated README to include these details.

**Comment by muzammil360** [comment]
> 
> 
> Just a quick question: where can I find the minival set you used in to train with the coco dataset?
> Currently I used a minival (5k images) set from here:
> https://dl.dropboxusercontent.com/s/o43o90bna78omob/instances_minival2014.json.zip?dl=0
> and the remaining 35K are in the following file:
> https://dl.dropboxusercontent.com/s/s3tw5zcg7395368/instances_valminusminival2014.json.zip?dl=0
> 
> awesome work by the way!

Thanks a lot @Jannick-v for asking this question here. It really helped me a lot to figure this minival dataset issue out.
