### ISSUE TITLE
question about PyramidROIAlign output shape

### ISSUE THREAD

**Issue by MyYaYa** [matterport/Mask_RCNN#210]
```python
x = PyramidROIAlign([pool_size, pool_size], image_shape, name="roi_align_classifier")([rois] + feature_maps)
x = KL.TimeDistributed(KL.Conv2D(1024, (pool_size, pool_size), padding="valid"),
```
PyramidROIAlign return a tensor whose shape is (1, ?, 7, 7, 256), but it's strange that after TimeDistributed operation, the tensor shape is (?, 200, 1, 1, 256), why it's happen? it's so confused to me.

The config I use is the default configuration in config.py

**Comment by MyYaYa** [comment]
I have known why.
The custom layer of Keras, should implements a function named "compute_output_shape". This function is used to auto-inferring the shape of this layer's output shape.

**Comment by everspark1982** [comment]
another question, if input 2 images, PyramidROIAlign also return a tensor whose shape(1, ?, 7, 7, 256), the first dimenstion is 1, how can decide boxes from which image?

**Comment by Superlee506** [comment]
@everspark1982 Do you solve this problem?

**Comment by zhang-qiang-github** [comment]
@everspark1982 I think the reason may be that the loss is calculated by combining the two images togather.
