### ISSUE TITLE
What is mAP? How to calculate AP AP50 AP75?

### ISSUE THREAD

**Issue by Lincoln93** [matterport/Mask_RCNN#2108]
I'm new in the object detection task. This evaluation metrics give me confusion. I've encountered following the implementation of `mAP`. Is `mAP` and `AP` refer to the same results? How to calculate `mAP50/AP50` and `mAP75/AP75` and `AP@[0.5:0.95]`. I have read this blog: https://medium.com/@yanfengliux/the-confusing-metrics-of-ap-and-map-for-object-detection-3113ba0386ef and http://cocodataset.org/#detection-eval but still, this thing bugging me.

```python
# Compute VOC-Style mAP @ IoU=0.5
from mrcnn import utils
image_ids = np.random.choice(test_set.image_ids, 606)
APs = []
for image_id in image_ids:
    # Load image and ground truth data
    image, image_meta, gt_class_id, gt_bbox, gt_mask =\
        modellib.load_image_gt(test_set, inference_config,
                               image_id, use_mini_mask=False)
    molded_images = np.expand_dims(modellib.mold_image(image, inference_config), 0)
    # Run object detection
    results = model.detect([image], verbose=0)
    r = results[0]
    # Compute AP
    AP, precisions, recalls, overlaps =\
        utils.compute_ap(gt_bbox, gt_class_id, gt_mask,
                         r["rois"], r["class_ids"], r["scores"], r['masks'])
    
    APs.append(AP)
    
print("mAP: ", np.mean(APs))
```

Any suggestions would be appreciated. Thanks.

**Comment by nataliameira** [comment]
@Lincoln93 How did you solve this? Your help will be appreciated.
