### ISSUE TITLE
TypeError: load_image_gt() got an unexpected keyword argument 'use_mini_mask'

### ISSUE THREAD

**Issue by omdxp** [matterport/Mask_RCNN#2111]
Hello everyone,
I get this error whenever I use modellib.load_image_gt() considering that I am using mrcnn2 (the one that works with tensorflow 2).

**Comment by DanSeith** [comment]
**Delete the use_mini_mask from the argument list.** It's enabled by default in config.py in this version.

**Comment by omdxp** [comment]
Okay, thank you for the feedback, I'll try to use it.

**Comment by bfhaha** [comment]
If someone is running the following cell in inspect_data.ipynb, 
delete the argument `use_mini_mask=False`

```
image_id = np.random.choice(dataset.image_ids, 1)[0]
image, image_meta, class_ids, bbox, mask = modellib.load_image_gt(
    dataset, config, image_id, use_mini_mask=False)

log("image", image)
log("image_meta", image_meta)
log("class_ids", class_ids)
log("bbox", bbox)
log("mask", mask)

display_images([image]+[mask[:,:,i] for i in range(min(mask.shape[-1], 7))])
```

**Comment by TheOGScottishKiwi** [comment]
the config function defaults to  USE_MINI_MASK = True (config.py). if you code required use_mini_mask=False you need to specify that where config is defined.
