### ISSUE TITLE
Can we apply this algorithm to detect objects in depth images? 

### ISSUE THREAD

**Issue by opencomvis** [matterport/Mask_RCNN#212]
Can we apply Mask_RCNN to detect objects in Depth images ? if not, is there a way to extend the algorithm to do this. thank you.

**Comment by waleedka** [comment]
I think it should work. You'll just need to replace the input from [height, width, 3] to [height, width, 1]. The only issue is that you're changing the shape of the input, which changes the shape of the weights of the first layer. You can solve that by:

1. Load the weights we provide but exclude the first layer, and train on that. This is what I'd recommend.
2. Fake a 3 channel depth input by either duplicating the depth values 3 times for the RGB channels, or by passing the depth in the R channel and leave the G and B channels as zeros.

**Comment by ApoorvaSuresh** [comment]
@opencomvis  did you try it? does it work?
