### ISSUE TITLE
How to resume training on custom dataset in colab ?

### ISSUE THREAD

**Issue by Mididou** [matterport/Mask_RCNN#2142]
_Hello Everyone._
_So , i'm following this tutorial to train a MaskRCnn on a custom Dataset on colab :_
https://colab.research.google.com/github/RomRoc/maskrcnn_train_tensorflow_colab/blob/master/maskrcnn_custom_tf_colab.ipynb#scrollTo=AjmxrVOwq0rC
_After the session ends and i restart the new one  , i try resuming the training from where it stoped using this command : !python roof.py train --dataset=Data/ --weights=last_
_But , it dosen't work because the *Logs* file where the checkpoints are saved is a temporary file that gets created when initializing the training , so my question is :_ 
_Dose anyone knows how i can save my checkpoints and resume training from the latest training model without losing anything everytime the session restarts ? , thank you_

**Comment by ejri** [comment]
You can try mounting your google drive, and saving the logs in a folder on the drive.

**Comment by Mididou** [comment]
Hi @ejri  , that's exactly what i've done at the end , i was looking for an other way , but facing the reality , that was the only solution i found , but thank you a lot for your contribution , i really appreciate it.

**Comment by ejri** [comment]
Check out theAIGuy's notebook for a yolov3 (darknet) model on colab:
https://colab.research.google.com/drive/1Mh2HP_Mfxoao6qNFbhfV3u28tG8jAVGk

in Step 5 of the notebook, there's a "trick" that he mentions. Weights get overwritten after 100 iterations, and saved after every 1000 iterations. 

It's really neat. I haven't had the time to look into a solution where weights get saved automatically in Mask RCNN. I have been saving them manually just like you mentioned.

**Comment by kimile599** [comment]
> Check out theAIGuy's notebook for a yolov3 (darknet) model on colab:
> https://colab.research.google.com/drive/1Mh2HP_Mfxoao6qNFbhfV3u28tG8jAVGk
> 
> in Step 5 of the notebook, there's a "trick" that he mentions. Weights get overwritten after 100 iterations, and saved after every 1000 iterations.
> 
> It's really neat. I haven't had the time to look into a solution where weights get saved automatically in Mask RCNN. I have been saving them manually just like you mentioned.

Do you tried how to change weights writing frequency? I am facing the harddrive is easily get full when in colab.

**Comment by ejri** [comment]
you can delete the older weights as it's training. 

For example, when it saves at iteration =500, you may not need to save all the weights at iteration =100, iteration =200, iteration =300, iteration =400, etc.. You can probably save a lot of space if you just keep the last few weights, and delete the rest.

**Comment by kimile599** [comment]
> you can delete the older weights as it's training.
> 
> For example, when it saves at iteration =500, you may not need to save all the weights at iteration =100, iteration =200, iteration =300, iteration =400, etc.. You can probably save a lot of space if you just keep the last few weights, and delete the rest.

That's what i am doing right now. But when you went sleep and let it run, you don't want to wake up every several hours.
Sometimes i change the training steps and extend time for each epoch.

That's why i want to know if there is place we can modify the code.

Thank you for the reply.

**Comment by ejri** [comment]
You'd have to change the iteration number from the code itself as suggested in this post. Please note that the link they use to code doesn't actually link to the iteration number. you have to go over some of the code (ctrl+F 100 or 1000)

https://github.com/AlexeyAB/darknet/issues/4761

**Comment by kimile599** [comment]
Thank you.  I will try to figure it out and let you know if it works.   Sent from Mail for Windows 10 From: EjriSent: Monday, September 7, 2020 10:04 PMTo: matterport/Mask_RCNNCc: kimile599; CommentSubject: Re: [matterport/Mask_RCNN] How to resume training on custom dataset in colab ? (#2142) You'd have to change the iteration number from the code itself as suggested in this post. Please note that the link they use to code doesn't actually link to the iteration number. you have to go over some of the code (ctrl+F 100 or 1000)AlexeyAB/darknet#4761—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
