### ISSUE TITLE
No mask only bounding boxes

### ISSUE THREAD

**Issue by leventozdemir** [matterport/Mask_RCNN#2148]
I have a dataset with 12 different classes the model detected all the bounding boxes but only generate the  mask for 10 classes i train the all layers and i trained the heads but still get the same results any one have an idea what should i do?
note: i changed config many times and still the same results.

**Comment by kazzastic** [comment]
Maybe you need to increase the number of epochs. 
If you can give more information on your model and configuration then maybe someone could solve it.

**Comment by leventozdemir** [comment]
i solved this issue :1- you must be sure that is the Config of the training is same as the Config when make prediction.
exp: when training : 
 IMAGES_PER_GPU = 1
    NUM_CLASSES = 1 + 12  # Background + toy
    STEPS_PER_EPOCH = 100
    BACKBONE='resnet101'
    USE_MINI_MASK=False
    USE_RPN_ROIS=False
    IMAGE_MIN_DIM=128
    VALIDATION_STEPS=10
    TRAIN_BN=True
    DETECTION_MIN_CONFIDENCE = 0.85
 so when make prediction if you use resnet50 then no mask will show and same for other Config properties
