### ISSUE TITLE
Faster output of ROI layer?

### ISSUE THREAD

**Issue by simaoh** [matterport/Mask_RCNN#216]
Is there a faster way to obtain the outputs of the RPN, at inference time, then model.run_graph? 

`detections = model.detect([image], verbose=1)` runs in 196ms (on a 256x256 image), whereas

`proposals = model.run_graph([image], [("proposals", mask_rcnn.keras_model.get_layer("ROI").output)])` runs in 447ms.

We should be able to retrieve the outputs of the proposals layer at least as fast as the last layer of the network. Any insight on how to do this?

**Comment by simaoh** [comment]
Found a solution to this. 
The code below gets proposals in 135ms (on a 256x256 image):
```
from keras import backend as K

get_ROI_layer_output = K.function([model.layers[0].input], [model.layers[362].output])

def get_proposals(image):    
    new_image = resize_image(image, min_dim=config.IMAGE_MIN_DIM, max_dim=config.IMAGE_MAX_DIM, padding=True)[0]-config.MEAN_PIXEL
    return get_ROI_layer_output([np.array([new_image])])[0]

proposals = get_proposals(image)
```

**Comment by ivshli** [comment]
hi, 
when I ran your code, I had a error: "'MaskRCNN' object has no attribute 'layers'"
so you added layers function in your code?

**Comment by simaoh** [comment]
Hi @ivshli, 
Define `model` as below:

```python 
mask_rcnn = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
mask_rcnn.load_weights(COCO_MODEL_PATH, by_name=True)
model = mask_rcnn.keras_model 
```

Then `model`  will have an attribute `.layers`.

**Comment by ivshli** [comment]
Thanks. that works
