### ISSUE TITLE
Connects to GPU but all training computation seems run on CPU

### ISSUE THREAD

**Issue by ninthtide** [matterport/Mask_RCNN#2163]
Hi, I've seen others report the same problem but couldn't find a solution.  

I can run the training script (balloon.py) and it absolutely can see my physical GPU, and it consumes all of the GPU available memory (and would like more), but on actual training, the GPU is at 0% - 3% load, whereas the CPU looks very active on about 30% load.  Is this correct/normal?

Config:
Windows 10
RTX 2070 Super
Cuda 10.0
Tensorflow-gpu 1.15.0
Keras 2.2.5

Samples of output:
`2020-05-06 09:23:30.107041: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-05-06 09:23:30.140764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2070 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.785
pciBusID: 0000:01:00.0
2020-05-06 09:23:30.146624: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll`

`2020-05-06 09:23:30.154658: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll`

`2020-05-06 09:23:30.163516: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll`

`2020-05-06 09:23:30.169803: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll`

`2020-05-06 09:23:30.178774: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll`

`2020-05-06 09:23:30.187260: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll`

`2020-05-06 09:23:30.201514: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll`

`2020-05-06 09:23:30.206479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0`

(and later)

`2020-05-06 09:23:52.576259: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.05GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.`

Any help would be greatly appreciated.  I feel like I bought a decent graphics card and it's not being used.

**Comment by ninthtide** [comment]
Update:
I went into Task Manager, and can see there are some tiny drop down controls under the GPU section.  When I select 'Cuda' I can see the card is working typically at about 25% load.  It was on '3D' and 'Copy' before - both of which were at 0%.  Perhaps this is a sign of it actually working correctly?

**Comment by Wo-Ki** [comment]
I have the same qeuestion.My gpu is RTX2080ti, when I train my own data, memory-usage is about 10585MB, but GPU-Util is 0%.I still don't how to solve it.

**Comment by ninthtide** [comment]
Hi Wo-Ki

Did you change the drop down in Task Manager to show Cuda?  E.g. instead of 3D and Copy?  that was my problem (I think).  My card is not as good as yours but is working at ~ 35% load now when training (still constrained by memory, or something else)

**Comment by Wo-Ki** [comment]
Hi, this question is because of my code. I use png as the label, but didn't get the right mask.Thank you for you help.
