### ISSUE TITLE
Training is stuck at Epoch 1/10

### ISSUE THREAD

**Issue by init-22** [matterport/Mask_RCNN#2168]
My model just doesnt start training, there's no error so I am unable to understand why! 
I downloaded json file in COCO format, it just has 10 images (was just trying to see if everything works well, going to add more) training it for 10 epochs, workders = 1, use_multiprocessing=False, Images per gpu =2, steps per epoch =10,validation steps = 10, TRAIN_ROIS_PER_IMAGE=50.... meaning I tried almost all suggestions from a similar issue, my keras version is 2.1.0, TF-GPU=1.15, GPU = Tesla T4, CUDA 10, CuDnn = 7.6

I would really appreciate if somebody can help me with this...
Thanks in advance.

**Comment by aldinorizaldy** [comment]
similar here. train on balloon dataset. use gtx 1050 4GB GPU on windows 10. I reduce the number of image into 1 and STEPS_PER_EPOCH = 10. It starts training but always stuck at some point, even when I reduce the steps into 2

![image](https://user-images.githubusercontent.com/52752546/82409894-f12a2900-9a98-11ea-9de3-239637b58c2d.png)

**Comment by init-22** [comment]
@aldinorizaldy I spent a lot of time on this too but didnt get the desired solution, I suggest you move to detectron2 until we understand whats the exact problem.

**Comment by andreap9** [comment]
> My model just doesnt start training, there's no error so I am unable to understand why!
> I downloaded json file in COCO format, it just has 10 images (was just trying to see if everything works well, going to add more) training it for 10 epochs, workders = 1, use_multiprocessing=False, Images per gpu =2, steps per epoch =10,validation steps = 10, TRAIN_ROIS_PER_IMAGE=50.... meaning I tried almost all suggestions from a similar issue, my keras version is 2.1.0, TF-GPU=1.15, GPU = Tesla T4, CUDA 10, CuDnn = 7.6
> 
> I would really appreciate if somebody can help me with this...
> Thanks in advance.

Is your GPU_Count set to 2?

**Comment by init-22** [comment]
@andreap9 Its set to 1.

**Comment by andreap9** [comment]
> 
> 
> @andreap9 Its set to 1.
I had the same problem and I solved it thanks to this (https://github.com/matterport/Mask_RCNN/issues/1899). However, I think that when using GPU, GPU_Count should be set to min 2 so the work is divided between CPU and GPU. Nevertheless, parallel_model.py is not working for me.

**Comment by aldinorizaldy** [comment]
I solve my problem by changing into ubuntu 16.04. I have dual OS. Tensorflow in my ubuntu is 1.6, keras 2.15, CUDA 9. I don't change the code at all. Still the same GPU. Just running on ubuntu and it solves, and I don't know the reason.

**Comment by bangnghh** [comment]
i have the same issues, please help

**Comment by mekkianes** [comment]
Change kera version to 2.3, workers=1 and   use_multiprocessing=False  in self.keras_model.fit_generator (model.py)

**Comment by burhr2** [comment]
Hi! kindly see this issue https://github.com/matterport/Mask_RCNN/issues/2312 there is a pointer to the same implementation that supports TensorFlow 2=>. If this solves your problem kindly close the issue so as others can navigate to other issues easier
