### ISSUE TITLE
image_area in PyramidROIAlign

### ISSUE THREAD

**Issue by TgithubJ** [matterport/Mask_RCNN#217]
Hi, 

Could you explain why we need (224.0 / tf.sqrt(image_area)), instead of just using 224.0 at the following line?

roi_level = log2_graph(tf.sqrt(h * w) / (224.0 / tf.sqrt(image_area)))  // model.py line 364

![screen shot 2018-01-26 at 5 50 47 pm](https://user-images.githubusercontent.com/15370311/35469495-a1501ff4-02ea-11e8-93e7-d5ed38f6b66e.png)

When I see the equation in FPN paper, I do not see tf.sqrt(image_area) part. 

Thank you very much.

**Comment by waleedka** [comment]
The equation in the paper assumes the width and height are in pixels. In the code, at that spot, the width and height are normalized (0 to 1). The additional division handles the difference in unit of measurement.
