### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'random_shuffle'

### ISSUE THREAD

**Issue by innat** [matterport/Mask_RCNN#2171]
It mainly occurs in `tensorflow 2x`, I think. And I know they're a few options we can select to get rid of this issue:

- downgrade to compatible version such as `tf 1.x`, OR
- modify code as: `tf.random_shuffle` to `tf.random.shuffle`

Is there any other way we can solve this issue when using this repo? I am mainly trying it on kaggle, so any suggestion regarding this would be really appreciated. 

Thanks

**Comment by misam72** [comment]
This problem occurred for me and when I fix it new problems occurred and finally I could not run the project.

**Comment by misam72** [comment]
I change **tensorflow version to 1.15.1** , **keras to 2.0.8** ,**clone mrcnn project again** (and run setup.py) and put my code in **new notebook** in colab.The problems(like AttributeError: module 'tensorflow' has no attribute 'random_shuffle' and others) did not occurred again.

**Comment by Ryuzerox** [comment]
It happens with any python library or module, check that no python file is saved with the name of random.py because what python will do is interpret that this is the module and not the one found in the installation path
