### ISSUE TITLE
Why the output mask's size different from the input image's size

### ISSUE THREAD

**Issue by zhaoguanao** [matterport/Mask_RCNN#2177]
I've used balloon.py to train an apple segmentation model,after training I've try it with a 960x1280 image,but the output mask's shape is 1024x1024.What should I do to change the output mask's size from 1024x1024 to 960x1280?(mask means r['masks'] in the end of inspect_balloon_data.ipynb)

**Comment by suchiz** [comment]
Hi there, it is due to the "square" mode in config.py

**Comment by zhaoguanao** [comment]
> Hi there, it is due to the "square" mode in config.py

It's done.I'm so stupid.the main reason for this question is that I dont know how to change the values of 'RESIZE_IMAGE_MODE'  and 'IMAGE_SHAPE'.In fact before you tell me that i've changed 'square' to 'none' in config.py but nothing happened.But after that i change these values in my test.py(under 'config = InferenceConfig()' and then it changes.but thx.I think that I shouldn't ask easy questions like this,it's quite easy for you guys

**Comment by suchiz** [comment]
I'm just a lambda person too. Don't worry. Don't forget to close it if it's done :)

**Comment by suchiz** [comment]
Didn't you have an incompatible shape error ?

**Comment by zhaoguanao** [comment]
> Didn't you have an incompatible shape error ?

what do your mean?I dont know what should a "incompatible shape error" look like

**Comment by suchiz** [comment]
The FPN part needs an input image dividable by 64. When you set IMAGE_RESIZE_MODE to 'none', you'll get an incompatible shape error. 

Just wanted to check with you. But you look fine :)

**Comment by zhaoguanao** [comment]
> The FPN part needs an input image dividable by 64. When you set IMAGE_RESIZE_MODE to 'none', you'll get an incompatible shape error.
> 
> Just wanted to check with you. But you look fine :)

my input size is 960x1280,,I'm lucky.

**Comment by zhaoguanao** [comment]
> The FPN part needs an input image dividable by 64. When you set IMAGE_RESIZE_MODE to 'none', you'll get an incompatible shape error.
> 
> Just wanted to check with you. But you look fine :)

dude,I have some questions,I wonder how long did you take to test a photo?my computer have i5-7300HQ 1050ti(4GB) and 8GB RAM,it spends 10-15s to test a 960x1280 picture

**Comment by suchiz** [comment]
Do you run it on CPU or GPU ?

Mine, if the inference model and the weights are already loaded:
GPU 1080 GTX (8Go): 1-3s
CPU I9: 3-10s
CPU I7: 10-15s
GPU 960 GTX (2Go): 15s-20s

**Comment by zhaoguanao** [comment]
> Do you run it on CPU or GPU ?
> 
> Mine, if the inference model and the weights are already loaded:
> GPU 1080 GTX (8Go): 1-3s
> CPU I9: 3-10s
> CPU I7: 10-15s
> GPU 960 GTX (2Go): 15s-20s

I run it on GPU,seems 10-15s is normal for 1054ti. But it's sooooooooooooo slow for application.

**Comment by suchiz** [comment]
Yes, they are able to run it 5-7 FPS on a NVIDIA Tesla so no wonder it is slow on a 1050. You should try to lower the input image, and use another backbone if you want something faster. 512*512 with resnet50 is already fast enough. But if you go throughout the issues, you will see some mobilenet implementation 256*256 which are real time. But ofc, don't expect the same quality of segmentation
