### ISSUE TITLE
How to calculate mean Average Recall (mAR)?

### ISSUE THREAD

**Issue by WillianaLeite** [matterport/Mask_RCNN#2178]
I customized the "https://github.com/matterport/Mask_RCNN.git" repository to train with my own data set, for object detection, ignoring the segmentation part of the mask. Now, I am evaluating my results, I can calculate the MAP through the function: compute_ap, from "https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/utils.py" which returns the "precisions, recalls, overlaps "for each image. I would like to know how can I calculate the mean Average Recall (mAR) using this function: compute_recall from "https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/utils.py"?

**Comment by gchai123** [comment]
> I customized the "https://github.com/matterport/Mask_RCNN.git" repository to train with my own data set, for object detection, ignoring the segmentation part of the mask. Now, I am evaluating my results, I can calculate the MAP through the function: compute_ap, from "https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/utils.py" which returns the "precisions, recalls, overlaps "for each image. I would like to know how can I calculate the mean Average Recall (mAR) using this function: compute_recall from "https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/utils.py"?

Could you please share how did you do the compute_ap()? I cannot figure out where I can get teh gt_boxes, gt_class)ids, gt_masks...........!

**Comment by burhr2** [comment]
Hi, would also appreciate seeing an answer for @gchai123 question as I am also looking for a way to evaluate my custom test set for segmentation

**Comment by Shakesbeer333** [comment]
any new insights?

**Comment by WillianaLeite** [comment]
Hi guys!
I believe I found the solution to this issue. It is available here: [issues 2513](https://github.com/matterport/Mask_RCNN/issues/2513)
