### ISSUE TITLE
Big Object Detection

### ISSUE THREAD

**Issue by Siset** [matterport/Mask_RCNN#2185]
Hi everyone,

I am trying to detect 6-7 classes but the objects are huge in relation with the image (sometimes it could be the whole image). We are having problems to train the maskrcnn to detect them (despite being very distinct) plus masks never get close to the borders.

Is there any configuration to improve for such objects? 

Thanks,

**Comment by fabiofumarola** [comment]
HI Siset

```
        rpn_anchor_scales:
            - 16
            - 32
            - 64
            - 128
            - 256

        rpn_anchor_ratios:
            - 0.5
            - 1.0
            - 2.0
```
These two parameters affect the size of the anchors used for the object detection. You can increase the first one to detect larger objects, and the second for the box aspect ratio

**Comment by Siset** [comment]
Hi @fabiofumarola,

Great! I will try it! :)

Thank you very much,
Siset
