### ISSUE TITLE
The "compute_ap" function uses which pattern? COCO or Pascal 2012?

### ISSUE THREAD

**Issue by WillianaLeite** [matterport/Mask_RCNN#2187]
The "**compute_ap**" function uses which standard to calculate Average Precision, Pascal VOC 2012 or COCO? I am confused by this because the way COCO calculates tests several thresholds, and in the function it uses only one, and the way Pascal calculates makes the 11 point interpolation, I cannot see any of these patterns applied to this "**compute_ap**" function , does anyone know which mathematical formula this function uses?

**Comment by Srini-1981** [comment]
@WillianaLeite , did you find answer for this one?

**Comment by WillianaLeite** [comment]
Hi @Srini-1981!
I believe I found the solution to this issue. It is available here: [issues 2513](https://github.com/matterport/Mask_RCNN/issues/2513)
