### ISSUE TITLE
compute_recall from utils.py returns average recall (AR)?

### ISSUE THREAD

**Issue by WillianaLeite** [matterport/Mask_RCNN#2189]
I'm trying to calculate the mean average recall (mAR), for that I need to calculate the Average Recall (AR), does anyone know if the 'compute_recall' function returns the AR of an image, or is it just the common recall calculation for an image. The return of this function is different from the recall returned by the 'compute_ap' function.

Help me please!

**Comment by gchai123** [comment]
> I'm trying to calculate the mean average recall (mAR), for that I need to calculate the Average Recall (AR), does anyone know if the 'compute_recall' function returns the AR of an image, or is it just the common recall calculation for an image. The return of this function is different from the recall returned by the 'compute_ap' function.
> 
> Help me please!

Did you figure it out? I am trying to us the compute_ap(), but I don't know how to get the gt_boxes, gt_class_ids........., are these are retrieved from the results that I get from the test inference?

**Comment by WillianaLeite** [comment]
Hi @gchai123 !
I believe I found the solution to this issue. It is available here: [issues 2513](https://github.com/matterport/Mask_RCNN/issues/2513)
