### ISSUE TITLE
Augmentation imgaug: SuspiciousSingleImageShapeWarning:!

### ISSUE THREAD

**Issue by innat** [matterport/Mask_RCNN#2192]
There is an issue of using the latest versions of` `imgaug` while performing augmentation methods in training time.  At every iteration during training, the following log message is to keep generating repeatedly. Is it harmful? I don't know. Is there any way to hind this annoying log message?

`SuspiciousSingleImageShapeWarning: You provided a numpy array of shape (512, 512, 82) as a single-image augmentation input, which was interpreted as (H, W, C). The last dimension however has a size of >=32, which indicates that you provided a multi-image array with shape (N, H, W) instead. If that is the case, you should use e.g. augmenter(imageS=<your input>) or augment_imageS(<your input>). Otherwise your multi-image input will be interpreted as a single image during augmentation. category=SuspiciousSingleImageShapeWarning)`

**Comment by zhangyiy0223** [comment]
I encountered the same problem and the program stopped there after epoch1.

**Comment by innat** [comment]
In my case, the program didn't stop. But at each step, it generates and messes the log option and further approaching to hang. I simply just tried to skip the warning message before start training and everything was good to go. But not sure under this warning message, is the augmentation working properly or not!!

```
import warnings
warnings.filterwarnings("ignore")
```
