### ISSUE TITLE
How can I plot proposed bounding boxes produced by RPN?

### ISSUE THREAD

**Issue by uzunper** [matterport/Mask_RCNN#2198]
Hi,
I am using your Mask R CNN code for nucleus detection. I am not training the model, just using the code for detection. I would like to plot regions proposed by RPN algorithm. How can I do this? Also I could not get the idea very well. In the test step, is it proposing different regions for each image? Or is it using learned regions from training?

**Comment by sinanbayraktar** [comment]
You should have a look at the **inspect_balloon_model** notebook. It shows the steps in the whole prediction process including anchors and RPN bounding boxes

**Comment by uzunper** [comment]
Thank you very much for your answer.
