### ISSUE TITLE
Training not runnning on GPU despite cuda and tf-gpu

### ISSUE THREAD

**Issue by Nelschka** [matterport/Mask_RCNN#2202]
Hello,
I am quite new here and I hope you could help me.
I am training on my own dataset for a university project and I want to run the training process on my GPU.
First of all, I followed the CUDA-installation instructions and verify my installation. Running of deviceQuery.exe was sucessfull.
Afterwards, I create an environment and downloaded all packages of requirement.txt. Furthermore, I installed tensorflow-gpu instead of tensorflow.
By running the following commands in jupyterlab;
tf.test.is_gpu_available() -->true

tf.test.is_built_with_cuda() -->true

hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello)) 
-->'Hello, TensorFlow!'

from tensorflow.python.client import device_lib
device_lib.list_local_devices()
-->[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 11579283865742518988,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 3189928755
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 9744168715882205447
 physical_device_desc: "device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0, compute capability: 5.2"]

Due to these outputs, I expected that tf-gpu would be probaly integrated and training would run on GPU.
BUT, by starting training process, the GPU-usage is 0-1%, while my CPU-usage 50% and my memory >90%
I also changed the tf-versions to 1.12/1.15/1.13...but nothing changed.
Also the other issue-topics(like #2163) does not solve my problem

Sytem Details:
Windows 10
GeForce GTX 970
i7-7700 CPU
CUDA Toolkit 9.0
cudnn 7.6.5.32/7.0.5 (tried both unsucessfull)
Python 3.6.10
TF-GPU 1.8.0
Keras 2.2.4

I have no more ideas how to continue. 
I would be very,very grateful, if you could help me 

Thanks in advance :) :)

**Comment by wwhQAQ** [comment]
I've had this problem before.Here's my solution: i uninstall tensorflow ，then install tensorflow-gpu，my python environment  exist only one （tensorflow-gpu）  
![image](https://user-images.githubusercontent.com/21196152/82986421-5f866280-a028-11ea-9df6-9d4f3dcd4289.png)
hope this helps ：）

**Comment by Nelschka** [comment]
Thanks for your help :)

I deinstalled CUDA 9.0 and installed CUDA 10.0 with tf-gpu 1.14.
It seems to running  now :)
