### ISSUE TITLE
RPN predictions are all wrong how can improve them

### ISSUE THREAD

**Issue by shepherd25** [matterport/Mask_RCNN#2211]
I am training a model to detect guns the model was trained once and I am getting this
as the RPN target
![1](https://user-images.githubusercontent.com/26917531/83147301-20820b00-a115-11ea-9647-d3722f457840.PNG)
but my RPN predictions are all wrong
![2](https://user-images.githubusercontent.com/26917531/83147233-08aa8700-a115-11ea-9751-845e925e0745.PNG)
![3](https://user-images.githubusercontent.com/26917531/83147257-0f38fe80-a115-11ea-85c6-7bd267ed83f1.PNG)
How can i fix this?

**Comment by SimchaGD** [comment]
I am also having this problem. Did you fixed it @shepherd25 ?

**Comment by shepherd25** [comment]
After training it multiple times i finally have the needed result.

**Comment by philippmaa** [comment]
@ shepherd25:
Did you also change some of the hyper parameters in order to get there?
I am currently facing the same issue at the moment and could fix it yet.

**Comment by shepherd25** [comment]
Not really it auto-corrected itself after sometime.
