### ISSUE TITLE
Have to change annotation file due to augmentation?

### ISSUE THREAD

**Issue by Nelschka** [matterport/Mask_RCNN#2222]
Hello, everyone,
I'm thinking about implementing a data augmentation in my project, because my data set is comparatively small and tends to overfitting. 
My annotations are saved as .xml files, and I have extracted the bounding box of each image. 
For the augmentation I plan to use Fliplr, Flipud and Rotate for the augmentation. 

But I am confused whether I need to adjust my annotations to the geometric transformation?

For example, I turn my image upside down: The bounding boxes will be in a different position than the original annotation file. Will the program automatically detect them or do I have to transform them?

I knew that similar discussions had already taken place in this forum, but the answers were different or sometimes confusing

I'd really glad to get your feedback.

**Comment by innat** [comment]
For this, you may like to check this notebook, I hope it will help.
https://www.kaggle.com/ipythonx/gwd-with-mask-rcnn-and-coco-transfer-learning

**Comment by suchiz** [comment]
Hi there, don't you plan to use the imaug augmentation proposed by the script ?

**Comment by Nelschka** [comment]
> 
> 
> Hi there, don't you plan to use the imaug augmentation proposed by the script ?

Hi,
yes, I am planning to use imgaug augmentation, but I was unsure about the bounding boxes.
Because on official website of imgaug you can find tutorials how to adjust your bounding boxes respectively your augmentation: 
https://imgaug.readthedocs.io/en/latest/source/examples_bounding_boxes.html

**Comment by Nelschka** [comment]
> 
> 
> For this, you may like to check this notebook, I hope it will help.
> https://www.kaggle.com/ipythonx/gwd-with-mask-rcnn-and-coco-transfer-learning

Thanks a lot for recommending me this notebook :)
So in this case, different augmentation types were used and the programm automatically adapts the boxes/masks.
I just have to define my types of augmentation and it will be fine. Am I right?

**Comment by suchiz** [comment]
Hi @Nelschka, indeed the bboxes are already modified by the script if you are using the augmentation variable. You can see actually doing it in data_generator function in model.py.

Small example for your case:

import imgaug.augmenters as iaa
augmentation = iaa.Sequential([iaa.Fliplr(0.5), iaa.Flipud(0.5), iaa.Affine(rotate=(-45, 45))])

**Comment by innat** [comment]
> > For this, you may like to check this notebook, I hope it will help.
> > https://www.kaggle.com/ipythonx/gwd-with-mask-rcnn-and-coco-transfer-learning
> 
> Thanks a lot for recommending me this notebook :)
> So in this case, different augmentation types were used and the programm automatically adapts the boxes/masks.
> I just have to define my types of augmentation and it will be fine. Am I right?

Yes, kind of. But be aware of your applied augmentation, not all augmentations are safe. You should check the [source code](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/model.py#L1235) that deals with it. And always visualize the outcomes after the augmentation, you can follow the procedure in the given kaggle notebook.

**Comment by Nelschka** [comment]
> 
> 
> > > For this, you may like to check this notebook, I hope it will help.
> > > https://www.kaggle.com/ipythonx/gwd-with-mask-rcnn-and-coco-transfer-learning
> > 
> > 
> > Thanks a lot for recommending me this notebook :)
> > So in this case, different augmentation types were used and the programm automatically adapts the boxes/masks.
> > I just have to define my types of augmentation and it will be fine. Am I right?
> 
> Yes, kind of. But be aware of your applied augmentation, not all augmentations are safe. You should check the [source code](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/model.py#L1235) that deals with it. And always visualize the outcomes after the augmentation, you can follow the procedure in the given kaggle notebook.

Thanks so much for your support :)
I validated and visualized my augmentation with your suggestions at the weekend.

Thanks a lot 👍

**Comment by Shakesbeer333** [comment]
Hi @Nelschka please share your script :-)
