### ISSUE TITLE
Computing AP, predicted masks instances number different from ground truth

### ISSUE THREAD

**Issue by cnemri** [matterport/Mask_RCNN#2230]
I would like to compute mAP (mean average precision) on my own dataset. I am only detecting one class of objects. I am using utils.compute_ap() to compute AP per image but I am having an error due to dimension incompatibility between predicted masks and ground truth masks and this is mainly due to the fact that the number of detected instances is not the same.
How to deal with it ?

**Comment by suchiz** [comment]
Hi there, shall I see your call of the compute_ap function plz :) ?

**Comment by cnemri** [comment]
Hi ! So here is the way I am calling compute_ap.
I followed the example of the [train_shapes.ipynb](https://github.com/matterport/Mask_RCNN/blob/master/samples/shapes/train_shapes.ipynb) that you can find under samples/shapes/ in the repo (see last code cell).

I apply some preprocessing to my images to enhance local contrasts (MSRCR) and then use three different weights to do my inference (and that's why I have the multi infere function)

And I actually solved my issue, a team member has changed the utils.py code, I brought it back to original and it worked.

```
APs = []


for i, image_id in enumerate(image_ids):
    # Load image and ground truth data
    image, image_meta, gt_class_id, gt_bbox, gt_mask =\
        modellib.load_image_gt(dataset_val, inference_config,
                               i, use_mini_mask=False)

    if msrcr_flag:
        image = MSRCR(image)

    molded_images = np.expand_dims(modellib.mold_image(image, inference_config), 0)

    results = multi_infere(image, models_paths, verbose = 0)
    r = fusion(results)

    # Compute AP
    AP, precisions, recalls, overlaps =\
        utils.compute_ap(gt_bbox, gt_class_id, gt_mask,
                         r["rois"], r["class_ids"], r["scores"], r['masks'])

    print('AP for current image : ', AP)

    APs.append(AP)
    
print("mAP: ", np.mean(APs))

```
