### ISSUE TITLE
Inaccurate detection

### ISSUE THREAD

**Issue by TyrionChou** [matterport/Mask_RCNN#2244]
hi, there!
    I want to ask why I detect a long thin target, the edge of the target often misses part of the border！
   Do you have any suggestions for parameter improvement?

**Comment by innat** [comment]
what's your config? Can you please show some samples with?

**Comment by TyrionChou** [comment]
@innat  config like this pictures!

![1](https://user-images.githubusercontent.com/25079938/84609588-2ab05180-aeea-11ea-9f65-1bd2e16206d9.jpg)
![2](https://user-images.githubusercontent.com/25079938/84609672-78c55500-aeea-11ea-84a0-f561dd6e316c.jpg)

**Comment by innat** [comment]
Yes, config like this. But could you please also share one of an example/sample? I config looks ok to me and pretty high.

**Comment by TyrionChou** [comment]
I think I find the reason, making more aug, result more better
