### ISSUE TITLE
there are some problems when i run train_shapes on MacOS 10.15

### ISSUE THREAD

**Issue by emptybottle** [matterport/Mask_RCNN#2250]
# Create model in training mode
model = modellib.MaskRCNN(mode="training", config=config,
                          model_dir=MODEL_DIR)
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-14-35abd1694da6> in <module>
      1 # Create model in training mode
      2 model = modellib.MaskRCNN(mode="training", config=config,
----> 3                           model_dir=MODEL_DIR)
      4 

~/Desktop/Mask_RCNN-master/mrcnn/model.py in __init__(self, mode, config, model_dir)
   1835         self.model_dir = model_dir
   1836         self.set_log_dir()
-> 1837         self.keras_model = self.build(mode=mode, config=config)
   1838 
   1839     def build(self, mode, config):

~/Desktop/Mask_RCNN-master/mrcnn/model.py in build(self, mode, config)
   1932             anchors = np.broadcast_to(anchors, (config.BATCH_SIZE,) + anchors.shape)
   1933             # A hack to get around Keras's bad support for constants
-> 1934             anchors = KL.Lambda(lambda x: tf.Variable(anchors), name="anchors")(input_image)
   1935         else:
   1936             anchors = input_anchors

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    920                     not base_layer_utils.is_in_eager_or_tf_function()):
    921                   with auto_control_deps.AutomaticControlDependencies() as acd:
--> 922                     outputs = call_fn(cast_inputs, *args, **kwargs)
    923                     # Wrap Tensors in `outputs` in `tf.identity` to avoid
    924                     # circular dependencies.

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py in call(self, inputs, mask, training)
    887         variable_scope.variable_creator_scope(_variable_creator):
    888       result = self.function(inputs, **kwargs)
--> 889     self._check_variables(created_variables, tape.watched_variables())
    890     return result
    891 

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py in _check_variables(self, created_variables, accessed_variables)
    914           Variables.'''
    915       ).format(name=self.name, variable_str=variable_str)
--> 916       raise ValueError(error_str)
    917 
    918     untracked_used_vars = [

ValueError: 
The following Variables were created within a Lambda layer (anchors)
but are not tracked by said layer:
  <tf.Variable 'anchors_1/Variable:0' shape=(8, 4092, 4) dtype=float32>
The layer cannot safely ensure proper Variable reuse across multiple
calls, and consquently this behavior is disallowed for safety. Lambda
layers are not well suited to stateful computation; instead, writing a
subclassed Layer is the recommend way to define layers with
Variables.

**Comment by YuhL6** [comment]
Hi, I met a similar problem as you did.
Could you tell about how you solved this problem?
