### ISSUE TITLE
None values not supported 

### ISSUE THREAD

**Issue by emptybottle** [matterport/Mask_RCNN#2251]
mrcnn_bbox = keras.layers.Reshape((s[1], num_classes, 4), name="mrcnn_bbox")(x)
    957 

ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.

**Comment by jinusean** [comment]
How did you fix this problem?

**Comment by RishikMani** [comment]
Were you able to fix this issue? Could you please provide a solution in that case!

**Comment by sruthikeerthi18** [comment]
@emptybottle Were you able to find a fix for this issue?

**Comment by hemanthh17** [comment]
How did u fix?

**Comment by kalikhademi** [comment]
did anyone find a fix for this issue?

**Comment by kylekohman** [comment]
Any fix on this issue?
