### ISSUE TITLE
how to call evaluation like Map,AP,etc please help me? , which one line i must change in utils.py ?

### ISSUE THREAD

**Issue by Adithia99** [matterport/Mask_RCNN#2265]

**Comment by ApoorvaOjha** [comment]
Hey, did you find how to do it?? Please convey the same to me. Thank You.

**Comment by DangerousY** [comment]
@ApoorvaOjha 
@Adithia99 
Hey, did you find how to do it?? Please convey the same to me. Thank You.

**Comment by ApoorvaOjha** [comment]
> @ApoorvaOjha
> @Adithia99
> Hey, did you find how to do it?? Please convey the same to me. Thank You.

no, I was not able to find...
