### ISSUE TITLE
could anyone please tell me, what does TRAIN_ROIS_PER_IMAGE does?

### ISSUE THREAD

**Issue by kazzastic** [matterport/Mask_RCNN#2268]
I have not been able to find what this variable does in config.py. Please someone explain.

**Comment by konstantin-frolov** [comment]
This can be interpreted as how many instances you are trying to detect in your image.
See more information [HERE](https://medium.com/analytics-vidhya/taming-the-hyper-parameters-of-mask-rcnn-3742cb3f0e1b)
And go to mrcnn/config.py. The code has good descriptions.
