### ISSUE TITLE
RPN anchors is highly different from paper?

### ISSUE THREAD

**Issue by Mabinogiysk** [matterport/Mask_RCNN#227]
I am reading the code of this implementation and I found the number of anchors is much different from paper.
For example, in train_shapes.ipynb, I have a image which has three objects. I get the `inputs` of the image from `data_generator`.

`inputs[2]` is `batch_rpn_match`,  the shape of `inputs[2]` is `(1, 4092, 1)`:
```
In : np.sum((inputs[2] > 0).astype(np.int32))
Out : 3
```
Which means only three anchors and the rest of lines are all zeros, this is the same with `inputs[3]`, which is `batch_rpn_bbox`
```
In : inputs[3].shape
Out: (1, 256, 4)

In : inputs[3][0,:10,:]
Out : array([[-1.40625   ,  2.34375   ,  1.23918082,  1.23918082],
       [ 0.703125  ,  1.328125  , -0.94295585, -1.54367741],
       [ 1.21533978,  1.76776695,  0.5975807 , -2.22506832],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])
```
In official paper *Mask R-CNN*, it says there are 512 anchors for FPN net with a ration of 1:3 of positive to negatives. In my opinion, this is a huge difference, I wonder how this implementation affects the performance.

**Comment by ppirrip** [comment]
I believe the 512 anchors is refer to the the shortest edge of image is 800px which gives around ~1:3 ratio. This ratio seems like is controlled by the config variable ROI_POSITIVE_RATIO, and it affects the positive_count and negative_count in model.py inside detection_targets_graph(). So the number of anchors maybe related to your image size?
