### ISSUE TITLE
How to update model to tf.2.2, I am so troubled.

### ISSUE THREAD

**Issue by Askfk** [matterport/Mask_RCNN#2271]
Hello guys, recently I am trying to update this project from tf1 to tf2. But when I change keras to tf.keras, I got a lot of errors and still cannot solve some of them currently. 
There are so many knowledges I don't to fix these errors and one of them is **ValueError: The two structures don't have the same sequence length. Input structure has length 0, while shallow structure has length 14.** which occurs during training the model and I am trapped in it for weeks.

Could anyone help me solve this problem or share your updated code of model.py of changing keras to tf.keras?
Thanks a lot.

**Comment by janmejai2002** [comment]
Hi, even I was running into the same errors while trying to change the code, but there are a lot of changes and the errors don't seem to go away. Matterport has even provided a script to convert all the code to tf2.0 but I had no success with it.
But I came across [this](https://github.com/akTwelve/Mask_RCNN). The code for tf2.0 has not been merged into the master branch of matterport's repo yet I believe. 
Hope it helps !

**Comment by Askfk** [comment]
> Hi, even I was running into the same errors while trying to change the code, but there are a lot of changes and the errors don't seem to go away. Matterport has even provided a script to convert all the code to tf2.0 but I had no success with it.
> But I came across [this](https://github.com/akTwelve/Mask_RCNN). The code for tf2.0 has not been merged into the master branch of matterport's repo yet I believe.
> Hope it helps !

Thank you very much, that helps a lot and my problems are solved!!
