### ISSUE TITLE
ValueError  shape (1024, 88) to weight has shape (1024, 324). 

### ISSUE THREAD

**Issue by gethubwy** [matterport/Mask_RCNN#2272]
ValueError: Layer #389 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 88) dtype=float32> has shape (1024, 88), but the saved weight has shape (1024, 324).    
please help me!!!        
`Instructions for updating:                                                                                                                                                                   box_ind is deprecated, use box_indices instead                                                                                                                                               Loading weights  /home/wy/pig/Mask_RCNN/mask_rcnn_coco.h5                                                                                                                                    Traceback (most recent call last):                                                                                                                                                             File "coco.py", line 486, in <module>                                                                                                                                                          model.load_weights(model_path, by_name=True)                                                                                                                                               File "/home/wy/anaconda3/envs/py36/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 2130, in load_weights                                                           File "/home/wy/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/saving.py", line 1328, in load_weights_from_hdf5_group_by_name                                                     str(weight_values[i].shape) + '.')                                                                                                                                                       ValueError: Layer #389 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 88) dtype=float32> has shape (1024, 88), but the saved weight has shape (1024, 324).                                                                                    `

**Comment by torta24x** [comment]
Try this thread, you should find the solution here.
link: https://github.com/matterport/Mask_RCNN/issues/849

**Comment by gethubwy** [comment]
> Try this thread, you should find the solution here.
> link: #849

Thank you!

**Comment by nandita96** [comment]
@gethubwy , how you managed to resolve it , please suggest i am facing same issues 
Tensorflow 1x
keras=2.2.4 and tried with 2.2.5


Layer #391 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc_5/kernel:0' shape=(1024, 8) dtype=float32_ref> has shape (1024, 8), but the saved weight has shape (1024, 20).

Thanks in advance.

**Comment by MatchaCookies** [comment]
> @gethubwy , how you managed to resolve it , please suggest i am facing same issues Tensorflow 1x keras=2.2.4 and tried with 2.2.5
> 
> Layer #391 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc_5/kernel:0' shape=(1024, 8) dtype=float32_ref> has shape (1024, 8), but the saved weight has shape (1024, 20).
> 
> Thanks in advance.

did you solve it? how?
