### ISSUE TITLE
python 3.6 on Mask_RCNN 2.0

### ISSUE THREAD

**Issue by ppirrip** [matterport/Mask_RCNN#228]
Has anyone experienced any issue with Mask_RCNN 2.0 on Python 3.6? I have the following issue on 3.6 (on Google Colab) but not on 3.5 (Ubunut 16.04 LTS stock), from the train_shapes.ipynb example. I notice that is an issue similar to this reported already, but there is no pull requested and I don't touch the code base unless there is no work around. 

/content/model.py in detection_targets_graph(proposals, gt_class_ids, gt_boxes, gt_masks, config)
    529     positive_count = tf.shape(positive_indices)[0]
    530     # Negative ROIs. Add enough to maintain positive:negative ratio.
--> 531     r = 1.0 / config.ROI_POSITIVE_RATIO
    532     negative_count = tf.cast(r * tf.cast(positive_count, tf.float32), tf.int32) - positive_count
    533     negative_indices = tf.random_shuffle(negative_indices)[:negative_count]

TypeError: unsupported operand type(s) for /: 'Tensor' and 'float'

**Comment by waleedka** [comment]
Is this the line causing the error?
```
r = 1.0 / config.ROI_POSITIVE_RATIO
```

That seems odd because the error is complaining about dividing a Tensor by a float. But, both 1.0 and the config value are floats. I think the error might be somewhere else.

**Comment by ppirrip** [comment]
It seems odd to me too, but python nails down to that line. I have this error in python 3.6 in revision 2, revision 1 and the release/archive version. I put a tf_cast to config.ROI_POSITIVE_RATIO to force it to float32 the issue went away. I prepared a pull request on it.

**Comment by waleedka** [comment]
I upgraded my own python version and ran the `train_shapes` notebook and it ran successfully. My `sys.version` is this:
```
'3.6.3 (default, Oct  6 2017, 08:44:35) \n[GCC 5.4.0 20160609]'
```

I think it's not a Python version issue. What's your TensorFlow version? I tested with Keras 2.1.3 and TF 1.5.0.

**Comment by ppirrip** [comment]
I am using Python 3.6.3 [GCC 7.2.0], TF 1.4.1, Keras 2.1.3 (that is standard version from Google Colab)

**Comment by John1231983** [comment]
@ppirrip : Could you tell me how can we upload the project to google colab. I have tried but I was not successful. Thanks

**Comment by ppirrip** [comment]
It is a bit tricky at first. Just grab my copy from below, save it in your google drive, and open it from Google colab at https://colab.research.google.com.  I use Python 3.6 with GPU acceleration.

https://drive.google.com/file/d/1S53vTGBkdskg6lRYQ5i6uvjaXOUMRug2/view?usp=sharing 

Let me know can you duplicate the problem (just change the github link back to the original instead of my forked copy).
