### ISSUE TITLE
How can I get the map that indicates the probability value of each pixel?

### ISSUE THREAD

**Issue by gwangjinjeong** [matterport/Mask_RCNN#2283]
I want to get the probability pixel map for plotting the ROC-curve.
But the model returns the score of detected box and masks indicated false and True.

This is an example; the model found 24 boxes and mask.
This is code
```python
original_image, image_meta, gt_class_id, gt_bbox, gt_mask =\
      modellib.load_image_gt(dataset_test, inference_config, 
                              image_id, use_mini_mask=False)

results = model.detect([original_image])
results
```
This is output
![01](https://user-images.githubusercontent.com/58495252/87631602-9fd5a780-c772-11ea-85a4-e233d8c04768.png)
![02](https://user-images.githubusercontent.com/58495252/87631607-a401c500-c772-11ea-85b5-f55848a54210.png)

**Comment by danflop** [comment]
Hi, @gwangjinjeong. I was wondering the same and I'd like to know if you managed to get the map. Thank you.
