### ISSUE TITLE
ValueError: No such layer: rpn_class_loss

### ISSUE THREAD

**Issue by BheemReddySoumyaReddy25** [matterport/Mask_RCNN#2286]
Selecting layers to train
In model:  rpn_model
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-1c26b876e251> in <module>()
----> 1 model.train(dataset_train,dataset_val,epochs=50,learning_rate=config.LEARNING_RATE,layers="head")

2 frames
/content/Mask_RCNN/mrcnn/model_1.py in train(self, train_dataset, val_dataset, learning_rate, epochs, layers, augmentation, custom_callbacks, no_augmentation_sources)
   2351         log("Checkpoint Path: {}".format(self.checkpoint_path))
   2352         self.set_trainable(layers)
-> 2353         self.compile(learning_rate, self.config.LEARNING_MOMENTUM)
   2354 
   2355         # Work-around for Windows: Keras fails on Windows when using

/content/Mask_RCNN/mrcnn/model_1.py in compile(self, learning_rate, momentum)
   2166             "mrcnn_class_loss", "mrcnn_bbox_loss", "mrcnn_mask_loss"]
   2167         for name in loss_names:
-> 2168             layer = self.keras_model.get_layer(name)
   2169             if layer.output in self.keras_model.losses:
   2170                 continue

/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py in get_layer(self, name, index)
   1866                 return layer
   1867 
-> 1868         raise ValueError('No such layer: ' + name)
   1869 
   1870     @property

ValueError: No such layer: rpn_class_loss

**Comment by BheemReddySoumyaReddy25** [comment]
Please help me out

**Comment by matt19git** [comment]
Did you ever figure this out?
