### ISSUE TITLE
Is that possible to get only mask image in the output (mask means r['masks'])?

### ISSUE THREAD

**Issue by hafizur-r** [matterport/Mask_RCNN#2287]
In Mask RCNN, I got the following result. 
<img width="298" alt="mapping_challenge" src="https://user-images.githubusercontent.com/9364093/87873333-f82cc500-c97d-11ea-947c-029d7fc0c4ad.png">

But I want only mask image the same size as the input image[my input image size is 229 by 256 3]. As the following image. 
![mapping_challenge1](https://user-images.githubusercontent.com/9364093/87873339-08dd3b00-c97e-11ea-87a0-026e97574551.png)

**Comment by konstantin-frolov** [comment]
model.detect returns a list of dictionaries. You can get an array of masks from these dictionaries. Then you need to put the mask on an array numpy.zeros with shape = shape of your image at the coordinates from the results['bbox']. Now multiply two numpy arrays - an array of images and masks.
