### ISSUE TITLE
Cannot train with tf higher than 2.0 but cannot import MaskRCNN with lower version

### ISSUE THREAD

**Issue by arditobryan** [matterport/Mask_RCNN#2304]
Hi, I am following this tutorial https://machinelearningmastery.com/how-to-train-an-object-detection-model-with-keras/?unapproved=547760&moderation-hash=39b4a429c5bf3d9a9dc176f353a714ad#comment-547760

When I arrive at the training step: 

model = MaskRCNN(mode='training', model_dir='./', config=config)

The following error occurs:
The following Variables were created within a Lambda layer (anchors)
but are not tracked by said layer...

I read in other post that this is not compatible with tf 2.2, so I installed 1.5.

With tf 1.5, 

from mrcnn.model import MaskRCNN
runs: ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

**Comment by VictorAtPL** [comment]
Which version of `Keras` do you have installed?

Please, try with `Keras==2.1.6` and `Keras==2.0.8`.

**Comment by burhr2** [comment]
Kindly check this issue for training with TensorFlow version 2=>with GPU https://github.com/matterport/Mask_RCNN/issues/2312. If it has solved your problem kindly close this issue.

**Comment by maskrcnnuser** [comment]
Similar error of Lambda layer. Immersivelivemint implementation throws errors while training. Works great with Demo though.
