### ISSUE TITLE
Why do we need fixed size in inference phase?

### ISSUE THREAD

**Issue by John1231983** [matterport/Mask_RCNN#232]
In the inference phase, you resize the testing image into fixed dimensions as

```
# Resize image to fit the model expected size
# TODO: move resizing to mold_image()
molded_image, window, scale, padding = utils.resize_image(  image,
                min_dim=self.config.IMAGE_MIN_DIM,
                max_dim=self.config.IMAGE_MAX_DIM,
                padding=self.config.IMAGE_PADDING)
```
I am wonder that why do we need fixed size in inference phase? Does it use fully connected layer in the network? Because I trained my image with size of `128x128` for saving memory, while my testing image is `512x1024`

**Comment by DingkunLiu** [comment]
Intuitively, you can think about that the bounding box is closely related to image size.

**Comment by John1231983** [comment]
In my opinion, the fixed size only affects the last layer. If the last layer used fully connected layer, then we have to use the fixed size. But if it used fully convolutional layer (ie. FCN), then the inference size can be arbitrary size. I am not sure about MaskRCNN case

**Comment by waleedka** [comment]
A fully connected layer is one reason to have a fixed size input, but it's not the only reason. In this model, the sizes of anchor boxes, the selection of pyramid feature maps, and the ROI Align layer are all trained on specific image sizes. The network will not give you good results if you run inferencing on a different size than what you trained on.

**Comment by John1231983** [comment]
Thanks @waleedka. So if I just replace fully connected by fully convolution, could we run your mask rcnn in arbitrary size? Which code should I change? I am focusing on problem of different input size in testing, rather than performance.
