### ISSUE TITLE
merging json files into one json file for training

### ISSUE THREAD

**Issue by YashRunwal** [matterport/Mask_RCNN#2320]
Hello guys,

So I have been using Mask-RCNN for work. I have to do custom object detection. For this I have labelled all my images using either **polygon or circle** depending on the geometry of the object in the given image. Now I have an annotations folder with separate annotations file for each image. i.e. I have 128 images and hence I have 128 annotations.json files. 

According to the balloon.py script we need only one annotation file. So my question is:

1. How do I merge these several JSON files into one?

2. Or is there a way to change the export_boxes and load_mask functions given in the code to accommodate my problem? If so, how do I do that? Also, consider that that I have 2 shapes in my JSON files. One is Polygon and other is circle. 

So a part of the JSON file which contains both polygon and circle is given below:
`{
      "label": "anchor",
      "points": [
        [
          35.70270270270271,
          18.37837837837838
        ],
        [
          60.56756756756755,
          15.675675675675675
        ],
        [
          70.29729729729729,
          32.43243243243243
        ],
        [
          59.486486486486484,
          49.729729729729726
        ],
        [
          38.40540540540539,
          49.729729729729726
        ],
        [
          30.29729729729729,
          37.2972972972973
        ]
      ],
      "group_id": null,
      "shape_type": "polygon",
      "flags": {}
    },
    {
      "label": "anchor",
      "points": [
        [
          244.35135135135135,
          168.64864864864865
        ],
        [
          250.2972972972973,
          183.78378378378378
        ]
      ],
      "group_id": null,
      "shape_type": "circle",
      "flags": {}
    }`

I would like to add something else. I have seen other issues which are related to this problem but I couldn't find any decisive answers and hence I am opening a new issue here. 

Please help me out. 

With regards,
Yash.

**Comment by Rimehdaoudi** [comment]
you can merge many json files to one using brackets or notepad editors or either an online editor like jsonformatter

**Comment by YashRunwal** [comment]
Can that merged file be used as "annotations.json" file for the entire training dataset? Or do I have to make some changes?
Because I have labelled my Images using "labelme" and the json format of the images labelled with VIA is different.

**Comment by YashRunwal** [comment]
If someone comes across this problem, one can merge the files easily and then use that file to convert to VGA Annotator Json format. Also, more simpler way would be to change the load_dataset and load_mask function according to the labelme json files. I am closing this issue now
