### ISSUE TITLE
Which verison of tensorflow and keras should be installed?

### ISSUE THREAD

**Issue by YashRunwal** [matterport/Mask_RCNN#2330]
Hello guys,

So in the requirements.txt file it is given tensorflow>=1.3. 
But when I use tensorflow 2.2.0, I am getting some errors about the lambda layers when I define my model. 

So which tensorflow version should I dowload?
Better yet, can someone tell me the necessary changes I should make in the requirements.txt file? 

Also, is it necessary to install tf-gpu and Cuda? I have only 128 images and I suspect that the training should not be too intensive so I would like to start training on CPU first. 

Please let me know. I would really appreicate your help. 

Regards,
Yash.

**Comment by bahablgn** [comment]
!pip install tensorflow-gpu==1.15 
!pip install keras==2.0.8
!pip install scipy==1.2.2

**Comment by YashRunwal** [comment]
@bahablgn Thanks for replying. So I am reinstalling anaconda distribuion with Python 3.8. Should I make an environment with Python 3.5 and then make the changes to the requirements.txt you mentioned?

**Comment by bahablgn** [comment]
You should use Python 3.6, make a new venv with Python 3.6 install required packages (tensorflow-gpu==1.15, keras==2.0.8, scipy==1.2.2).

**Comment by YashRunwal** [comment]
Okay, thanks. I will do the required and come back to you if I have any problems. If everything works then I will close this issue.

**Comment by YashRunwal** [comment]
Also @bahablgn first of all, thanks for responding. Can I just install tensorflow==1.5 if don't want to use GPU?

**Comment by burhr2** [comment]
Hi! kindly see this issue https://github.com/matterport/Mask_RCNN/issues/2312 there is a pointer to the same implementation that supports TensorFlow 2=> (with GPU). If this solves your problem kindly close the issue so as others can navigate to other issues easier
