### ISSUE TITLE
[Multiple Frames/Video] Error: IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by joeyism** [matterport/Mask_RCNN#234]
I'm trying to run `model.detect` on a numpy array of shape `(10, 720, 1280, 3)`, where the shape is `( no of frames, height, width, rgb )`. However, when I run it, I get the error
```
UnknownError (see above for traceback): IndexError: index 1 is out of bounds for axis 0 with size 1
         [[Node: mrcnn_detection_2/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](ROI_2/packed_2, mrcnn_c
lass_2/Reshape_1, mrcnn_bbox_2/Reshape, _arg_input_image_meta_2_0_1)]]
```

The code I used is as follows:

```python
import imageio
import PIL.Image as Image
import numpy as np
import model as modellib
import coco
import os

class InferenceConfig(coco.CocoConfig):
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1

config = InferenceConfig()
config.display()


reader = imageio.get_reader("firmino-arsenal-2.mkv", "ffmpeg")
fps = reader.get_meta_data()["fps"]
frames = np.array([ np.uint8(frame) for i, frame in enumerate(reader) if i < 10 ])
config.BATCH_SIZE = frames.shape[0]

ROOT_DIR = os.getcwd()
COCO_MODEL_PATH = os.path.join(ROOT_DIR, "mask_rcnn_coco.h5")
MODEL_DIR = os.path.join(ROOT_DIR, "logs")


model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
model.load_weights(COCO_MODEL_PATH, by_name=True)
model.detect(frames)
```

**Comment by joeyism** [comment]
If I set `IMAGES_PER_GPU` and `BATCH_SIZE` to be the same number, it works for small batch sizes (~10). But when I extract frames from a short video (425 frames), it throws the same error.

**Comment by joeyism** [comment]
I figured it out.

**Comment by DimplesL** [comment]
well, I have met the same error, so could you please tell me how did you figure it out? @joeyism

**Comment by joeyism** [comment]
Setting `IMAGES_PER_GPU` and `BATCH_SIZE` to be the same works for me for small batches, where I have enough memory.

One mistake I made was trying to change config between batches, which just doesn't fly.

If that doesn't work, I think I might be able to help you better if I could see your code segment.
