### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools'

### ISSUE THREAD

**Issue by iresusharma** [matterport/Mask_RCNN#2345]
i have been getting the above error while installing coco. Have alraedy follwed all the steps as mentioned in the link https://github.com/philferriere/cocoapi
While ruunig the command $ pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI, i am facing following error:- 
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to /tmp/pip-req-build-shfdssk5
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/renu/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-shfdssk5/PythonAPI/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-shfdssk5/PythonAPI/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-joj6fjct
       cwd: /tmp/pip-req-build-shfdssk5/PythonAPI
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/pycocotools
  copying pycocotools/__init__.py -> build/lib.linux-x86_64-3.7/pycocotools
  copying pycocotools/coco.py -> build/lib.linux-x86_64-3.7/pycocotools
  copying pycocotools/mask.py -> build/lib.linux-x86_64-3.7/pycocotools
  copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-3.7/pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/pycocotools
  creating build/common
  gcc -pthread -B /home/renu/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/renu/anaconda3/lib/python3.7/site-packages/numpy/core/include -I../common -I/home/renu/anaconda3/include/python3.7m -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.7/pycocotools/_mask.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  ERROR: Command errored out with exit status 1:
   command: /home/renu/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-shfdssk5/PythonAPI/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-shfdssk5/PythonAPI/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-req-build-shfdssk5
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-shfdssk5/PythonAPI/setup.py", line 25, in <module>
      cythonize(ext_modules)
    File "/home/renu/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 972, in cythonize
      aliases=aliases)
    File "/home/renu/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "/home/renu/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pycocotools/_mask.pyx' doesn't match any files
  ----------------------------------------
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
DEPRECATION: Could not build wheels for pycocotools which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: pycocotools
    Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: /home/renu/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-shfdssk5/PythonAPI/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-shfdssk5/PythonAPI/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-p_de5uei/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/renu/.local/include/python3.7m/pycocotools
         cwd: /tmp/pip-req-build-shfdssk5/PythonAPI
    Complete output (8 lines):
    running install
    running build
    running build_py
    running build_ext
    building 'pycocotools._mask' extension
    gcc -pthread -B /home/renu/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/renu/anaconda3/lib/python3.7/site-packages/numpy/core/include -I../common -I/home/renu/anaconda3/include/python3.7m -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.7/pycocotools/_mask.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/renu/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-shfdssk5/PythonAPI/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-shfdssk5/PythonAPI/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-p_de5uei/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/renu/.local/include/python3.7m/pycocotools Check the logs for full command output.

Please suggest me what to do.?

**Comment by YashRunwal** [comment]
Can you try this link: [https://stackoverflow.com/questions/11094718/error-command-gcc-failed-with-exit-status-1-while-installing-eventlet]
