### ISSUE TITLE
typo in comments of model.py

### ISSUE THREAD

**Issue by siriusdemon** [matterport/Mask_RCNN#235]
class ProposalLayer(KE.Layer):
    """Receives anchor scores and selects a subset to pass as proposals
    to the second stage. Filtering is done based on anchor scores and
    non-max suppression to remove overlaps. It also applies bounding
    box **_refinment detals_** to anchors.

-------------------------------------------------------

class PyramidROIAlign(KE.Layer):
    """Implements ROI Pooling on multiple levels of the feature pyramid.
    Params:
    - pool_shape: [height, width] of the output pooled regions. Usually [7, 7]
    - image_shape: [height, width, _**chanells**_]. Shape of input image in pixels

**Comment by waleedka** [comment]
Thank you! Fixed.
