### ISSUE TITLE
Subplot visualize.display_instances ... Results

### ISSUE THREAD

**Issue by YashRunwal** [matterport/Mask_RCNN#2359]
Hello,

I have successfully trained the model and I can see the results one after another.

`
def visualize_model(image_id):
    image, image_meta, gt_class_id, gt_bbox, gt_mask = modellib.load_image_gt(dataset_val, config, image_id,   use_mini_mask=False)
    info = dataset_val.image_info[image_id]
    print("image ID: {}.{} ({}) {}".format(info["source"], info["id"], image_id, dataset_val.image_reference(image_id)))

    # Run object detection
    results = model.detect([image], verbose=1)
    
    # Display results
    r = results[0]
    
    return visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'], dataset_val.class_names)`

    
`
for image_id in range(0, len(test_images) - 2):
    visualize_model(image_id=image_id)
`

But I want to have a subplot of the results (images). 

Any idea how to do this?
I have tried multiple ways but it seemed to fail every single time. 
I want to use the function plt.subplot, plt.subplots from matplotlib. 

Regards,
Yash Runwal.

**Comment by suchiz** [comment]
Hello, can you give me an example of your tries. i'll try to help you out

**Comment by YashRunwal** [comment]
@suchiz I figured out the mistake. My mask dimensions were wrong. But Thanks. Closing this issue.
