### ISSUE TITLE
Is it possible to finetune coco weights on a dataset that only has bboxes?

### ISSUE THREAD

**Issue by aytackanaci** [matterport/Mask_RCNN#238]
I want to get rough segmentation for new labels basically.

**Comment by JackieZhangdx** [comment]
That is a transfer learning problem. This paper may help you 
Learning to segment everything. https://arxiv.org/abs/1711.10370

**Comment by aytackanaci** [comment]
@JackieZhangdx I was asking if the code in this repo supports it. Sorry if it wasn't clear.

**Comment by waleedka** [comment]
It doesn't support it out of the box, but it shouldn't be too hard to add that if you're willing to dive into the code and make changes.
