### ISSUE TITLE
AttributeError: module 'mrcnn.model' has no attribute 'MeanAveragePrecisionCallback'

### ISSUE THREAD

**Issue by vishnuvardhan58** [matterport/Mask_RCNN#2402]
Tried using 

mean_average_precision_callback = modellib.MeanAveragePrecisionCallback(model,
model_inference, dataset_val, calculate_map_at_every_X_epoch=5, verbose=1)

giving error as : 

AttributeError                            Traceback (most recent call last)

<ipython-input-56-bfb1f211dcfb> in <module>()
----> 1 mean_average_precision_callback = modellib.MeanAveragePrecisionCallback(model,
      2 model_inference, dataset_val, calculate_map_at_every_X_epoch=5, verbose=1)

AttributeError: module 'mrcnn.model' has no attribute 'MeanAveragePrecisionCallback'

**Comment by ozgurkan** [comment]
I've been having the same problem for a few days now.  I think he opinion is correct. You can look this link: https://github.com/matterport/Mask_RCNN/pull/1024#issuecomment-468019810

**Comment by vishnuvardhan58** [comment]
@ozgurkan Thanks, that resolved my issue.

**Comment by kimile599** [comment]
> I've been having the same problem for a few days now. I think he opinion is correct. You can look this link: [#1024 (comment)](https://github.com/matterport/Mask_RCNN/pull/1024#issuecomment-468019810)

Hi is ther any way to fix it. I delete part of the code from setup.py . Still not wroking
