### ISSUE TITLE
Getting nan values in map

### ISSUE THREAD

**Issue by vishnuvardhan58** [matterport/Mask_RCNN#2403]
This is the way I am caluculating map : 
AP, precisions, recalls, overlaps = compute_ap(gt_bbox, gt_class_id, gt_mask, r["rois"], r["class_ids"], r["scores"], r['masks'])
		APs.append(AP)

My Test dataset contains some of the images where no objects are present. Is that the reason I am getting nan values while calculating mAp ? 

[0.42857142857142855, 0.0, 0.6634146341463415, 0.0, 0.6818181818181818, 0.6818181818181818, 0.6634146341463415, 0.32, 0.32, 0.6634146341463415, 0.6634146341463415, 0.6634146341463415, 0.32, 0.0, 0.4551724137931034, 0.0, 0.0, 0.0, 0.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

**Comment by sahaj432** [comment]
Fixes #2400

**Comment by jhasaurabh12** [comment]
Have you figured out why there are nan values of AP? I am also facing the same issue

**Comment by kecyarchana** [comment]
Hello, have you figured out why the AP and mAP values are nan ?

I am trying to calculate mean average precision as a callback for my validation dataset during training in every 5 epochs but I am getting nan values and a runtime warning as below.

![mAP_nan](https://user-images.githubusercontent.com/22496671/148529239-b60444c4-8384-4e2f-aa81-aa6687168a62.PNG)

what might be the cause ? Any help would be greatly appreciated.

Thanks

**Comment by jhasaurabh12** [comment]
In my case, some images of my dataset was causing this issue of NaN in AP and mAP. I removed those images from the dataset and it worked fine for me. I know that's not the robust solution but I couldn't figure out any other reason.

**Comment by kecyarchana** [comment]
Hey thank you for the answer. I have few questions regarding Mask RCNN and I cannot find any resources regarding it. Can I get your email please ?  Thankyou

**Comment by jhasaurabh12** [comment]
Yeah sure connect with me at jhasaurabh12@gmail.com. I will try to help you.

**Comment by dayana123456789** [comment]
This can be due to the improper annotations or the number of classes defined ,annotations check the annotation are undefined or incorrect. (print the objects while starting training so that you can figure out where you made mistake).

**Comment by dayana123456789** [comment]
IF THE ISSUE STILL PERSIST TRY USING CPU INSTEAD OF GPU

**Comment by thaithanhtuan** [comment]
It happens to me because there is image without any objects inside. So, the groundtruth is empty.

**Comment by dayana123456789** [comment]
@thaithanhtuan  figured out.
