### ISSUE TITLE
convert yolo annotations to via json

### ISSUE THREAD

**Issue by pafechet** [matterport/Mask_RCNN#2407]
Hi, 

I have done annotation using yolo annotator on ~ 300 images. I get txt file for each images with class and coordinates of rectangles. 

I wonder if i can easily convert this annotation dataset into via json format? Or at least an understandable format for mask-rcnn...

**Comment by pafechet** [comment]
Hi again, 

I just format my data using dict/list and dump them into a json. 

I post my code here it may help. 

```
for txtFile in tqdm(txtFileList):
    regions_list=[]
    with open(os.path.join(originLabelsDir, txtFile), 'r') as fr:
        labelList = fr.readlines()
        for label in labelList:
            label = label.strip().split()
            classe = label[0]
            x = float(label[1])
            y = float(label[2])
            wx = float(label[3])
            hy = float(label[4])
                # convert x,y,w,h to x1,y1,x2,y2

            image = cv2.imread(originImagesDir+txtFile[:-3] + 'jpg')

            height_size, width_size, channels = image.shape
            
            all_points_x =  [round((x - wx/2) * width_size),
                             round((x - wx/2) * width_size),
                             round((x + wx/2) * width_size),
                             round((x + wx/2) * width_size)]
                             
            all_points_y = [round((y - hy/2) * height_size),
                            round((y + hy/2) * height_size),
                            round((y + hy/2) * height_size),
                            round((y - hy/2) * height_size)]
            
            name = classe
            
            shape_attributes = {"name":"polygon",
                               "all_points_x" : all_points_x,
                               "all_points_y" : all_points_y
                               }
            
            region_attributes = {"Name" : name}
            
            
            annotation_dict =  {"shape_attributes" : shape_attributes,
                                "region_attributes" : region_attributes}
            #annotation_dict =annotation_dict.copy()
            #print(annotation_dict)
            regions_list.append(annotation_dict)
            
        dict_file = {
            "filename" : txtFile[:-3]+'jpg',
            "size" : height_size*width_size,
            "regions" :regions_list    
            }
    big_dict [str(txtFile)] = dict_file
    


with open(originImagesDir +'via_region_data.json', 'w') as fp:
    json.dump(big_dict, fp)
  ```

**Comment by Nhatcao99** [comment]
> Hi again,
> 
> I just format my data using dict/list and dump them into a json.
> 
> I post my code here it may help.
> 
> ```
> for txtFile in tqdm(txtFileList):
>     regions_list=[]
>     with open(os.path.join(originLabelsDir, txtFile), 'r') as fr:
>         labelList = fr.readlines()
>         for label in labelList:
>             label = label.strip().split()
>             classe = label[0]
>             x = float(label[1])
>             y = float(label[2])
>             wx = float(label[3])
>             hy = float(label[4])
>                 # convert x,y,w,h to x1,y1,x2,y2
> 
>             image = cv2.imread(originImagesDir+txtFile[:-3] + 'jpg')
> 
>             height_size, width_size, channels = image.shape
>             
>             all_points_x =  [round((x - wx/2) * width_size),
>                              round((x - wx/2) * width_size),
>                              round((x + wx/2) * width_size),
>                              round((x + wx/2) * width_size)]
>                              
>             all_points_y = [round((y - hy/2) * height_size),
>                             round((y + hy/2) * height_size),
>                             round((y + hy/2) * height_size),
>                             round((y - hy/2) * height_size)]
>             
>             name = classe
>             
>             shape_attributes = {"name":"polygon",
>                                "all_points_x" : all_points_x,
>                                "all_points_y" : all_points_y
>                                }
>             
>             region_attributes = {"Name" : name}
>             
>             
>             annotation_dict =  {"shape_attributes" : shape_attributes,
>                                 "region_attributes" : region_attributes}
>             #annotation_dict =annotation_dict.copy()
>             #print(annotation_dict)
>             regions_list.append(annotation_dict)
>             
>         dict_file = {
>             "filename" : txtFile[:-3]+'jpg',
>             "size" : height_size*width_size,
>             "regions" :regions_list    
>             }
>     big_dict [str(txtFile)] = dict_file
>     
> 
> 
> with open(originImagesDir +'via_region_data.json', 'w') as fp:
>     json.dump(big_dict, fp)
> ```

Thank you, just asking does it work on this implementation. ???

**Comment by pafechet** [comment]
It might not be the best optimized code, but in my case it use to work well.

**Comment by pafechet** [comment]
> > Hi again,
> > I just format my data using dict/list and dump them into a json.
> > I post my code here it may help.
> > ```
> > for txtFile in tqdm(txtFileList):
> >     regions_list=[]
> >     with open(os.path.join(originLabelsDir, txtFile), 'r') as fr:
> >         labelList = fr.readlines()
> >         for label in labelList:
> >             label = label.strip().split()
> >             classe = label[0]
> >             x = float(label[1])
> >             y = float(label[2])
> >             wx = float(label[3])
> >             hy = float(label[4])
> >                 # convert x,y,w,h to x1,y1,x2,y2
> > 
> >             image = cv2.imread(originImagesDir+txtFile[:-3] + 'jpg')
> > 
> >             height_size, width_size, channels = image.shape
> >             
> >             all_points_x =  [round((x - wx/2) * width_size),
> >                              round((x - wx/2) * width_size),
> >                              round((x + wx/2) * width_size),
> >                              round((x + wx/2) * width_size)]
> >                              
> >             all_points_y = [round((y - hy/2) * height_size),
> >                             round((y + hy/2) * height_size),
> >                             round((y + hy/2) * height_size),
> >                             round((y - hy/2) * height_size)]
> >             
> >             name = classe
> >             
> >             shape_attributes = {"name":"polygon",
> >                                "all_points_x" : all_points_x,
> >                                "all_points_y" : all_points_y
> >                                }
> >             
> >             region_attributes = {"Name" : name}
> >             
> >             
> >             annotation_dict =  {"shape_attributes" : shape_attributes,
> >                                 "region_attributes" : region_attributes}
> >             #annotation_dict =annotation_dict.copy()
> >             #print(annotation_dict)
> >             regions_list.append(annotation_dict)
> >             
> >         dict_file = {
> >             "filename" : txtFile[:-3]+'jpg',
> >             "size" : height_size*width_size,
> >             "regions" :regions_list    
> >             }
> >     big_dict [str(txtFile)] = dict_file
> >     
> > 
> > 
> > with open(originImagesDir +'via_region_data.json', 'w') as fp:
> >     json.dump(big_dict, fp)
> > ```
> 
> Thank you, just asking does it work on this implementation. ???

It might not be the best optimized code, but in my case it use to work well.
