### ISSUE TITLE
Mask RCNN multiple class detection, but only one class is detected in the result.

### ISSUE THREAD

**Issue by kimile599** [matterport/Mask_RCNN#2433]
Hi all, 

I am running a  4 class detection. modified from the ballon example. I have 160 for training and 40 pics for val.
Of course this is a small dataset, but i have seen some magical touch in other projects, they also get reasonable results. But mine is pretty terrible.

But my test results only showed 1 class. 
Here is my configureation 
Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        200
DETECTION_MIN_CONFIDENCE       0.9
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 1
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  512
IMAGE_META_SIZE                17
IMAGE_MIN_DIM                  512
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [512 512   3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  1e-05
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               20
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           microplastic
NUM_CLASSES                    5
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        2000
POST_NMS_ROIS_TRAINING         2000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.3, 1, 7]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.3
RPN_TRAIN_ANCHORS_PER_IMAGE    800
STEPS_PER_EPOCH                300
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       True
TRAIN_ROIS_PER_IMAGE           800
USE_MINI_MASK                  False
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.001

and results:

<img width="768" alt="Untitled" src="https://user-images.githubusercontent.com/53457043/100524936-a0d70680-3160-11eb-8b32-3bb1ce820950.png">

If you can read from the pic, all mask are labelled as fragment, which is one of the four class i designed. Is there any place i messed up therefore only one class is showed? I have other pics, in all of them, only fragments are showed.

My loss curve all looks ok. 
<img width="768" alt="Untitled1" src="https://user-images.githubusercontent.com/53457043/100524983-1347e680-3161-11eb-9485-47e07fd1829f.png">

Thank you for your time.

Your every suggestion will be helpful.

**Comment by konstantin-frolov** [comment]
I see a lot of underfitting in your example. Try to grow your dataset by at least 500 training images. And use a lot of data agmentation (flipud, fliplr, random rotate).

**Comment by kimile599** [comment]
> I see a lot of underfitting in your example. Try to grow your dataset by at least 500 training images. And use a lot of data agmentation (flipud, fliplr, random rotate).

Thank you for your suggestion. I have enabled the data aug and also increase the dataset size. Now the loss is much better. However, the positive ROI is quite low. Therefore i still don't get a good results yet.

**Comment by mozillah** [comment]
@kimile599  can you tell me how did u solved the problem because i am facing the same issue but could not find out how to resolve this issue.
