### ISSUE TITLE
Help understand outputs of Mask RCNN tflite model 

### ISSUE THREAD

**Issue by MeghaGhosh** [matterport/Mask_RCNN#2476]
Hi, I could really do with some help in understanding the outputs of the tflite model of Mask RCNN.

I have converted the model to tflite using Tensorflow 2.3.

The model takes 3 inputs - the resized image, image meta and anchors

I have written the android equivalent code for the resized image - included padding and subtracted pixel means, as well as the image meta and anchors. The model is running but I can't seem to understand which output stands for what. 

There are 7 outputs of the tflite model which have dimensions as follows:

[1][1][1]
[1][1000][81][4]
[1][1000][81]
[1][100][6]
[1][100][28][28][81]
[1][1][4]
[1][1][2]

I assume [1][100][28][28][81] is for the masks and I thought [1][100][6] would be the class ID, probability score and bounding boxes. However that doesn't seem to be consistent with the results. I can share the tflite model and the first few results of the outputs if that helps. Any help would be very much appreciated!

**Comment by sauravsolanki** [comment]
Hi @MeghaGhosh, Is your conversion successfull? Can you please share the conversion and inference code?

**Comment by tharindu326** [comment]
@MeghaGhosh 
did find out what are these outputs? 
I'm also getting following 7 outputs with  dimensions; 

```
print(model.get_tensor(output_details[1]['index'])[0].shape)
(100, 28, 28, 81)

print(model.get_tensor(output_details[2]['index'])[0].shape)
(1000, 81, 4)

print(model.get_tensor(output_details[3]['index'])[0].shape)
(261888, 2)

print(model.get_tensor(output_details[4]['index'])[0].shape)
(261888, 4)

print(model.get_tensor(output_details[5]['index'])[0].shape)
(1000, 81)

print(model.get_tensor(output_details[6]['index'])[0].shape)
(1000, 4)

print(model.get_tensor(output_details[7]['index'])[0].shape)
(100, 6)
```

Also can you let me know how did you visualize these results. if possible could you please share the inference code.

**Comment by babanthierry94** [comment]
@MeghaGhosh @tharindu326 
Please can you let me know if you succeed to visualize inference results.
Please I need some help.
