### ISSUE TITLE
scipy.misc has no attribute 'imread' when scipy version is 1.0.0

### ISSUE THREAD

**Issue by PaulChongPeng** [matterport/Mask_RCNN#25]
When I run demo ,there is an error:
scipy.misc has no attribute 'imread'.

I check the code and find that 'imread' is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
But the fact is that when I use the scipy with version  1.0.0, error occurs.
I chage the scipy version to 1.0.0rc2 and then the demo run ok.

Could you provide the dependence list for the project to guide user preparing the environment.

**Comment by waleedka** [comment]
Thanks for reporting this. I just pushed a quick fix to use skimage.io.imread() insetad. This is going to be an ongoing maintenance effort to update the code as libraries change over time.

The dependencies are listed in the READMe file. There is also a link to a Docker image that's been verified to run the code. You don't need use the Docker image necessarily, but it's Dockerfile contains the code for building which you can borrow from if needed.
