### ISSUE TITLE
Is it possible to know every result came from which layer of feature map?

### ISSUE THREAD

**Issue by EricccChung** [matterport/Mask_RCNN#251]
I wonder the way to know every MRCNN result came from which layer of feature map.

Do I need to modify the model.py to label every RoI in the RPN or it can be found somewhere in the code?

I want to use the advantage of FPN to input the BEST feature map into LSTM behind MRCNN.

This has troubled me for a long time. 

Many thanks for any help!

**Comment by waleedka** [comment]
Check the `PyramidROIAlign` class in `model.py`.  Find the part where it calculates `roi_level`. That's where the level of the pyramid is selected for each anchor box. It's a simple formula, which is explained in the paper. 

Thet selected level is not propagated to the output, though. So you won't have access to it unless you change the model a bit.

**Comment by EricccChung** [comment]
@waleedka 
This really helps me a lot, THANK YOU!
