### ISSUE TITLE
MASK_SHAPE parameter

### ISSUE THREAD

**Issue by ghost** [matterport/Mask_RCNN#2529]
In the configuration it says: 

# Shape of output mask
    # To change this you also need to change the neural network mask branch
    MASK_SHAPE = [28, 28]

Does anyone have any suggestions as to where these changes are to be done and how??

Update: 

I added the following extra layer to def build_fpn_mask_graph to model.py, and set MASK_SHAPE =[56,56] :

    x = KL.TimeDistributed(KL.Conv2D(256, (3, 3), padding="same"),
                           name="mrcnn_mask_conv5")(x)
    x = KL.TimeDistributed(BatchNorm(),
                           name='mrcnn_mask_bn5')(x, training=train_bn)
    x = KL.Activation('relu')(x)

But am still getting an error:

tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [11,56,56] vs. [11,28,28]
	 [[{{node mrcnn_mask_loss_1/mul}}]]
	 [[add_metric_7/Identity/_6415]]
  (1) Invalid argument: Incompatible shapes: [11,56,56] vs. [11,28,28]
	 [[{{node mrcnn_mask_loss_1/mul}}]]

**Comment by sohinimallick** [comment]
> In the configuration it says:
> 
> # Shape of output mask
> ```
> # To change this you also need to change the neural network mask branch
> MASK_SHAPE = [28, 28]
> ```
> 
> Does anyone have any suggestions as to where these changes are to be done and how??
> 
> Update:
> 
> I added the following to build_fpn_mask_graph to model.py:
> 
> ```
> x = KL.TimeDistributed(KL.Conv2D(256, (3, 3), padding="same"),
>                        name="mrcnn_mask_conv5")(x)
> x = KL.TimeDistributed(BatchNorm(),
>                        name='mrcnn_mask_bn5')(x, training=train_bn)
> x = KL.Activation('relu')(x)
> ```
> 
> But am still getting an error:
> 
> tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
> (0) Invalid argument: Incompatible shapes: [11,56,56] vs. [11,28,28]
> [[{{node mrcnn_mask_loss_1/mul}}]]
> [[add_metric_7/Identity/_6415]]
> (1) Invalid argument: Incompatible shapes: [11,56,56] vs. [11,28,28]
> [[{{node mrcnn_mask_loss_1/mul}}]]
