### ISSUE TITLE
Using bounding box coordinates for segmentation

### ISSUE THREAD

**Issue by ghost** [matterport/Mask_RCNN#2533]
The dataset that I have only has bounding box annotations in the pascal voc format. Is there a way to just use that to the do the instance segmentation? Perhaps a change in the code somewhere??

**Comment by syed-javed** [comment]
> The dataset that I have only has bounding box annotations in the pascal voc format. Is there a way to just use that to the do the instance segmentation? Perhaps a change in the code somewhere??

Sohinimallick, did you solve this issue:?
