### ISSUE TITLE
class_weight ValueError [model has 0 outputs]

### ISSUE THREAD

**Issue by acivit** [matterport/Mask_RCNN#2535]
Hello!

I am working on a model with a high imbalance of data, and since i cannot separate it in small datasets to compensate that imbalance (I'd lose about 80% of the dataset) I thought that using the class_weight option from keras.fit would be the best option. 

It seemed as simple as adding the class_weight parameter in the model.py file (in def train ...) having something like this:

        self.keras_model.fit(
            train_generator,
            initial_epoch=self.epoch,
            epochs=epochs,
            steps_per_epoch=self.config.STEPS_PER_EPOCH,
            callbacks=callbacks,
            validation_data=val_generator,
            validation_steps=self.config.VALIDATION_STEPS,
            max_queue_size=100,
            class_weight=class_weight,
            workers=1,#workers,
            use_multiprocessing=False, #workers > 1,
        )

I tried creating class_weight as a dict and as a list, but i got the following error when training:

ValueError: Provided `class_weight` was a list of 3 elements, but the model has 0 outputs. You should provide one `class_weight`array per model output.

Did anyone face the same error? Or someone has idea of how to solve it? 

Thanks!

**Comment by poempel123** [comment]
Hi @acivit ,

did you find any solution for this problem? I get the same error when I try to implement class_weights...

**Comment by acivit** [comment]
Hi @poempel123 , take a look at this #910 here i commented a method to implement class weights, hope it is useful for you!

**Comment by poempel123** [comment]
Thank you so much @acivit!
I was following the mentioned issue aswell. Thank you for sharing :-)
