### ISSUE TITLE
Wrong implementation of ROIAlign layer?

### ISSUE THREAD

**Issue by DingkunLiu** [matterport/Mask_RCNN#254]
In ROIAlign layer, the [equation](https://github.com/matterport/Mask_RCNN/blob/master/model.py#L365) for choosing fpn level seems incorrect, comparing with the equation in original paper without the "/sqrt(image_area)" item.

**Comment by DingkunLiu** [comment]
Also the FAIR official repo [here](https://github.com/facebookresearch/Detectron/blob/master/lib/modeling/FPN.py#L454)

**Comment by waleedka** [comment]
Duplicate of https://github.com/matterport/Mask_RCNN/issues/217

I believe the equation is correct, just being applied to a different unit of measurement.
