### ISSUE TITLE
Model can't train from "last" weights

### ISSUE THREAD

**Issue by Kuanyu458** [matterport/Mask_RCNN#2540]
I'm trying to do transfer learning from last weights I have already train,but after execution ,it's only output this without error.
![S__1875973](https://user-images.githubusercontent.com/24841000/115653522-e7244080-a361-11eb-84b5-df57ce7de39d.jpg)

I have seen #1546 are similar like my issues.

my code file is here,please give some advice.tks
[train.zip](https://github.com/matterport/Mask_RCNN/files/6355375/train.zip)

**Comment by UsmanAfzaal** [comment]
I think when you define the weights as "last" in line 183, then the model path should be defined as
model_path= model.find_last() at line 197.

instead of model_path = "C:/......"
