### ISSUE TITLE
stuck in epoch 75 

### ISSUE THREAD

**Issue by Jeffin21** [matterport/Mask_RCNN#2552]
Hey, tried adding pull request this, https://github.com/matterport/Mask_RCNN/pull/1611/commits/c4f592c27f785ff923ac540ef70f9f1bbb7bc942 and this 
https://github.com/matterport/Mask_RCNN/pull/1611/commits/37e9f4a91cf381632b4003cbe31f555aa55e6e0a
anyone please help me to deal with this situation trying to figure it for last 2 days 
![thalap](https://user-images.githubusercontent.com/24267705/116785733-c756f000-aab8-11eb-9a97-1276cbbaef44.PNG)

**Comment by aadi-mishra** [comment]
What was your solution ?
