### ISSUE TITLE
can anyone help me to convert .h5 file to pb for custom dataset?

### ISSUE THREAD

**Issue by Jeffin21** [matterport/Mask_RCNN#2555]
got this error when i try to convert 

```
import onnx
import keras2onnx
 
# Load the keras model
model = load_model('/content/drive/MyDrive/thirip2/mask_rcnn_bottle_0002.h5')
 
# Convert it into onnx
onnx_model = keras2onnx.convert_keras(model, model.name)
 
# Save the model as flower.onnx
onnx.save_model(onnx_model, 'flowers_model.onnx')

# Load the keras model


 
# Convert it into onnx
onnx_model = keras2onnx.convert_keras(model, model.name)
 
# Save the model as flower.onnx
onnx.save_model(onnx_model, '/content/sample_data/flowers_model.onnx')
```

179     model_config = f.attrs.get('model_config')
    180     if model_config is None:
--> 181       raise ValueError('No model found in config file.')
    182     model_config = json_utils.decode(model_config.decode('utf-8'))
    183     model = model_config_lib.model_from_config(model_config,

ValueError: No model found in config file.

**Comment by FrancescoMandru** [comment]
Did you solve your issue?
