### ISSUE TITLE
how does crop mode work ?

### ISSUE THREAD

**Issue by luna9722** [matterport/Mask_RCNN#2563]
Hello everybody,
Can someone clarify the cropping mode for me ? in config.py it says:
 crop: Picks random crops from the image. First, scales the image based # on IMAGE_MIN_DIM and IMAGE_MIN_SCALE, then picks a random crop of # size IMAGE_MIN_DIM x IMAGE_MIN_DIM. Can be used in training only. # IMAGE_MAX_DIM is not used in this mode.

My images are all 1024x1280, so if I use these settings:

IMAGE_RESIZE_MODE = "crop" IMAGE_MIN_DIM = 512 IMAGE_MAX_DIM = 512 IMAGE_MIN_SCALE = 0

it would first rescale the image to 512 and then randomly crop 640x640 in that? I don't understand it doesn't make sense to me.
or does it crops randomly from the image (1024x1280) images with size 512x512. Please can someone explain this to me. I am really in need to understand this for my project. thanks in advance.

**Comment by luna9722** [comment]
![image](https://user-images.githubusercontent.com/48836506/118057325-a4afbb80-b383-11eb-8126-5adf11e803b3.png)
while reading the resize_image function in utils.py , it is clear that the crop mode takes randomly crops from the image with size min x min (so it doesn't scale it first to min x min then apply the crop)

**Comment by rainylt** [comment]
> ![image](https://user-images.githubusercontent.com/48836506/118057325-a4afbb80-b383-11eb-8126-5adf11e803b3.png)
> while reading the resize_image function in utils.py , it is clear that the crop mode takes randomly crops from the image with size min x min (so it doesn't scale it first to min x min then apply the crop)

You are right，when your image's short side has exceeded MIN_DIM, the scale is set to 1 and the image won't be resized.
