### ISSUE TITLE
StopIteration @data_utils.py                            

### ISSUE THREAD

**Issue by kelvin84hk** [matterport/Mask_RCNN#257]
Hi,

I got error below for the generator when running train_shapes Notebook. I am using Python 3.6.2, Tensorflow 1.4.0 and Keras 2.0.9.  Please advice. Thanks a lot!

StopIteration                             Traceback (most recent call last)
<ipython-input-9-2101606c7d8e> in <module>()
      6             learning_rate=config.LEARNING_RATE,
      7             epochs=1,
----> 8             layers='heads')

H:\My Documents\AlgoResearch\Kaggle\DataScienceBowl2018\Mask_RCNN-master\model.py in train(self, train_dataset, val_dataset, learning_rate, epochs, layers)
   2236             max_queue_size=100,
   2237             workers=workers,
-> 2238             use_multiprocessing=True,
   2239         )
   2240         self.epoch = max(self.epoch, epochs)

H:\MyPrograms\Anaconda3\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

H:\MyPrograms\Anaconda3\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2044                 batch_index = 0
   2045                 while steps_done < steps_per_epoch:
-> 2046                     generator_output = next(output_generator)
   2047 
   2048                     if not hasattr(generator_output, '__len__'):

H:\MyPrograms\Anaconda3\lib\site-packages\keras\utils\data_utils.py in get(self)
    657                 all_finished = all([not thread.is_alive() for thread in self._threads])
    658                 if all_finished and self.queue.empty():
--> 659                     raise StopIteration()
    660                 else:
    661                     time.sleep(self.wait_time)

StopIteration:

**Comment by waleedka** [comment]
Happens if execution stops inside the data generator. I think recreateing the data generator object should solve it.
