### ISSUE TITLE
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by jianrun** [matterport/Mask_RCNN#2575]
I run the demo and threw an error
Keras: 2.4.3 
Tensorflow: 2.5.0

If Tensorflow  drops down to version 2.1, will encounter #2574 problems

**Comment by linj24** [comment]
For me, it was `keras-nightly` that was causing the problem.

`pip uninstall keras-nightly`
`pip uninstall keras`
`pip install keras`

And that did the trick.

**Comment by jianrun** [comment]
thanks @linj24
