### ISSUE TITLE
How to use mAP (defined in utils)?

### ISSUE THREAD

**Issue by SebastianNagy** [matterport/Mask_RCNN#2578]
Hello

I'm trying to train the mask RCNN on my own dataset and I would like to use mAP as a metric. Does anyone know how to use it so that it will print the results during training (and print graphs in tensorboard if possible)?

Thank you

**Comment by bhsnada** [comment]
> Hello
> 
> I'm trying to train the mask RCNN on my own dataset and I would like to use mAP as a metric. Does anyone know how to use it so that it will print the results during training (and print graphs in tensorboard if possible)?
> 
> Thank you

Me too I am looking to use mAP as a metric, if you find  a solution please share with us

**Comment by kuluruvineeth** [comment]
> > Hello
> > I'm trying to train the mask RCNN on my own dataset and I would like to use mAP as a metric. Does anyone know how to use it so that it will print the results during training (and print graphs in tensorboard if possible)?
> > Thank you
> 
> Me too I am looking to use mAP as a metric, if you find a solution please share with us

# calculate the mAP for a model on a given dataset
def evaluate_model(dataset, model, cfg):
      APs = list()
      for image_id in dataset.image_ids:
          ####load image, bounding boxes and masks for the image id
           image, _, gt_class_id, gt_bbox, gt_mask = load_image_gt(dataset, cfg,image_id,use_mini_mask=False)
          ####convert pixel values (e.g. center)
          scaled_image = mold_image(image, cfg)
          ####convert image into one sample
          sample = expand_dims(scaled_image, 0)
          #### make prediction
          yhat = model.detect(sample, verbose=0)
          #### extract results for first sample
           r = yhat[0]
           #### calculate statistics, including AP
           AP, _, _, _ = compute_ap(gt_bbox, gt_class_id, gt_mask, r["rois"], r["class_ids"],
r["scores"], r[ 'masks'])
          ####store
          APs.append(AP)
   #### calculate the mean AP across all images
   mAP = mean(APs)
   return mAP

**Comment by SebastianNagy** [comment]
Thank you!
