### ISSUE TITLE
Kernel has died when running the demo.py

### ISSUE THREAD

**Issue by p506738532** [matterport/Mask_RCNN#258]
my notebook has GTX950M with 2 GB memery,12G RAM.
cuda 9.0 and cuDNN v6.0 for cuda 8.0 are installed.
there is a issue when running the demo.py. when running the code below,kernel has died and have to restart.
`# Run detection
results = model.detect([image], verbose=1)`
there are some error information
` could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED`
Is cuDNN's version error or Graphics memory small ?
could you help me,3Q

**Comment by fastlater** [comment]
Same error. CUDA_ERROR_UNKNOW.
Any update or suggestion?

**Comment by p506738532** [comment]
I have soleved this erro through using the cuDNN7.0 . 
"https://www.tensorflow.org/install/install_windows" update as below:
![image](https://user-images.githubusercontent.com/16209077/36484241-914677a2-1753-11e8-909b-1d19e690b2f8.png)
@fastlater

**Comment by fastlater** [comment]
@p506738532
Thank you for your reply. I will try it later. Are you using tf 1.5? 2gb memory was enough for inference?

**Comment by p506738532** [comment]
@fastlater my gpu is 2GB too. maybe don't use the latest nvidia screen driver because the CUDA9.0 has a screen driver.

**Comment by fastlater** [comment]
@p506738532  well. I have been installing, uninstalling, and installing again the code and keep getting the CUDNN_STATUS_MAPPING_ERROR error. Do you know someone here you can help me out.  I have read the instructions several times and all the files are placed as the youtube tutorial https://www.youtube.com/watch?v=2TikTv6PWDw

2018-02-27 11:45:23.275524: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructi
ons that this TensorFlow binary was not compiled to use: AVX
2018-02-27 11:45:23.533539: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with pro
perties:
name: Quadro K2000 major: 3 minor: 0 memoryClockRate(GHz): 0.954
pciBusID: 0000:01:00.0
totalMemory: 2.00GiB freeMemory: 1.79GiB
2018-02-27 11:45:23.552540: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow dev
ice (/device:GPU:0) -> (device: 0, name: Quadro K2000, pci bus id: 0000:01:00.0,
 compute capability: 3.0)
[I 11:45:53.864 NotebookApp] Saving file at /Mask_RCNN/demo.ipynb
2018-02-27 11:46:41.003970: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran
 out of memory trying to allocate 2.07GiB. The caller indicates that this is not
 a failure, but may mean that there could be performance gains if more memory is
 available.
2018-02-27 11:46:52.468626: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\stream_executor\cuda\cuda_driver.cc:1080] failed to synchronize the
 stop event: CUDA_ERROR_UNKNOWN
2018-02-27 11:46:52.584632: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\stream_executor\cuda\cuda_timer.cc:54] Internal: error destroying C
UDA event in context 00000000258FE360: CUDA_ERROR_UNKNOWN
2018-02-27 11:46:52.585632: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\stream_executor\cuda\cuda_timer.cc:59] Internal: error destroying C
UDA event in context 00000000258FE360: CUDA_ERROR_UNKNOWN
2018-02-27 11:46:52.585632: F C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\stream_executor\cuda\cuda_dnn.cc:2289] failed to set stream for cud
nn handle: CUDNN_STATUS_MAPPING_ERROR
[I 11:47:24.287 NotebookApp] KernelRestarter: restarting kernel (1/5), keep rand
om ports
WARNING:root:kernel 134641e2-3f62-4019-9536-be72010310fa restarted

**Comment by p506738532** [comment]
@fastlater there are two points to notice.
1.cuda9.0 is right in environment path as below.
![image](https://user-images.githubusercontent.com/16209077/36713619-8fe67afe-1bc9-11e8-9991-7259fba24b13.png)
2.cudnn7.0 for cuda9.0 in win7 is copied to to the right place.for example,the right place in my laptop is C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin,C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib\x64,C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include

**Comment by fastlater** [comment]
@p506738532  Thank you for your recommendations. However, I dont think it is about path problems. If it was about path, error will say something like: Could not find 'cudart64_90.dll

I added some extra paths but still get this:

![gpu error](https://user-images.githubusercontent.com/30107093/36715486-6b4bb86e-1bd1-11e8-9f52-c8a433d6ef26.JPG)

**Comment by p506738532** [comment]
@fastlater 兄弟，中文交流可以的吗，我英文不好。简体中文能看懂的吗？
你可以在这个项目里提交自己的问题，就像我这样。也可以去tensorflow的GitHub那里去提交“https://github.com/tensorflow/tensorflow”
但是关于这个gpu版的tensorflow就两点需要注意，cuda和cudnn。你可以截图一下电脑的环境变量，然后就是你那个cudnn的版本对不，cudnn是否拷贝到了对应的位置。

**Comment by p506738532** [comment]
@fastlater please tell me the cudnn version and the path that the cudnn is copied to.maybe i could find some wrong.for example , my cudnn version is "cudnn-9.0-windows10-x64-v7.zip".

**Comment by fastlater** [comment]
@p506738532  Thank you for reply. 
I posted my problem in tensorflow github and nvidia forum. I will wait for their reply. 

According to https://stackoverflow.com/questions/48566505/how-can-i-check-if-keras-tensorflow-is-using-cudnn , if tensorflow does not detect the cuda and cudnn, it output a notification immediately. I hope someone in tf or nvidia can clarify this situation.
Thank you again for your kind support. I hope I can solve this issue, come back here to post the solution and then keep working on mask_rcnn.

**Comment by p506738532** [comment]
@fastlater  you're welcome and good luck.I think the official website of tensorflow has told us the right way to build the tensorflow-gpu.you can try more times following here "https://www.tensorflow.org/install/install_windows"

**Comment by fastlater** [comment]
Nvidia replied my question. It was a WDDM event. Increasing the TdrDelay value solved the problem.

**Comment by p506738532** [comment]
congratulation！Asking question at the right place is very important.

**Comment by HanYuanyuaner** [comment]
@fastlater where to change TdrDelay value?
