### ISSUE TITLE
test issue when run "build_rpn_model"

### ISSUE THREAD

**Issue by pidanxhq** [matterport/Mask_RCNN#26]
![image](https://user-images.githubusercontent.com/18607961/32434372-e2de2c5c-c318-11e7-8918-141763996e27.png)

**Comment by waleedka** [comment]
Can you repost the stack trace in text? The image is not loading

**Comment by pidanxhq** [comment]
@waleedka Thx for attention.,it's solved by https://github.com/matterport/Mask_RCNN/issues/30
