### ISSUE TITLE
As a result of training with custom data, all images will be the first class ID. 

### ISSUE THREAD

**Issue by toyotoyodir** [matterport/Mask_RCNN#2612]
I learned custom data with the "balloon" sample. There are five classes. For example 

"AAA"
"BBB"
"CCC"
"DDD"
"EEE" 

As a result of learning, all images will be recognized as class "AAA".

Why. I don't know why.

I used the annotation software "VGG Image Annotator (VIA)" when learning.
I set "name" in "Attributes" and entered "AAA", "BBB", etc. in it.
The saved file is "AS JSON" instead of "COCO FORMAT".
In the source, it is defined as follows. 

# code
self.add_class("balloon", 1, "AAA")
self.add_class("balloon", 2, "BBB")
self.add_class("balloon", 3, "CCC")
self.add_class("balloon", 4, "DDD")
self.add_class("balloon", 5, "EEE")

please tell me. Thank you.

**Comment by nataliameira** [comment]
I have the same problem.

**Comment by nataliameira** [comment]
@toyotoyodir look #372

**Comment by toyotoyodir** [comment]
To nataliameira
Thank you very much!
I will check it!
