### ISSUE TITLE
I can't find anything about P6 in the Mask RCNN paper where can i find details about this part?

### ISSUE THREAD

**Issue by JaspervDalen** [matterport/Mask_RCNN#263]
You make a difference between rpn_reature_maps and mrcnn_feature_maps, however in the paper both the classification/bb network and the mask network get the ROI's as input right? So why do you split them up into two different inputs?

**Comment by waleedka** [comment]
It's mentioned, in passing, in the FPN paper. https://arxiv.org/abs/1612.03144 

> Here we introduce P6 only for covering a larger anchor scale of 512.
P6 is simply a stride two subsampling of P5. P6 is not used by the Fast
R-CNN detector in the next section.

**Comment by JaspervDalen** [comment]
Thanks, but isn't Mask R-cnn based on fast R-CNN and should thus not use P6 as stated by your comment? If you look through slides and presentations from FAIR about Mask R-Cnn they all seem to use a rgion proposal network based on R-Cnn or am I missing something? Their figures of the architecutre also use the Fast R-CNN architecture having two fc layers of 1024.

**Comment by JaspervDalen** [comment]
never mind i mixed up fast and faster r_cnn
