### ISSUE TITLE
Visualize augmented images and masks

### ISSUE THREAD

**Issue by jatinrastogi** [matterport/Mask_RCNN#2631]
So I was trying to save the augmented images and masks on them but I ran through some error when I tried to save masks, As mask gives a boolean array so I tried to apply it on the image like this 
![Screenshot from 2021-07-12 20-03-57](https://user-images.githubusercontent.com/67838197/125306118-8eef5000-e34c-11eb-9748-c8d6baaa2925.png)

But then I face type error
`TypeError:can't multiply sequence of non-int type float`
Then I replaced 0.5*color[c]*255 with color[c]*255
But then I faced this error
`operands could not be broadcast together shapes (1024,1024) (765,)`

**Comment by jainakhil88** [comment]
@jatinrastogi  How did you fix it?

**Comment by jatinrastogi** [comment]
@jainakhil88  I solved it by looping through the masks to save the augmented image

**Comment by jainakhil88** [comment]
> @jainakhil88 I solved it by looping through the masks to save the augmented image

How?? Can you share the code?
