### ISSUE TITLE
Loading .h5 failed

### ISSUE THREAD

**Issue by miladsade96** [matterport/Mask_RCNN#2634]
Hi all
I have downloaded the .h5 format of model in order to use it in tensorflow.
but when i want to load it the error bellow occurs:

Sample code:
```python
"""
Loading the pre-trained model
"""

from tensorflow.keras.models import load_model


new_model = load_model("mask_rcnn_coco.h5")

new_model.summary()

```

and error:

![error](https://user-images.githubusercontent.com/57490926/125460035-9af9d159-d6a6-4fc2-8bbe-ef4e8c3a4256.png)

**Comment by agbozo1** [comment]
I suppose you are not pointing it to the exact folder where the model exists.
To verify this, move the **mask_rcnn_coco.h5** file to the main folder where your model code exists.

**Comment by miladsade96** [comment]
@agbozo1 Thanks
