### ISSUE TITLE
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' 

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [matterport/Mask_RCNN#2637]
I keep getting different error relating to `Keras` and `Tensorflow` most likely due to version compatibility issues. 
Since I was getting this error: `TypeError: Could not build a TypeSpec for <KerasTensor: shape=(None, None, 4)` I downgraded `tf` to `2.3.0`.
Now I keep getting this error:
```
Traceback (most recent call last):
  File "flower.py", line 43, in <module>
    from mrcnn import model as modellib, utils
  File "/content/gdrive/My Drive/Mask_RCNN_GrapeDetection/Mask_RCNN/mrcnn/model.py", line 26, in <module>
    import keras.engine.topology as KE
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.7/dist-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 37, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py)
```

I tried modifying `model.py`, mainly the way I import `keras` and its modules; changed `import keras` to `from tensorflow import keras` but I keep getting some kind of an error.

If someone could mention a `pip freeze > out.txt` with versions and dependencies that are needed for proper training, that'd be great!

**Comment by nataliameira** [comment]
@mansi-aggarwal-2504 
Hey
I trained my model and visualized the data.
My training was held on June 3, 2021.
I used:

pip uninstall keras-nightly
pip uninstall -y tensorflow
h5py==2.10.0
tensorflow==1.15
tensorflow-gpu==1.15.0
keras==2.1.6

**Comment by mansi-aggarwal-2504** [comment]
Thank you @nataliameira! This helped.

**Comment by Sultan91** [comment]
It says `Could not find a version that satisfies the requirement tensorflow==1.15 `

**Comment by nataliameira** [comment]
> It says `Could not find a version that satisfies the requirement tensorflow==1.15 `

@Sultan91 Use python version 3.6
