### ISSUE TITLE
RCNN's default classes are being detected with the newly transfer trained class

### ISSUE THREAD

**Issue by Minkleberry** [matterport/Mask_RCNN#2653]
Hello!

I've been trying to get the RCNN to detect mosquitoes, which I've been able to do successfully but it also classifies chairs, vases, and tables as a mosquito as well. I think these are from the base 80 objects trained.

I've been trying to remove these other objects with no success.

I've tried to re-add the base classes back and set "mosquito" as a new class. But I keep getting errors with the weight shape.

Is there anyway to separate any objects detected in the background from the mosquito? 

Any help at all would be greatly appreciated. Thanks!

class TestConfig(Config):
	NAME = "test"
	GPU_COUNT = 1
	IMAGES_PER_GPU = 1
	NUM_CLASSES = 1 + 80 + 1

`ValueError: Layer #391 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 324) dtype=float32_ref> has shape (1024, 324), but the saved weight has shape (1024, 8).
`

<img width="551" alt="Capture" src="https://user-images.githubusercontent.com/88025663/127120959-37329b87-bc85-4933-bb76-173c3131f6fe.PNG">
<img width="775" alt="Capture2" src="https://user-images.githubusercontent.com/88025663/127121108-6a1c9c9a-547d-4de2-859c-eb33db758204.PNG">

**Comment by modraa-pixels** [comment]
you should set NUM_CLASSES to 1+1 ( 1 for bg and 1 for your mosquitto class)

**Comment by Minkleberry** [comment]
> 
> 
> you should set NUM_CLASSES to 1+1 ( 1 for bg and 1 for your mosquitto class)

Hi! Whenever I tried to set it like this, the net classifies other objects as "mosquito"

![image](https://user-images.githubusercontent.com/88025663/127206652-8dbca32f-758a-479c-865a-2871234de496.png)


class_names = ['BG', 'mosquito']

class TestConfig(Config):
	NAME = "test"
	GPU_COUNT = 1
	IMAGES_PER_GPU = 1
	NUM_CLASSES = 1 + 1

def Testnew2():
	# define the model
	rcnn = MaskRCNN(mode='inference', model_dir='./', config=TestConfig())
	# load coco model weights
	os.chdir(r'E:')
	#rcnn.load_weights('mask_rcnn_mosquito_cfg_0011.h5', by_name=True, exclude=["mrcnn_class_logits", "mrcnn_bbox_fc","mrcnn_bbox", "mrcnn_mask"])
	rcnn.load_weights('mask_rcnn_mosquito_cfg_0011.h5', by_name=True)
	#rcnn.load_weights('mask_rcnn_coco.h5', by_name=True)
	#rcnn.load_weights('mask_rcnn_mosquito_cfg_0011.h5', by_name=True)
	# load photograph
	#img = load_img('024571.png')
	img = load_img('Backyard.jpg')
	img = img_to_array(img)
	# make prediction
	results = rcnn.detect([img], verbose=0)
	# get dictionary for first prediction
	r = results[0]
	# show photo with bounding boxes, masks, class labels and scores
	print(r['rois'], r['class_ids'], class_names, r['scores'])
	display_instances(img, r['rois'], r['masks'], r['class_ids'], class_names, r['scores'])

**Comment by modraa-pixels** [comment]
@Minkleberry how do you load the weights when you do training/inference ?

**Comment by Minkleberry** [comment]
@mohamedkaraa Here's my config & loading weights code for training:

class MosquitoConfig(Config):
	# define the name of the configuration
	NAME = "mosquito_cfg"
	# number of classes (background + 1)
	NUM_CLASSES = 1 + 1
	# number of training steps per epoch
	STEPS_PER_EPOCH = 90

model = MaskRCNN(mode='training', model_dir=r'./', config=config)
	# load weights (mscoco) and exclude the output layers
	model.load_weights('mask_rcnn_coco.h5', by_name=True, exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", "mrcnn_bbox", "mrcnn_mask"])
	# train weights (output layers or 'heads')
	model.train(train_set, test_set, learning_rate=config.LEARNING_RATE, epochs=11, layers='heads')






Here is my current code to test the weight:

class TestConfig(Config):
	NAME = "test"
	GPU_COUNT = 1
	IMAGES_PER_GPU = 1
	NUM_CLASSES = 1 + 1

rcnn = MaskRCNN(mode='inference', model_dir='./', config=TestConfig())
rcnn.load_weights('mask_rcnn_mosquito_cfg_0011.h5', by_name=True)
img = load_img('Backyard.jpg')
img = img_to_array(img)
results = rcnn.detect([img], verbose=0)
r = results[0]
print(r['rois'], r['class_ids'], class_names, r['scores'])
display_instances(img, r['rois'], r['masks'], r['class_ids'], class_names, r['scores'])


If there is anything else you would like me to show, please just ask. Thank you!!

**Comment by modraa-pixels** [comment]
@Minkleberry maybe your model is not trained enough or your dataset is small to train it. Also i think to make it distinguish mosquittos you may want to feed the model images that contain mosquittos and non-mosquittos at a comparable scale

**Comment by Minkleberry** [comment]
@mohamedkaraa Thanks, I'll see if I can add non-mosquito images to teach the model with.

One last question. I know that the original weights 'mask_rcnn_coco.h5' has 80 pre-trained objects in it. And the network seems to be detecting these objects and classifying them as mosquito. Do you know if I could somehow get the transfer learned model to tell me when it detects a "vase" or "chair" and just exclude it from detections?

**Comment by modraa-pixels** [comment]
> @mohamedkaraa Thanks, I'll see if I can add non-mosquito images to teach the model with.
> 
> One last question. I know that the original weights 'mask_rcnn_coco.h5' has 80 pre-trained objects in it. And the network seems to be detecting these objects and classifying them as mosquito. Do you know if I could somehow get the transfer learned model to tell me when it detects a "vase" or "chair" and just exclude it from detections?

you'll have to add all the classes to your config class and then exclude them if detected. But i think that will make your model more complex and it's not practical!

**Comment by Minkleberry** [comment]
> 
> 
> > @mohamedkaraa Thanks, I'll see if I can add non-mosquito images to teach the model with.
> > One last question. I know that the original weights 'mask_rcnn_coco.h5' has 80 pre-trained objects in it. And the network seems to be detecting these objects and classifying them as mosquito. Do you know if I could somehow get the transfer learned model to tell me when it detects a "vase" or "chair" and just exclude it from detections?
> 
> you'll have to add all the classes to your config class and then exclude them if detected. But i think that will make your model more complex and it's not practical!

Ah alrighty. Dang.

I'll see if I can add some non-mosquito training data into the mix. I wanted to thank you again for your help!
