### ISSUE TITLE
precision-recall curve

### ISSUE THREAD

**Issue by nataliameira** [matterport/Mask_RCNN#2661]
Hi all,
I understand that the compute_ap function calculates the AP metric.

My model has 5 classes + background.

When I generate the precision-recall curve several times, the AP values are different.

Can someone explain to me? Thank you for your help.
![curva precision-recall 1](https://user-images.githubusercontent.com/56967314/128062921-655e3724-6765-475f-8b22-a83a978b6077.png)

**Comment by software93** [comment]
hello dear ???? i have same problem ?
how did you solve it ?
