### ISSUE TITLE
Training on custom dataset with coco annotation format

### ISSUE THREAD

**Issue by chhigansharma** [matterport/Mask_RCNN#2666]
Hi All, 

I want to train mask_rcnn on my custom dataset for 1 class with coco annotation format so i was trying to edit coco.py config according to my dataset but ended up getting up errors. I have also looked at balloon sample for 1 class but that is not using coco format.

If anyone come across such scenarios please help.
Regards,
Chhigan Sharma

#""ANNOTTATIONS"

"categories": [
        {
            "supercategory": "AgriculturalFields",
            "id": 1,
            "name": "agfields_singleclass"
        }
    ],
    "images": [
        {
            "file_name": "COCO_val2016_000000100004.jpg",
            "id": 100004,
            "height": 128,
            "width": 128
        },
 ............................................................continue

"annotations": [
        {
            "id": 1,
            "image_id": 100004,
            "category_id": 1,
            "mycategory_name": "agfields_singleclass",
            "old_multiclass_category_name": "springcereal",
            "old_multiclass_category_id": 1,
            "bbox": [
                8.8,
                110.51,
                13.74,
                17.49
            ],
            "area": 89.76729724821337,
            "iscrowd": 0,
            "segmentation": [
                [
                    8.8,
                    128.0,
                    20.3,
                    110.51,
                    22.54,
                    111.97,
                    19.9,
                    116.38,
                    22.3,
                    117.25,
                    15.1,
                    128.0,
                    8.8,
                    128.0
                ]
            ]
        },

# sample annotations of my dataset

**Comment by nataliameira** [comment]
@chhigansharma
Hi. I received your e-mail.
 What error did you get?

**Comment by chhigansharma** [comment]
@nataliameira 

I'm having issues while editing coco.py for 1 custom class and getting errors while doing data inspection.
If you can provide sample coco.py for custom coco annotations format data that would be great help.

Thanks & Regards,
Chhigan Sharma

**Comment by nataliameira** [comment]
@chhigansharma 

I implemented my model from the balloon.py example. I don't have the coco.py example.
I saw that some changes are similar. Look this: <https://towardsdatascience.com/mask-rcnn-implementation-on-a-custom-dataset-fd9a878123d4>

Good luck!

**Comment by chhigansharma** [comment]
I have resolved error, Following train_shapes and this article.
Even though at the time of calling weights getting one system error.
""
model.load_weights(COCO_MODEL_PATH, by_name=True,
                       exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", 
                                "mrcnn_bbox", "mrcnn_mask"]) ""

After executing i'm getting below error 

UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-13-b502c6c49fa5> in <module>
     10     model.load_weights(COCO_MODEL_PATH, by_name=True,
     11                        exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", 
---> 12                                 "mrcnn_bbox", "mrcnn_mask"])
     13 elif init_with == "last":
     14     # Load the last model you trained and continue training

~\Documents\boundary detection\Mask_RCNN\mrcnn\model.py in load_weights(self, filepath, by_name, exclude)
   2113         if h5py is None:
   2114             raise ImportError('`load_weights` requires h5py.')
-> 2115         with h5py.File(filepath, mode='r') as f:
   2116             if 'layer_names' not in f.attrs and 'model_weights' in f:
   2117                 f = f['model_weights']

c:\users\20013819\anaconda3\envs\tensorflow\lib\site-packages\h5py\_hl\files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    393                 name = repr(name).encode('ASCII', 'replace')
    394             else:
--> 395                 name = filename_encode(name)
    396 
    397             if track_order is None:

c:\users\20013819\anaconda3\envs\tensorflow\lib\site-packages\h5py\_hl\compat.py in filename_encode(filename)
    112     if sys.platform == "win32":
    113         if isinstance(filename, six.text_type):
--> 114             return filename.encode(WINDOWS_ENCODING, "strict")
    115         return filename
    116     return fsencode(filename)

UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

Thanks

**Comment by nataliameira** [comment]
I used:

pip uninstall keras-nightly
pip uninstall -y tensorflow
h5py==2.10.0
tensorflow==1.15
tensorflow-gpu==1.15.0
keras==2.1.6

Try this.

**Comment by chhigansharma** [comment]
I'm using

h5py==2.10.0
tensorflow==2.30
tensorflow-gpu==2.3.0

**Comment by sauravsolanki** [comment]
1. `sudo pip install --no-deps tensorflow==1.15.3`
    `sudo pip install --no-deps keras==2.2.4`
2. Git clone this repo
3. then 
`cd Mask_RCNN`
`python setup.py install`

**Comment by chhigansharma** [comment]
Hi All,

I have trained model on custom dataset using tensorflow 2.3 and keras 2.4 version. I have resolved the errors.

Thanks
