### ISSUE TITLE
not upward compatible

### ISSUE THREAD

**Issue by hanhern** [matterport/Mask_RCNN#2689]
the model isn't compatible with later versions of tensorflow and keras

**Comment by nataliameira** [comment]
Hey @hanhern 

I trained my model and visualized the data.
My training was held on June 3, 2021.
I used:

```
pip uninstall keras-nightly
pip uninstall -y tensorflow
h5py==2.10.0
tensorflow==1.15
tensorflow-gpu==1.15.0
keras==2.1.6
```

**Comment by fulltrend** [comment]
the version combination above should work with  python 3.6
