### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes 

### ISSUE THREAD

**Issue by chhigansharma** [matterport/Mask_RCNN#2693]
I have trained Mask_RCNN on my custom dataset using Tensorflow 2.3 but i'm not able to inference image.

# Test on a random image
image_id = random.choice(dataset_val.image_ids)
original_image, image_meta, gt_class_id, gt_bbox, gt_mask =\
    modellib.load_image_gt(dataset_val, inference_config, 
                           image_id)

log("original_image", original_image)
log("image_meta", image_meta)
log("gt_class_id", gt_class_id)
log("gt_bbox", gt_bbox)
log("gt_mask", gt_mask)

visualize.display_instances(original_image, gt_bbox, gt_mask, gt_class_id, 
                            dataset_train.class_names, figsize=(8, 8)) 

**ERROR**

original_image           shape: (128, 128, 3)         min:   38.00000  max:  246.00000  uint8
image_meta               shape: (14,)                 min:    0.00000  max: 1590.00000  int32
gt_class_id              shape: (29,)                 min:    1.00000  max:    1.00000  int32
gt_bbox                  shape: (29, 4)               min:    0.00000  max:  128.00000  int32
gt_mask                  shape: (56, 56, 29)          min:    0.00000  max:    1.00000  bool
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-4994cf6a2e6a> in <module>
     12 
     13 visualize.display_instances(original_image, gt_bbox, gt_mask, gt_class_id, 
---> 14                             dataset_train.class_names, figsize=(8, 8))

~\Documents\boundary detection\Mask_RCNN\mrcnn\visualize.py in display_instances(image, boxes, masks, class_ids, class_names, scores, title, figsize, ax, show_mask, show_bbox, colors, captions)
    150         mask = masks[:, :, i]
    151         if show_mask:
--> 152             masked_image = apply_mask(masked_image, mask, color)
    153 
    154         # Mask Polygon

~\Documents\boundary detection\Mask_RCNN\mrcnn\visualize.py in apply_mask(image, mask, color, alpha)
     77                                   image[:, :, c] *
     78                                   (1 - alpha) + alpha * color[c] * 255,
---> 79                                   image[:, :, c])
     80     return image
     81 

<__array_function__ internals> in where(*args, **kwargs)

ValueError: operands could not be broadcast together with shapes (56,56) (128,128) (128,128)

**Comment by nataliameira** [comment]
Hey @chhigansharma, 

For a random image, try this:

```
image_id = random.choice(dataset.image_ids)
image, image_meta, gt_class_id, gt_bbox, gt_mask =\
    modellib.load_image_gt(dataset, config, image_id, use_mini_mask=False)
info = dataset.image_info[image_id]
print("image ID: {}.{} ({}) {}".format(info["source"], info["id"], image_id, 
                                       dataset.image_reference(image_id)))

results = model.detect([image], verbose=1)

ax = get_ax(1)
r = results[0]
visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'], 
                            dataset.class_names, r['scores'], ax=ax,
                            title="Predictions")
log("gt_class_id", gt_class_id)
log("gt_bbox", gt_bbox)
log("gt_mask", gt_mask)
```

For a known image, use this:

```
image1 = mpimg.imread('dataset/teste/002.jpg')    #update this path

print(len([image1]))
results1 = model.detect([image1], verbose=1)

mrcnn = model.run_graph([image1], [
    ("detections", model.keras_model.get_layer("mrcnn_detection").output),
    ("masks", model.keras_model.get_layer("mrcnn_mask").output),
])

det_class_ids = mrcnn['detections'][0, :, 4].astype(np.int32)
det_count = np.where(det_class_ids == 0)[0][0]
det_class_ids = det_class_ids[:det_count]

print("{} detections: {}".format(
    det_count, np.array(dataset.class_names)[det_class_ids]))


ax = get_ax(1)
r1 = results1[0]
visualize.display_instances(image1, r1['rois'], r1['masks'], r1['class_ids'],
                            dataset.class_names, r1['scores'], ax=ax, show_bbox=False, show_mask=False,
                            title="Predictions")
```

**Comment by chhigansharma** [comment]
Thanks @nataliameira .

This works.
