### ISSUE TITLE
How to exclude image shape when loading model weights?

### ISSUE THREAD

**Issue by christianburbon** [matterport/Mask_RCNN#2703]
I am getting this error message when loading weights from custom model I trained even though I used the same config where both configs use

    IMAGE_MIN_DIM = 256
    IMAGE_MAX_DIM = 256

I also already tried using how COCO weights are loaded but still not working
  

>   model.load_weights(os.path.join(MODEL_DIR,modelh5_path),exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", 
>                                 "mrcnn_bbox", "mrcnn_mask"])

(Pretrained weights using https://www.kaggle.com/alexo98/leaf-detection)
Detail on error message

```

>   File "D:\Anaconda3\envs\mask_rcnn\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 256, in model_iteration
>     batch_outs = batch_function(*batch_data)
> 
>   File "D:\Anaconda3\envs\mask_rcnn\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 1038, in train_on_batch
>     extract_tensors_from_dataset=True)
> 
>   File "D:\Anaconda3\envs\mask_rcnn\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 2308, in _standardize_user_data
>     batch_size=batch_size)
> 
>   File "D:\Anaconda3\envs\mask_rcnn\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 2335, in _standardize_tensors
>     exception_prefix='input')
> 
>   File "D:\Anaconda3\envs\mask_rcnn\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 582, in standardize_input_data
>     str(data_shape))
> 
> ValueError: Error when checking input: expected input_image to have shape (512, 512, 3) but got array with shape (256, 256, 3)
> 
> 

Any suggestions?

**Comment by VeeranjaneyuluToka** [comment]
Based on the above error, it looks like your pre-trained model is with input size 512x512x3 and trying to load it with input size 256x256x3. So may be you can try with input size 512x512x3 and check if the error disappear.

**Comment by christianburbon** [comment]
> Based on the above error, it looks like your pre-trained model is with input size 512x512x3 and trying to load it with input size 256x256x3. So may be you can try with input size 512x512x3 and check if the error disappear.

@VeeranjaneyuluToka Yes, the error does disappear when I do this. However, I am trying to look for a solution where I can disregard the input shape of my pre-trained model similar to how the Coco pre-trained weights are loaded. Any ideas?

**Comment by VeeranjaneyuluToka** [comment]
Am not 100% sure but i think if your pre-trained model is created with unknown shape such as (None, None, 3) rather than a fixed size ( in this 512,512,3), then it would have been possible. If your pre-trained model is created with fixed size (512x512x3), then you need to go for transfer learning to change. Let us also know if i am wrong and if you find a solution.

**Comment by christianburbon** [comment]
I see. Thanks for that insight @VeeranjaneyuluToka. I'll explore what you mentioned and come back if I resolve the issue.

**Comment by christianburbon** [comment]
Update:
It might not be very intuitive but when I restarted python it worked. It seems like it was loading weights from previous models in memory which is why I was having issues even though I have same configurations.

However, still have not found any solution with regards to loading model with different weights. I would suggest inspecting model.py and figure out which layers and/or losses depend on shape inputs and exclude that when loading the weights.
