### ISSUE TITLE
Previously working detection failing

### ISSUE THREAD

**Issue by vassanyig** [matterport/Mask_RCNN#2705]
I had been using the code in Google Colab to train a model using the pretrained one based on my own data. In February the training and detection was working fine. However, the exact same code results in an error when training a new model, and detection fails when trying to use prevoiusly trained models from February. 
Instead of finding one or two rois on a test image as desired, the program detects about one hundred. When visualized, the rois are not even remotely close to anything that would make sense.
The last working code used these versions: 
python ==3.6.4
tensorflow==2.0 
tensorflow-gpu==2.0
Since then my colleague managed to get the model training part working by modifying the keras core.py and the mrcnn model.py files, but the detection still fails using models trained this way. 
I suspect the problem is caused due to Colab using newer versions eg. tensorflow 2.6.0, but I am not sure whether this is the case or how it could be managed.

**Comment by nataliameira** [comment]
Hello @vassanyig ,

You can use

```
pip uninstall keras-nightly
pip uninstall -y tensorflow
pip install h5py==2.10.0
pip install tensorflow==1.15
pip install tensorflow-gpu==1.15.0
pip install keras==2.1.6
```

So,
`python3 custom.py train --dataset=dataset --weights=coco`

**Comment by vassanyig** [comment]
Cheers, I started over and now it works.
