### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (571,800,3) (300,506,3) 

### ISSUE THREAD

**Issue by hcyeow** [matterport/Mask_RCNN#2713]
I was trying to remove the background and only include the the segmented object in my image but however only 1 image worked but the rest showing me this error. Any one has faced this issue? 
![image](https://user-images.githubusercontent.com/67724089/138850353-36eef9b5-90cd-44cf-bc55-a05f0f3f0472.png)

**Comment by jainakhil88** [comment]
@hcyeow how did you fix it?
