### ISSUE TITLE
Help me! training model not working! (Converting sparse IndexedSlices to a dense Tensor of unknown shape.)

### ISSUE THREAD

**Issue by JunhoSer** [matterport/Mask_RCNN#2729]
I'm going to learn the sapcenet and detect the building.
However, learning is no longer progressing in Epoch 1. (GPU is 100% working.)
Print out the phrase below and stop at Epoch 1/1.
'Converting sparse IndexedSlices to a dense Tensor of unknown shape.'

There are only two classes I need: Background and Building.
I wrote layers='head' but it doesn't work out.

I need the help of many people because I am a beginner at detecting objects for the first time.

Please help me.

The code I executed is as follows. (Attach the entire code as .txt.) Please convert to ipynd and take a look.):

model = modellib.MaskRCNN(mode="training", config=config,
                          model_dir=MODEL_DIR)
init_with = "imagenet"  # imagenet, coco, or last

if init_with == "imagenet":
    model.load_weights(model.get_imagenet_weights(), by_name=True)
elif init_with == "coco":
    # Load weights trained on MS COCO, but skip layers that
    # are different due to the different number of classes
    # See README for instructions to download the COCO weights
    model.load_weights(COCO_MODEL_PATH, by_name=True,
                       exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", 
                                "mrcnn_bbox", "mrcnn_mask"])
elif init_with == "last":
    # Load the last model you trained and continue training
    #model.load_weights(model.find_last(), by_name=True)
    model.load_weights(model.find_last(), by_name=True)
model.train(dataset_train, dataset_val, 
            learning_rate=config.LEARNING_RATE, 
            epochs=100, 
            layers='all')
[Training.txt](https://github.com/matterport/Mask_RCNN/files/7559944/Training.txt)

For your information, my working environment is as follows:
window 10
intel i5 10400f
gtx3060ti
32g ram
tensorflow-gpu 1.13.1
keras 2.1.6

**Comment by JunhoSeo2075** [comment]
> I'm going to learn the sapcenet and detect the building. However, learning is no longer progressing in Epoch 1. (GPU is 100% working.) Print out the phrase below and stop at Epoch 1/1. 'Converting sparse IndexedSlices to a dense Tensor of unknown shape.'
> 
> There are only two classes I need: Background and Building. I wrote layers='head' but it doesn't work out.
> 
> I need the help of many people because I am a beginner at detecting objects for the first time.
> 
> Please help me.
> 
> The code I executed is as follows. (Attach the entire code as .txt.) Please convert to ipynd and take a look.):
> 
> model = modellib.MaskRCNN(mode="training", config=config, model_dir=MODEL_DIR) init_with = "imagenet" # imagenet, coco, or last
> 
> if init_with == "imagenet": model.load_weights(model.get_imagenet_weights(), by_name=True) elif init_with == "coco": # Load weights trained on MS COCO, but skip layers that # are different due to the different number of classes # See README for instructions to download the COCO weights model.load_weights(COCO_MODEL_PATH, by_name=True, exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", "mrcnn_bbox", "mrcnn_mask"]) elif init_with == "last": # Load the last model you trained and continue training #model.load_weights(model.find_last(), by_name=True) model.load_weights(model.find_last(), by_name=True) model.train(dataset_train, dataset_val, learning_rate=config.LEARNING_RATE, epochs=100, layers='all') [Training.txt](https://github.com/matterport/Mask_RCNN/files/7559944/Training.txt)
> 
> For your information, my working environment is as follows: window 10 intel i5 10400f gtx3060ti 32g ram tensorflow-gpu 1.13.1 keras 2.1.6
