### ISSUE TITLE
After I trained the model for text recognition, it was confusing to recognize characters between 6 and 9. 

### ISSUE THREAD

**Issue by leekwunfung817** [matterport/Mask_RCNN#2730]
After I trained the model for text recognition, it was confusing to recognize characters between 6 and 9. 

Could anyone tell me the reason?

**Comment by yajain** [comment]
Maybe the dataset needs to be looked at. Must have an equally high number of both classes otherwise the classification heads won't do a good job.

**Comment by leekwunfung817** [comment]
> Maybe the dataset needs to be looked at. Must have an equally high number of both classes otherwise the classification heads won't do a good job.

The directions of the detect instances are dynamic?

**Comment by leekwunfung817** [comment]
I cannot completely fix this problem, because these two characters have some similarities in a different direction.
Also, it will train in different directions even the annotation has the same direction, so we have to have a post-process after the inference.
