### ISSUE TITLE
"ImportError: cannot import name 'Layers' from 'keras.layers'

### ISSUE THREAD

**Issue by mlsy123** [matterport/Mask_RCNN#2734]
Note: I am running this locally on Jupyter notebook, not on Google Colab.

"""""""""""""" CODE """"""""""""""""""""
sys.path.append(ROOT_DIR)  # To find local version of the library
from mrcnn.config import Config
from mrcnn import utils
*import mrcnn.model as modellib*
from mrcnn import visualize
from mrcnn.model import log
""""""""""""""""""""""""""""""""""""""""""""""

"""""""""" ERROR""""""""""""""""""""""
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_17240/1810757526.py in <module>
     17 from mrcnn.config import Config
     18 from mrcnn import utils
---> 19 import mrcnn.model as modellib
     20 from mrcnn import visualize
     21 from mrcnn.model import log

~\Anaconda3\lib\site-packages\mrcnn\model.py in <module>
     22 import keras.backend as K
     23 import keras.layers as KL
---> 24 from keras.layers import Layers as KE
     25 #import keras.engine.topology as KE
     26 import keras.models as KM

ImportError: cannot import name 'Layers' from 'keras.layers' (C:\Users\a1737542\Anaconda3\lib\site-packages\keras\layers\__init__.py)
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
I know this issue has been brought up several time across the internet, but none of the solutions provided so far is working for me.  I have tried
1. Changing 'import keras.engine as KE' to 'import keras.engine.topology as KE'
2. !pip install tensorflow==1.13.1
    !pip install keras==2.0.8
    !pip install h5py==2.10.0
Getting this error : ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0)
ERROR: No matching distribution found for tensorflow==1.13.1
I am having a tensorflow version of 2.7.0 now.

**Comment by BupyeongHealer** [comment]
The original mask-rcnn uses the tensorflow 1.X version.
I modified it for tensorflow 2.X version.

https://github.com/BupyeongHealer/Mask_RCNN_tf_2.x

**Comment by mlsy123** [comment]
> The original mask-rcnn uses the tensorflow 1.X version. I modified it for tensorflow 2.X version.
> 
> https://github.com/BupyeongHealer/Mask_RCNN_tf_2.x

I'm still getting the same issue but it's attribute error rather than import error now.

**Comment by BupyeongHealer** [comment]
I just modified demo.ipynb for inference.

Can you upload the error message?

**Comment by mlsy123** [comment]
![image](https://user-images.githubusercontent.com/94586300/144943999-39ffd6f7-5569-40dd-aefd-e5c4678c4c7f.png)

This is the error I'm getting when running demo.ipynb.

**Comment by BupyeongHealer** [comment]
How about install tensorflow 2.5.0 and keras 2.5.0?

**Comment by mlsy123** [comment]
![image](https://user-images.githubusercontent.com/94586300/144961102-f2bf443c-7447-4a5d-b3e0-0b7c2109d503.png)
Couldn't seem to do that.

**Comment by BupyeongHealer** [comment]
In that case, you didn't recommend install keras, just install tensorflow 2.5.0.

**Comment by mlsy123** [comment]
![image](https://user-images.githubusercontent.com/94586300/144963277-f415f7d0-d7c7-4a3c-bffb-7df9e42be2ff.png)
I'm getting this now.

**Comment by BupyeongHealer** [comment]
I think you resolve the setting problem for your own device.
because, depend on device, you can install the possible version.

**Comment by mlsy123** [comment]
I've resolved the issue and I now have tensorflow 2.5.0 installed, however I'm still getting the same attribute error.

**Comment by BupyeongHealer** [comment]
I'm not sure. I recommend the 
replace 
**import keras.engine as KE**
with
**import keras.engine.topology as KE**

**Comment by mlsy123** [comment]
I have managed to resolved the above error after installing a tensorflow of version 2.5.0 , keras of version 2.4.0  and replaced this line as recommended. Thanks .
