### ISSUE TITLE
Error while loading weights of training on custom dataset!

### ISSUE THREAD

**Issue by Kamlesh364** [matterport/Mask_RCNN#2768]
Hello there!
I've trained MRCNN on my custom dataset of dental X-rays. I've not made any changes to the model architecture. Just trained the model for 100 epochs and save the weights, in ".h5" format, after each epoch and using its own "save_weights" method. But whenever I try to load the weights again for further training, using "load_weights" method, I get the error shown below. 
Please help me to solve this issue.

**ValueError: Layer #362 (named "anchors"), weight <tf.Variable 'Variable_2:0' shape=(2, 261888, 4) dtype=float32> has shape (2, 261888, 4), but the saved weight has shape (1, 261888, 4).**

**Comment by rocks-leazy** [comment]
I have exact same error. I just set weights to `last`. Do you happen to have any progress?

**Comment by Kamlesh364** [comment]
> I have exact same error. I just set weights to `last`. Do you happen to have any progress?

Make sure that the parameters "IMAGES_PER_GPU" value is same in both the cases, "training" and "inference". I trained the model while keeping "IMAGES_PER_GPU=1". But, while choosing "inference" mode, I kept "IMAGES_PER_GPU=2" and that was the thing causing the error. So, please make sure you're not doing the same mistake.
Let me know if you need further help.

**Comment by rocks-leazy** [comment]
@Kamlesh364 

Yeah, it was not complicated issue, though. I resolved the problem by your help. You are such a nice person. Thank you.
