### ISSUE TITLE
Masks are not correctly drawn

### ISSUE THREAD

**Issue by lydiakienbaum** [matterport/Mask_RCNN#2772]
I trained certain models for detecting objects of 3 different classes and chose the model with the highest mAP. However, it seems that the masks are not correctly displayed. Is there any solution?
![01-annotation_image-validation_HUA](https://user-images.githubusercontent.com/59022575/152575699-0fec37a2-ced1-4da9-ba5d-7fc40286a8ef.jpg)

**Comment by lydiakienbaum** [comment]
I figured it out myself...I was expanding the mask branch and still using for the detection the old code of the layer. This is why the masks wee not correctly created.

**Comment by f-macfarlane95** [comment]
I am having a similar issue with tf==1.15 and keras==2.2.5. How exactly did you fix this?
