### ISSUE TITLE
How to train using dataset which is in segmented masks in png format ?

### ISSUE THREAD

**Issue by dd2-42** [matterport/Mask_RCNN#2784]
The dataset is in segmented masks in png format as shown below structure, any suggestion on how to train it. The dataset structure is :

Object_Images
         -> img1.png
         -> img2.png
         . . . 
Object_Segmented_Masks
         ->img1_seg_mask.png
         ->img2_seg_mask.png
        . . . 

There is no annotations data in usual 'json' format. Any suggestion?

**Comment by dd2-42** [comment]
Wrote my own code.

**Comment by asterberova** [comment]
Hi, can I ask how did you solve it?

**Comment by jgoueslard** [comment]
> Wrote my own code.

Could you share us what you did because Im trying to do this but I have some problems with the creation of masks

Thanks,

**Comment by dd2-42** [comment]
@asterberova @jgoueslard  Sorry I missed the message. Could you both please share your folder tree structure of files along with their types and sample images so that I can let you know how to format and preprocess your data.

**Comment by jgoueslard** [comment]
Hello, I actually found a way to solve my problem and it seems to be working but I'll come back to you if I have a question. 

Thanks for you help !

**Comment by asterberova** [comment]
Hi, I also already solved it. Thank you:)

**Comment by dd2-42** [comment]
Great !
