### ISSUE TITLE
When running train_shapes.ipynb AttributeError occured.

### ISSUE THREAD

**Issue by shravankumar147** [matterport/Mask_RCNN#28]
```
model.train(dataset_train, dataset_val, 
            learning_rate=config.LEARNING_RATE, 
            epochs=1, 
            layers='heads')
```
AttributeError: Can't pickle local object 'GeneratorEnqueuer.start.<locals>.data_generator_task'

**Comment by waleedka** [comment]
I think this is a duplicate of issue https://github.com/matterport/Mask_RCNN/issues/13
