### ISSUE TITLE
Doing data augmentation before image/mask resizing

### ISSUE THREAD

**Issue by keven4ever** [matterport/Mask_RCNN#280]
Hi,

I wonder why the data augmentation is applied after image resizing in `load_image_gt` instead of before resizing. I am thinking to do more augmentation like rotation, cropping, etc. Doing these augmentation after resizing will have different pb, like zero area mask, or change the size of image. What do you think?

**Comment by John1231983** [comment]
@keven4ever : Have you see some effect of data augmentation? This is current PR
https://github.com/matterport/Mask_RCNN/pull/301
