### ISSUE TITLE
modellib.load_image_gt image mask shape mismatch

### ISSUE THREAD

**Issue by Ayshine** [matterport/Mask_RCNN#2817]
I am trying to run the cells in `inspect_baloon_data.ipynb`  for the Mini Masks cells for the following code I noticed that my masks and images does not match after using `load_image_gt` function. I guess this may be the reason I get  `ValueError: operands could not be broadcast together with shapes (56,56) (1024,1024) (1024,1024) ` error when I ran `visualize.display_instances(image, bbox, mask, class_ids, dataset.class_names)` line. My question is how should I resolve this? 

<img width="796" alt="Screen Shot 2022-04-27 at 17 00 27" src="https://user-images.githubusercontent.com/28358926/165538020-c1bcf2f8-1588-4371-be7c-fa4ef6fd3ff3.png">
`

**Comment by Malte-Weber** [comment]
same issue, not sure if it pertains to this https://github.com/matterport/Mask_RCNN/issues/636 ?

**Comment by Ayshine** [comment]
I tried the add the lines as suggested on the issue you passed. It didn't work. I am trying baloon tutorial from the reference [article](https://engineering.matterport.com/splash-of-color-instance-segmentation-with-mask-r-cnn-and-tensorflow-7c761e238b46) on README on the repo. Should it just work fine?

**Comment by Malte-Weber** [comment]
Same here, I am working on getting this all fixed in the hopes to understand how to adapt the Mask RCNN.
The broadcasting issue seems to be within the matrix multiplication. 
https://www.statology.org/operands-could-not-be-broadcast-together-with-shapes/
I will implement it and let you know if that resolves the issue. Besides, see #578 even, so it did not help me.

Have you come across the #2112? That is another one that stomps me right now.

**Comment by Ayshine** [comment]
I haven't seen that error. I hope you resolve them both. I would like to learn if you have any suggestions for this issue

**Comment by Ayshine** [comment]
seems like dot works for me.  I just changed the apply_mask function from `visualize.py` like below
`def apply_mask(image, mask, color, alpha=0.5):
    """Apply the given mask to the image.
    """
    for c in range(3):
        #image[:, :, c] = np.where(mask == 1,
         #                         image[:, :, c] *
         #                         (1 - alpha) + alpha * color[c] * 255,
         #                         image[:, :, c])
        image[:, :, c] = np.where(mask == 1,
                                  image[:, :, c].dot(
                                  (1 - alpha) + alpha * color[c] * 255),
                                  image[:, :, c])
    return image
`

Thanks for the link

**Comment by Ayshine** [comment]
Ok now I have the second issue you are facing too.

**Comment by Malte-Weber** [comment]
I found https://github.com/ahmedfgad/Mask-RCNN-TF2 which is seemingly more up to date. Working on something else, atm. Please reach out to me if you gain some insight into the matter.

**Comment by Ayshine** [comment]
Thanks for passing the link. Let me try that version and inform you if it works.

**Comment by MGudik** [comment]
I think its a leftover from a change. Before you could specify use_minimask=False.

Mini masks are used during training to minimize the load. A workaround is to specify the config

```
config.USE_MINI_MASK = False
original_image, image_meta, gt_class_id, gt_bbox, gt_mask = load_image_gt(
            self.dataset_val, config, image_id)
```

**Comment by Ayshine** [comment]
@Weber-AILand  I tried the repo you suggested. I was able to run training and predictions of the kangaroo example they gave. I'll keep working on that. Thanks!
