### ISSUE TITLE
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by Ayshine** [matterport/Mask_RCNN#2825]
While training on my own dataset I get the following error. Can't find which point it is thrown. Could you help me?

Full output 
`Using TensorFlow backend.
Traceback (most recent call last):
  File "cleavage.py", line 187, in <module>
    if not os.path.exists(weights_path):
NameError: name 'weights_path' is not defined
>> python cleavage.py
Using TensorFlow backend.
Training network heads

Starting at epoch 0. LR=0.001

Checkpoint Path: //logdir//train/mask_rcnn_cleavage_{epoch:04d}.h5
Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)
/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/keras/engine/training_generator.py:48: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.
  warnings.warn(
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... cannot pickle '_thread.RLock' object
Epoch 1/30
Killed`

I can also share my code if it helps.

**Comment by Ayshine** [comment]
looks like this is just a warning. My model was not training for some other reasons. But solved.

**Comment by yesidospitiamedina** [comment]
Hi, I have the same warning but then I also got this error "Ignoring... cannot pickle '_thread.RLock' object".

Following by:
Exception in thread Exception in thread Thread-42Thread-41:
Traceback (most recent call last):
  File "/Users/guest1/opt/anaconda3/envs/MaskRCNN/lib/python3.8/threading.py", line 932, in _bootstrap_inner

Any idea to solve this?
Thank you a lot.

**Comment by Ayshine** [comment]
Hey there, they don't mean anything. Even after I was able to train mrcnn with my own data I can see them. Just ignore them. I don't know about your second error.
