### ISSUE TITLE
Possible bug in untold_detections

### ISSUE THREAD

**Issue by albertorepo** [matterport/Mask_RCNN#283]
Hello folks,

I was getting an strange error when predicting the mask of some images. Tracing the error back I think I might have found a bug.

In the function ** unmold_detections** defined like:

`    def unmold_detections(self, detections, mrcnn_mask, image_shape, window):
        """Reformats the detections of one image from the format of the neural
        network output to a format suitable for use in the rest of the
        application.

        detections: [N, (y1, x1, y2, x2, class_id, score)]
        mrcnn_mask: [N, height, width, num_classes]
        image_shape: [height, width, depth] Original size of the image before resizing
        window: [y1, x1, y2, x2] Box in the image where the real image is
                excluding the padding.

        Returns:
        boxes: [N, (y1, x1, y2, x2)] Bounding boxes in pixels
        class_ids: [N] Integer class IDs for each bounding box
        scores: [N] Float probability scores of the class_id
        masks: [height, width, num_instances] Instance masks
        """
        # How many detections do we have?
        # Detections array is padded with zeros. Find the first class_id == 0.
        zero_ix = np.where(detections[:, 4] == 0)[0]
        N = zero_ix[0] if zero_ix.shape[0] > 0 else detections.shape[0]`

This last line is intended to be like that? If the first detection is 0, then zero_ix[0] will be 0 as well (first index). It should be like:

`N = zero_ix.shape[0] if zero_ix.shape[0] > 0 else detections.shape[0]`

Am I right?

**Comment by FruVirus** [comment]
I think the line is correct.

If the class ID of the first detection in detections is 0, that means you have no positive samples and in this case, you want N = 0. zero_ix.shape[0] will give 1 instead of 0 and you would incorrectly index into this box, class ID, score, and mask in the rest of the function.
