### ISSUE TITLE
When I feed the run_graph with 2 images, the output batch_size is still 1.

### ISSUE THREAD

**Issue by Superlee506** [matterport/Mask_RCNN#285]
![image](https://user-images.githubusercontent.com/13114675/36757939-ce6e29ea-1be0-11e8-8a83-49d73151dbba.png)
As show in the figure, when I  feed 2 same images into the model, the output batch_size of proposal is still 1. What's wrong with it？

**Comment by FruVirus** [comment]
hmmmm, at the moment i'm not sure what is going on since I haven't gotten to this portion yet. I'll keep it mind as I go through the code and see if I can make sense of it

**Comment by Superlee506** [comment]
I know the reason,  in this demo, they set "IMAGES_PER_GPU=1". When you feed with more than 1 image, you should change the setting. But I think they should add a"assert" here.
