### ISSUE TITLE
When running train_shapes.ipynb AttributeError occured as well

### ISSUE THREAD

**Issue by JerryMiao** [matterport/Mask_RCNN#29]
![image](https://user-images.githubusercontent.com/17524893/32450706-82184710-c2da-11e7-99ae-ad8e1f1794b1.png)

**Comment by waleedka** [comment]
I can't replicate the issue so it's hard to guess. Can you add a few print() statements to show the values of `shape` and `dims`?

**Comment by JerryMiao** [comment]
I add two print() in this function 
![image](https://user-images.githubusercontent.com/17524893/32482225-4d5d8d5a-c35c-11e7-88ee-91b01d153fc3.png)
and this is the output
![image](https://user-images.githubusercontent.com/17524893/32482237-6022eafc-c35c-11e7-89cf-8c5b81a42258.png)

**Comment by yanxp** [comment]
@JerryMiao ,hello,I also meet the problem. Have you solved it?

**Comment by waleedka** [comment]
@yanxp That's great. Although, to be honest, I still don't see why that line would fail on Python 2.7.
