### ISSUE TITLE
How could I train a model from scratch?

### ISSUE THREAD

**Issue by John1231983** [matterport/Mask_RCNN#293]
Because my dataset is very different with imagenet and coco. I also want to design a new backbone model that did not provide pre-trained weight. So, I want to train the project from scratch? Is it correct if I just delete the line [L469](https://github.com/matterport/Mask_RCNN/blob/master/coco.py#L469) in the coco.py? Anything else?
```
model.load_weights(model_path, by_name=True)
```

**Comment by fastlater** [comment]
input data are images?

**Comment by John1231983** [comment]
Yes. Why not images?

**Comment by fastlater** [comment]
Well, just asking because you said dataset was different. I guess you was talking about your classes are too different than the classes used to train the coco/imagenet weights.

**Comment by John1231983** [comment]
Actually, I want to reproduce the performance with resnet-50 without using pre-trained model for my dataset (medical images). Hence, I would like to train it from scratch. What should I delete in the code to make the project training from scratch?

**Comment by FruVirus** [comment]
@John1231983 

To train a model from scratch, just don't call model.load_weights() after create the model object.

**Comment by John1231983** [comment]
Thanks I got it.

**Comment by shaolei-wang** [comment]
thanks so much

**Comment by mudasar477** [comment]
If i am going to start training from **balloon.py** file then from which file i have to comment out the line **model.load_weights(model_path, by_name=True)** either balloon.py or coco.py?

**Comment by martinschnurer** [comment]
What if I want to train new model (new head model), but backbone remain the same. I don't want to train backbone from scratch, only retrain all the head layers.

**Comment by mudasar477** [comment]
> What if I want to train new model (new head model), but backbone remain the same. I don't want to train backbone from scratch, only retrain all the head layers.

check that hopefully it helps you : https://github.com/matterport/Mask_RCNN/issues/372

**Comment by martinschnurer** [comment]
@mudasar477 The referenced thread doesn't explain anyting about creating cutom model (custom layers) and working with them.
