### ISSUE TITLE
Getting Score (mAP, F1-Score) per class

### ISSUE THREAD

**Issue by AISoltani** [matterport/Mask_RCNN#2949]
Hey guys,
i have a big problem with getting scores for each class, i have almost 33 cmplex class that need to identify for diagnois, how can i calculating scores for each one?

**Comment by Adamjamel** [comment]
> Hey guys, i have a big problem with getting scores for each class, i have almost 33 cmplex class that need to identify for diagnois, how can i calculating scores for each one?

hey bro can u tell me how can i implement mask r cnn on tenserflow 2.0 ?

**Comment by gSayak** [comment]
@Adamjamel you can check the video by pysource on MaskRcnn (https://youtu.be/WuvY0wJDl0k). The code is provided in the description of the video

**Comment by AISoltani** [comment]
> > Hey guys, i have a big problem with getting scores for each class, i have almost 33 cmplex class that need to identify for diagnois, how can i calculating scores for each one?
> 
> hey bro can u tell me how can i implement mask r cnn on tenserflow 2.0 ?

i modified packages for TF 2.0, and will be uploading for all here, what is your cuda version?

**Comment by gSayak** [comment]
@AISoltani can you provide me the "mrcnn" folder for the maskRCNN training? I didn't get much help about running it on TF2 and the devs seem to have forgotten about this so I switched to yoloV5 instance segmentation

**Comment by AISoltani** [comment]
I thinks it better to switch to YOLO method, or using segmentation from detectron2, old Mask-RCNN have many limited and didn't update many years.
