### ISSUE TITLE
ValueError while creating model

### ISSUE THREAD

**Issue by JavisPeng** [matterport/Mask_RCNN#295]
When I run this command
`model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)`
get this error message in the file Mask_RCNN-master\model.py", line 294
` normalized_boxes = boxes / np.array([[height, width, height, width]])`
`ValueError: operands could not be broadcast together with shapes (0,) (1,4)`

**Comment by JavisPeng** [comment]
I've just solved this problem because there's no GPU on my computer.

**Comment by KordorMawblei** [comment]
so without gpu it turns out ok?
