### ISSUE TITLE
Weird Prediction Result for custom dataset

### ISSUE THREAD

**Issue by Unmicool** [matterport/Mask_RCNN#3000]
Hello
Anyone can help me with understanding of my problem origin?
I tried the Mask RCNN for model training  on my dataset. It works well, but the prediction result is strange. I do not understand why.
It appears that the bounding boxes are consistently located in the upper corner or just the upper part of the image, rather than accurately localizing objects. What is the reason?
Thank you in advance.
![Figure_1](https://github.com/matterport/Mask_RCNN/assets/139842560/45e7b93d-fc45-48e9-92e3-fcc9f383eceb)
![Figure_2](https://github.com/matterport/Mask_RCNN/assets/139842560/f12ab9b1-a9b4-42ad-b0a1-4fc3cb8ce303)

**Comment by zikav1** [comment]
Hi, i'm having the same problem. Did you solve this in any way and if so, how?

**Comment by Unmicool** [comment]
> Hi, i'm having the same problem. Did you solve this in any way and if so, how?

Hello, I found solution from this reply https://github.com/matterport/Mask_RCNN/issues/2822#issuecomment-1129205788

**Comment by zikav1** [comment]
Thank you much appreciated , were did you put those lines in the code?

**Comment by Unmicool** [comment]
> Thank you much appreciated , were did you put those lines in the code?

Please add these few lines at the top your main script (model.py) and try again.
