### ISSUE TITLE
how to draw bounding box and mask only on few classes

### ISSUE THREAD

**Issue by anju54** [matterport/Mask_RCNN#307]
while testing the images I want to draw mask or bounding box only on the class I want to.
for eg. I want to detect person in an image then bounding box should be drawn on person class only
it should not draw on any other class of coco dataset .

can u tell me how to do that?

**Comment by anjuasadel** [comment]
thank you for ur help.
now I'm able to successfully print the bounding box and mask over my interested class only.
I just read the corresponding id of my class ( i.e person ) and i put  this line  under display_instance method as u told...
 if ( class_id ==1 ):
      then draw box or mask.
Thank You.

**Comment by awaiseye** [comment]
what is the location of visualize.py ?

**Comment by anju54** [comment]
inside Mask_RCNN/mrcnn/visualize.py

**Comment by awaiseye** [comment]
got it . but after doing that i get following error

UnboundLocalError: local variable 'box' referenced before assignment 
and 
index out of range. any solution?

**Comment by anju54** [comment]
how you are doing that ..send me code that u have modified for your requirement

**Comment by anju54** [comment]
and what is ur requirement ..

**Comment by awaiseye** [comment]
I want to detect a **human** and a **motorcycle** ONLY. 
how can I send you the code?
`

**Comment by awaiseye** [comment]
through email or post here?
