### ISSUE TITLE
No instances to display error !run demo.ipynb using own data h5 file of train_shapes_ipynb trained!

### ISSUE THREAD

**Issue by chinamaoge** [matterport/Mask_RCNN#318]
Train_shapes.ipynb train my picture (pixel 192*192 and 100 total) later save the mask_rcnn_shapes_0001.h5 file.
Demo.ipynb load the mask_rcnn_shapes_0001.h5 weight testting picture as same as the trainning picture.
The test result show No instances to display error!
I'm not familiar with it. I wonder if you have any idea about solving this problem??
train picture show below:
![qq 20180309102708](https://user-images.githubusercontent.com/32806476/37253513-a625ec84-256d-11e8-88c0-eab8552408d5.jpg)
I use labelme annotation and label_visulization piture show below:
![label_viz](https://user-images.githubusercontent.com/32806476/37253539-09152a4e-256e-11e8-97f8-d21a74410f6d.png)
Train the data using model train_shapes.ipynb each partially loss and picture show below:
![loss3](https://user-images.githubusercontent.com/32806476/37253593-a47a2034-256e-11e8-90f1-19e5f17510a3.png)
Demo.ipynb test error show below:
![11](https://user-images.githubusercontent.com/32806476/37253600-d80e7b52-256e-11e8-8f87-2f3de094ab13.jpg)

**Comment by chinamaoge** [comment]
@waleedka Thank you very much for your really awesome repo!Can you give me some help? Thanks!

**Comment by chinamaoge** [comment]
> pixel

resolution

**Comment by fastlater** [comment]
@chinamaoge  Did you run the model evaluation? What is the value of the mAP?

**Comment by chinamaoge** [comment]
@fastlater I run the model evaluation and the value of the mAP is 0....

**Comment by fastlater** [comment]
@chinamaoge  mAP=0 means your model detects nothing from testing data. 
When you check the shapes demo, mAP was above 0.9 what means the model was very good.

**Comment by chinamaoge** [comment]
@fastlater  Do you means my model have problem?

**Comment by fastlater** [comment]
> Do you means my model have error?

I will guess yes. The model that you created is not working at all. Probably model didn't learn anything from training.

**Comment by chinamaoge** [comment]
@fastlater  thanks you very much!

**Comment by chinamaoge** [comment]
@fastlater I run the train_shapes.ipynb and train picture data.
I set the Epoch 100 times and each Epoch is 100 times.
Get the mAP is 1.0 and test picture as same as train picture using demo.ipynb.
Why is the result very bad!
what's the problem？
mAP:
![11](https://user-images.githubusercontent.com/32806476/37454710-412e4806-2876-11e8-85e8-fc9f63711abe.jpg)
each loss:
![33](https://user-images.githubusercontent.com/32806476/37458720-dfd55af8-2880-11e8-8544-802b7d628dc9.png)
testing picture result:
![55](https://user-images.githubusercontent.com/32806476/37458748-f2cff58c-2880-11e8-83a7-76d95f135e77.png)
label visualization picture:
![label_viz0](https://user-images.githubusercontent.com/32806476/37458766-02d0503a-2881-11e8-81d0-718b71490a2a.png)
