### ISSUE TITLE
GPU to CPU?

### ISSUE THREAD

**Issue by Gloupys** [matterport/Mask_RCNN#320]
Hello,

I wanted to know what should change in the code so that we would be able to use the CPU instead of the GPU... I know we have to describe the config and put GPU to 0 but I can't figure out where in the code.

Thanks!

**Comment by joeyism** [comment]
I think setting `GPU_COUNT` to 1 uses CPU, according to [this comment](https://github.com/matterport/Mask_RCNN/blob/master/config.py#L29)

**Comment by Gloupys** [comment]
Well I am working on the "train_shapes" notebook with GPU_COUNT set to 1 and it does use the GPU instead of the CPU... And putting it to 0 would then be a problem for the batch size since it's GPU_COUNT * IMAGES_PER_GPU...

**Comment by joeyism** [comment]
Did you install GPU TF? I think you can just install CPU TF

**Comment by Gloupys** [comment]
Yeah, turns out I was indeed working with GPU TF, so I had to precise the device used before it actually trained. For those interested here's the code that works for that matter:

import tensorflow as tf
DEVICE = "/cpu:0"
with tf.device(DEVICE):
    <The training code>

Thank you for your answer!
