### ISSUE TITLE
ImportError: cannot import name 'Config' when using Spyder

### ISSUE THREAD

**Issue by Baozhang-Ren** [matterport/Mask_RCNN#322]
I get the following error when using Spyder to run the code in the demo.
  File "<ipython-input-2-7eff4ab50a8d>", line 10, in <module>
    import coco

  File "/Users/baozhang/Mask_RCNN/coco.py", line 48, in <module>
    from config import Config

ImportError: cannot import name 'Config'

**Comment by fastlater** [comment]
did you edit the` config.py`?
Do you have `class Config(object):` in the config.py?

**Comment by Baozhang-Ren** [comment]
I didn’t edit config.py and I do have class config in the config.py. And the error didn’t occur when using Jupyter.

**Comment by fastlater** [comment]
>  I do have class config
Check if the class name has the capital letter. The class name is Config, not config
> the error didn’t occur when using Jupyter
In that case, don't you think the problem is Spider and not the code?

**Comment by Baozhang-Ren** [comment]
I do think it’s spyder’s problem. I have already check the name and it’s Config. The import code is the same as the one in Jupyter.

**Comment by JigyasaK** [comment]
Hi, I am facing the same error. Can you tell me how did you solve it?
