### ISSUE TITLE
load_image_gt - zeros boxes filtering

### ISSUE THREAD

**Issue by ericj974** [matterport/Mask_RCNN#324]
I see under `load_image_gt`:
`_idx = np.sum(mask, axis=(0, 1)) > 0`
` mask = mask[:, :, _idx]`

Shouldn't we add as well the following ?
`class_ids = class_ids[_idx]`

**Comment by lianyi** [comment]
Yes, it should.  @John1231983 reported the same fix.  Sorry I missed that as I regenerate the class_ids somewhere else.

**Comment by waleedka** [comment]
Thanks! The fix is merged.
