### ISSUE TITLE
self.keras_model.fit_generator() shows EOFError when using other dataset

### ISSUE THREAD

**Issue by GriffithKQ** [matterport/Mask_RCNN#334]
I can finish the shapes dataset in this project successfully,  but when i change the data to myself, something crashed.
it seems that the problems locates at line2234 , self.keras_model.fit_generator(), in the model.py.
Besides that , i have overwritten the load_image and load_mask function in the new ipynb.I print them and compare to the shapes dataset, i am sure that the format and content of my data is correct as the shapedataset.

I have tried change the parameters in this function.  Such as changing workers=1 and use_multiprocessing = False, but it still showed this problem.

Ps: My operation systerm is linux

so what's wrong ?

EOFError                                  Traceback (most recent call last)
<ipython-input-10-91b48e1d9afa> in <module>()
      6             learning_rate=config.LEARNING_RATE,
      7             epochs=1,
----> 8             layers='heads')
      9 
     10 

~/Kaggle/master/kerastf_maskrcnn/model.py in train(self, train_dataset, val_dataset, learning_rate, epochs, layers)
   2242             max_queue_size=1000,
   2243             workers=workers,
-> 2244             use_multiprocessing=True,
   2245         )
   2246         self.epoch = max(self.epoch, epochs)

~/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2174                                                  use_multiprocessing=use_multiprocessing,
   2175                                                  wait_time=wait_time)
-> 2176                 enqueuer.start(workers=workers, max_queue_size=max_queue_size)
   2177                 output_generator = enqueuer.get()
   2178             else:

~/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/utils/data_utils.py in start(self, workers, max_queue_size)
    701             self.max_queue_size = max_queue_size
    702             if self._use_multiprocessing:
--> 703                 self._manager = multiprocessing.Manager()
    704                 self.queue = self._manager.Queue(maxsize=max_queue_size)
    705                 self._stop_event = multiprocessing.Event()

~/anaconda3/envs/tensorflow/lib/python3.5/multiprocessing/context.py in Manager(self)
     53         from .managers import SyncManager
     54         m = SyncManager(ctx=self.get_context())
---> 55         m.start()
     56         return m
     57 

~/anaconda3/envs/tensorflow/lib/python3.5/multiprocessing/managers.py in start(self, initializer, initargs)
    481         # get address of server
    482         writer.close()
--> 483         self._address = reader.recv()
    484         reader.close()
    485 

~/anaconda3/envs/tensorflow/lib/python3.5/multiprocessing/connection.py in recv(self)
    248         self._check_closed()
    249         self._check_readable()
--> 250         buf = self._recv_bytes()
    251         return ForkingPickler.loads(buf.getbuffer())
    252 

~/anaconda3/envs/tensorflow/lib/python3.5/multiprocessing/connection.py in _recv_bytes(self, maxsize)
    405 
    406     def _recv_bytes(self, maxsize=None):
--> 407         buf = self._recv(4)
    408         size, = struct.unpack("!i", buf.getvalue())
    409         if maxsize is not None and size > maxsize:

~/anaconda3/envs/tensorflow/lib/python3.5/multiprocessing/connection.py in _recv(self, size, read)
    381             if n == 0:
    382                 if remaining == size:
--> 383                     raise EOFError
    384                 else:
    385                     raise OSError("got end of file during message")

EOFError:

**Comment by khuangaf** [comment]
@GriffithKQ Can you share how did you solve this issue? I appreciate your help.

**Comment by raymond30031** [comment]
Not a solution, but at least i can start training.
I bypassed it by setting workers to 1 and setting user multiprocessing to False in model.py.
would also like to know if there is a real solution.

**Comment by harishkool** [comment]
I also did the same thing you have done, turning off the multiprocessor. Thanks for the reply

**Comment by aparajita31pandey** [comment]
Try rebooting the system and then ugrade all the packages. Upgrading all the packages  could help and  also check if your tensorflow version is comaptible with cuda. I was struggling through the same  and trying these helped me
