### ISSUE TITLE
Only detection

### ISSUE THREAD

**Issue by ShiningCoding** [matterport/Mask_RCNN#358]
@waleedka  Thank you for your code!
If I'm only interested in detection at present, what should I do to make the model only train for detection, but not segmentation?

Thank you !

**Comment by ShiningCoding** [comment]
Some answers at #256 , closed.

**Comment by Mikcal** [comment]
what should I do to make the model only train for detection,

**Comment by Mikcal** [comment]
I have encountered the same problem, can you tell me how to solve it？ can you share your code? Thank you！
