### ISSUE TITLE
Unable to train on multiple GPUs

### ISSUE THREAD

**Issue by Jannick-v** [matterport/Mask_RCNN#36]
I am trying to run coco.py on a machine with 8 Tesla P100 GPUs... However, it seems like there is something going wrong when I try to use more than one GPU. 
I was able to run the `parallel_model.py` file on all GPUs without a problem.
The error that is dumped in my terminal is the following one:

```
Epoch 1/40
2017-11-09 14:49:19.639818: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [15,4] vs. [30,4]
	 [[Node: rpn_bbox_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rpn_bbox_loss/concat, rpn_bbox_loss/GatherNd)]]
2017-11-09 14:49:19.639903: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [15,4] vs. [30,4]
	 [[Node: rpn_bbox_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rpn_bbox_loss/concat, rpn_bbox_loss/GatherNd)]]
2017-11-09 14:49:19.640016: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [15,4] vs. [30,4]
	 [[Node: rpn_bbox_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rpn_bbox_loss/concat, rpn_bbox_loss/GatherNd)]]
2017-11-09 14:49:19.640329: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [15,4] vs. [30,4]
	 [[Node: rpn_bbox_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rpn_bbox_loss/concat, rpn_bbox_loss/GatherNd)]]
2017-11-09 14:49:19.640406: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [15,4] vs. [30,4]
	 [[Node: rpn_bbox_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rpn_bbox_loss/concat, rpn_bbox_loss/GatherNd)]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [15,4] vs. [30,4]
	 [[Node: rpn_bbox_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rpn_bbox_loss/concat, rpn_bbox_loss/GatherNd)]]
	 [[Node: proposal_targets/roi_assertion_1/AssertGuard/Assert/Switch/_1627 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5177_proposal_targets/roi_assertion_1/AssertGuard/Assert/Switch", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "coco.py", line 417, in <module>
    layers='heads')
  File "/projects/mask_rcnn/model.py", line 2110, in train
    **fit_kwargs
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2077, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1797, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2332, in __call__
    **self.session_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [15,4] vs. [30,4]
	 [[Node: rpn_bbox_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rpn_bbox_loss/concat, rpn_bbox_loss/GatherNd)]]
	 [[Node: proposal_targets/roi_assertion_1/AssertGuard/Assert/Switch/_1627 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5177_proposal_targets/roi_assertion_1/AssertGuard/Assert/Switch", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'rpn_bbox_loss/sub', defined at:
  File "coco.py", line 365, in <module>
    model_dir=MODEL_DIR)
  File "/projects/mask_rcnn/model.py", line 1646, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/projects/mask_rcnn/model.py", line 1794, in build
    [input_rpn_bbox, input_rpn_match, rpn_bbox])
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/core.py", line 651, in call
    return self.function(inputs, **arguments)
  File "/projects/mask_rcnn/model.py", line 1793, in <lambda>
    rpn_bbox_loss = KL.Lambda(lambda x: rpn_bbox_loss_graph(config, *x), name="rpn_bbox_loss")(
  File "/projects/mask_rcnn/model.py", line 987, in rpn_bbox_loss_graph
    diff = K.abs(target_bbox - rpn_bbox)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4636, in _sub
    "Sub", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [15,4] vs. [30,4]
	 [[Node: rpn_bbox_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rpn_bbox_loss/concat, rpn_bbox_loss/GatherNd)]]
	 [[Node: proposal_targets/roi_assertion_1/AssertGuard/Assert/Switch/_1627 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5177_proposal_targets/roi_assertion_1/AssertGuard/Assert/Switch", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```
Is there anyone that has faced a similar error here?
My system is running python 3.5 and the latest keras (2.0.9) and tensorflow (1.4.0) versions.
Thanks!

**Comment by waleedka** [comment]
Can you post the changes you made to the configurations?

**Comment by Jannick-v** [comment]
Nothing except for the `GPU_COUNT` (and as a consequence, the `BATCH_SIZE`) actually.
I actually implemented by extending your command line parser in the  `main` of `coco.py` as shown below. Additionally I also allow to train the model from scratch if no weight file is given.
```
# original parser options
parser.add_argument('--ngpu', default = 1, type = int,  help= 'number of GPUs to use')
args = parser.parse_args()

if args.command == "train":
        config = CocoConfig()
        IMAGES_PER_GPU = 1
        config.GPU_COUNT = args.ngpu
        config.BATCH_SIZE = config.GPU_COUNT * config.IMAGES_PER_GPU
```

**Comment by waleedka** [comment]
Did you mean to write `config.IMAGES_PER_GPU = 1` rather than `IMAGES_PER_GPU = 1`?

**Comment by Jannick-v** [comment]
You caught me on a typo there!
In my code it is indeed ´config.IMAGES_PER_GPU = 1´.
On how many GPUs have you tried to train @waleedka? And have you seen such an error before?

**Comment by zamponotiropita** [comment]
I get the same error if I set BATCH_SIZE > 1

**Comment by waleedka** [comment]
@Jannick-v I pointed that because the error seems to be due to mismatched dimensions and errors in the configuration class are a common source of that. I can't really guess from the stack trace alone. I usually train on 8GPUs or 1 GPU. I haven't seen this particular error before. 

One possibility is a mismatch in the software versions. Check the README file and verify that you're using the correct versions of Python, TF, and Keras.

**Comment by Jannick-v** [comment]
I double checked everything:
      installed vs required
Python 3.5.2 > 3.4 ==> OK
keras 2.0.8 == 2.0.8 ==> OK
tensorflow 1.3.0 == 1.3.0 ==OK
@waleedka If you train on 8 GPUs, do you only change the variable `GPU_COUNT` in `cocoConfig()` class or are there other config parameters that should be changed as well (which I missed)?
If there are more parameters that have to be changed, can you please give a list of them here?

**Comment by Jannick-v** [comment]
@zamponotiropita Are you training on multiple GPU's or single GPU with bigger batch size? And what are the python/keras/tf versions you are using?

**Comment by zamponotiropita** [comment]
@Jannick-v tf 1.4.0, keras 2.0.9, python 3.5.2
The problem was arising on 1 GPU. I don't have the problem anymore and unfortunately I can't reproduce it anymore since it was on a earlier commit and my config has changed.

**Comment by harishannavajjala** [comment]
@Jannick-v  Hi , I am also getting the same error as you when I try to run coco.py on just one GPU and batchsize = 2. But I don't get this error if I try to run on the same one GPU with batchsize = 1. Should the batch size be always equal to the number of GPUs as we are using stochastic gradient descent and the   here? Pls correct my understanding if I am wrong.

**Comment by waleedka** [comment]
> @waleedka If you train on 8 GPUs, do you only change the variable GPU_COUNT in cocoConfig() 

Yes, I only change GPU_COUNT. 

> If there are more parameters that have to be changed, can you please give a list of them here?

No other parameters that I can think of that might cause this issue.

The error message points to a dimension mismatch in the RPN bounding box loss function. This seems like a configuration error somewhere. Try updating the CocoConfig class rather than updating the property value after the class is created like in the code above, just in case there is a config value not being updated correctly.

**Comment by Jannick-v** [comment]
@waleedka Good news, I did a fresh clone of the code repo (didn't update my local repo the last two weeks) to have a clean start again. I'm currently training on 8 GPU's using 4 images per GPU. So far so good! 
At the moment it takes +- 50 mins to train one epoch. I believe this number can be decreased by using more workers to generate the data (my GPU usage is not near 100% at all) and/or by increasing the queue.

@harishannavajjala The effective batch size should be at least the number of GPU's you are using. That's why you can find `self.BATCH_SIZE = self.IMAGES_PER_GPU * self.GPU_COUNT`  in `config.py`. Me personally had no problems running the code on one GPU using different values for images_per_gpu so I don't know what exactly is going wrong at your end. Maybe you  could ask @zamponotiropita for help?

**Comment by a6225301** [comment]
@Jannick-v  Hi， have you find any solution to this? I have the same error.
