### ISSUE TITLE
How to use the network for inference?

### ISSUE THREAD

**Issue by Paulito-7** [matterport/Mask_RCNN#369]
Hello all,

I would like to use the Mask R-CNN on brand new pictures for inference. Yet I can't figure out how to use an image that has not been used in a validation or train dataset object.

Can someone help me with this?

Thank you!

**Comment by fastlater** [comment]
@Paulito-7  try the train_shapes demo [link](https://github.com/matterport/Mask_RCNN/blob/master/train_shapes.ipynb), Detection. After you load the model and mold the input, use model.detect.

**Comment by Paulito-7** [comment]
@fastlater  Many thanks for your answer!
I managed to do inference using utils.py functions and works perfectly now!

**Comment by eljirg** [comment]
Hi, I am following the balloon tutorial and has been able to trained the model with my own dataset (1 class only, same with the balloon).
I trying to inference many test images outside train and val set, however i got lost here as it accept only train and val. Can you give some pointers for the balloon case?
