### ISSUE TITLE
KL.UpSampling2D()

### ISSUE THREAD

**Issue by liruilong940607** [matterport/Mask_RCNN#37]
You used KL.UpSampling2D() to build the FPN network. Did you mean un-pooling or deconv?

Because when I looked into keras' document, it says this function is to repeats the rows and columns. (more like un-pooling). See from this: https://keras.io/layers/convolutional/#upsampling2d

But it seems like this process should be more like deconv. Am I wrong about understanding FPN ?

**Comment by waleedka** [comment]
My understanding of FPN is that they use standard up sampling to increase the resolution of the feature maps before concatenating with the lower layer. If you think that's wrong, please point me to where the issue might be.
