### ISSUE TITLE
How to use standard data augmentation?

### ISSUE THREAD

**Issue by Paulito-7** [matterport/Mask_RCNN#373]
Hello everyone,

I saw that in 'load_image_gt' it is possible to add an option for data augmentation and that this one is used in 'data_generator` used in 'inspect_data.ipynb'. Yet in the notebook I can't see where you can use it for data augmentation for training.
It seems that it is automatically called for training, is that right?

Thanks!

**Comment by waleedka** [comment]
It used to be automatically called for training. And it did right/left flipping 50% of the time. 

But as of earlier today, I pushed an update that makes two changes:
1. Augmentation is not done automatically anymore. Instead you need to pass the `augmentation` parameter to `train()`.
2. The model now uses the `imgaug` library for augmentation, and that allows a very wide range of possible augmentations. 

The commit is here: https://github.com/matterport/Mask_RCNN/commit/c7e3aa7a32a2ff4e265ef9746ca87dd91ed6bfa2

**Comment by Paulito-7** [comment]
Thank you for your answer! 
I didn't see the commit, it looks great!
