### ISSUE TITLE
Specific question about training and detection of many of the same class in one image

### ISSUE THREAD

**Issue by Aptamer1** [matterport/Mask_RCNN#378]
Hi,

Currently I'm training this algorithm on one class.
My images have between 50 and 300 objects on the same image and the goal is to detect them all.

Now I did a limited pilot test and detection/mask generation does work, however during this test I only annoted about 10 objects per image.
During detection it detects between 7 to 14 objects per image.

Now I was wondering if there is any relationship between this training and the detection or should I just get a larger training set.
Should I annotate my images completely for training for example all 300 objects? Or can I annotate a subset for training and will it then be able to detect everything or will the algorithm presume everything else I did not annotate is background?

Thanks in advance,
Kind regards,
Sören

**Comment by waleedka** [comment]
> or will the algorithm presume everything else I did not annotate is background?

Yes, that's the issue. Areas of the image that you don't annotate are also used for training. They train the network on what not to detect.
