### ISSUE TITLE
Labelling two-halves of occluded individuals 

### ISSUE THREAD

**Issue by franksRsrch** [matterport/Mask_RCNN#383]
Some individuals in my training data are occluded so that they are divided into two parts. How do I go about labelling this kind of data? If I label each half separately, then I'm telling Mask-RCNN that they are different individuals. Do I just label the entire individual, including the parts that are occluded? The problem there is that when an individual is partly occluded, it's standard to draw around only the visible parts. I'm using VGG image annotator.

**Comment by waleedka** [comment]
Good question. The COCO dataset labels both parts of the person as one object (example: http://cocodataset.org/#explore?id=293564). That's the right way to do it. 

I don't know if VGG Image Annotator supports that option. If not, here are a few ideas to consider:

1. Use a different image annotation tool.
2. Mark the two parts as two objects and give them a certain unique attribute in VGG Image Annotator, and then in your Dataset class merge objects that have the same unique attribute.
3. Use one polygon to cover both parts but make the connection between the two as thin as possible. If the connection is thin and in different location every time, then hopefully the network will not learn it.

**Comment by franksRsrch** [comment]
Great - thanks for your help!

**Comment by bing1zhi2** [comment]
thanks ,I had the same question. Now I konw how to do .

**Comment by tharindu-mathew** [comment]
@doingRsrch did this work well for you? Did you get good results?
