### ISSUE TITLE
specify gpu in inspect_model.ipynb

### ISSUE THREAD

**Issue by liushrui** [matterport/Mask_RCNN#384]
Briefly, even I set the following settings in inspect_model.ipynb, the gpu cannot be specified
```
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ['CUDA_VISIBLE_DIVICES'] = "1"
```
but anything work well in train_shapes.ipynb, I wonder what is the difference and how can I fix it.
Maybe a leak happens somewhere I do not find...  
Thanks!

**Comment by liushrui** [comment]
If someone runs into the same problem, try to comment following code maybe help~
`with tf.device(DEVICE):`

**Comment by waleedka** [comment]
I think the solution in https://github.com/matterport/Mask_RCNN/issues/426 might help.
