### ISSUE TITLE
how to train with coco2017

### ISSUE THREAD

**Issue by Programmerwyl** [matterport/Mask_RCNN#398]
No instances_valminusminival2017.json file found

**Comment by JonathanCMitchell** [comment]
Yeah there currently isn't one in existence. Simply rename the 2014 one to the 2017 name, or just train on the 2014 dataset.

**Comment by Programmerwyl** [comment]
Thanks for your advices !

**Comment by isalirezag** [comment]
@JonathanCMitchell  but how did you get the `instance_minival2014.json` at the first place? can you explain how make that...

**Comment by AlanNaoto** [comment]
> @JonathanCMitchell but how did you get the `instance_minival2014.json` at the first place? can you explain how make that...
On this link by rbgirshick https://github.com/rbgirshick/py-faster-rcnn/blob/master/data/README.md are some dropbox links for the files "instances_minival2014.json" and "instances_valminusminival2014.json".
