### ISSUE TITLE
utils.resize_image scipy.misc.imresize() inconsistency

### ISSUE THREAD

**Issue by ciararogerson** [matterport/Mask_RCNN#399]
utils uses scipy.misc.imresize() to resize any images with scale != 1. scipy.misc.imresize outputs type uint8 in the range 0 - 255 as default. This means that you can be sending in images that are float 0-1 range, say, but the result of the resizing will transform them to 0 -255 scale.

The problem manifests most severely when you have some images that are being resized (scale != 1) and some that are not (scale == 1). In this instance if the images you feed in are in a range that is not 0 - 255 you are going to get a mismatch in images being fed into the model.

This may be a problem if you are using greyscale images via skimage.color.rgb2gray(), for example. skimage.color.rgb2gray outputs type float in the range 0 - 1 as default.

**Comment by mpsampat** [comment]
@waleedka , fyi i saw someone in the DSB competition also reported this issue.

**Comment by waleedka** [comment]
Thanks! I just pushed an update to replace scipy resize with `skimage.transform.resize` and using the preserve range option. I think that should fix it.
