### ISSUE TITLE
How to evaluate this model?

### ISSUE THREAD

**Issue by timecommunication** [matterport/Mask_RCNN#403]
If I trained my own dataset by this Mask R-CNN model, how I could evaluate this model?
In this case, what is accuracy? 
It seems that this model involves the Detection and Segmentation, I have no idea about the evaluation of this model.....
I'm new here, need help.

**Comment by fastlater** [comment]
The authors of this repo used mAP to evaluate the model. Please check the samples. In [shapes_demo](https://github.com/matterport/Mask_RCNN/blob/master/samples/shapes/train_shapes.ipynb) , you can find the evaluation at the botton of the script.
