### ISSUE TITLE
How much gpu memory required for inference?

### ISSUE THREAD

**Issue by yulong314** [matterport/Mask_RCNN#41]
I have a gtx 780 card which have 3Gb of memory, but when runing the demo example,  an error ocurred :"W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.07GiB."

so how much gpu memory required to run an inference example ?

**Comment by waleedka** [comment]
This model is fairly big. Training requires a 12GB card for 1024x1024 images. Inference should work with less, but I haven't tested. Alternatively, if this is just to experiment with the model then you can run the inferencing on CPU. It'll be slow, but it will work.
