### ISSUE TITLE
ValueError: Error when checking input: expected input_image_meta to have shape (13,) but got array with shape (14,)

### ISSUE THREAD

**Issue by caozi** [matterport/Mask_RCNN#410]
the same dataset I create of my own, doing well.
But after update to 2.1, in training,  I got this error message:
ValueError                                Traceback (most recent call last)
<ipython-input-5-4640b621f228> in <module>()
      2             learning_rate=config.LEARNING_RATE,
      3             epochs=2,
----> 4             layers='all')

/mnt/disks/sdb/Mask_RCNN/mrcnn/model.py in train(self, train_dataset, val_dataset, learning_rate, epochs, layers, augmentation)
   2312             max_queue_size=100,
   2313             workers=workers,
-> 2314             use_multiprocessing=True,
   2315         )
   2316         self.epoch = max(self.epoch, epochs)

~/tensorflow_GPU/lib/python3.5/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/tensorflow_GPU/lib/python3.5/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2222                     outs = self.train_on_batch(x, y,
   2223                                                sample_weight=sample_weight,
-> 2224                                                class_weight=class_weight)
   2225 
   2226                     if not isinstance(outs, list):

~/tensorflow_GPU/lib/python3.5/site-packages/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight)
   1875             x, y,
   1876             sample_weight=sample_weight,
-> 1877             class_weight=class_weight)
   1878         if self.uses_learning_phase and not isinstance(K.learning_phase(), int):
   1879             ins = x + y + sample_weights + [1.]

~/tensorflow_GPU/lib/python3.5/site-packages/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
   1474                                     self._feed_input_shapes,
   1475                                     check_batch_axis=False,
-> 1476                                     exception_prefix='input')
   1477         y = _standardize_input_data(y, self._feed_output_names,
   1478                                     output_shapes,

~/tensorflow_GPU/lib/python3.5/site-packages/keras/engine/training.py in _standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    121                             ': expected ' + names[i] + ' to have shape ' +
    122                             str(shape) + ' but got array with shape ' +
--> 123                             str(data_shape))
    124     return data
    125 

ValueError: Error when checking input: expected input_image_meta to have shape (13,) but got array with shape (14,)
Could anyone help me with this?
Thanks a lot

**Comment by waleedka** [comment]
The error doesn't tell me what might be wrong. But, generally, the length of the meta data vector is determined dynamically, so check the `compose_image_meta()` function in **model.py**. Also, are you on release 2.1 or are you on the latest **master** branch?

**Comment by azakhtyamov** [comment]
Playing with "shapes" example too. Changing NUM_CLASSES from 4 to something else results into "ValueError: Error when checking input: expected input_image_meta to have shape (212,) but got array with shape (16,)"

**Comment by caozi** [comment]
@waleedka I am on the latest mater branch.

**Comment by kvigulis** [comment]
Hi caozi, how did you solve the issue?

**Comment by kvigulis** [comment]
Hi, can anyone who solved this please share how you did it? Thanks.

**Comment by waleedka** [comment]
The error is clearly happening due to a mismatch in the size of the image_meta tensor. The size of this tensor is computed in the `Config` class. That's where I'd start looking and try to trace it to see why the expected image_meta size is different from what the model is getting.

**Comment by mminervini** [comment]
@kvigulis, just in case you were still struggling...

I ran into the same issue and started tracking input_image_meta all over `model.py` until I realized that I was setting NUM_CLASSES in `Config` too late, i.e. after instantiating the class!
The expected length of input_image_meta corresponds to IMAGE_META_SIZE, which is computed in the `__init__` method of `Config` (as hinted by @waleedka). Assuming that you are sub-classing `Config` to override default parameters, you need to set NUM_CLASSES first and then let `Config.__init__()` compute IMAGE_META_SIZE with the correct information at its disposal.
For example, I solved with something as simple as the following...
Define your configuration:
```
class MyConfig(Config):

    # Setting all other parameters...

    def __init__(self, num_classes):
        self.NUM_CLASSES = num_classes
        super().__init__()
```
And then use it:
```
config = MyConfig(num_classes=7)
```

**Comment by waleedka** [comment]
I think @mminervini got to the root of it. Changing NUM_CLASSES after the config object is created would cause this error.

By the way, unless you need to change the number of classes dynamically, which I would expect is a very rare case, you can update the config in a simpler way like this::

```
class MyConfig(Config):
    NUM_CLASSES = 17

config = MyConfig()
```

**Comment by qnkhuat** [comment]
@waleedka I've done like that but I still got this
ValueError: Error when checking input: expected input_image_meta to have shape (16,) but got array with shape (93,)
Can u help me ?

**Comment by tianzhuotao** [comment]
@waleedka  Thanks bro.

**Comment by arturjordao** [comment]
@qnkhuat try this:
After line 2412 in mrccnn/model.py ("image_meta = compose_image_meta...") add "image_meta = image_meta[0:16]". This is not an elegant solution but works fine for me. I think the problem is the number of classes in your config file (in debug mode consider to check the function compose_image_meta).

**Comment by caozi** [comment]
Sorry for the delay, a little busy, I didn’t solve the issue , after pulling the latest repo, the problem disappeared.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: kvigulis <notifications@github.com>
发送时间: Wednesday, April 11, 2018 11:04:08 AM
收件人: matterport/Mask_RCNN
抄送: zi cao; State change
主题: Re: [matterport/Mask_RCNN] ValueError: Error when checking input: expected input_image_meta to have shape (13,) but got array with shape (14,) (#410)


Hi caozi, how did you solve the issue?

―

**Comment by cardboardcode** [comment]
@arturjordao Thanks for the suggestion. It worked in removing the following error:

`ValueError: Error when checking input: expected input_image_meta to have shape (13,) but got array with shape (14,)`

I was modifying `balloon.py` under [samples/balloon](https://github.com/matterport/Mask_RCNN/blob/master/samples/balloon/balloon.py) to detect more than one type of object.
Changed the **NUM_CLASSES variable** under **BalloonConfig** class in `balloon.py`, line 69, to reflect the number of different object instances I am trying to detect. 

eg. Originally, balloon.py detects only two objects: BG (background) + balloon
`NUM_CLASSES = 1 + 1`
      After modification, balloon.py detects three objects: BG + balloon + pen
`NUM_CLASSES = 1 + 2`

**Comment by eVen-gits** [comment]
In case this helps anyone, I had the same issue and this is how I solved it;

I created my CustomConfig from template. Now because I had my "coco style dataset", I didn't need to add classes manually like so:

```python    
    #override
    def load_coco(self, dataset_dir, subset=None, class_ids=None, return_coco=False):
        # Add classes
        #The following two lines were comented out/removed
        #self.add_class("element", 1, "class_a")
        #self.add_class("element", 2, "class_b")```

I know it might be a rookie mistake, but I think it could help someone out.

**Comment by shishirsingh66** [comment]
Waleed, first of all this is just great! Thankyou So Much as I really learned the most by reviewing your code!!

Ran into the same error (setting 1000 Targets), forgot that background is always 0. So changing NUM_CLASSES to 1001 in config, resolved this issue.

**Comment by vaishnavm217** [comment]
Hi,
Even I am getting the same error. I think it is because of my classes is greater than the 80 classes.
```
Error when checking input: expected input_image_meta to have shape (104,) but got array with shape (15,)
```

**Comment by adutchnano** [comment]
I had the same error. The way I fixed it was to change my load_dataset function so that I added one class for every declared class in my config. (I had 32 classes, so I used self.add_class for 1-31 in the load_dataset function)

**Comment by yerzhik** [comment]
In my case I was trying to finetune model with certain class (do not need all 81 classes, was interested only in one). So I resolved the problem by adding 

```
        for i in range(1, len(class_names)):
            self.add_class("mysource", i, class_names[i])
```
where class_names is defined in demo.py (list of all class labels). 
Loop should start from 1 because class id 0 is BG.

Then at load_mask function I make sure that I return mask with appropriate id 
in my case i use

```
np.ones([mask.shape[-1]], dtype=np.int32) * desired_id
```

Using this method I have to load the whole model, without removing last layers.

**Comment by Spiffy1** [comment]
> @kvigulis, just in case you were still struggling...
> 
> I ran into the same issue and started tracking input_image_meta all over `model.py` until I realized that I was setting NUM_CLASSES in `Config` too late, i.e. after instantiating the class!
> I was getting the dimension mismatch error because of doing something like this:
> 
> ```
> config = MyConfig()
> config.NUM_CLASSES = 7
> ```
> 
> So, if this is your case, below is the way around it.
> 
> The expected length of input_image_meta corresponds to IMAGE_META_SIZE, which is computed in the `__init__` method of `Config` based on the value of NUM_CLASSES (as hinted by @waleedka). Assuming that you are sub-classing `Config` to override default parameters, you need to set NUM_CLASSES first and then let `Config.__init__()` compute IMAGE_META_SIZE with the correct information at its disposal.
> For example, I solved with something as simple as the following...
> Define your configuration:
> 
> ```
> class MyConfig(Config):
> 
>     # Setting other parameters...
> 
>     def __init__(self, num_classes):
>         self.NUM_CLASSES = num_classes
>         super().__init__()
> ```
> 
> And then use it:
> 
> ```
> config = MyConfig(num_classes=7)
> ```

This solution works for me. Thank you very much. You will also need to (add num_classes=7) to the inference config below.

**Comment by JavierClearImageAI** [comment]
I know it seems silly, but even knowing it I forgot to add the extra class for the background. Check that you didn't make the same mistake.

*`NUM_CLASSES = your number of classes + 1 `*

...hey, wait. Don't down-vote me yet ... I was just trying to be helpful!         :-p

**Comment by MalusJ** [comment]
I solved this by change the INPUT_META_SIZE in config. So i had error report as 'ValueError: Error when checking input: expected input_image_meta to have shape (13,) but got array with shape (93,) '  so I changed it to 93 and it now works.

**Comment by joangog** [comment]
> Waleed, first of all this is just great! Thankyou So Much as I really learned the most by reviewing your code!!
> 
> Ran into the same error (setting 1000 Targets), forgot that background is always 0. So changing NUM_CLASSES to 1001 in config, resolved this issue.

Thank you! I had also forgotten the background!

**Comment by christianburbon** [comment]
I was able to resolve this issue by using the solution from @waleedka + modifying `self.IMAGE_META_SIZE` from `def__init__(self)`
originally it was `self.IMAGE_META_SIZE = 1 + 3 + 3 + 4 + 1 + self.NUM_CLASSES`
since mine was saying expected shape (14,) but got array with shape (15,). I tried removing `+1` and it worked.

modified to:
`self.IMAGE_META_SIZE = 1 + 3 + 3 + 4 + self.NUM_CLASSES`

hope this helps

**Comment by mlsy123** [comment]
The solutions above are not working for me. Are there any other solutions to solve this problem?

**Comment by spurs30** [comment]
I also had the problem. But i solved it through modify the Config class(Maybe you rewrite the class). Firstly,  you must check you NUM_CLASSES, it should be the number of your classes then plus one(this is refer to the background class). Secondly, check these three properties IMAGE_RESIZE_MODE, IMAGE_MIN_DIM, IMAGE_MAX_DIM. I change the IMAGE_RESIZE_MODE="none" and it found  the error. You should enlarge the last two properties if necessary. If that did't work, I suggest you change the IMAGE_RESIZE_MODE="square", which is the default one.
GOOK LUCK.

**Comment by 7595258** [comment]
老兄我知道了！我调试出来了！我是这样调试的：
找到model.py下的compose_image_meta函数，看它的实现过程。原来我的active_class_ids不对，为什么不对呢？原来我在train_test.py下的load_shapes里面的
  ```
      self.add_class("shapes", 1, "face")
        self.add_class("shapes", 2, "glasses")
        self.add_class("shapes", 3, "mask")
```
写成了
```
        self.add_class("shapes", 1, "face")
        self.add_class("shapes", 2, "glasses")
        self.add_class("shapes", 2, "mask")
```
这导致我active_class_ids比原来小了一。
进而compose_image_meta返回的meta不对，由compose_image_meta生成的image_meta当然就不对了！

Dude, I got it!  Here's how I debug it:
Find the **compose_image_meta** function under **model.py** and see its implementation. Turns out my **active_class_ids** is wrong. Why is it wrong? Originally, I was in **load_shapes** under **train_test.py**

```
self.add_class("shapes", 1, "face")
self.add_class("shapes", 2, "glasses")
self.add_class("shapes", 3, "mask")

```
Be written into

```
self.add_class("shapes", 1, "face")
self.add_class("shapes", 2, "glasses")
self.add_class("shapes", 2, "mask")

```
This causes my **active_class_ids** to be one smaller than before.
The **meta** returned by **compose_image_meta** is not correct, and of course the **image_meta** generated by **compose_image_meta** is not correct!

**Comment by JB-Rockstar** [comment]
# After this line of code in your prediction file:

for image_id in image_ids:
    image = dataset.load_image(image_id)
    mask, class_ids = dataset.load_mask(image_id)

    # Add this line of code and the error is gone:

    # limit to total number of classes
    display_top_masks(image, mask, class_ids, dataset.class_names, limit=5)

**Comment by ruman23** [comment]
To resolve the shape-related issue in training a Mask R-CNN model, ensure that the training and validation datasets contain images and annotations for the same number of classes. If they differ, add sample images and corresponding JSON files for the missing classes to the validation dataset. This alignment will prevent class mismatch errors during model training.
