### ISSUE TITLE
Changing NUM_CLASSES results in error while training in train_shapes.ipynb

### ISSUE THREAD

**Issue by azakhtyamov** [matterport/Mask_RCNN#414]
For NUM_CLASSES = 7, instead of 4:
ValueError: Error when checking input: expected input_image_meta to have shape (19,) but got array with shape (16,)

**Comment by waleedka** [comment]
Can you post your code? How did you set NUM_CLASSES?

**Comment by azakhtyamov** [comment]
Simply changed config's NUM_CLASSES:

class ShapesConfig(Config):
    GPU_COUNT = 1
    IMAGES_PER_GPU = 8

    # Number of classes (including background)
    NUM_CLASSES = 1 + 6  # background + 6 shapes

    # Use small images for faster training. Set the limits of the small side
    # the large side, and that determines the image shape.
    IMAGE_MIN_DIM = 128
    IMAGE_MAX_DIM = 128

    # Use smaller anchors because our image and objects are small
    RPN_ANCHOR_SCALES = (8, 16, 32, 64, 128)  # anchor side in pixels

    # Reduce training ROIs per image because the images are small and have
    # few objects. Aim to allow ROI sampling to pick 33% positive ROIs.
    TRAIN_ROIS_PER_IMAGE = 32

    # Use a small epoch since the data is simple
    STEPS_PER_EPOCH = 100

    # use small validation steps since the epoch is small
    VALIDATION_STEPS = 5

**Comment by xiaolisarah** [comment]
i think if u change the NUM_CLASSES  here ,u should change the class={'',''...},so the train num_label match the number u set here

**Comment by JonathanCMitchell** [comment]
@xiaolisarah What do you mean by change the `class={","..}` ?

**Comment by xiaolisarah** [comment]
@JonathanCMitchell i say , in class ShapesDataset(utils.Dataset):　should add 7 class

**Comment by azakhtyamov** [comment]
@xiaolisarah , got this, thank you!

**Comment by xiaolisarah** [comment]
@azakhtyamov welcome

**Comment by xiaolisarah** [comment]
@azakhtyamov welcome

**Comment by mehshankhan** [comment]
> Simply changed config's NUM_CLASSES:
> 
> class ShapesConfig(Config):
> GPU_COUNT = 1
> IMAGES_PER_GPU = 8
> 
> ```
> # Number of classes (including background)
> NUM_CLASSES = 1 + 6  # background + 6 shapes
> 
> # Use small images for faster training. Set the limits of the small side
> # the large side, and that determines the image shape.
> IMAGE_MIN_DIM = 128
> IMAGE_MAX_DIM = 128
> 
> # Use smaller anchors because our image and objects are small
> RPN_ANCHOR_SCALES = (8, 16, 32, 64, 128)  # anchor side in pixels
> 
> # Reduce training ROIs per image because the images are small and have
> # few objects. Aim to allow ROI sampling to pick 33% positive ROIs.
> TRAIN_ROIS_PER_IMAGE = 32
> 
> # Use a small epoch since the data is simple
> STEPS_PER_EPOCH = 100
> 
> # use small validation steps since the epoch is small
> VALIDATION_STEPS = 5
> ```

Thanks facing the same issue this solved my problerm

**Comment by ZumelzuR** [comment]
You have to restrict just for your classes. In the coco example [https://github.com/matterport/Mask_RCNN/blob/master/samples/coco/coco.py](url)

you will have to change on load_coco the class_ids attribute. You have to put your classes (if you want to detect a some coco classes, if not you have to check the ballons example
 [https://github.com/matterport/Mask_RCNN/tree/master/samples/balloon](url)). For example for 2 classes could be (1,20) , where 1 and 20 are the ids of the classes of the coco dataset, you have to change that for the load_coco for train and val (also check that you put NUM_CLASSES = 1 + 2 in the case of you have 2 classes.
