### ISSUE TITLE
How to extract the object from image?

### ISSUE THREAD

**Issue by timecommunication** [matterport/Mask_RCNN#419]
I can run the inspect_balloon_model.ipynb.
But how can I get the single balloon picture from the whole picture?

**Comment by fastlater** [comment]
You can crop the object from the whole picture using the bounding box coordinates of the detected object.

**Comment by timecommunication** [comment]
So, the mask is useless for object extraction?
LOL...
How could I extract the object using mask bounding?

**Comment by QJvic** [comment]
Have you solved this problem?If you do,please tell me how to do this.

**Comment by jamesthesken** [comment]
It would be nice to directly receive the values for the coordinates of the mask. Although there are a few examples in the notebooks that review displaying each determined mask. What I think I'll try as a crude method is to use OpenCV on those images to find the coordinates of the contours.

**Comment by jamesthesken** [comment]
The function unmold_mask is also something I've been looking at. If anyone has any suggestions those would be greatly appreciated

**Comment by LetsGo12300** [comment]
Do you know how this can be done? If you do, please tell me. Thank you so much :)

**Comment by timecommunication** [comment]
> Do you know how this can be done? If you do, please tell me. Thank you so much :)

I remember that i could find mask matrix in the main program. in the process of splash, you can set the uninterested position's value as 0, then you can get an image with interested object. This result image's background is white,  you can also set it to all black. You need to crop the object by yourself, maybe OpenCV if you like.
