### ISSUE TITLE
How to assign a specific GPU to train?

### ISSUE THREAD

**Issue by zhoulukuan** [matterport/Mask_RCNN#426]
I need to use other GPU to train instead of the first one. However, I tried different ways as follows to assign other GPU for this program but none of them succeeded. What should I do?

keras version: 2.1.5
tf version:1.4.1 
system version: ubuntu 14.04.1 LTS
1:
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"
```
2:
```
import tensorflow as tf
import keras.backend.tensorflow_backend as KTF
KTF.set_session(tf.Session(config=tf.ConfigProto(device_count={'gpu':2})))
```
3:
```
with tf.device("/gpu:2"):
    print("Training network heads")
    model.train(dataset_train, dataset_val,
                    learning_rate=config.LEARNING_RATE,
                    epochs=40,
                    layers='heads',
                    augmentation=augmentation)
```
Could anyone help me? Thanks in advance.

**Comment by waleedka** [comment]
You're almost there. I think you need to use `with tf.device("/gpu:2")` to wrap the **creation** of the model rather than the **training**.
