### ISSUE TITLE
masks not showing up when using custom coco dataset

### ISSUE THREAD

**Issue by waspinator** [matterport/Mask_RCNN#429]
I'm trying to train using a custom coco-style dataset. Running through the `train_shapes.ipynb` example substituting the dataset to my coco-style dataset, I get bounding box detection working, but masks do not. consequently `mAP` is 0.0. 

Masks seem to show up fine when using the toy shapes dataset.

**Comment by filipduch** [comment]
are you on up to date master?

If your files are old you need to update because there was a bug. Check here #396

**Comment by waspinator** [comment]
that's probably it then. I haven't updated my local version in a week or so. Thanks

**Comment by chengchu88** [comment]
hello all,
I updated the master on Apr 27 and still have the same issue.. any help would be appreciated. thanks!

**Comment by eyildiz-ugoe** [comment]
Is there anyone who figured out how to load a coco-style dataset into Mask R-CNN? I've tried all the samples (nucleus, shape, etc.) but I couldn't get it running. I cannot load my own coco-style dataset and thus it does not work. 

An update on this would be nice. 

@waspinator  Do you have the running code?
