### ISSUE TITLE
Wrong line in demo.ipynb: utils should be mrcnn.utils

### ISSUE THREAD

**Issue by hiankun** [matterport/Mask_RCNN#438]
Hi, I was trying to follow the content in `deom.ipynb`, and found the following line:
`    utils.download_trained_weights(COCO_MODEL_PATH)`
should be
`    mrcnn.utils.download_trained_weights(COCO_MODEL_PATH)`

**Comment by waleedka** [comment]
Thanks for reporting it. We did a big refactoring recently and it looks like we missed a spot. I just pushed a fix to replace `import mrcnn.utils` with `from mrcnn import utils` to be consistent with the other notebooks.
