### ISSUE TITLE
Is this a bug where the gt_mask size is gt_mask[1], gt_mask[1] for both dimensions

### ISSUE THREAD

**Issue by JonathanCMitchell** [matterport/Mask_RCNN#439]
https://github.com/matterport/Mask_RCNN/blob/9e6eea50d9dbdb8b187422bde831723ea897777e/mrcnn/model.py#L1728

I would think it would be `gt_masks.shape[0], gt_masks.shape[1]`

**Comment by waleedka** [comment]
Good catch. I'm pushing a fix shortly. It doesn't cause any issues, though, because this code is used during training, and the model only supports training on square images (resize mode = square) or square crops (resize mode = crop).
