### ISSUE TITLE
Using circles and rects

### ISSUE THREAD

**Issue by Zumbalamambo** [matterport/Mask_RCNN#440]
along with plygons, my json also has circles and rect as follows. How do I parse this as well and use it while training baloon dataset?

```
{
  "various_shapes.jpg21513": {
    "fileref": "",
    "size": 21513,
    "filename": "apple.jpg",
    "base64_img_data": "",
    "file_attributes": {
      "caption": "apple"
    },
    "regions": {
      "0": {
        "shape_attributes": {
          "name": "circle",
          "cx": 476,
          "cy": 529,
          "r": 48
        },
        "region_attributes": {
          "name": "circle"
        }
      },
      "5": {
        "shape_attributes": {
          "name": "rect",
          "x": 439,
          "y": 93,
          "width": 135,
          "height": 92
        },
        "region_attributes": {}
      }
    }
  }
}
```

**Comment by fastlater** [comment]
The easiest way is: convert them into polygon. Rectangles could be easily converted in a 4 points polygon. For circle, maybe you will need to set a list of points to define the circumference.

**Comment by wtahir** [comment]
I have same problem, I converted json annotations in circles to polygons but somehow the file format looks a little bit different as @waleedka and that's where problem starts. I was hoping to find an implementation of Mask_RCNN with circles or finding a way to get polygons in json with similar format as provided in splas colour filter implementation
