### ISSUE TITLE
How to get the pixel coordinates of the predicted bounding boxes in the input image dimension?

### ISSUE THREAD

**Issue by ChunHsinWang** [matterport/Mask_RCNN#442]
The current detection bounding boxes are in the coordinates of resized image, how do you get the coordinates with respect to the original input size?

for example, My original image size is 1920x1080, where my network is trained with 1024x1024, so the image is first resized and padded to 1024x1024. The predicted bounding boxes coordinates is in within the 1024x1024 coordinates, but how do I get the coordinates in 1920x1080 coordinates?

**Comment by ChunHsinWang** [comment]
Thank you

**Comment by akrsrivastava** [comment]
> I give you a hint: Image was resized using linear interpolation.

A bit more detail please? Plus, it seems bilinear interpolation is being used.   Thanks!
