### ISSUE TITLE
ValueError: Layer roi_align_classifier was called with an input that isn't a symbolic tensor.

### ISSUE THREAD

**Issue by jycloud** [matterport/Mask_RCNN#451]
ValueError: Layer roi_align_classifier was called with an input that isn't a symbolic tensor. Received type: <type 'list'>. Full input: [[], <tf.Tensor 'input_image_meta:0' shape=(?, 93) dtype=float32>, <tf.Tensor 'fpn_p2/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'fpn_p3/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'fpn_p4/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'fpn_p5/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>]. All inputs to the layer should be tensors.

I get this error when I run the code:
mrcnn_model = model.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)

In my MacBook without GPU.
tf.__version__=1.3.0
keras.__version__=2.0.8

how can I solve this problem?

**Comment by jycloud** [comment]
@fastlater ok,I have modified the title,I have a question,is this code available in cpu model?

**Comment by qnkhuat** [comment]
@jycloud can u share how did u solve this?

**Comment by aminemosbah** [comment]
the same error down here §§§

**Comment by mabdullahrafique** [comment]
Any update

**Comment by aminemosbah** [comment]
try it on googlecolab, it s running smoothly

**Comment by universewill** [comment]
I also run it on mac, tf.version=1.3.0, keras.version=2.0.8. I set the config GPU_COUNT = 0 and IMAGES_PER_GPU = 0. Also got the problem.

Any help?

**Comment by kongzhiyou** [comment]
I have same problem, and I use mac to run this model, but have appeared this problem , my config  tf.version=1.6.0 and set IMAGES_PER_GPU=0 , anyone have anwser?

**Comment by Sofiane23i** [comment]
GPU_COUNT = 1
IMAGES_PER_GPU = 1

put these values, it works for me even on cpu
