### ISSUE TITLE
Demo.ipynb not working : *** No instances to display *** 

### ISSUE THREAD

**Issue by anujgupta82** [matterport/Mask_RCNN#452]
I cloned the Repo and tried to run demo.ipynb

I am consistently getting *** No instances to display *** 

I have NOT trained my model. I simply ran the notebook, it downloaded "mask_rcnn_coco.h5" from "https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5"

Attaching screen shots of output

![123](https://user-images.githubusercontent.com/11848354/38795264-43e5aed2-4175-11e8-80ff-078d00f0d23e.png)

**Comment by waleedka** [comment]
It looks like you're getting a divide by zero error. Are you on Python 2.7 by any chance?

**Comment by drewleonard** [comment]
@waleedka, does the error come from the following `model.py` code?
```
window = utils.norm_boxes(window, image_shape[:2])
wy1, wx1, wy2, wx2 = window
```
It looks like `window` might be assigned to those 4 variables incorrectly—causing the `divide by zero` error—but I'm unsure.

**Comment by ahmetozlu** [comment]
@waleedka , 

I am getting same error too, do you have any suggestions to solve it? I am using Python Version 2.7. Thanks...

**Comment by waleedka** [comment]
I see. That confirms my guess. I'm afraid the code requires Python 3.5+ and was never tested on earlier versions. If you can, try it on Python 3.5 or later and I think the problem will go away.

I'll close this issue for now as it's out of scope. But I would welcome any pull requests that fix Python 2.7 issues.

**Comment by andeyeluguo** [comment]
I meet the same question,but I am using the python3.5. Now I don't know how to do .

**Comment by andeyeluguo** [comment]
the information is like this:

Processing 1 images
image                    shape: (438, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  150.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32

**Comment by andeyeluguo** [comment]
plus ,I use the docker which the author commented.

**Comment by lqhuy93** [comment]
try this: https://github.com/matterport/Mask_RCNN/pull/515

**Comment by lindsayliu404** [comment]
> plus ,I use the docker which the author commented.

I am using python 3.6 and meet same question, have your problem solved?

**Comment by Pari-singh** [comment]
> try this: #515

What about those facing same error in Python3.5?
