### ISSUE TITLE
understand shift in norm_boxes and denorm_boxes

### ISSUE THREAD

**Issue by raytroop** [matterport/Mask_RCNN#455]
https://github.com/matterport/Mask_RCNN/blob/2a7bcfc82294c7856ad63a07cc27a4dfd90696ab/mrcnn/utils.py#L871
https://github.com/matterport/Mask_RCNN/blob/2a7bcfc82294c7856ad63a07cc27a4dfd90696ab/mrcnn/utils.py#L872
why (y2, x2) shift by 1 pixel ?

**Comment by waleedka** [comment]
There are actually two transformations happening in this function:
1. Converting pixel coordinates to normalized coordinates. This one is clear.
2. Changing how a range is described. In pixel coordinates, we follow the Python practice of having the second value of the range be outside the range. For example, range(0, 10) means 0, 1, 2, ..., 9 but does not include 10. Similarly, `x1=0, x2=10` includes the pixels 0,1, ...9 but not 10. In the normalized coordinates, though, this doesn't work and the second value of a range is included in the range. So, a range of 0-1 includes pixels 0, 0.1, 0.2, ..., and 1.0. 

The comment in the function hints at it, but doesn't delve into the details.

https://github.com/matterport/Mask_RCNN/blob/2a7bcfc82294c7856ad63a07cc27a4dfd90696ab/mrcnn/utils.py#L863-L864
