### ISSUE TITLE
Suggest 

### ISSUE THREAD

**Issue by MaeThird** [matterport/Mask_RCNN#46]
1.`2159         exclude_ix = np.where((boxes[:, 2] - boxes[:, 0]) * (boxes[:, 2] - boxes[:, 0]) <= 0)[0]` --line 2159 in function `unmold_detections(self, detections, mrcnn_mask, image_shape, window)` the bboxes area calculations was misspelt.
2.  Also in this function the **filtering out zero area process**  is better placed after the **translation coordinates backing to image domain process** for the reason that the latter process may still cause zero area.

**Comment by waleedka** [comment]
Good catch. Thank you. I pushed a fix.
