### ISSUE TITLE
ZeroDivisionError when starting to train

### ISSUE THREAD

**Issue by GustavZ** [matterport/Mask_RCNN#460]
I see a ZeroDivisionError when i start training, any idea what could be the reason?

```
Epoch 1/160

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-11-3e6fda036ff5> in <module>()
      5             epochs=160,
      6             layers='heads',
----> 7             augmentation=augmentation)

/home/gustav/workspace/Mobile_Mask_RCNN/mrcnn/model.py in train(self, train_dataset, val_dataset, learning_rate, epochs, layers, augmentation)
   2871             max_queue_size=100,
   2872             workers=workers,
-> 2873             use_multiprocessing=True,
   2874         )
   2875         self.epoch = max(self.epoch, epochs)

/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2113                 batch_index = 0
   2114                 while steps_done < steps_per_epoch:
-> 2115                     generator_output = next(output_generator)
   2116 
   2117                     if not hasattr(generator_output, '__len__'):

/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.pyc in get(self)
    733             success, value = self.queue.get()
    734             if not success:
--> 735                 six.reraise(value.__class__, value, value.__traceback__)

/home/gustav/.local/lib/python2.7/site-packages/six.pyc in reraise(tp, value, tb)

ZeroDivisionError: float division by zero

```

**Comment by YubinXie** [comment]
I also met this error after update to the recent release. After some testing, when I set my training GPU to 1 (was 2), image/node=1, the error disappeared. But I have 16n images, why there would be such error?

**Comment by GustavZ** [comment]
What exactly do you mean by “but I have 16n images”?

After you did the changes the error disappeared?

**Comment by YubinXie** [comment]
I though it was because of my image number can not be divided by GPU nodes number, but my images number is 16 * n, while my node is 2. Then this is not the reason.

Anyway, I changed gpu number to 1, it disappeared. Are you using multi-GPU?

**Comment by GustavZ** [comment]
When I faced the error it was already on single gpu, will try some changes later and report you how it went.

**Comment by waleedka** [comment]
> if i train on low res, should i change RPN_ANCHOR_SCALES and MINI_MASK_SHAPE too?
Any other config params taht need to be changed when changing input resolution?

You might want to change `RPN_ANCHOR_SCALES` to smaller numbers since your objects are likely smaller in size. It shouldn't cause a division by zero error, though. I think that's not related. Take a look at `train_shapes` which uses small images, and also check the nucleus sample, which uses smaller images as well.

> which value means 1 GPU?
`GPU_COUNT  = 1` covers both cases: training with CPU and training with 1GPU

> expected input_image_meta to have shape (None, 14) but got array with shape (2, 93)
Are you updating the config object after it's created? That would cause this problem. Subclass the config class rather than updating its properties directly.

> ZeroDivisonError is due to python2.7

Good catch. Thanks for reporting back. I think this might solve similar issues in other threads as well.

**Comment by waleedka** [comment]
parallel_model is used to parallelize the model on multiple GPUs. If you use one GPU, you don't need it.

**Comment by wxianfeng** [comment]
ZeroDivisonError is due to python2.7

if use python 2.7, how to fix it

must upgrade python 3 ?

**Comment by GustavZ** [comment]
This version is fully py2.x / py3.x compatible
https://github.com/GustavZ/Mobile_Mask_RCNN

**Comment by doomSDey** [comment]
I almost pulled all my hairs out for this error and it turns out it needed a new folder inside the given directory.
Are you kidding me?
Anyways thanks guys ....Real lifesaver

**Comment by doomSDey** [comment]
fixed it through subdirs. The path needs to be to a folder (that contains the images) as opposed to directly to the images.

**Comment by genaunit** [comment]
I had the same division by zero problem on training start: in my case, it was as silly as having max_steps parameter set lower than the dataset size! Some rounding leads to global_step being 0 and divided on.
