### ISSUE TITLE
Divide by 0 error after clone the new release 

### ISSUE THREAD

**Issue by YubinXie** [matterport/Mask_RCNN#462]
I updated my clone and ran it on my previous codes, which worked great in previous MASK-R-CNN, but now it gives me error like when training:
InvalidArgumentError: Integer division by zero
	 [[Node: training/SGD/gradients/mrcnn_bbox_loss_1/concat_grad/mod = FloorMod[T=DT_INT32, _class=["loc:@mrcnn_bbox_loss_1/concat"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_class_loss_1/concat/axis, training/SGD/gradients/mrcnn_bbox_loss_1/concat_grad/Rank)]]

Any ideas? Thanks!

**Comment by YubinXie** [comment]
After some testing, when I set my training GPU to 1 (was 2), image/node=1, the error disappeared. But I have 16n images, why there would be such error?

**Comment by YubinXie** [comment]
OK, I found a duplicate. Will close this one.

**Comment by LeYangNwpu** [comment]
@YubinXie How did you solve this problem?
I encounter the same situation as you
tensorflow.python.framework.errors_impl.InvalidArgumentError: Integer division by zero
         [[Node: training/SGD/gradients/mrcnn_bbox_loss_1/concat_grad/mod = FloorMod[T=DT_INT32, _class=["loc:@mrcnn_bbox_loss_1/concat"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](split_2/split_dim, training/SGD/gradients/mrcnn_bbox_loss_1/concat_grad/Rank)]]
         [[Node: training/SGD/gradients/Mean_4_grad/Size/_5003 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_12017_training/SGD/gradients/Mean_4_grad/Size", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by wdma** [comment]
I am seeing a similar error using only 1 GPU.  Is this related to your problem, LeYangNwpu?

tensorflow.python.framework.errors_impl.InvalidArgumentError: Integer division by zero
	 [[Node: TensorSliceDataset/input_layer/fives/div = FloorDiv[T=DT_INT32](TensorSliceDataset/input_layer/fives/Sub, TensorSliceDataset/input_layer/fives/Sub_1)]]
	 [[Node: OneShotIterator = OneShotIterator[container="", dataset_factory=_make_dataset_54446384[], output_shapes=[[?,5], [?,1]], output_types=[DT_FLOAT, DT_FLOAT], shared_name="", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by LeYangNwpu** [comment]
When I updated TensorFlow to 1.7, this problem disappeared.

2018-05-15 3:28 GMT+08:00 Diana <notifications@github.com>:
