### ISSUE TITLE
Anchors needed for inference ?

### ISSUE THREAD

**Issue by hadim** [matterport/Mask_RCNN#473]
In the last version of this repo, when running an inference with [an exported TensorFlow model](https://github.com/matterport/Mask_RCNN/issues/218), a third tensor is needed for the input: `input_anchors`.

Are we supposed to build the `anchors` with a similar function at this one: https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L2552 ?

Or is it only used for training? In that case, how can we disable it?

For example:

```python
with tf.Session() as sess:
    
    # Prepare inputs and outputs
    input_image_tensor = sess.graph.get_tensor_by_name(f'{INPUT_NODE_IMAGE_NAME}:0')
    input_image_metadat_tensor = sess.graph.get_tensor_by_name(f'{INPUT_NODE_IMAGE_METADATA_NAME}:0')

    input_data = {input_image_tensor: processed_image,
                  input_image_metadat_tensor: metadata}

    output_data = {node_name: sess.graph.get_tensor_by_name(f'output_{node_name}:0') for node_name in OUTPUT_NODE_NAMES}
    
    # Run the prediction
    raw_results = sess.run(fetches=output_data, feed_dict=input_data)
```

returns:

```
InvalidArgumentError: You must feed a value for placeholder tensor 'input_anchors' with dtype float and shape [?,?,4]
	 [[Node: input_anchors = Placeholder[dtype=DT_FLOAT, shape=[?,?,4], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by waleedka** [comment]
Anchors are needed for both, training and inferencing. The recent update, which changes anchors from a static value to a dynamic value, was added to allow the model to run inferencing on variable image sizes. So now, anchors are created on the fly depending on the input image size.

**Comment by hadim** [comment]
I see. Thank you for the clarification.

**Comment by hadim** [comment]
An additional question: all the mold and unmold operation are done on the Python side. Could we imagine doing those in the graph directly?

I am asking because I am trying to run prediction on Java and all the mold/unmold operations are pretty long to implement. Having them in the graph would be fantastic.

Now, it might be unwanted or impossible...

**Comment by waleedka** [comment]
I don't see any particular reason that would prevent doing them in the graph. It was done this way for convenience at the time since Python is easier to debug than graph code.

**Comment by hadim** [comment]
Ok, I understand. Would you consider such a big modification to the model for inclusion in the repo?

**Comment by waleedka** [comment]
Yes, sure. Happy to merge a pull request if it's well tested. Considering the big change, it might be best if divided into two or three small PRs rather than a giant one. It makes it easier to review and test.

**Comment by hadim** [comment]
For the record, I have created two graphs for processing purposes, one for pre and the other for post-processing: https://gist.github.com/hadim/2f82562022b12ce46c58cd1c98d711db

Unfortunately, it's unlikely I find time any time soon to integrate it into this repo. That being said, with the above notebook, it should be easy.

Hope it can help.

**Comment by NoahDolev** [comment]
Hi Hadim,

Do you know how I should handle the "created on the fly" anchors when deploying to Google's cloud engine? I get the message:

```{Python}
Exception during running the graph: You must feed a value for placeholder tensor 'input_anchors' with dtype float and shape [?,?,4] 
```

I can create a placeholder tensor but I am not sure how to pass this to the model since the anchors are created on the fly. 

```{Python}
input_anchors = tf.placeholder(tf.float32, shape=[None,None,4], name='input_anchors')
```
Any suggestions?

Thanks a lot!
