### ISSUE TITLE
Performance of Nucleus Data Science Bowl model

### ISSUE THREAD

**Issue by cklat** [matterport/Mask_RCNN#474]
Hi,

I realized that you put up a nice tutorial with ready-to-go implementation for training mask-rcnn on the data science bowl 2018. Unfortunately, I couldn't find any performance related figures of the implementation that you provided. Could you roughly tell me, what performance I would achieve, if training the mask-rcnn with the code?

Thanks a lot for your help!

**Comment by waleedka** [comment]
There is a thread about it here: 
https://www.kaggle.com/c/data-science-bowl-2018/discussion/54089
