### ISSUE TITLE
module 'coco' has no attribute 'CocoConfig'

### ISSUE THREAD

**Issue by aarondt** [matterport/Mask_RCNN#486]
I am trying to run the demo.ipynb file, however upon running:
```
class InferenceConfig(coco.CocoConfig):
    # Set batch size to 1 since we'll be running inference on
    # one image at a time. Batch size = GPU_COUNT * IMAGES_PER_GPU
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1
```

I receive the following error: module 'coco' has no attribute 'CocoConfig'

However, I have imported the coco module. Hence I wonder how to fix this?

**Comment by HC-2016** [comment]
How did you solve the problem?

**Comment by jericovalino** [comment]
does somebody has solved this problem?

**Comment by tc-one** [comment]
does any1 have an idea for this problem?

**Comment by Wismute** [comment]
If somebody will read this in future and has not seen a solution -- [it's here](https://github.com/matterport/Mask_RCNN/issues/596#issuecomment-392259014)

Replace this:
`import coco`

With this:
`from samples.coco import coco`

**Comment by Benito2204** [comment]
Hi Daniil404,

When I run from samples.coco import coco, it throws me error like this "No module named samples".

Please help

**Comment by ShashiAdhikari** [comment]
> Hi Daniil404,
> 
> When I run from samples.coco import coco, it throws me error like this "No module named samples".
> 
> Please help

did you fix this error
