### ISSUE TITLE
function apply_box_deltas_graph

### ISSUE THREAD

**Issue by DevinCheung** [matterport/Mask_RCNN#492]
@waleedka 
when "Applies the given deltas to the given boxes.", 

the author let:
center_y += deltas[:, 0] * height
height *= tf.exp(deltas[:, 2])

why use "multiply" not "add", i.e. center_y += deltas[:, 0], height += deltas[:, 2]?
why dy, ..., dh mean multiple, not increment?

Thanks!!

**Comment by waleedka** [comment]
Deltas are relative to the original height. So, a delta dy of value 0.1 means 0.1 of the original height. That's why we multiply the delta by the origin height first, then add it to center_y.
