### ISSUE TITLE
How to load resnet50?

### ISSUE THREAD

**Issue by rujiao** [matterport/Mask_RCNN#5]
Hi @waleedka ,

I have a less powerful GPU and want to train my own data which contain only 3 classes. Therefore I would use Resnet50 to speed up the model. How can I switch to Resnet50?  Thanks for your help.

**Comment by waleedka** [comment]
Code for ResNet50 is available but I haven't tested it recently. Try the following, and if you encounter any issues let me know. 

First, you need to change the model architecture. In model.py change this line from:
````
_, C2, C3, C4, C5 = resnet_graph(input_image, "resnet101", stage5=True)
````
to
````
_, C2, C3, C4, C5 = resnet_graph(input_image, "resnet50", stage5=True)
````

With this change, you'll be using a ResNet50 backbone. You could train it from random weights, but that's not a great idea as it will take a very long time. You'd want to load ResNet50 weights trained on ImageNet or COCO. Keras provides such weights free to download. Check `get_imagenet_weights()` in model.py and update the URL to point to ResNet50 weights (you might need to scan the Keras source code to find the right link).

**Comment by waleedka** [comment]
Actually, I just realized that the "imagenet" weights we're using are those of ResNet50. So then your work is easier, just change the line I mentioned above. See `coco.py` for how to start training starting from imagenet weights.

Keep in mind that I haven't tested this on ResNet50 recently. Did in the beginning, but switched to Resnet101 later and most of the work and testing was done on that. If you encounter any bugs, please do report them.

**Comment by Cyndishine** [comment]
@rujiao 
Hi! I can't find the pretrained model in ~/.keras/models/ in the site you provided. Could you please give me a pretrained model of resnet50?

**Comment by rujiao** [comment]
@Cyndishine please find the model here:
https://github.com/fchollet/deep-learning-models/releases/
