### ISSUE TITLE
Pre trained weights

### ISSUE THREAD

**Issue by abarthakur** [matterport/Mask_RCNN#50]
The README mentions pre trained weights trained on the COCO dataset. However it doesn't seem to be there in the repo! Could you please commit/link it, it would be really useful.

**Comment by hayk-ghazaryan** [comment]
The readme mentions it also.

https://github.com/matterport/Mask_RCNN/releases

**Comment by abarthakur** [comment]
Ah I can't believe I missed that. Sorry and thank you!
