### ISSUE TITLE
Have anyone trained on Pascal Voc dataset ?

### ISSUE THREAD

**Issue by yanxp** [matterport/Mask_RCNN#51]

**Comment by jinyu121** [comment]
Try [this file](https://github.com/matterport/Mask_RCNN/files/1473777/jinyu121_pascal.zip).

**Comment by yanxp** [comment]
@jinyu121  Thanks!

**Comment by yanxp** [comment]
@jinyu121 Hello,AttributeError: 'module' object has no attribute 'compute_mask_right_wrong'

**Comment by jinyu121** [comment]
Well...

The first function have some personal code, I will rewrite and release it soon.

The second problem... You mean the result array is empty, right? I have met the same problem. I mean, I copied the demo code from `train_shapes`, but if you test 100 images, there can be at most 10 detection results. It confused me so long and I don't know why. Could you please debug it? THX

**Comment by yanxp** [comment]
So strange!! However, I can test the train_shapes. I will try it.

**Comment by Sharathnasa** [comment]
I had trained. But mask didn't come. Only the small patch of mask was there.

**Comment by jinyu121** [comment]
```python
def compute_mask_right_wrong(gt_bbox, gt_mask, gt_cls, pred_bbox, pred_mask, pred_cls, pred_score, overlap_thresh=0.5):
    n_gt = len(gt_bbox)
    n_pre = len(pred_bbox)
    corrcet_list = [False] * n_pre
    overlap_list = [0] * n_pre

    gt_taken = [False] * n_gt
    take_order = (-pred_score).argsort()

    for ith_pre in take_order:
        best_overlap = -1
        besp_overlap_place = -1
        for jth_gt in range(n_gt):
            if not gt_taken[jth_gt] and pred_cls[ith_pre] == gt_cls[jth_gt]:
                overlap = mask_overlap(pred_bbox[ith_pre], gt_bbox[jth_gt],
                                       pred_mask[:, :, ith_pre], gt_mask[:, :, jth_gt])
                if overlap > best_overlap:
                    best_overlap = overlap
                    besp_overlap_place = jth_gt
        if best_overlap > overlap_thresh:
            corrcet_list[ith_pre] = True
            gt_taken[besp_overlap_place] = True
            overlap_list[ith_pre] = best_overlap

    return np.array(corrcet_list), pred_score[take_order], overlap_list
```

and we need to import <https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/datasets/voc_eval.py> because we need `mask_overlap` and `voc_ap` function.

**Comment by dongdong092** [comment]
Sorry,but in the file voc_eval.py,I don't find the founction mask_overlap

**Comment by yanxp** [comment]
@dongdong092  do you have maks results after training on voc?

**Comment by yanxp** [comment]
@jinyu121  Can you test pascal voc successfully?

**Comment by anuchandra** [comment]
@yanxp @dongdong092 Were you able to test on Pascal VOC successfully? I am not interested in the Pascal VOC data set itself. But I can create annotations / binary masks in pascal voc format so I want to train with the code @jinyu121 shared. If it works, could you please let me know? Thanks

**Comment by dongyingchn** [comment]
@dongdong092 You can try this one https://github.com/daijifeng001/MNC/blob/master/lib/transform/mask_transform.py, there is a function mask_overlap. It should be noted that the masks in this function are already croped from the whole images, yet the Mask R-CNN here provide the gt_mask and pred_mask in the shape of whole original image, so I made some changes to this function.

```
def mask_overlap(box1, box2, mask1, mask2):
    """
    This function calculate region IOU when masks are
    inside different boxes
    Returns:
        intersection over unions of this two masks
    """
    mask1_crop = mask1[box1[0]:box1[2], box1[1]:box1[3]]
    mask2_crop = mask2[box2[0]:box2[2], box2[1]:box2[3]]

    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])

    if x1 > x2 or y1 > y2:
        return 0
    w = x2 - x1 + 1
    h = y2 - y1 + 1
    # get masks in the intersection part
    start_ya = y1 - box1[1]
    start_xa = x1 - box1[0]
    inter_maska = mask1_crop[start_xa: start_xa + w - 1, start_ya:start_ya + h - 1]

    start_yb = y1 - box2[1]
    start_xb = x1 - box2[0]
    inter_maskb = mask2_crop[start_xb: start_xb + w - 1, start_yb:start_yb + h - 1]

    assert inter_maska.shape == inter_maskb.shape

    inter = np.logical_and(inter_maskb, inter_maska).sum()
    union = mask1.sum() + mask2.sum() - inter
    if union < 1.0:
        return 0
    return float(inter) / float(union)

**Comment by ps48** [comment]
@jinyu121 @yanxp [https://github.com/cocodataset/cocoapi/blob/master/MatlabAPI/CocoUtils.m](Pascal to COCO) This is from official COCO tools repo to convert Pascal VOC to COCO.  But the bummer is it's in Matlab!

**Comment by nayriz** [comment]
@ps48 were you able to use it? I tried with Octave but there is a variable called `containers` that is not defined, and the comments don't explain what it is supposed to be...

**Comment by ps48** [comment]
@nayriz This link is from Facebook's Detectron repo [Pascal in Coco format](https://storage.googleapis.com/coco-dataset/external/PASCAL_VOC.zip)

**Comment by Ekram-B** [comment]
Hi, for those working on it, was anyone able to draw from PASCAL successfully?

**Comment by Buithienbao** [comment]
Hi, is anyone here have the problem with the code of @jinyu121 ? I train the model on Google Colab with PASCAL VOC 2012 datasets and encounter this error
`ERROR:root:Error processing image {'id': 1122, 'source': 'voc', 'path': '/content/VOCdevkit/VOC2012/JPEGImages/2010_003532.jpg', 'mask_path': '/content/VOCdevkit/VOC2012/SegmentationObject/2010_003532.png', 'objs': [OrderedDict([('name', 'horse'), ('bndbox', OrderedDict([('xmax', '432'), ('xmin', '66'), ('ymax', '364'), ('ymin', '41')])), ('difficult', '0'), ('occluded', '1'), ('pose', 'Unspecified'), ('truncated', '0')]), OrderedDict([('name', 'horse'), ('bndbox', OrderedDict([('xmax', '147'), ('xmin', '10'), ('ymax', '211'), ('ymin', '19')])), ('difficult', '0'), ('occluded', '1'), ('pose', 'Left'), ('truncated', '1')])], 'width': '500', 'height': '375'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1212, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "/content/Mask_RCNN/samples/pascal_voc/pascal_voc.py", line 180, in load_mask
    mask = np.ones(tmp_mask.shape[:2]).astype(np.bool)
AttributeError: 'bool' object has no attribute 'shape'`

Any help would be very appreciated.

**Comment by genausz** [comment]
Check out my implementation of TRAINING Mask_RCNN with PASCAL VOC 2012 dataset.

> https://github.com/genausz/Mask_RCNN


code are in dir ./samples/voc
