### ISSUE TITLE
Bug or any deeper consideration?  The callbacks in "/mrcnn/model.py"

### ISSUE THREAD

**Issue by ziyigogogo** [matterport/Mask_RCNN#544]
It seems that the "log_dir" is created in the callback "keras.callbacks.TensorBoard".

But in my application, I don't need the "tensorboard" analysis which could be a really time consuming job for my hardware condition.

So, i comment the 2298-2299 lines in file "/mrcnn/model.py".

```python
keras.callbacks.TensorBoard(log_dir=self.log_dir,
                                        histogram_freq=0, write_graph=True, write_images=False),
```

After that an error happened:
OSError: Unable to create file (unable to open file: name = 'D:\XXXX\mask_rcnn\logs\XXXX20180510T1347\mask_rcnn_XXXX_0001.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)

A workaround now is to add the following codes after line ~~2295~~ 2237 in "model.py":

```python
if not os.path.exists(self.log_dir):
    os.makedirs(self.log_dir)
```

But i am not sure that if there is a deeper consideration for the current behave, please kindly let me know if so@waleedka

**Comment by ziyigogogo** [comment]
Hmm, i think do the creation @line 2237 in the "set_log_dir" function is better

**Comment by waleedka** [comment]
Thanks you! The PR is merged so I'm closing this.
