### ISSUE TITLE
About the handling of "steps_per_epoch"

### ISSUE THREAD

**Issue by ziyigogogo** [matterport/Mask_RCNN#550]
Hi there,
I am confused with the document here:

> steps_per_epoch: Total number of steps (batches of samples) to yield from generator before declaring one epoch finished and starting the next epoch. It should **typically** be equal to the number of unique samples of your dataset divided by the batch size.

In my poor understanding, the steps_per_epoch should be "**EXACTLY THE SAME**" as "NUM_OF_SAMPLES / batch_size", so all the samples can be iterated once.

To understand more about this param, I really want to know what keras dose when step_per_epoch is set **un-typically** .

To be clear, my questions are:

1.  when step_per_epoch < NUM_OF_SAMPLES / batch_size
    > if some of the samples were skipped? So, the trainer gets the input size < NUM_OF_SAMPLES?

2. when step_per_epoch > NUM_OF_SAMPLES / batch_size,
    > if  some of the samples imported multiple times to the trainer, so the actual input size > NUM_OF_SAMPLES?

Thank you so much for your time.

**Comment by ziyigogogo** [comment]
For anyone who may concern,[Keras issue#10164](https://github.com/keras-team/keras/issues/10164) solved my question.

**Comment by patrickcgray** [comment]
@ziyigogogo I see how it works based on your question at https://github.com/keras-team/keras/issues/10164 but I'm curious if you've found what is _ideal_? Should you just always set steps_per_epoch = num_samples / batch_size ? Have you done any experimentation with this? I just realized I have 100 images and have been setting batch_size=1 and then 30 steps_per_epoch, so my real epoch count is basically a third of what I thought it was.

**Comment by ziyigogogo** [comment]
@patrickcgray 
In my experience, there is no general IDEAL setting. 
But in my practice,  i always let num_epoch * batch_size * setps_per_peoch  > num_images.
So that during training process, all your images can be feed at once.
In your example, batch_size =1 and 30 steps_per_epoch, so I set num_epoch = 4. 
As the result, all 100 images plus 20 duplicated images(from your 100 images) are iterated.

**Comment by aratimcs** [comment]
Hello sir, I'm working on deep learning based classification problem. i'm not need learning expert. i have a little doubt on selecting number of samples to train model at a time. what will happen when we take when we take step_per_epochs less than total NUM_OF_SAMPLES is it degrades the performance. when i select step_per_epochs = total NUM_OF_SAMPLES / batch_size then it takes more iterations per epochs on training and also it increases computation time. Could you please clear my doubt. Please reply
