### ISSUE TITLE
AP not between 0 and 1 ?

### ISSUE THREAD

**Issue by baristahell** [matterport/Mask_RCNN#551]
So, i'm using `compute_ap` to compute a mean average precision in the following way (similar to the example in `train_shapes`) :

- APs = []
- For all images in my validation dataset
- - Load image
- - Detect on image
- - - If "rois" is empty, AP = 0
- - - Else  `AP, precisions, recalls, overlaps = utils.compute_ap()`
- - Append AP to APs
- mAP = mean(APs)

My problem is that a lot of AP values i compute are over 1.0 (example of an APs of a small set : `[2.0, 2.0, 2.0, 2.0, 2.0, 0.3333333333333333, 2.0, 0.05555555555555555, 1.375, 2.0, 2.0, 2.0, 0, 1.375, 2.0, 2.0, 2.0, 2.0, 1.5, 1.3, 2.0, 1.138888920346896, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 2.0, 1.5, 2.0, 2.0, 2.0, 1.25, 1.5, 2.0, 1.375, 1.6666666666666665, 2.0, 0.0, 0.25, 1.25, 2.0, 1.375, 1.375, 2.0, 2.0, 2.0, 0.5, 1.1666666666666667, 2.0, 2.0, 0.8333333333333333, 2.0, 1.5]` )

So my mAP is `mAP :  1.6073586750158326`, over 1.0 and i don't get it. Maybe it's because i have multiple detections for the same object? Maybe i don't understand what AP stands for and in this case i think i would like it very much if someone could help me :zipper_mouth_face: 

Thanks.

PS : i think I'm simply mistaking AP for precisions but now the same issue appears with my recalls, that are spread between 0 and 2 and it makes no sense to me.

**Comment by baristahell** [comment]
Also, my  `precisions` and `recalls` have variable lengths, and i find this troubling. I don't know what they're referring too and i don't know what thresholds are used to, which makes that i don't know how to compute the overall precision of my system : should i use the last value in the list (almost always 0)? The first (almost always 1)?

**Comment by patrick-12sigma** [comment]
I confirm that I have the same issue. It is on my to do list to debug but I haven't got around to do it. Any help in fixing this is appreciated.
