### ISSUE TITLE
When i use the mobilenet as a backbone,i met this mistake?

### ISSUE THREAD

**Issue by chrispolo** [matterport/Mask_RCNN#558]
Hello,i use the mobilenet as a backbone to train on the pretrained weights:mask_rcnn_coco.h5,
i met this mistake:
Loading weights  /root/data/mrcnn_test/mask_rcnn_coco.h5
Traceback (most recent call last):
  File "coco.py", line 484, in <module>
    model.load_weights(model_path, by_name=True)
  File "/root/data/mrcnn_test/model.py", line 2402, in load_weights
    topology.load_weights_from_hdf5_group_by_name(f, layers)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 3201, in load_weights_from_hdf5_group_by_name
    ' element(s).')
ValueError: Layer #2 (named "conv1") expects 1 weight(s), but the saved weights have 2 element(s).
How to fix it?

**Comment by liangbo-1** [comment]
Have you solved your problem?

**Comment by chrispolo** [comment]
i　have solved the problem,if needed  you can check my project

**Comment by ApoorvaSuresh** [comment]
Hi,

I am using mobilenet backbone, but getting this error while inference:

ValueError: Layer #1 (named "conv1") expects 2 weight(s), but the saved weights have 1 element(s).


Any idea why?

**Comment by impravin22** [comment]
Me either. 
Anyone solved this problem?

**Comment by tbnxyzfz1** [comment]
I solved this problem by downloading the file from the website mentioned in this code from model.py, then use the file path directly.

def get_imagenet_weights(self):
        """Downloads ImageNet trained weights from Keras.
        Returns path to weights file.
        """
        from keras.utils.data_utils import get_file
        TF_WEIGHTS_PATH_NO_TOP = 'https://github.com/fchollet/deep-learning-models/'\
                                 'releases/download/v0.2/'\
                                 'resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5'
        weights_path = get_file('resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5',
                                TF_WEIGHTS_PATH_NO_TOP,
                                cache_subdir='models',
                                md5_hash='a268eb855778b3df3c7506639542a6af')
        return weights_path
