### ISSUE TITLE
error: operands could not be broadcast together with shapes (1280,1280,4) (3,) 

### ISSUE THREAD

**Issue by franksRsrch** [matterport/Mask_RCNN#578]
My training has gone fine, but I'm getting the following error when I try to infer from an image. I'm using the balloon template to apply a splash image. Any help would be very much appreciated.

```
image                    shape: (3000, 4000, 4)       min:    0.00000  max:  255.00000  uint8
Traceback (most recent call last):
  File "test.py", line 374, in <module>
    video_path=args.video)
  File "test.py", line 238, in detect_and_color_splash
    r = model.detect([image], verbose=1)[0]
  File "/scratch/df525/Mask_RCNN-master/mrcnn/model.py", line 2457, in detect
    molded_images, image_metas, windows = self.mold_inputs(images)
  File "/scratch/df525/Mask_RCNN-master/mrcnn/model.py", line 2356, in mold_inputs
    molded_image = mold_image(molded_image, self.config)
  File "/scratch/df525/Mask_RCNN-master/mrcnn/model.py", line 2757, in mold_image
    return images.astype(np.float32) - config.MEAN_PIXEL
ValueError: operands could not be broadcast together with shapes (1280,1280,4) (3,) 

```

**Comment by curryandone** [comment]
I met this problem too.

**Comment by abhi-kumar** [comment]
Was this error solved?

**Comment by franksRsrch** [comment]
Yes - You need to remove the alpha channel, because it expects just the RGB channels without the alpha. That's why it's giving the error, it's the 4 in the shape that's the problem, removing alpha makes it 3.

**Comment by abhi-kumar** [comment]
Thank you for the clarification. 
png images do have that alpha channel. Scikit-image tends to take it whereas opencv doesn't (in default input mode).

**Comment by kaisark** [comment]
Cool Project. I’m was a little surprised to learn that balloons were not part of the COCO dataset. I ran on Amazon EC2 P2 instance using the pre-trained model and got good results with both an image (small balloon) and video (giant balloons)! 

![splash_20180611t050521](https://user-images.githubusercontent.com/3580312/41215815-0ca0339e-6d20-11e8-9ade-9980ed4f8c82.png)

![animated gif-downsized_large](https://user-images.githubusercontent.com/3580312/41215823-14650abe-6d20-11e8-903d-1c46e4f25835.gif)

**Comment by doingRsrch** [comment]
@eyildiz-ugoe 

```
# Remove alpha channel, if it has one
    if image.shape[-1] == 4:
        image = image[..., :3]
```

**Comment by athityakumar** [comment]
Ah, thanks for the fix @eyildiz-ugoe 😄

**Comment by eyildiz-ugoe** [comment]
Well, not really. I still get the same error.

`ValueError: operands could not be broadcast together with shapes (1200,800) (1433,1075) (1433,1075) `

**Comment by chibohe** [comment]
I got the same problem, have you fixed it @eyildiz-ugoe

**Comment by eyildiz-ugoe** [comment]
@chibohe No I couldn't. With or without that suggested piece of code, it gives error for me. It is true that the problem could be channels as the error appears to be related to `image[:, :, c])` but I don't know what exactly is wrong.

**Comment by salamohamad** [comment]
You need to avoid PNG images as they seem to be the root of this problem. Using jpg seems fine but png breaks into this issue!

**Comment by padmaksha18** [comment]
Hi All, I am facing the same issue while classification , images having channels 4 are throwing this error in broadcasting. I tried changing that channels value in IMAGE_SHAPE initialisation  to 1 as suggested but that is throwing error in training itself. Is there any way around or do you suggest resizing all images to a particular dimension, not sure if that will harm classification results.Please advice.

**Comment by bhuiyanmobasshir94** [comment]
[ValueError: operands could not be broadcast together with shapes (1024,1024,4) (3,)]. I am getting this error while I am trying to inference. Please help me out from this situation.

**Comment by theevilone45** [comment]
I've got the same problem, @bhuiyanmobasshir94 have you fixed this?

**Comment by hpeiyan** [comment]
### Png To Jpg
```
from PIL import Image
img = Image.open('path/xx.png')
img = img.convert('RGB')
img.save('path/xx.jpg')
```

**Comment by Basma-hash** [comment]
I have got the same problem, Have anyone fixed it?

**Comment by alikanakar** [comment]
@Basma-hash have you solved the problem, I am facing the same problem?

**Comment by Basma-hash** [comment]
@alikanakar the problem was from the png format of nucleus dataset, if you run the code in your custom data, it will be run.

**Comment by alikanakar** [comment]
@Basma-hash thank you for your answer but I have already used my own dataset and it doesn't contain any png images. I am still working on it

**Comment by imen-g** [comment]
ValueError: operands could not be broadcast together with shapes (712,) (712,5)  any help !

**Comment by MartinJensen37** [comment]
I'm getting the following error while trying to train my mask rcnn on 3 classes instead of 81: 
```
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1772, in data_generator
    batch_images[b] = mold_image(image.astype(np.float32), config)
ValueError: could not broadcast input array from shape (480,640,3) into shape (427,640,3)

```

**Comment by imen-g** [comment]
@MartinJensen37 i solve the problem of shapes by using 
y_test=np.argmax(y_test, axis=1)  
u can check my notebook tomoreunderstanding: https://github.com/imen-g/Deep-Learning/blob/master/perceptron_Titanic_kaggle.ipynb

**Comment by yrodriguezmd** [comment]
For me, it resolved when I converted the images to RGB :)

**Comment by LUAI-SH** [comment]
I got the error when using PNG images. 
Converting them to JPG solved the problem!

**Comment by yuan-ge** [comment]
> ### Png To Jpg
> ```
> from PIL import Image
> img = Image.open('path/xx.png')
> img = img.convert('RGB')
> img.save('path/xx.jpg')
> ```

This helps me a lot, thanks much!
