### ISSUE TITLE
Slower training time when increasing IMAGES_PER_GPU

### ISSUE THREAD

**Issue by schmidje** [matterport/Mask_RCNN#589]
Hi,

First of all thank you the authors of this great repo! 

I am puzzled with something, I hope you can help me figuring out what's the problem.

My setup:
- Linux rhel 7
- 4x GeForce GTX 1080 8 GB
- tf 1.8.0, python 3.6, cuda 9.2.88.1, cuDNN 7.1.4 and nvidia driver 396.26 
- 128x128 image size in the config
- own data composed of X-ray images with up to 4 masks saved in binary format for fast loading.

Basically, I started by noticing that a multi-gpu training was slower than a single GPU one....! So, I focused on a single GPU version and I noticed that the more I reduced the IMAGES_PER_GPU the faster was my training:
- ~10 min with 1 image per gpu, 
- ~10 min 40 sec with 2 images per gpu, 
- ~13 min with 4 images per gpu.
- ~20 min with 8 images per gpu, 

I imagine that an excessive number of images per gpu will harm performance with possible out-of-memory issues, but my I pretty sure that my GPUs can properly handle e.g. 4 images per gpu and I thought that by increasing IMAGES_PER_GPU things will go faster. 

Before I start digging the multi-gpu issue, what am I missing here?

Thanks!

**Comment by liangbo-1** [comment]
I have encountered the same problem. Have you solved your problem?

**Comment by schmidje** [comment]
Nope.... :(

By curiosity what is your setup packages, distro and gpu? I wonder if the last tf, Cuda combo is not yet ok since to make it work I had to compile a lot of stuff from scratch. 

Thx

**Comment by ericj974** [comment]
@schmidje I also had the same issue: "I started by noticing that a multi-gpu training was slower than a single GPU one." 
After some code changes (see PR #710), my training is much better on a multi-gpu setup

**Comment by schmidje** [comment]
Thanks I will have a look!

**Comment by maxfrei750** [comment]
I think we may have found the explanation in #875.

**Comment by waleedka** [comment]
Closing this. Explanation posted in #708 and #875.
