### ISSUE TITLE
error ：model.load_weights(COCO_MODEL_PATH, by_name=True) 

### ISSUE THREAD

**Issue by lianshushu** [matterport/Mask_RCNN#59]
I get an error when running the demon code : model.load_weights(COCO_MODEL_PATH, by_name=True)

IOError: Unable to open file (truncated file: eof = 255370586, sblock->base_addr = 0, stored_eoa = 257558264)

**Comment by balajiwix** [comment]
please help me on this issue. I am getting this issue.
