### ISSUE TITLE
Do I need to resize mask after resizing image?

### ISSUE THREAD

**Issue by JerryMiao** [matterport/Mask_RCNN#61]
Hi,I made some masks for some 2048*2048 images.Then I found it's too big for my memory.So I change the IMAGE_MAX_DIM in config .But I couldn't find anywhere to change the size of the masks.Will the size of the masks change automatically?

**Comment by Walid-Ahmed** [comment]
Very nice question.
May I ask you how did you prepare your data set to be in Coco format?
How actually were the masks encodes in the dataset?

Thanks

**Comment by waleedka** [comment]
@JerryMiao The mask gets resized automatically to match the image. It's done in model.py in `load_image_gt()`
