### ISSUE TITLE
Can not find the source code about the neural network mask branch parts

### ISSUE THREAD

**Issue by showersi** [matterport/Mask_RCNN#623]
# Shape of output mask
    # To change this you also need to change the neural network mask branch
    MASK_SHAPE = [28, 28]

I have changed the MASK_SHAPE to [14,14], but i cant find the code of the neural network mask branch about this. Can you tell me how to find the codes?

**Comment by waleedka** [comment]
It's the `build_fpn_mask_graph()` function in `model.py`
