### ISSUE TITLE
Training stopped without releasing GPU memory -- Out of memory

### ISSUE THREAD

**Issue by netw0rkf10w** [matterport/Mask_RCNN#626]
Hello,

I tried training my custom dataset, which I converted to COCO's format. What I did is to copy `coco.py` and modify the name etc. Unfortunately I have never got the training to run successfully, due to out of memory issue. A strange issue is that when the problem breaks, it does not release the memory of the GPU. I had to reboot my server each time a training session failed :(

Lately I tried using resnet50 and reducing the image size:

```
BACKBONE = "resnet50"
IMAGE_RESIZE_MODE = "square"
IMAGE_MIN_DIM = 512
IMAGE_MAX_DIM = 512
```
it started to train but then error again:

> Epoch 1/40
>    1/1000 [..............................] - ETA: 17:10:49 - loss: 9.0742 - rpn_class_loss: 2.6839 - rpn_bbox_loss: 2.2965 - mrcnn_class_loss: 1.5021 - mrcnn_bbox_loss: 1.8991 - mrcnn_mask_loss: 0   2/1000 [..............................] - ETA: 8:41:46 - loss: 8.5584 - rpn_class_loss: 2.4432 - rpn_bbox_loss: 2.3522 - mrcnn_class_loss: 1.5195 - mrcnn_bbox_loss: 1.5785 - mrcnn_mask_loss: 0.   3/1000 [..............................] - ETA: 5:52:02 - loss: 7.8795 - rpn_class_loss: 2.4402 - rpn_bbox_loss: 2.2415 - mrcnn_class_loss: 1.1957 - mrcnn_bbox_loss: 1.3006 - mrcnn_mask_loss: 0.   4/1000 [..............................] - ETA: 4:26:59 - loss: 7.5652 - rpn_class_loss: 2.3533 - rpn_bbox_loss: 2.2754 - mrcnn_class_loss: 0.9323 - mrcnn_bbox_loss: 1.2874 - mrcnn_mask_loss: 0.   5/1000 [..............................] - ETA: 3:36:07 - loss: 7.0885 - rpn_class_loss: 2.2964 - rpn_bbox_loss: 2.1484 - mrcnn_class_loss: 0.7573 - mrcnn_bbox_loss: 1.1683 - mrcnn_mask_loss: 0.   6/1000 [..............................] - ETA: 3:02:14 - loss: 6.9631 - rpn_class_loss: 2.1952 - rpn_bbox_loss: 2.0658 - mrcnn_class_loss: 0.8401 - mrcnn_bbox_loss: 1.1630 - mrcnn_mask_loss: 0.   7/1000 [..............................] - ETA: 2:38:45 - loss: 6.6486 - rpn_class_loss: 2.0803 - rpn_bbox_loss: 2.0185 - mrcnn_class_loss: 0.7252 - mrcnn_bbox_loss: 1.1160 - mrcnn_mask_loss: 0.   8/1000 [..............................] - ETA: 2:20:35 - loss: 6.3481 - rpn_class_loss: 1.9904 - rpn_bbox_loss: 1.9701 - mrcnn_class_loss: 0.6393 - mrcnn_bbox_loss: 1.0321 - mrcnn_mask_loss: 0.   9/1000 [..............................] - ETA: 2:06:30 - loss: 6.0660 - rpn_class_loss: 1.8920 - rpn_bbox_loss: 1.8877 - mrcnn_class_loss: 0.5828 - mrcnn_bbox_loss: 0.9873 - mrcnn_mask_loss: 0.71622018-06-01 10:05:23.677419: F ./tensorflow/core/util/cuda_launch_config.h:127] Check failed: work_element_count > 0 (0 vs. 0)
> zsh: abort (core dumped)  CUDA_VISIBLE_DEVICES=2 python custom_coco.py train  --model=imagenet
> 

The worst thing is that it never releases the memory. My GPU is showing `10953MiB / 11439MiB` although the program was stopped as shown above.

Is there a way to release the GPU memory without rebooting? I have other training sessions running at the same time so each time I reboot I have to restart them again, which is very annoying.

I would like to use resnet101 and higher image dimensions. Which parameters should I change to reduce further the memory usage?

I attached below the current full configuration.

Thank you very much in advance for your help!

> Configurations:
> BACKBONE                       resnet50
> BACKBONE_STRIDES               [4, 8, 16, 32, 64]
> BATCH_SIZE                     1
> BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
> DETECTION_MAX_INSTANCES        100
> DETECTION_MIN_CONFIDENCE       0.7
> DETECTION_NMS_THRESHOLD        0.3
> GPU_COUNT                      1
> GRADIENT_CLIP_NORM             5.0
> IMAGES_PER_GPU                 1
> IMAGE_MAX_DIM                  512
> IMAGE_META_SIZE                19
> IMAGE_MIN_DIM                  512
> IMAGE_MIN_SCALE                0
> IMAGE_RESIZE_MODE              square
> IMAGE_SHAPE                    [512 512   3]
> LEARNING_MOMENTUM              0.9
> LEARNING_RATE                  0.001
> LOSS_WEIGHTS                   {'mrcnn_mask_loss': 1.0, 'rpn_class_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'rpn_bbox_loss': 1.0}
> MASK_POOL_SIZE                 14
> MASK_SHAPE                     [28, 28]
> MAX_GT_INSTANCES               100
> MEAN_PIXEL                     [123.7 116.8 103.9]
> MINI_MASK_SHAPE                (56, 56)
> NAME                           qopius
> NUM_CLASSES                    7
> POOL_SIZE                      7
> POST_NMS_ROIS_INFERENCE        1000
> POST_NMS_ROIS_TRAINING         2000
> ROI_POSITIVE_RATIO             0.33
> RPN_ANCHOR_RATIOS              [0.5, 1, 2]
> RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
> RPN_ANCHOR_STRIDE              1
> RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
> RPN_NMS_THRESHOLD              0.7
> RPN_TRAIN_ANCHORS_PER_IMAGE    256
> STEPS_PER_EPOCH                1000
> TRAIN_BN                       False
> TRAIN_ROIS_PER_IMAGE           200
> USE_MINI_MASK                  True
> USE_RPN_ROIS                   True
> VALIDATION_STEPS               50
> WEIGHT_DECAY                   0.0001

**Comment by asibley-13** [comment]
As far as out of memory errors, do some of your rois have a lot of annotations? A large number of annotations will increase the memory usage. If you lower MAX_GT_INSTANCES it will subsample your annotations and that should decrease memory usage. 

I've had issues with that error too "Check failed: work_element_count > 0 (0 vs. 0)" I think it is caused by feeding the net a batch size of 0. Since you are using a batch size of 1, do all of your training examples contain annotations? Or are some empty? 

Not sure about the memory release. Is there a process holding the memory that you can kill?

**Comment by asibley-13** [comment]
You might also try using a more stable version of tensorflow. I seem to get that cuda error in 1.8 but not 1.5.

**Comment by waleedka** [comment]
Often I use `sudo killall python3` to release GPU memory. Obviously only use it if you know that the jupyter notebook is the only Python task you care about. It works most times, but not always. Sometimes I still have to reboot the server to reclaim GPU memory.

Also, this is a big model that uses a lot of memory. I wouldn't train other models with it at the same time. 

And, finally, I put a wiki page of the most common memory optimizations since this is a fairly common issue:
https://github.com/matterport/Mask_RCNN/wiki

**Comment by netw0rkf10w** [comment]
@asibley-13 Thanks for your replies!
Indeed, I'm using Tensorflow 1.8 and the number of annotations per image in my dataset is quite large (some images can have more than 150 annotations). I think would try TF 1.5 as you suggested.
On the memory issue, no there's is no process holding the memory, which is why it is annoying :(

@waleedka Thanks. I think I should play more with the parameters.

**Comment by netw0rkf10w** [comment]
@asibley-13 I come here to thank you again ;) I tried TF 1.5 and so far (4th epoch) so good!
