### ISSUE TITLE
TypeError: Failed to convert object of type <class 'theano.tensor.var.TensorVariable'> to Tensor.

### ISSUE THREAD

**Issue by tizpibes** [matterport/Mask_RCNN#627]
Hi all, 
i'm encountering this error in the following simple code: 

from rllab.spaces import Box 
import tensorflow as tf 

a = Box(1,4,shape(1,4))
b = a.new_tensor_variable('b',extra_dims=2)
c = tf.shape(b)[0]

I have already try to look at the keras backend and it's correct.
Any suggestion? Thank you!

**Comment by zungam** [comment]
I think you use Theano as back end, but try to impose keras on tensorflow as back end. You must decide which backend you want to use. See issue: [305](https://github.com/matterport/Mask_RCNN/issues/305)

**Comment by antoniotizzano** [comment]
No,  I'm sure to use tensorflow. But is it possible to evaluate the shape of a theano tensor variable with tensorflow?
