### ISSUE TITLE
Sanity check -- how much GPU memory does the train_shapes.ipynb require? 

### ISSUE THREAD

**Issue by ketkar** [matterport/Mask_RCNN#630]
I'm setting up the environment for running this in a Docker container. Currently my 1050ti  4GB is OOMing on the train_shapes example. 

Can someone with a larger card please tell me how much memory this notebook requires when running with the default settings? 

I'm trying to figure out if it's my CUDA/CuDNN being incompatible with the Tensorflow version, or if it truly requires more memory.

**Comment by waleedka** [comment]
On my GTX 1070 with 8GB, nvidia-smi reports the task using 6939MiB. This is on Ubuntu 18.04, TF 1.8, and CUDA 9.1.

**Comment by ketkar** [comment]
Tensorflow by default allocates as much GPU memory as possible, which is likely why the 8GB is mostly allocated.  I ran the notebook on a P6000 and it allocated 23GB, but it successfully ran.

4 GB is not enough for sure -- either way, thank you! Closing this out.
