### ISSUE TITLE
balloon_dataset.p3 file not present on release page for download

### ISSUE THREAD

**Issue by kewlcoder** [matterport/Mask_RCNN#631]
Hi,

I was checking the Mask_RCNN/samples/balloon/README.md file. It asks to download the balloon_dataset.p3 file from the "https://github.com/matterport/Mask_RCNN/releases" page. However such file is not there on the page. 
Further, while running the code it crashes with the error - "Mask_RCNN/datasets/train/via_region_data.json file not found".
Am I doing something wrongly?

**Comment by waleedka** [comment]
Looks like you found a typo. It's `.zip` not `.p3`. I fixed the documentation.
