### ISSUE TITLE
*** No instances to display ***  when detecting on test images, but normal results on coco dataset

### ISSUE THREAD

**Issue by GustavZ** [matterport/Mask_RCNN#638]
I see the *** No instances to display ***  Error when i do detection on test images like in the demo notebook.

But in contrast to that when i do it over the coco dataset like in the inspect_model notebook i get normal results.

@waleedka do you have an idea why that is? Even if the test images are manually taken from the original coco dataset.

I know some of those errors are py2/3 related but as far as i know i solved all python version depending issues (like stated in my PR)

Edit: I solved it with casting all boxes to floats in the function norm_boxes.

I will include this into the PR, i hope finally my fork is completely py2/3 compatible

**Comment by raghavgurbaxani** [comment]
@GustavZ  Could you detail the steps to do the casting, I'm getting the *** No instances to display ***
 error as well. 

Thanks.

**Comment by FImhaouran** [comment]
@GustavZ same
