### ISSUE TITLE
Loading a coco-style own dataset and training M-RCNN

### ISSUE THREAD

**Issue by eyildiz-ugoe** [matterport/Mask_RCNN#649]
Hi, 

Is there a way to load a coco-style dataset and make Mask-RCNN work? I've already checked nucleus and shape examples, but they don't help since shape generates its own dataset and nucleus has hardcoded numbers such as (657 for steps per epoch calculation, no idea where this number comes from) and other hardcoded values. Also, nucleus has only one class, it doesn't help at all when you want to load multiple classes in your dataset.

All in all, one cannot load the dataset without facing a problem, even if the dataset is coco-style dataset. You usually get an error such as:

`TypeError: list indices must be integers or slices, not str`

I've also tried to use the loader class `coco.py` has, and no luck:

```
def load_components(self, dataset_dir, subset, year=DEFAULT_DATASET_YEAR, class_ids=None,
                  class_map=None, return_coco=False, auto_download=False):
        """Load a subset of the COCO dataset.
        dataset_dir: The root directory of the COCO dataset.
        subset: What to load (train, val, minival, valminusminival)
        year: What dataset year to load (2014, 2017) as a string, not an integer
        class_ids: If provided, only loads images that have the given classes.
        class_map: TODO: Not implemented yet. Supports maping classes from
            different datasets to the same class ID.
        return_coco: If True, returns the COCO object.
        auto_download: Automatically download and unzip MS-COCO images and annotations
        """

        coco = COCO("{}/annotations/instances_{}{}.json".format(dataset_dir, subset, year))
        if subset == "minival" or subset == "valminusminival":
            subset = "val"
        image_dir = "{}/{}{}".format(dataset_dir, subset, year)

        # Load all classes or a subset?
        if not class_ids:
            # All classes
            class_ids = sorted(coco.getCatIds())

        # All images or a subset?
        if class_ids:
            image_ids = []
            for id in class_ids:
                image_ids.extend(list(coco.getImgIds(catIds=[id])))
            # Remove duplicates
            image_ids = list(set(image_ids))
        else:
            # All images
            image_ids = list(coco.imgs.keys())

        # Add classes
        for i in class_ids:
            self.add_class("coco", i, coco.loadCats(i)[0]["name"])

        # Add images
        for i in image_ids:
            self.add_image(
                "coco", image_id=i,
                path=os.path.join(image_dir, coco.imgs[i]['file_name']),
                width=coco.imgs[i]["width"],
                height=coco.imgs[i]["height"],
                annotations=coco.loadAnns(coco.getAnnIds(
                    imgIds=[i], catIds=class_ids, iscrowd=None)))
        if return_coco:
            return coco


```
Can someone help with a generic load function which loads any coco-style dataset? (The examples given such as shapes and nucleus aren't what I am asking for.)

**Comment by kuba-chledowski** [comment]
Hi!

Have you figured out how to use two classes in nucleus? Could please you share some tips with me?

Thanks!

**Comment by remindchobits** [comment]
Hi, I get the same problem too, is there any solution yet?
Thanks !

**Comment by nudro** [comment]
@eyildiz-ugoe I found that using COCO json annotation with RLE (run-length-encoding) works. I initially used one without RLE and faced the same error. After running with RLE, it no longer throws an error and I'm able to generate the masks. 

I'm running Ubuntu 16.04.5 LTS, CUDA 10, Anaconda3. The annotator tool I'm using is the Mac RectLabel Version 2.87. 

<img width="760" alt="Screen Shot 2019-07-16 at 8 00 38 PM" src="https://user-images.githubusercontent.com/26872787/61337760-af8b7a80-a804-11e9-949b-68b33031d03a.png">

**Comment by nnuk** [comment]
Hey @eyildiz-ugoe  did you solve the problem for using coco style dataset json file?
