### ISSUE TITLE
error: module 'keras.engine.topology' has no attribute 'load_weights_from_hdf5_group_by_name'

### ISSUE THREAD

**Issue by captainst** [matterport/Mask_RCNN#703]
Hi there,

I am using tensorflow-gpu 1.8.0 and keras 2.2. (win10)
I followed the installation guide and successfully run the first 2 cells in demo.ipynb in sample folder.

When loading the weights from the 3rd cell, jupyter complained that module 'keras.engine.topology' has no attribute 'load_weights_from_hdf5_group_by_name'. I went to the keras source of topology.py and discovered that indeed probably this python file has been modifed during the latest releases:
https://github.com/keras-team/keras/blob/master/keras/engine/topology.py

How to fix this problem ? 

Many thanks.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-138183a2a830> in <module>()
      3 
      4 # Load weights trained on MS-COCO
----> 5 model.load_weights(COCO_MODEL_PATH, by_name=True)

C:\ProgramData\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py in load_weights(self, filepath, by_name, exclude)
   2117 
   2118         if by_name:
-> 2119             topology.load_weights_from_hdf5_group_by_name(f, layers)
   2120         else:
   2121             topology.load_weights_from_hdf5_group(f, layers)

AttributeError: module 'keras.engine.topology' has no attribute 'load_weights_from_hdf5_group_by_name'

**Comment by engrchrishenry** [comment]
You can follow this pull request #662 to solve your problem. You just need to change 'topology' with 'saving' in model.py as shown in the referenced pull request.

**Comment by captainst** [comment]
@engrchrishenry thanks you very much ! 
The only problem now is that in my case (as shown in the error above), the "model.py" file is located "C:\ProgramData\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py".

But I could only find **mask_rcnn-2.1-py3.6.egg** in that directory. How could I modify the model.py in this case? (do I need to run the installation process again ?)

Thank you again!

**Comment by captainst** [comment]
@engrchrishenry thanks you very much !

Following the instructions provided in #566, after modifying the model.py and re-install the setup.py, the demo.py now works !
