### ISSUE TITLE
Can anybody give me a model trained with nucleus...

### ISSUE THREAD

**Issue by engineer1109** [matterport/Mask_RCNN#707]
My memory is always out.
Training used too much memory. And core dumps.
Can anybody give me a model trained with nucleus?
I want to try to demo.

**Comment by engineer1109** [comment]
GTX 1060 memory out.......

**Comment by fuzzyBatman** [comment]
I know it has been a long time.

[Here](https://goo.gl/V9aD5P) is the model that was trained for 40 epochs, starting with ImageNet weights.

Though, I have not tried using it for inference yet.
Will do later. Let me know if it works for you! :)
