### ISSUE TITLE
model.py line 1272 causes TypeError: only integer arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by radzfoto** [matterport/Mask_RCNN#717]
Running model.py unmodified, called from a custom dataset implementation, results in following error:
```
Traceback (most recent call last):
  File "/home/raul/Mask_RCNN/samples/highwai/hwm.py", line 348, in <module>
    train(model)
  File "/home/raul/Mask_RCNN/samples/highwai/hwm.py", line 164, in train
    image, image_meta, class_ids, bbox, mask = modellib.load_image_gt(dataset_train, config, 0)
  File "/home/raul/Mask_RCNN/mrcnn/model.py", line 1272, in load_image_gt
    class_ids = class_ids[_idx]
TypeError: only integer scalar arrays can be converted to a scalar index

Process finished with exit code 1
```
For reference, I am using Python 3.6.5, TensorFlow 1.8 with nVidia GPU, Keras 2.2.

In line 1270, _idx is a boolean array used to filter out masks (and corresponding class_ids) that have been cropped and no longer contain the portion of the mask that constitutes the object in question. When  applying _idx to the mask array, it works fine because the mask array in a numpy array. However, when the same indexing operation is applied to class_ids, it fails because class_ids is a list, and boolean indexes cannot be used on Python lists.

I have implemented the following code fix (it is deliberately written on several lines for clarity) in my own branch:
```
    # Line below gets this error: TypeError: only integer scalar arrays can be converted to a scalar index
    # class_ids = class_ids[_idx]
    # Changed to:
    class_ids_arr = np.array(class_ids)
    class_ids_arr_filtered = class_ids_arr[_idx]
    class_ids = list(class_ids_arr_filtered)
```
This new code has been tested and does not exhibit this TypeError. There are multiple ways to resolve this error. For example, another way would be to replace line 1272 with a list comprehension.

I have not submitted a pull request with this fix because I cannot find any other bug reports with this error. If someone believes it is important to submit this fix, please let me know and I'll submit a pull request.

**Comment by radzfoto** [comment]
The fix above only worked partially. It turns out that class_ids are used elsewhere and indexed using an array. As a result, I had to modify class_ids to be a numpy array permanently. So the revised fix is:
```
    # Line below gets this error: TypeError: only integer scalar arrays can be converted to a scalar index
    # class_ids = class_ids[_idx]
    # Changed to:
    class_ids_arr = np.array(class_ids)
    class_ids_arr_filtered = class_ids_arr[_idx]
    class_ids = listclass_ids_arr_filtered
```
The code fix is deliberately verbose for clarity. Note that the only change was to modify the last line to NOT convert class_ids into a list, but, rather, to keep it as a numpy array.

**Comment by moorage** [comment]
@radzfoto on your last line, what is `listclass_ids_arr_filtered` exactly?

**Comment by radzfoto** [comment]
@moorage: actually, it looks like you fixed the bug at a different point by converting the list class_ids to an array after the return. I fixed it within the function by returning an array, i.e. listclass_ids_arr_filtered is an array of class ids that's been masked or selected by _idx. I then assign this numpy array to class_ids to return it. Either approach works fine.

**Comment by waleedka** [comment]
The function `Dataset.load_mask()` is expected to return an array of class_ids, rather than a list. It's actually mentioned in the comments, but it would be nice if the code validates it and raises a clearer message.

```
    def load_mask(self, image_id):
        """Generate instance masks for an image.
       Returns:
        masks: A bool array of shape [height, width, instance count] with
            one mask per instance.
        class_ids: a 1D array of class IDs of the instance masks.
        """
```
I'll close this issue since I don't think it's a bug. But I'm happy to merge a pull request that validates class_ids and raises an informative error message.
