### ISSUE TITLE
Restricting gpu for testing

### ISSUE THREAD

**Issue by CptK1ng** [matterport/Mask_RCNN#742]
Hi,

i am trying to run the net together with an open world game. To get playable fps, i need to restrict the gpu which keras is using. Unfortunalety, i cannot find the part in the code where i can adjust the usage of the gpu. 

I would be very appreciated for your help. Thanks.

**Comment by coreywho** [comment]
Don't have a GPU to test this on, but perhaps something adding something like this into the top of train() of model.py would help:

`
sess_config = tf.ConfigProto()
sess_config.gpu_options.per_process_gpu_memory_fraction = self.config.GPU_MEMORY_PERCENT
K.set_session(tf.Session(config=sess_config))
`

**Comment by JoeLogan1981** [comment]
Try this before importing Keras:

```
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="0"
```

Replace the `0` with whichever GPU you want to expose to Keras.  You may need to check in `nvidia-smi` to make sure you are exposing the right one.

**Comment by CptK1ng** [comment]
I solved it by adding these lines before importing keras:

`#----------------Restricitng GPU to 30% -------------
from keras.backend.tensorflow_backend import set_session
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.3
config.gpu_options.visible_device_list = "0"
set_session(tf.Session(config=config))`
