### ISSUE TITLE
save .h5 file

### ISSUE THREAD

**Issue by 123liluky** [matterport/Mask_RCNN#747]
I want save only 0020.h5, 0040.h5, 0060.h5, 0080.h5, ...... instead of every .h5. How can I revise the code? I can't find out corresponding code. Thank you.

**Comment by talhasaruhan** [comment]
Change the checkpoint patience in model.py. I don't remember exact line number but search for callbacks array, it should be there.

**Comment by coreywho** [comment]
Should be line 2325 in model.py.
You should be able to add a `period=20` (or however many epochs between saves) to the ModelCheckpoint callback.

```
        # Callbacks
        callbacks = [
            keras.callbacks.TensorBoard(log_dir=self.log_dir,
                                        histogram_freq=0, write_graph=True, write_images=False),
            keras.callbacks.ModelCheckpoint(self.checkpoint_path,
                                            verbose=0, save_weights_only=True, period=20),
        ]
```

**Comment by 123liluky** [comment]
Thank you!
