### ISSUE TITLE
Number of ROIs per image to feed, why not 512?

### ISSUE THREAD

**Issue by fangwudi** [matterport/Mask_RCNN#76]
In config.py, TRAIN_ROIS_PER_IMAGE = 128  # TODO: paper uses 512
Is there any problem when considering this setting?

**Comment by waleedka** [comment]
The paper suggests a foreground ROIs to background ROIs ratio of 1:3. However, most images contain only a few objects, which means that the number of positive ROIs is often low. For example, if an image has 10 objects and there are 4 ROIs overlapping each object with > 0.5 IoU (i.e. positive) then we have a total of 40 positive ROIs. Then we sample a 80 negative ROIs to maintain the 1:3 ratio for a total of 120 ROIs. 

Based on my experiments, it's very rare for images to have more than 128 ROIs. I'm currently experimenting with reducing the NMS threshold in the ProposalLayer to allow it to generate mover overlapping proposals. This generates about 170 total ROIs on average. I'm yet to figure out how to get close to 512 ROIs per image while maintaining the 1:3 ratio.

**Comment by fangwudi** [comment]
thank you @waleedka

**Comment by Walid-Ahmed** [comment]
@waleedka 
you mentioned "10 objects and there are 4 ROIs overlapping each object with > 0.5 IoU"
in training do not I have only one box per object?, why would I have 4 ROIs overlapping each object
I am starting to get confused if we are talking about training or prediction
Thanks

**Comment by FruVirus** [comment]
@Walid-Ahmed 

During training, we use jittered examples in order to artifically expand our training set. This approach was first mentioned in the original R-CNN paper, Appendix B.
