### ISSUE TITLE
Extracting area from a mask

### ISSUE THREAD

**Issue by MattBarkway** [matterport/Mask_RCNN#765]
I'm looking to use the outputted masks from the model to extract the area of the image taken up by each object mask. 
My issue is that I don't know how to interpret the r['masks'] array, for each mask it appears to be a list of lists with each element being a boolean value. I am not sure how to extract the information I need from this.
If you have any ideas, or know where I should be looking to learn more I'd be very grateful.

**Comment by tanmaypandey7** [comment]
hey @MattBarkway how did you solve it? can you post the solution

**Comment by MattBarkway** [comment]
So the mask is stored as an array of the same size as the image, with True and False as the 'pixel' values. True means that the mask covers that pixel. 
If an image has more than one mask within it, the `r['masks']` array will contain multiple 2-dimensional masks, that you can access individually like so 
`r['masks][:, :, my_mask_number]`.

To get the relative area of a mask you need the number of pixels covered by the mask and the total pixels in the image (but only in 2-dimensions, as we do need to worry about rgb).

To do this I started by getting the relevant image, and initialising an empty 2-dimensional numpy array of the same size.
I then filtered it so that anything outside the mask had a pixel value of zero and and anything within the mask had a value of 255 (the values aren't actually important, so long as they are different). 
`image[mask] = 255`
`image[~mask] = 0`
Then I used an inbuilt numpy method to count the occurrences of the different pixel values in the image
`unique, counts = np.unique(image, return_counts=True)`
from this you get a sorted array of the values in the image and their respective counts.
So the mask area can be calculated as:
`mask_area = counts[1] / (counts[0] + counts[1])`
and then you can multiply it by 100 to get a percentage, or do whatever you want with it.

**Comment by xiongshuai520** [comment]
num = len(r['class_ids'])  how many instance   
print(num)
num_area = []
for i in range(num):
     no_care ,counts = np.unique(r['masks'][:,:,i:i+1].reshape(1,-1), return_counts=True)
     num_area.append(counts[1])
     print(num_area)
in this way,you can get every instance area of pixels

**Comment by Dgs29** [comment]
@MattBarkway I want to find the total number of masks as well as the individual mask areas. Could you please share your code. I'm not sure where to write the above mentioned lines.

**Comment by Dgs29** [comment]
Please let me know where is that **mask** variable (image[mask]) coming from? Also what value do you pass for **my_mask_number** to find the number of total number of masks in image?

**Comment by MattBarkway** [comment]
I was reusing the variable names from https://github.com/matterport/Mask_RCNN/blob/master/samples/demo.ipynb
When you run 
`results = model.detect(image)`
r is equal to
`r = results[0]`
then your masks are at
`r['masks]`
Which if i remember correctly is a big 3d array
the shape is then (y, x, n)
where y and x are the sizes of the mask
and n is the number of masks

I'm going off memory here, so its worth double checking when you run it

**Comment by Dgs29** [comment]
@MattBarkway Thank you so much. I am now able to find number of masks in my image. But I am still unsure about individual mask areas. I have tried to implement based on your idea.

image shape: (716, 6000, 3)
r['masks'] shape: (716, 6000, 27)
Here total number of masks in my image is 27.

for i in range(r['masks'].shape[-1]):
        mask = r['masks'][:, :, i]
        image[mask] = 255
        image[~mask] = 0
        unique, counts = np.unique(image, return_counts=True)
        mask_area = counts[1] / (counts[0] + counts[1])
        print(mask_area*100)

Is this how to do it?
