### ISSUE TITLE
OSError: Unable to open file

### ISSUE THREAD

**Issue by JohnWnx** [matterport/Mask_RCNN#778]
Hi, I'm able to run a training session, can  anyone advise?

Thanks.

(MASKR) john@john-H270N-WIFI:~/Mask_RCNN$ sudo python3 samples/coco/coco.py train --dataset=/path/to/coco/ --model=coco
Using TensorFlow backend.
Command:  train
Model:  coco
Dataset:  /path/to/coco/
Year:  2014
Logs:  /home/logs
Auto Download:  False

Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     2
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.7
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 2
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                93
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'mrcnn_mask_loss': 1.0, 'rpn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'rpn_bbox_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           coco
NUM_CLASSES                    81
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                1000
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001

Loading weights  /home/mask_rcnn_coco.h5
Traceback (most recent call last):
  File "samples/coco/coco.py", line 474, in <module>
    model.load_weights(model_path, by_name=True)
  File "/home/john/Mask_RCNN/samples/coco/mrcnn/model.py", line 2123, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/john/.local/lib/python3.5/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/john/.local/lib/python3.5/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/mask_rcnn_coco.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by rbavery** [comment]
You have `Auto Download: False` set. Have you checked that the weights file
has been downloaded and are you correctly setting the path to that weights
file?

*Ryan Avery*
*Graduate Student, WAVES Lab*
*Department of Geography*
*University of California, Santa Barbara*

*http://caylor.eri.ucsb.edu/people/avery/
<http://caylor.eri.ucsb.edu/people/avery/>*

**Comment by JohnWnx** [comment]
@rbavery I have set dataset path to my downloaded train images from MSCOCO dataset and weights path to mask_rcnn_coco.h5 
However, I'm still getting the error:
OSError: Unable to open file (unable to open file: name = '/home/john/MASK_RCNN/mask_rcnn_coco.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

![image](https://user-images.githubusercontent.com/40804580/42730893-769cca3a-8834-11e8-9819-47c6b07d343d.png)

![image](https://user-images.githubusercontent.com/40804580/42730912-028dd3c2-8835-11e8-9138-e466c47f962c.png)


Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     2
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.7
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 2
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                93
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'mrcnn_class_loss': 1.0, 'mrcnn_mask_loss': 1.0, 'rpn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'rpn_bbox_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           coco
NUM_CLASSES                    81
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                1000
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001


Loading weights  /home/john/MASK_RCNN/mask_rcnn_coco.h5
Traceback (most recent call last):
  File "samples/coco/coco.py", line 474, in <module>
    model.load_weights(model_path, by_name=True)
  File "/home/john/Mask_RCNN/samples/coco/mrcnn/model.py", line 2123, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/john/.local/lib/python3.5/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/john/.local/lib/python3.5/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/john/MASK_RCNN/mask_rcnn_coco.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by rbavery** [comment]
Change MASK_RCNN to Mask_RCNN when you specify the model path.
Capitalization needs to match.

**Comment by artisvirat** [comment]
I am running it on Windows and am getting almost the same error but mine is not able to look for the coco model. This is the error:
error: the following arguments are required: --weights.
Can anyone please provide the balloon.py that they successfully ran on their system. I think it is some kind of linking error.
Thanks

**Comment by ccpwcn** [comment]
> I am running it on Windows and am getting almost the same error but mine is not able to look for the coco model. This is the error:
> error: the following arguments are required: --weights.
> Can anyone please provide the balloon.py that they successfully ran on their system. I think it is some kind of linking error.
> Thanks

It does not support windows system.

**Comment by artisvirat** [comment]
Sorry for the late reply. Thanks for your insight @ccpwcn. I have already run the model successfully and yes it does support windows. The error had nothing to do with that. Thanks Anyway

**Comment by RaXephon** [comment]
@artisvirat Sorry I'm a newbie. Could you tell me what steps you followed to get it to work?

**Comment by artisvirat** [comment]
@RaXephon Hey sorry for the late reply. Where do you need help to make it work?

**Comment by akkshita** [comment]
i getting this error while running nucleus.py


/workspace/Mask_RCNN-master (1)/Mask_RCNN-master/datasets/nucleus
/workspace/Mask_RCNN-master (1)/Mask_RCNN-master
Loading weights  ./mask_rcnn_nucleus.h5

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-8-1f33d0769759> in <module>
     10 # Load weights
     11 print("Loading weights ", weights_path)
---> 12 model.load_weights(weights_path, by_name=True)

/workspace/Mask_RCNN-master (1)/Mask_RCNN-master/mrcnn/model.py in load_weights(self, filepath, by_name, exclude)
   2113         if h5py is None:
   2114             raise ImportError('`load_weights` requires h5py.')
-> 2115         f = h5py.File(filepath, mode='r')
   2116         if 'layer_names' not in f.attrs and 'model_weights' in f:
   2117             f = f['model_weights']

/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    392                 fid = make_fid(name, mode, userblock_size,
    393                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 394                                swmr=swmr)
    395 
    396             if swmr_support:

/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    168         if swmr and swmr_support:
    169             flags |= h5f.ACC_SWMR_READ
--> 170         fid = h5f.open(name, flags, fapl=fapl)
    171     elif mode == 'r+':
    172         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = './mask_rcnn_nucleus.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by DongyingYu** [comment]
> i getting this error while running nucleus.py
> 
> /workspace/Mask_RCNN-master (1)/Mask_RCNN-master/datasets/nucleus
> /workspace/Mask_RCNN-master (1)/Mask_RCNN-master
> Loading weights ./mask_rcnn_nucleus.h5
> 
> OSError Traceback (most recent call last)
> in
> 10 # Load weights
> 11 print("Loading weights ", weights_path)
> ---> 12 model.load_weights(weights_path, by_name=True)
> 
> /workspace/Mask_RCNN-master (1)/Mask_RCNN-master/mrcnn/model.py in load_weights(self, filepath, by_name, exclude)
> 2113 if h5py is None:
> 2114 raise ImportError('`load_weights` requires h5py.')
> -> 2115 f = h5py.File(filepath, mode='r')
> 2116 if 'layer_names' not in f.attrs and 'model_weights' in f:
> 2117 f = f['model_weights']
> 
> /usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py in **init**(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
> 392 fid = make_fid(name, mode, userblock_size,
> 393 fapl, fcpl=make_fcpl(track_order=track_order),
> --> 394 swmr=swmr)
> 395
> 396 if swmr_support:
> 
> /usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
> 168 if swmr and swmr_support:
> 169 flags |= h5f.ACC_SWMR_READ
> --> 170 fid = h5f.open(name, flags, fapl=fapl)
> 171 elif mode == 'r+':
> 172 fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
> 
> h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
> 
> h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
> 
> h5py/h5f.pyx in h5py.h5f.open()
> 
> OSError: Unable to open file (unable to open file: name = './mask_rcnn_nucleus.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)



> Hi, I'm able to run a training session, can anyone advise?
> 
> Thanks.
> 
> (MASKR) john@john-H270N-WIFI:~/Mask_RCNN$ sudo python3 samples/coco/coco.py train --dataset=/path/to/coco/ --model=coco
> Using TensorFlow backend.
> Command: train
> Model: coco
> Dataset: /path/to/coco/
> Year: 2014
> Logs: /home/logs
> Auto Download: False
> 
> Configurations:
> BACKBONE resnet101
> BACKBONE_STRIDES [4, 8, 16, 32, 64]
> BATCH_SIZE 2
> BBOX_STD_DEV [0.1 0.1 0.2 0.2]
> COMPUTE_BACKBONE_SHAPE None
> DETECTION_MAX_INSTANCES 100
> DETECTION_MIN_CONFIDENCE 0.7
> DETECTION_NMS_THRESHOLD 0.3
> FPN_CLASSIF_FC_LAYERS_SIZE 1024
> GPU_COUNT 1
> GRADIENT_CLIP_NORM 5.0
> IMAGES_PER_GPU 2
> IMAGE_MAX_DIM 1024
> IMAGE_META_SIZE 93
> IMAGE_MIN_DIM 800
> IMAGE_MIN_SCALE 0
> IMAGE_RESIZE_MODE square
> IMAGE_SHAPE [1024 1024 3]
> LEARNING_MOMENTUM 0.9
> LEARNING_RATE 0.001
> LOSS_WEIGHTS {'mrcnn_mask_loss': 1.0, 'rpn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'rpn_bbox_loss': 1.0}
> MASK_POOL_SIZE 14
> MASK_SHAPE [28, 28]
> MAX_GT_INSTANCES 100
> MEAN_PIXEL [123.7 116.8 103.9]
> MINI_MASK_SHAPE (56, 56)
> NAME coco
> NUM_CLASSES 81
> POOL_SIZE 7
> POST_NMS_ROIS_INFERENCE 1000
> POST_NMS_ROIS_TRAINING 2000
> ROI_POSITIVE_RATIO 0.33
> RPN_ANCHOR_RATIOS [0.5, 1, 2]
> RPN_ANCHOR_SCALES (32, 64, 128, 256, 512)
> RPN_ANCHOR_STRIDE 1
> RPN_BBOX_STD_DEV [0.1 0.1 0.2 0.2]
> RPN_NMS_THRESHOLD 0.7
> RPN_TRAIN_ANCHORS_PER_IMAGE 256
> STEPS_PER_EPOCH 1000
> TOP_DOWN_PYRAMID_SIZE 256
> TRAIN_BN False
> TRAIN_ROIS_PER_IMAGE 200
> USE_MINI_MASK True
> USE_RPN_ROIS True
> VALIDATION_STEPS 50
> WEIGHT_DECAY 0.0001
> 
> Loading weights /home/mask_rcnn_coco.h5
> Traceback (most recent call last):
> File "samples/coco/coco.py", line 474, in
> model.load_weights(model_path, by_name=True)
> File "/home/john/Mask_RCNN/samples/coco/mrcnn/model.py", line 2123, in load_weights
> f = h5py.File(filepath, mode='r')
> File "/home/john/.local/lib/python3.5/site-packages/h5py/_hl/files.py", line 312, in **init**
> fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
> File "/home/john/.local/lib/python3.5/site-packages/h5py/_hl/files.py", line 142, in make_fid
> fid = h5f.open(name, flags, fapl=fapl)
> File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> File "h5py/h5f.pyx", line 78, in h5py.h5f.open
> OSError: Unable to open file (unable to open file: name = '/home/mask_rcnn_coco.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I meet the same probolem. Could you please tell what you do to solve this problem？Thank you very much!

**Comment by Akash481** [comment]
I faced the same issue. Instead of just putting the file name, I replaced it with the full directory address. Worked for me.

**Comment by chhigansharma** [comment]
Hi I'm facing similar issue with tensorflow 2.3 version, I have tried all possible solutions but didn't worked

**Comment by chhigansharma** [comment]
OSError: Unable to open file #2677 

Please have a look at this issue for more info.

Regards
