### ISSUE TITLE
Problem on  training on 2 classes (including background).

### ISSUE THREAD

**Issue by Walid-Ahmed** [matterport/Mask_RCNN#78]
I am trying to train on 2 classes (including background).

`NUM_CLASSES = 1 + 1 
`
The problem is that I can't load the starting coco weights any  more as I get the following error:-

> ValueError: Dimension 1 in both shapes must be equal, but are 8 and 324 for 'Assign_682' (op: 'Assign') with input shapes: [1024,8], [1024,324].

if I change the line` NUM_CLASSES = 80 + 1 ` , loading of weights is successful.

should something else be changed?
Thanks

**Comment by Walid-Ahmed** [comment]
Solved when  loaded the weights as follows:-
`    model.load_weights(model_path, by_name=True,exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", "mrcnn_bbox", "mrcnn_mask"])`

**Comment by AlexTS1980** [comment]
Thanks. What was the trick? And why these specific layers? Judging by other inputs, the problem should be with Keras/TF version and the order or dimensions.
