### ISSUE TITLE
Balloon Tutorial: inspect_balloon_model.ipynb bug

### ISSUE THREAD

**Issue by eljirg** [matterport/Mask_RCNN#783]
Hi I am trying to learn the mask rcnn using balloon tutorial, however there are parts of the tutorial that I can't replicate even though i use the code straight from the repo.

The parts where I encounter the issue are these:
1. Show top anchors with refinement. Then with clipping to image boundaries
2. Show refined anchors after non-max suppression

Both of them show only the original image and no box at all. Is there something that is incorrect here?

Thx!

**Comment by keineahnung2345** [comment]
The reason why is doesn't show any boxes is that visualize.draw_boxes() takes image coordinates as arguments, however the example passed in normalized coordinates.
Take 1.b RPN Predictions as an demonstration, here's my workaround:

`#revised
h, w = config.IMAGE_SHAPE[:2]
pre_nms_anchors = rpn["pre_nms_anchors"][0, :limit] * np.array([h, w, h, w])
refined_anchors = rpn["refined_anchors"][0, :limit] * np.array([h, w, h, w])
refined_anchors_clipped = rpn["refined_anchors_clipped"][0, :limit] * np.array([h, w, h, w])

# Show top anchors with refinement. Then with clipping to image boundaries
limit = 50
ax = get_ax(1, 2)
visualize.draw_boxes(image, boxes=pre_nms_anchors, 
           refined_boxes=refined_anchors, ax=ax[0])
visualize.draw_boxes(image, refined_boxes=refined_anchors_clipped, ax=ax[1])`

**Comment by eljirg** [comment]
Thx for the help!

**Comment by keineahnung2345** [comment]
I have sent a pull request fixing this bug. 
https://github.com/matterport/Mask_RCNN/pull/876
