### ISSUE TITLE
Imbalance  data and augmentation only 3 classes in data

### ISSUE THREAD

**Issue by maycuatroi** [matterport/Mask_RCNN#787]
I got an Imablance data trouble ( 1 of classes have too many) .
First, I try to augmentation another classes to improve another classes data
How can I setting augmentation only selected classes ?
👍

**Comment by aegorfk** [comment]
Did you try something like tf.nn.weighted_cross_entropy_with_logits?
Because if you have images with many classes on the picture, I guess, you need to exclude the polygons for another classes from annotation and them augment.
