### ISSUE TITLE
I have an unannotated .jpg dataset of 1000 images how do i convert that  to coco format

### ISSUE THREAD

**Issue by artisvirat** [matterport/Mask_RCNN#789]
I also have looked through all the issues in this repository and did not find find even one that was informative and in detail. LabelMe doesn't really work for the issue.

**Comment by darrell-rg** [comment]
I followed this example using vgg image annotator and it worked for me. https://engineering.matterport.com/splash-of-color-instance-segmentation-with-mask-r-cnn-and-tensorflow-7c761e238b46

**Comment by artisvirat** [comment]
@darrell-rg Did you get the exact format needed, the exact one like MS COCO?

**Comment by cardboardcode** [comment]
@artisvirat 
Give this a try. 
https://github.com/Deep-Magic/COCO-Style-Dataset-Generator-GUI/

**Comment by artisvirat** [comment]
Done using VIA.
