### ISSUE TITLE
Square shapes get bad mask prediction results

### ISSUE THREAD

**Issue by yenlianglintw** [matterport/Mask_RCNN#80]
I run with the example code in train_shapes.ipynb. It works fine with triangle and circle. However, it gets wrong mask prediction results on the square category (bounding boxes look OK). The errors seems to be caused by USE_MINI_MASK.

**Comment by waleedka** [comment]
I'm curious, how did you solve the problem? I noticed you closed the issue.

**Comment by yenlianglintw** [comment]
Hi Waleed,

I found that there is a small bug in the function: minimize_mask and
expand_mask (in utils.py)

The imresize functions will generate all zeros (m variables) for the square
shapes. Therefore, I modify the image resize function to:
m = scipy.misc.imresize(m.astype(float)*255, mini_shape,
interp='bilinear',mode='F')

The shape example works good now.

Thanks,
Yenliang


2017-11-27 16:37 GMT-05:00 Waleed <notifications@github.com>:

**Comment by waleedka** [comment]
Thanks for catching that. I'll push a fix for it.
