### ISSUE TITLE
Images with more than 3 channels

### ISSUE THREAD

**Issue by mehditlili** [matterport/Mask_RCNN#800]
Hi, I am still trying to read and understand the papers and the structure of the trained network. Mask RCNN trained on COCO is already showing promising results on my data but I was wondering how complicated it would be to present images as input augmented with a fourth channel (depth image). Would that require retraining the whole network or even changing the network's structure?

**Comment by rbavery** [comment]
Check this out, the wiki has some guidelines for including more channels at the bottom: https://github.com/matterport/Mask_RCNN/wiki

One step it neglects to mention is that you will need to change part of the `build` function in mrcnn/model.py. I changed the `input_image` variable to accept an arbitrary number of channels that is passed in the config class:         
```
# Inputs, changed from original mrcnn to allow variable channels besides 3
        input_image = KL.Input(
            shape=[None, None, config.CHANNELS_NUM], name="input_image")
```

**Comment by mehditlili** [comment]
Thanks for the hint,
I tried doing it following the wiki and what you mentioned but I still have some troubles loading my pretrained model.
After excluding the layer 'input_image' it complains about the second layer:

`ValueError: Layer #2 (named "conv1"), weight <tf.Variable 'conv1_3/kernel:0' shape=(7, 7, 4, 64) dtype=float32_ref> has shape (7, 7, 4, 64), but the saved weight has shape (64, 3, 7, 7).`

**Comment by rbavery** [comment]
It looks like you are trying to use pretrained weights from Imagenet or Coco, which are 3 channel datasets. Should have specified in my earlier comment, but you can't use pretrained weights if your input data has a different number of channels that the pretrain dataset. At least, not without changing more of the underlying mrcnn code. These code changes will only allow you to train from scratch on your data.

Since most large image datasets are RGB and most satellite remote sensing datasets have RGB plus Near-Infrared, it'd be fantastic to be able to start from 3 channel pretrain weights with inputs of more than 3 channels. If anybody has suggestions on how to do this please comment! I'm pretty new to CNNs so advice is much appreciated.

**Comment by mehditlili** [comment]
I deleted the second channel, conv1 instead of the first channel and it seems to be training fine, was just a fast try, not sure if only the second layer was remove or all layers called conv1

**Comment by moorage** [comment]
I second doing both:

In `model.py` , in the `def build` function:
```
        input_image = KL.Input(
            shape=[None, None, config.IMAGE_SHAPE[2]], name="input_image")
```

```
model.load_weights(weights_path, by_name=True, exclude=[
                "mrcnn_class_logits", "mrcnn_bbox_fc",
                "mrcnn_bbox", "mrcnn_mask", "conv1"])
```

**Comment by moorage** [comment]
I also issued a related PR https://github.com/matterport/Mask_RCNN/pull/940

**Comment by moorage** [comment]
@lunasdejavu I just did `layers='all'` , see https://github.com/moorage/Mask_RCNN/blob/master/samples/greppy/greppy.py#L365-L368

**Comment by lunasdejavu** [comment]
@moorage  thanks because I wrote the code from sample/train_shapes.py
it trains 'heads' first then 'all'.
But I am not sure what is the difference between training layers separately and training all for once?

**Comment by saskra** [comment]
> May I ask you how to include Conv1 please? I am trying to use the grayscale image 2448x2048

> @moorage thanks because I wrote the code from sample/train_shapes.py
> it trains 'heads' first then 'all'.
> But I am not sure what is the difference between training layers separately and training all for once?

I also have these two questions. Can anyone help?

**Comment by avnerst1** [comment]
> Thanks for the hint, I tried doing it following the wiki and what you mentioned but I still have some troubles loading my pretrained model. After excluding the layer 'input_image' it complains about the second layer:
> 
> `ValueError: Layer #2 (named "conv1"), weight <tf.Variable 'conv1_3/kernel:0' shape=(7, 7, 4, 64) dtype=float32_ref> has shape (7, 7, 4, 64), but the saved weight has shape (64, 3, 7, 7).`

I am using grayscale images with one channel to train my model. I've uploaded the coco pre-trained weights and excluded all the layers as specified above, and was able to train the model and get the new weights. I still get the error you've specified when trying to load the new weights I've received from training to getting predictions from new photos.
this is the code I use for loading the weights and prediction:
`model = MaskRCNN(mode='inference', model_dir='./', config=cfg)
model.load_weights(model_path, by_name=True)`
have any ideas?
