### ISSUE TITLE
Structure of mask ?

### ISSUE THREAD

**Issue by haixoay96** [matterport/Mask_RCNN#81]
I want to nkow struct return method load_mask , i have 1 image size 2592x4068 and object with boxdingbox xmin: 279 ymin:723 xmax:2431 ymin2784 . I see masks : A bool array of shape [height, width, instance count] . i was confused . please give me good explain

**Comment by MatinHz** [comment]
load_mask returns `[height, width, number of instances] `, which each instance is a binary **mask** for one object, not its bounding box.
