### ISSUE TITLE
Training on pretrained weights leads to a ValueError

### ISSUE THREAD

**Issue by CptK1ng** [matterport/Mask_RCNN#811]
Hi there,
i trained the heads of the coco pretrained resnet 101. My dataset includes masks and i bring them into the correct form of [height, width, objects]. Training runs without errors on 1080TI for 40 Epochs with 200 step size. 
Now i want to test the new model but got the following error:

```ValueError: Layer #391 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 324) dtype=float32_ref> has shape (1024, 324), but the saved weight has shape (1024, 132).```

i have no idea why i got this error. The dataset i used for training have 32 classes instead of the 80 coco and i didn't changed anything in the model definition in MASK_RCNN - class.

**Comment by CptK1ng** [comment]
Problem solved. I used the false dataset config in InferenceConfig

**Comment by harshitha1989** [comment]
Could you tell me in detail where you have used false dataset config ,since I'm also facing this issue?

**Comment by LackesLab** [comment]
I am sorry, this was one year ago. I already stopped working with this network and i do not remember how i solved it.
