### ISSUE TITLE
How to use balloon.py for multiple classes?

### ISSUE THREAD

**Issue by knnrhml** [matterport/Mask_RCNN#818]
Balloon example considers only one class - balloon, how can I modify it to work with multiple classes?

**Comment by baolinliu** [comment]
https://github.com/SUYEgit/Surgery-Robot-Detection-Segmentation/blob/master/surgery.py shows you how

**Comment by knnrhml** [comment]
amazing! thanks you so much

**Comment by knnrhml** [comment]
Hi, any idea how a dataset should look like for multi-classes? I can't figure out how to add class names in VIA tool. Thanks

**Comment by baolinliu** [comment]
I use this version, https://www.robots.ox.ac.uk/~vgg/software/via/via-1.0.6.html

**Comment by knnrhml** [comment]
me too, for one class, you just keep adding annotations, the class name is defined in the code, how about multi-class mode? Where do I add the class names in the VIA tool?

**Comment by baolinliu** [comment]
I don't, I assign a number and keep track of it

**Comment by knnrhml** [comment]
can you give me an example?

**Comment by knnrhml** [comment]
```
        self.add_class("surgery", 1, "arm")
        self.add_class("surgery", 2, "ring")
```

I see you are assigning arm to 1 and ring to 2, but for exmaple if you have two arms in the images and you annotated them, they would be 1 and 2, therefore it would classify them wrong. Am I missing something?

**Comment by baolinliu** [comment]
anything that is an arm would be a 1, anything that is a ring would be 2.  This is not my code by the way.  I got it to work too, but in my own way.

**Comment by knnrhml** [comment]
can you send me an example from your .json file?

**Comment by baolinliu** [comment]
should come out as an array of numbers like [1,1,2,2,2,1,1,] that's all I can tell you.

**Comment by knnrhml** [comment]
Thanks, I won't use it, but I took your idea of using numbers as references. That's cool. Thank you.

Did you try the inspect_dataset with your code? I am running into this error:

`ERROR:root:Error processing image {'id': 'image4.png', 'source': 'surgery', 'path': '/home/ec2-user/SageMaker/setUpEnv/Mask_RCNN/datasets/balloon/train/image4.png', 'width': 1920, 'height': 1080, 'polygons': [{'name': 'polygon', 'all_points_x': [637, 1016, 1074, 725, 652, 637], 'all_points_y': [86, 647, 619, 16, 47, 86]}, {'name': 'polygon', 'all_points_x': [1119, 998, 1012, 1078, 1119], 'all_points_y': [164, 125, 279, 314, 164]}], 'names': [{'name': 'a'}, {'name': 'r'}]}
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/setUpEnv/Mask_RCNN/mrcnn/model.py", line 1736, in data_generator
    rpn_rois, gt_class_ids, gt_boxes, gt_masks, config)
  File "/home/ec2-user/SageMaker/setUpEnv/Mask_RCNN/mrcnn/model.py", line 1318, in build_detection_targets
    gt_class_ids.dtype)
AssertionError: Expected int but got int64`

Should I open a new issue for this?

**Comment by knnrhml** [comment]
well, not really what I was asking. I ended up using something else. But thanks for the idea of assigning numbers to classes. I will use it, thank you.

**Comment by whl0753** [comment]
could you please give me an example about you via's files?I made it,but it had some probelms in the file,i want to compare our json files to fina my problems.Thank you very much.

**Comment by amandalmia14** [comment]
@baolinliu Can you please share the sample json file of your work. 
@knnrhml were you able to solve it?
Thanks
