### ISSUE TITLE
level_boxes are in the input image coordinate spaces which are different from the feature maps, is the crop_and_resize operation correct here?

### ISSUE THREAD

**Issue by TinyJie** [matterport/Mask_RCNN#83]

**Comment by jimeffry** [comment]
@TinyJie @waleedka 
I had the same question some time ago. Now , in my opinion, the normalization is used for boxes in PyramidROIAlign. [ ( anchors_boxes/ feature_stride) / (input_image_shape/ feature_stride) == feature_boxes / feature_shape ]. Is it right?
