### ISSUE TITLE
BBOX_STD_DEV for what?

### ISSUE THREAD

**Issue by fangwudi** [matterport/Mask_RCNN#85]
May I ask a question, maybe silly. 
What's the point for RPN_BBOX_STD_DEV and BBOX_STD_DEV in config.py? And where the value come from?

**Comment by ppwwyyxx** [comment]
Fast R-CNN Section 2.3.

**Comment by fangwudi** [comment]
thanks I will check it out @ppwwyyxx

**Comment by Yolanda-FuTengYu** [comment]
@ppwwyyxx hi! Do you know the means of RPN_BBOX_STD_DEV and BBOX_STD_DEV now? I read the paper of Fast R-CNN, but have no answers

**Comment by ppwwyyxx** [comment]
> The hyper-parameter λ in Eq. 1 controls the balance between
the two task losses. We normalize the ground-truth
regression targets vi
to have zero mean and unit variance.
All experiments use λ = 1.

**Comment by Yolanda-FuTengYu** [comment]
thanks! @ppwwyyxx
