### ISSUE TITLE
Predict stuck when I serve this model with Flask

### ISSUE THREAD

**Issue by wangke1003** [matterport/Mask_RCNN#850]
First, thanks for sharing this amazing model and i learn a lot from it.
Briefly, my trouble is that predict seems just work after the model is loaded and not work for next coming requests. 
I use a class to load the model. The test detecting inside `init` method works well.
```
import cv2
import mrcnn.model as modellib
from mrcnn.config import Config
import tensorflow as tf

class MyService:

    def __init__(self):
        self.graph = tf.get_default_graph()
        with self.graph.as_default():
            self.config = Config()
            self.model = 
                   modellib.MaskRCNN(mode="inference", config=self.config, model_dir="logs")
            self.model.load_weights(self.config.WEIGHTS_PATH, by_name=True)
        
        test_img = cv2.imread('test.jpg')
        # detecting works here
        self.detect(test_img)

    def detect(self, image):
        with self.graph.as_default():
            r = self.model.detect([image], verbose=1)[0]
        ....
```
I import this class in a flask script like this and run it with a uwsgi server.
```
from flask import Flask, jsonify, request, make_response
from service import MyService
import numpy as np
import cv2

app = Flask(__name__)
service = MyService()

@app.route('/test', methods=['POST'])
def test_method():
    img = cv2.imread("test.jpg")
    
    # this detect cannot get return
    result = service.detect(img)
    
    return jsonify(result)
```
I tried many times and every result is the same: only detecting inside `init` can work. I figure out by printing logs that image data is stuck at the `predict` method of the Keras model, in `mrcnn.model.py`.
```
class MaskRCNN():
    ...
    def detect(...):
        ...
        # stuck here
        detections, _, _, mrcnn_mask, _, _, _ =\
            self.keras_model.predict([molded_images, image_metas, anchors], verbose=0)
        ...
``` 
Am I serve the model in wrong way or it's a bug of Keras?
Because I'm new in ML and English is not my first language, this issue may be silly.
Thanks for your reading, anyway. I'd be quite appreciated if anyone can help.

**Comment by waspinator** [comment]
This might be the same issue:

https://github.com/keras-team/keras/issues/2397

I got it to work by calling on a dummy input when I initialize the api

    def __init__(self):

        self.inference_config = ModelConfig()

        self.model = modellib.MaskRCNN(mode="inference", 
                                config=self.inference_config,
                                model_dir=MODEL_DIR)

        self.model_path = self.model.find_last()[1]
        self.model.load_weights(self.model_path, by_name=True)

        dummy_input = Image.new('RGB', (256, 256))
        self.detect(dummy_input)

**Comment by wangke1003** [comment]
@waspinator Thanks for your kind reply! I've tried the method you describe actually and it didn't work for me. Thanks anyway. I'll close the issue.

**Comment by Nitin286roxs** [comment]
i am also facing same problem at 
keras_model.predict([molded_images, image_metas, anchors], verbose=0)?
