### ISSUE TITLE
can't continue with the last weights

### ISSUE THREAD

**Issue by kalanka29** [matterport/Mask_RCNN#863]
I edited `balloon.py` (following this: [https://github.com/matterport/Mask_RCNN/issues/372](url) ) and use it for multi classes. It took half a day to train (20 images for both training set and validating set) and i manually stoped the training. But after that I can't continue with this command 
`python3 neural_code.py train --dataset=../../datasets/screens --weights=../../logs/test20180816T1444`

**Note that:**  test20180816T1444 is the file saved after training in `logs` directory
                       and my laptop's specs:
                       intel core i5 (4th gen) ,8gb ram
                       nvidia geforce 830M (2gb) 256 cuda cores

And now I cannot start the training again from the beginning.

`python3 neural_code.py train --dataset=../../datasets/screens --weights=coco`

It give this error  

`Traceback (most recent call last):`
  `File "/home/scit/anaconda3/lib/python3.6/site-packages/theano/tensor/type.py", line 269, in ``dtype_specs`
   ` }[self.dtype]`
`KeyError: "<dtype: 'int32'>"`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
  `File "neural_code.py", line 427, in <module>
    model_dir=args.logs)`
  `File "/home/scit/Desktop/My_work/object_detection/mask_rcnn/mrcnn/model.py", line 1845, in __init__
    self.keras_model = self.build(mode=mode, config=config)`
  `File "/home/scit/Desktop/My_work/object_detection/mask_rcnn/mrcnn/model.py", line 1870, in build
    shape=[None, 1], name="input_rpn_match", dtype=tf.int32)`
  `File "/home/scit/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 1439, in Input
    input_tensor=tensor)`
 ` File "/home/scit/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)`
  `File "/home/scit/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 1348, in __init__
    name=self.name)`
  `File "/home/scit/anaconda3/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 234, in placeholder`
    `x = T.TensorType(dtype, broadcast)(name)`
 ` File "/home/scit/anaconda3/lib/python3.6/site-packages/theano/tensor/type.py", line 51, in __init__
    self.dtype_specs()  # error checking is done there`
  `File "/home/scit/anaconda3/lib/python3.6/site-packages/theano/tensor/type.py", line 272, in dtype_specs`
  `  % (self.__class__.__name__, self.dtype))`
`TypeError: Unsupported dtype for TensorType: <dtype: 'int32'>
`
What may be the case here

**Comment by ashuta03** [comment]
To continue training from the latest checkpoint you need to provide the full absolute path of the checkpoint file, not just the log directory in which the checkpoint was saved. 
for e.g.:
 `python3 neural_code.py train --dataset=../../datasets/screens --weights=../../logs/test20180816T1444/mask_rcnn_ship_0005.h5 `
This should probably address your first problem for pre-trained weights.

**Comment by kalanka29** [comment]
@ashuta03 :but it is having just a `binary` file...Is it the checkpoint file? I was bit confused to use that cuz it was not in `.h5` format

**Comment by ashuta03** [comment]
If you have trained your model correctly then inside the `logs` folder, there should be checkpoint files (one for each epoch) in `.h5` format. In your case, if `test20180816T1444` is the correct directory then, inside this directory, you should have your checkpoint files. Multiple directories inside logs folder are created for each new training session. so, you can inspect the folders and find out the latest checkpoint file.

**Comment by kalanka29** [comment]
@ashuta03 :+1: Yes, you are correct. It will save a `.h5` file in `logs` directory for each epoch in  separate folders

**Comment by avnerst** [comment]
> 

hey, I have tried to load my weights in the same way but I'm getting this error:
`ValueError: Layer #362 (named "anchors"), weight <tf.Variable 'Variable:0' shape=(4, 261888, 4) dtype=float32> has shape (4, 261888, 4), but the saved weight has shape (2, 261888, 4).`
do you have any idea what I'm doing wrong>
I have explained in more detail in [this issue](https://github.com/matterport/Mask_RCNN/issues/2842)
please let me know if you can help.
thanks!

> To continue training from the latest checkpoint you need to provide the full absolute path of the checkpoint file, not just the log directory in which the checkpoint was saved. for e.g.: `python3 neural_code.py train --dataset=../../datasets/screens --weights=../../logs/test20180816T1444/mask_rcnn_ship_0005.h5 ` This should probably address your first problem for pre-trained weights.
