### ISSUE TITLE
Systematic analysis of the multi GPU problem

### ISSUE THREAD

**Issue by maxfrei750** [matterport/Mask_RCNN#875]
Hello everybody,
along with others (@waleedka, @ericj974, @schmidje, @liangbo-1, @dil, @kmh4321, @zgxsin, @YubinXie, @pieterbl86), I'm searching for the solution to the problem that the use of multiple GPUs can have a severely negative impact on the training speed (see #589, #676, #708, #710). There are however users, who claim that they are running or have run configurations, which don't have this problem. Therefore I'd like to make a poll how many users are affected by this problem.

### Poll: I already encountered a configuration, with which I was able to train _significantly_ faster on multiple GPUs than on a single GPU.
[![](https://api.gh-polls.com/poll/01CNBR2307K85882J5MMK81PGT/yes)](https://api.gh-polls.com/poll/01CNBR2307K85882J5MMK81PGT/yes/vote)
[![](https://api.gh-polls.com/poll/01CNBR2307K85882J5MMK81PGT/no)](https://api.gh-polls.com/poll/01CNBR2307K85882J5MMK81PGT/no/vote)

Obviously, the poll alone does not help too much. Therefore, I'd like to gather working and non-working configurations. Please include the following information in your post:
- Did it work?
- Number of GPUs (GPU_COUNT)
- Number of images per GPU (IMAGES_PER_GPU)
- utilized script (e.g. train_shapes.ipynb)
- GPU model(s)
- OS
- CUDA version
- cuDNN version
- Driver version
- Mask-RCNN version (URL of the repo and hash specifying the state of the repo)
- Tensorflow version
- Keras version
- approx. speed up

Thank you very much for your help.

**Comment by maxfrei750** [comment]
- **Did it work?**
**no**
- Number of GPUs (GPU_COUNT)
2
- Number of images per GPU (IMAGES_PER_GPU)
1
- utilized script
train_shapes.ipynb
- GPU model(s)
2 x GTX1080
- OS
Ubuntu 16.04
- CUDA version
9.0.176
- cuDNN version
7.1.4.18
- Driver version
384.130
- Mask-RCNN version (URL of the repo and hash specifying the state of the repo)
URL: https://github.com/matterport/Mask_RCNN
Commit: 41e7c596ebb83b05a4154bb0ac7a28e0b9afd017
- Tensorflow version
1.10
- Keras version
2.1.3
- approx. speed up
-33%

**Comment by maxfrei750** [comment]
- **Did it work?**
**sort of**
- Number of GPUs (GPU_COUNT)
2
- Number of images per GPU (IMAGES_PER_GPU)
1
- utilized script
train_shapes.ipynb
- GPU model(s)
2 x GTX1080
- OS
Ubuntu 16.04
- CUDA version
9.0.176
- cuDNN version
7.1.2.21
- Driver version
384.130
- Mask-RCNN version (URL of the repo and hash specifying the state of the repo)
URL: https://github.com/ericj974/Mask_RCNN
Commit: 638ad2f399cbc67cfddf01ba69e0a23435010905
- Tensorflow version
1.8
- Keras version
2.1.6
- speed (1 GPU):
2 s/step
- speed (2 GPUs):
337 s/step

- comment:
higher speed with 2 GPUs than with 1 GPU for this particular configuration, but still not superior to the fastest 1 GPU configuration

**Comment by YubinXie** [comment]
Could it be possible that 2 GPUs in this MasRCNN means 'double' training?

**Comment by maxfrei750** [comment]
@YubinXie Thanks for joining the discussion! What do you mean by 
> 'double' training

?

Do you mean a training using double instead of single values as the datatype? That's an interesting idea but I really don't think so. The corresponding code definitively has to do something with parallelisation. Apart from that there are people who set GPU_COUNT to higher numbers than 2 (e.g. 4).

**Comment by maxfrei750** [comment]
I just saw that someone actually voted _yes_ in the poll. Obviously, it would be really interesting to get hints concerning the configuration that was used. So dear stranger, please share your precious knowledge with us. 

Unless of course you were only trolling... if so, then your GPU may melt instantly and die a fiery death. 🔥 😈

**Comment by YubinXie** [comment]
Oh, I meant 'the amount of training' is doubled. I saw smaller loss after one epoch with 2 GPU than 1 GPU.

**Comment by maxfrei750** [comment]
@YubinXie Ah ok, I see... I'm a numpty. 😅 Well that would be very interesting. I'm gonna see if I can find supporting evidence for your theory tomorrow.

**Comment by dil** [comment]
- Did it work?
No
- Number of GPUs (GPU_COUNT)
2
- Number of images per GPU (IMAGES_PER_GPU)
1
- utilized script
https://github.com/ericj974/Mask_RCNN/commit/638ad2f399cbc67cfddf01ba69e0a23435010905
- GPU model(s)
4 x GeForce GTX 1080
- OS
Ubuntu 16.04.3 LTS
- CUDA version
9.0.176
- cuDNN version
7.0.5
- Driver version
390.30
- Mask-RCNN version
URL: https://github.com/ericj974/Mask_RCNN/commit/638ad2f399cbc67cfddf01ba69e0a23435010905
- Tensorflow version
tensorflow_gpu==1.7.0
- Keras version
2.1.6
- speed (1 GPU)
5s/step
- speed (2 GPUs)
6s/step

**Comment by maxfrei750** [comment]
@dil Thanks for contributing! I saw that you have 4 GPUs available. It would be great if you ran the test also on 3 and 4 GPUs and added the results. Maybe we can extract some info from the scaling behaviour as well.

**Comment by schmidje** [comment]
-  Did it work?
nope
-     Number of GPUs (GPU_COUNT)
4 (also reported for 2, see speed up section)
-     Number of images per GPU (IMAGES_PER_GPU)
I tried various combinations like I reported in issue #589, so I stick with 1 images per gpu which is also theoretically a waste.
-     utilized script: 
custom derived from example in train_shapes.ipynb. Masks are preloaded in memory.
-     GPU model(s)
GeForce GTX 1080 8 GB
-     OS
Linux rhel 7
-     CUDA version
9.2.88.1
-     cuDNN version
7.1.4
-     Driver version
396.26
-     Mask-RCNN version (URL of the repo and hash specifying the state of the repo)
repo; https://github.com/matterport/Mask_RCNN
hash: 6c9c82f5feaf5d729a72c67f33e139c4bc71399b
I also tried recently with a new version of the repo which made several changes. Things did not really improved and I needed to temporarily disable stuff in my code (which has not impact on the training, only on the evaluation stage), so I came back to the version of the hash.
-     Tensorflow version
1.8.0
-     Keras version
2.1.6
-     approx. speed up
single GPU vs 2 GPUs speed-up: 1.2x (i.e. single GPU faster)
single GPU vs 4 GPUs speed-up: 1.7x

**Comment by maxfrei750** [comment]
@schmidje Thanks for contributing your results and insights so far! It's nice to see that so many people are willing to put effort in this topic. Could you do me a favor and reformat your post a little, so that it matches the structure of the other posts a little more, making it easier to compare all the configurations? Thanks in advance.

@YubinXie I had a look at this phenomenon you mentioned 
> Oh, I meant 'the amount of training' is doubled. I saw smaller loss after one epoch with 2 GPU than 1 GPU.

using the configuration I described here: https://github.com/matterport/Mask_RCNN/issues/875#issuecomment-414343272

It seems that you are actually right, in so far as that the loss is smaller when training with 2 GPUs:
1 GPU: loss = 2.309 ± 0.007 (3 runs)
2 GPUs: loss = 2.061 ± 0.1365 (3 runs)

However, I'm not too sure about how to interpret this.

Another thing I just saw is that the `STEPS_PER_EPOCH` can severely influence the measured speed, due to the fact that the relative overhead gets bigger for smaller numbers of `STEPS_PER_EPOCH`. Therefore, the default value of `STEPS_PER_EPOCH=100` in `train_shapes.ipynb` might be to small to measure accurate speeds.

Example 1 (again using this configuration: https://github.com/matterport/Mask_RCNN/issues/875#issuecomment-414343272):

|   | 100 steps/epoch | 1000 steps/epoch  |
| ------------- | ------------- |------------- |
| **1 GPU** | 0.376 s/step | 0.145 s/step |
| **2 GPUs**  | 0.572 s/step  | 0.197 s/step |

Example 2 (this time using the most promising configuration so far: https://github.com/matterport/Mask_RCNN/issues/875#issuecomment-414367180):

|   | 100 steps/epoch | 1000 steps/epoch  |
| ------------- | ------------- |------------- |
| **1 GPU** | 2 s/step | 2 s/step |
| **2 GPUs**  | 0.337 s/step  | 0.207 s/step |

Unfortunately, again we can see the same pattern as before. The "fixed" version of @ericj974 is slower than the current official version of @waleedka, even when using 2 GPUs. And still the fastest configuration is the official version with just a single GPU. :unamused:

**Comment by dil** [comment]
@maxfrei750 Currently, my colleague is actively using the other two GPUs. I'll run the tests when they are available and provide updates here.

**Comment by celsisusdegr** [comment]
I have performed some experiments with multiple GPUs, but ran into some issues related to multiprocessing (see https://github.com/matterport/Mask_RCNN/issues/888).

I had a look on what others mentioned above and I am a bit confused about the time measurement per step. Isn't it normal that the time/step for 2 GPUs to be greater or equal than the time/step for 1 GPU?
For 2 GPUs the batch size per step is double the batch per step for 1 GPU, isn't it?

**Comment by maxfrei750** [comment]
@celsisusdegr That could actually be right! At least it would also explain, why increasing `IMAGES_PER_GPU` also increases the time/step. And it is supported by the fact that the accuracy is better, when training with multiple GPUs for the same number of steps (see https://github.com/matterport/Mask_RCNN/issues/875#issuecomment-414640476). I'd love to find the passage in the source code, where the actual batch size is calculated, but after a short search, I couldn't find it. However, I'm going to search it some more after this post. Of course, I'll link it as soon as i find it.

**Comment by celsisusdegr** [comment]
It's computed in mrcnn/config.py:
`self.BATCH_SIZE = self.IMAGES_PER_GPU * self.GPU_COUNT`

**Comment by maxfrei750** [comment]
Great! I was searching in mrcnn/model.py...

As far as I understand you're totally right.

In mrcnn/config.py:
```
...
self.BATCH_SIZE = self.IMAGES_PER_GPU * self.GPU_COUNT
...
```

In mrcnn/model.py:
```
...
train_generator = data_generator(train_dataset, self.config, shuffle=True,
                                    augmentation=augmentation,
                                    batch_size=self.config.BATCH_SIZE,
                                    no_augmentation_sources=no_augmentation_sources)
...
self.keras_model.fit_generator(
    train_generator,
    initial_epoch=self.epoch,
    epochs=epochs,
    steps_per_epoch=self.config.STEPS_PER_EPOCH,
    callbacks=callbacks,
    validation_data=val_generator,
    validation_steps=self.config.VALIDATION_STEPS,
    max_queue_size=100,
    workers=workers,
    use_multiprocessing=True,
)
...
```
From the Keras documentation (see [here](https://keras.io/models/sequential/)):
```
fit_generator(
    generator, 
    steps_per_epoch=None,
    epochs=1, 
    verbose=1, 
    callbacks=None, 
    validation_data=None, 
    validation_steps=None, 
    class_weight=None, 
    max_queue_size=10, 
    workers=1, 
    use_multiprocessing=False, 
    shuffle=True, 
    initial_epoch=0)
```

> **steps_per_epoch**: Integer. Total number of steps (batches of samples) to yield from generator before declaring one epoch finished and starting the next epoch. It should typically be equal to the number of samples of your dataset divided by the batch size. Optional for Sequence: if unspecified, will use the len(generator) as a number of steps.

So the solution to this problem is... that there is no problem... 👍 

I feel like a numpty but at least I was not the only one confused and we were able to sort it out. 😄 Thanks a lot everyone, especially @celsisusdegr.

**Comment by schmidje** [comment]
Hi,

I am still confused here.... 

The keras documentation says for steps per epoch "should typically be equal to the number of samples of your dataset divided by the batch size". If it is the case here, the batch size is larger for a higher number of GPUs and a higher number of images per gpu, hence the number of steps per epoch should be smaller. As a result an epoch should last less time in a multi-GPU setup, leading to a speed-up...!

Is the mask-rcnn implementation different from that perspective?

How can I have change parameters to have the same accuracy as in the single GPU setup with a multi-GPU setup? I understand accuracy is important but I want speed.

Thanks !

**Comment by maxfrei750** [comment]
I can't guarantee that the following explanation is true, as I have not tested it yet, however here are my two cents:
According to the Keras documentation recommendation:
`STEPS_PER_EPOCH = NUMBER_OF_SAMPLES/BATCH_SIZE`
According to the MaskRCNN code:
`BATCH_SIZE = IMAGES_PER_GPU*GPU_COUNT`
That means that:
`STEPS_PER_EPOCH = NUMBER_OF_SAMPLES/(IMAGES_PER_GPU*GPU_COUNT)`

So if you double the `GPU_COUNT` (e.g. from 1 to 2) or the `IMAGES_PER_GPU`respectively, you should halve the `STEPS_PER_EPOCH` to achieve approximately the same accuracy (remember that there is some random stuff going on during the training), while reducing the total training time.

As I said before, I didn't have the time to test this yet.

**Comment by maxfrei750** [comment]
Ok... now I had the time to perform some quick tests. Unfortunately, the results do not look as promising as I had hoped.

Configuration: https://github.com/matterport/Mask_RCNN/issues/875#issuecomment-414343272

Test 1:
=======
GPU_COUNT = 1
IMAGES_PER_GPU = 1
STEPS_PER_EPOCH = 1000
Total time: 155s
loss: 1.0574

Test 2:
=======
GPU_COUNT = 1
IMAGES_PER_GPU = 1
STEPS_PER_EPOCH = 500
Total time: 116s
loss: 1.2042

Test 3:
=======
GPU_COUNT = 2
IMAGES_PER_GPU = 1
STEPS_PER_EPOCH = 500
Total time: 114s
loss: 1.17

Test 4:
=======
GPU_COUNT = 2
IMAGES_PER_GPU = 8
STEPS_PER_EPOCH = 63
Total time: 106s
loss: 2.2320

**Comment by pesekon2** [comment]
Just to show results also from another repo based on this one:

* **Did it work?**
   **no**
 * Number of GPUs (GPU_COUNT)
    2
 * Number of images per GPU (IMAGES_PER_GPU)
    1
 *  GPU model(s)
    4 x GeForce GTX 1080 Ti (crashing when using more than 2 as GPU_COUNT)
 * OS
    Ubuntu 18.04
 * CUDA version
    9.0.176
 * cuDNN version
    7.2.1.38
 * Mask-RCNN version
    Using my own rep derived from this repo
    URL: [repo](https://github.com/ctu-geoforall-lab/i.ann.maskrcnn) ([hash](f88f43c)) (should somehow correspond with this repo at 41e7c59)
 * Tensorflow version
    1.10
 * Keras version
    2.1.3
 * speed (1 GPU)
    6.5 s/step
 * speed (2 GPUs)
    15 s/step
 * comment
    more than two times slower and the loss throughout epochs is very similar to the one from 1 GPU

**Comment by pesekon2** [comment]
With greater number of steps per epoch:

* **Did it work?**
   **yes**
 * Number of GPUs (GPU_COUNT)
    2
 * Number of images per GPU (IMAGES_PER_GPU)
    1
 *  GPU model(s)
    4 x GeForce GTX 1080 Ti (crashing when using more than 2 as GPU_COUNT)
 * OS
    Ubuntu 18.04
 * CUDA version
    9.0.176
 * cuDNN version
    7.2.1.38
 * Mask-RCNN version
    Using my own rep derived from this repo
    URL: [repo](https://github.com/ctu-geoforall-lab/i.ann.maskrcnn) ([hash](f88f43c)) (should somehow correspond with this repo at 41e7c59)
 * Tensorflow version
    1.10
 * Keras version
    2.1.3
 * speed (1 GPU)
    4 s/step
 * speed (2 GPUs)
    7 s/step (=3.5 s/image)

**Comment by schmidje** [comment]
@pesekon2 so, are you able to reach the same training accuracy in less than with two GPUs?
If yes how did you set that?

Thanks!

**Comment by pesekon2** [comment]
@schmidje Well, to be honest, I am not sure about the training accuracy as the loss function is more-less the same. And the result kinda depends on the random crop of the data during each epoch. But for sure I reached faster speed per image. And I finally ran it with 4 GPUs after setting `max_queue_size parameter` from `fit_generator` in `model.py` to 10 and the speed is even better (well, not even times faster than 1 GPU, but still speaking in favour of the usage of 4 GPUs). See my previous comment. 

I have also tried to compare 4 images per GPU with the usage of 1 GPU and 1 image per GPU for the usage of 4 GPUs:  
4 images per GPU with the usage of 1 GPU: 4.25 s/image  
1 image per GPU for the usage of 4 GPUs:  3.25 s/image

**Comment by waleedka** [comment]
I posted this in another thread, but I'll add it here as well as it might help:

* Following Keras convention, an epoch doesn't always mean a full pass through the dataset. Rather, the STEPS_PER_EPOCH config setting allows you to control the number of steps per epoch. You can use small epochs to get more frequent updates in TensorBoard, or you can set it such that it corresponds with a full pass through the dataset.

* BATCH_SIZE = GPU_COUNT * IMAGES_PER_GPU.

* Therefore, images per epoch = STEPS_PER_EPOCH * IMAGES_PER_GPU * GPU_COUNT

* When you increase the GPU_COUNT, you're also increasing the number of images you're training on per epoch. So it's normal for training an epoch to take longer. You're effectively training a larger epoch.

* On Windows, the effect is more obvious. Keras has a feature that allows loading data in parallel on multiple CPU threads, but this doesn't work on Windows due to the way Python threads are implemented. So, most likely, the bottleneck in Windows is in data loading.

**Comment by schmidje** [comment]
@pesekon2 thanks for the information, I will have a look to the suggested modification!
@waleedka thanks for the details but I am still confused how I can achieve the same performance I have now with a single GPU by using my 4 GPUs and get a speed-up. I don't want to improve the accuracy by having a larger epoch, I just want to speed-up things. Based on your comments, should I a simply reduce STEPS_PER_EPOCH by 4 when using 4 GPUs to yield the same #images per epoch and eventually the same training results but with a speed-up?
I hope I make myself clear :(

Thanks!

**Comment by ash1995** [comment]
I have the same question as @schmidje. How can we get the same performance but with a speedup using multiple GPUs? 

@schmidje Were you able to solve this?

**Comment by schmidje** [comment]
Not really. I am still using the single GPU version, and I don't have currently the time to finely tune the batchsize to see if I can get the same accuracy in a faster time.

Maybe my suggestion to simple divide STEPS_PER_EPOCH is sufficient but I did not try it since I cannot have a clear answer : (

**Comment by rbavery** [comment]
@schmidje @ashnair1 did you eventually try out and see speedups by reducing the number of epochs or step size per epoch, proportional to GPU_COUNT? I'll be trying this out soon but curious what I should expect.

**Comment by ppwwyyxx** [comment]
Regardless of number of epochs or step size per epoch, you can just look at how much time each step takes and compute the throughput (img/s). Some benchmark numbers can be seen at [here](https://github.com/tensorpack/benchmarks/tree/master/MaskRCNN).

**Comment by travishsu** [comment]
Turning off validation and adopting #1611 give me significant speed improvement, give a try!

**Comment by Adblu** [comment]
Did it work?
    YES !
    Number of GPUs (GPU_COUNT)
    8
    Number of images per GPU (IMAGES_PER_GPU)
    2
    GPU model(s)
    8 x K80
    OS
    Ubuntu 18.04 on EC2 AWS
    CUDA version
    10.0
    cuDNN version
    7.1.4
    Driver version
    440.59
    Mask-RCNN version
    URL: 3deaec5
    Tensorflow version
    1.13.1
    Keras version
    2.1.3
    speed (8 GPUs)
   9 s/step
