### ISSUE TITLE
Questions on Masks and class  predictions

### ISSUE THREAD

**Issue by Walid-Ahmed** [matterport/Mask_RCNN#88]
Hello,

In prediction  stage, I have these questions:-

1-How can the FCN responsible for predicting masks deal with the different dimensions of the ROI?
and how m×m floating-number mask output is resized to the RoI size?

2- It seems that the classification does not benefit from segmentation at all, as the authors decoupled segmentation  and classification. I assumed better results will be from classification of a segment without any irrelevant pixels. Am i missing something?
May be "indirectly" as we try to improve segmentation results we will be forced to improve the detection results as the regions proposals should become more efficient  and this outputted better results than feeding segment to classifier in a cascade manner. After all the losses is the aggregation of masking,classification and detection.

Thanks

**Comment by waleedka** [comment]
Your questions in #1 are answered in the [Mask R-CNN paper](https://arxiv.org/abs/1703.06870). Look for the section about ROIAlign. You might want to check [this presentation](http://kaiminghe.com/iccv17tutorial/maskrcnn_iccv2017_tutorial_kaiminghe.pdf) from the author. They have a couple of slides about the masks.

For #2, it's also addressed in the paper. The benefit is indirect as you mentioned.
