### ISSUE TITLE
Have anyone trained on Cityscapes dataset ?

### ISSUE THREAD

**Issue by Nirvana93** [matterport/Mask_RCNN#891]

**Comment by fastlater** [comment]
In #774 someone mentioned. I guess some people did since that dataset is large enough and already prepared.

**Comment by waleedka** [comment]
I believe Cityscapes includes semantic segmentation, not instance segmentation. In other words, all cars are marked with the same "car" label. Mask RCNN requires that each instance of an object is marked individually (e.g. car1, car2, car3, ....etc.). So this model cannot be used with Cityscapes.

**Comment by jinfagang** [comment]
@waleedka Indeed cityscapes provide instance level label. But after I try, result seems bad

**Comment by davidchuyaya** [comment]
@waleedka 
Doesn't the [dataset](https://www.cityscapes-dataset.com/dataset-overview/#labeling-policy) state that 
> * Single instance annotations are available. However, if the boundary between such instances cannot be clearly seen, the whole crowd/group is labeled together and annotated as group, e.g. car group.
And the repo of [scripts](https://github.com/mcordts/cityscapesScripts) has this option:
> preparation/createTrainIdInstanceImgs.py convert annotations in polygonal format to png images with instance IDs, where pixels encode instance IDs composed of "train IDs".

**Comment by JoltonDsouza** [comment]
> @waleedka
> Doesn't the [dataset](https://www.cityscapes-dataset.com/dataset-overview/#labeling-policy) state that
> 
> > Single instance annotations are available. However, if the boundary between such instances cannot be clearly seen, the whole crowd/group is labeled together and annotated as group, e.g. car group.
> 
> And the repo of [scripts](https://github.com/mcordts/cityscapesScripts) has this option:
> `preparation/createTrainIdInstanceImgs.py` convert annotations in polygonal format to png images with instance IDs, where pixels encode instance IDs composed of "train IDs".

@davidchuyaya When you say the png images have pixelwise encoding according to the trainIDs, how do we further use it for training? Is there a way to visualize that the classes are having the particular IDs?

**Comment by SaidaSaad** [comment]
Anyone know if there captions of descriptions available for Cityscapes dataset ?
