### ISSUE TITLE
AssertionError  when I run  inspect_model.py 

### ISSUE THREAD

**Issue by HMHY2** [matterport/Mask_RCNN#893]
When I run the RPN graph and display its predictions in inspect_model.py, there is such a error:
the error lines in ` ("post_nms_anchor_ix", nms_node)` How can I debug it?

`AssertionError                            Traceback (most recent call last)
<ipython-input-105-20b8e42bbf9f> in <module>()
     13     ("refined_anchors_clipped", model.ancestor(pillar, "ROI/refined_anchors_clipped:0")),
     14     ("post_nms_anchor_ix", nms_node),
---> 15     ("proposals", model.keras_model.get_layer("ROI").output),
     16 ])

~/anaconda3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py in run_graph(self, images, outputs, image_metas)
   2692         outputs = OrderedDict(outputs)
   2693         for o in outputs.values():
-> 2694             assert o is not None
   2695 
   2696         # Build a Keras function to run parts of the computation graph

AssertionError: `

**Comment by HMHY2** [comment]
The code is attached below：

`# Run RPN sub-graph
pillar = model.keras_model.get_layer("ROI").output  # node to start searching from
 
# TF 1.4 introduces a new version of NMS. Search for both names to support TF 1.3 and 1.4
nms_node = model.ancestor(pillar, "ROI/rpn_non_max_suppression:0")
if nms_node is None:
    nms_node = model.ancestor(pillar, "ROI/rpn_non_max_suppression/NonMaxSuppressionV2:0")
 
rpn = model.run_graph([image], [
    ("rpn_class", model.keras_model.get_layer("rpn_class").output),
    ("pre_nms_anchors", model.ancestor(pillar, "ROI/pre_nms_anchors:0")),
    ("refined_anchors", model.ancestor(pillar, "ROI/refined_anchors:0")),
    ("refined_anchors_clipped", model.ancestor(pillar, "ROI/refined_anchors_clipped:0")),
    ("post_nms_anchor_ix", nms_node),
    ("proposals", model.keras_model.get_layer("ROI").output),
])`

**Comment by keineahnung2345** [comment]
Do you use TF1.9+? You could check my PR: https://github.com/matterport/Mask_RCNN/pull/876/commits/c61909a392e5f124e756140903aa34c093e95cfb, it provides workaround to the problem of different version of NonMaxSuppression.

**Comment by waleedka** [comment]
@keineahnung2345 's PR is merged, so I'm closing this issue.

**Comment by keineahnung2345** [comment]
@waleedka Thank you!

**Comment by pkugyf** [comment]
Change the V2:0 to V3:0 in line
nms_node = model.ancestor(pillar, "ROI/rpn_non_max_suppression/NonMaxSuppressionV2:0")
can solve it
