### ISSUE TITLE
AssertionError in  "1.b RPN Predictions" within  inspect_model.ipynb

### ISSUE THREAD

**Issue by PengTedShen** [matterport/Mask_RCNN#92]
# Run RPN sub-graph
pillar = model.keras_model.get_layer("ROI").output  # node to start searching from
rpn = model.run_graph([image], [
    ("rpn_class", model.keras_model.get_layer("rpn_class").output),
    ("pre_nms_anchors", model.ancestor(pillar, "ROI/pre_nms_anchors:0")),
    ("refined_anchors", model.ancestor(pillar, "ROI/refined_anchors:0")),
    ("refined_anchors_clipped", model.ancestor(pillar, "ROI/refined_anchors_clipped:0")),
    ("post_nms_anchor_ix", model.ancestor(pillar, "ROI/rpn_non_max_suppression:0")),
    ("proposals", model.keras_model.get_layer("ROI").output),
])

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-30-b40a13f2b82a> in <module>()
      7     ("refined_anchors_clipped", model.ancestor(pillar, "ROI/refined_anchors_clipped:0")),
      8     ("post_nms_anchor_ix", model.ancestor(pillar, "ROI/rpn_non_max_suppression:0")),
----> 9     ("proposals", model.keras_model.get_layer("ROI").output),
     10 ])

~\Mask_RCNN\model.py in run_graph(self, images, outputs)
   2295         outputs = OrderedDict(outputs)
   2296         for o in outputs.values():
-> 2297             assert o is not None
   2298 
   2299         # Build a Keras function to run parts of the computation graph

AssertionError:

**Comment by waleedka** [comment]
Is this similar to this other issue https://github.com/matterport/Mask_RCNN/issues/23 ?

**Comment by PengTedShen** [comment]
Yes , thank you , after I changed to : 
    ("post_nms_anchor_ix", model.ancestor(pillar, "ROI/rpn_non_max_suppression/NonMaxSuppressionV2:0")),

it solved this issue
