### ISSUE TITLE
Faster RCNN from the original implementation (with results)

### ISSUE THREAD

**Issue by gaborvecsei** [matterport/Mask_RCNN#922]
Hi all,
I tried to just quickly remove the mask part, so we can use it for object detection easily.
Unfortunately I got very bad results for the simple shapes dummy dataset.

Implementation:
[https://github.com/gaborvecsei/Dirty-Keras-Faster-RCNN](https://github.com/gaborvecsei/Dirty-Keras-Faster-RCNN)

Result:
![image](https://user-images.githubusercontent.com/18753533/45360952-395d2c80-b5d1-11e8-9748-c41580603f18.png)

Could you give me hints why is it happening? Maybe the removal of the code was too fast 🤔 😢

**Comment by ApoorvaSuresh** [comment]
Hi,
how did you remove the mask part?
