### ISSUE TITLE
load_image_gt data augmentation not doing anything

### ISSUE THREAD

**Issue by jremillard** [matterport/Mask_RCNN#94]
The augment parameter is using random.randint(0,1), which always returns 0. The images are never getting flipped. It should be random.randint(0,2) in modely.py

**Comment by waleedka** [comment]
I double checked this and I think it works correctly. 

```
>>> import random
>>> 
>>> random.randint(0,1)
1
>>> random.randint(0,1)
1
>>> random.randint(0,1)
1
>>> random.randint(0,1)
0
>>> random.randint(0,1)
0
>>> random.randint(0,1)
0
>>> random.randint(0,1)
0
>>> random.randint(0,1)
1
```

**Comment by jremillard** [comment]
Sorry about that, I was testing it with numpy.random.randint, not random.randint....
