### ISSUE TITLE
AttributeError: 'list' object has no attribute 'read' (getOpenFileName)

### ISSUE THREAD

**Issue by nayzen** [matterport/Mask_RCNN#951]
Hi all,

I am trying to use a Gui Interface (PyQt) to load an image, and launch the detection on it through a button.
But when I select my image, it displays this error:

![problem2](https://user-images.githubusercontent.com/37196095/45816917-5f738280-bcdd-11e8-9cc6-3db8a8c34390.PNG)

My code for this is:

![problem1](https://user-images.githubusercontent.com/37196095/45816920-626e7300-bcdd-11e8-96e7-e3dfe0a4b7ff.PNG)

I don't know how to convert the "list" file (fileName) to the corresponding input for the network.
Sorry, I'm a beginner in Python.

EDIT: It works with the commented line:
`filePath = os.path.join(IMAGE_DIR, 'image56.jpg')`
But I want to load my image through the "getOpenFileName" :(

Regards,
Antoine

**Comment by nayzen** [comment]
?

**Comment by nayzen** [comment]
I solved my problem. It was because I wrote "**GetOpenFileNames**" and it was "**GetOpenFileName**".

**Comment by GouravVashistha** [comment]
Hey bro, how you can solve this problem??????

**Comment by Jhomar1158-ux** [comment]
**(SOLVED)** I had the same Error **AttributeError: 'list' object has no attribute 'read'** in Django, I uninstalled a package called "subprocess.run" with "pip uninstall [package-name]" and that's all. You can run your project ✔

**Comment by Troy-Boy** [comment]
> **(SOLVED)** I had the same Error **AttributeError: 'list' object has no attribute 'read'** in Django, I uninstalled a package called "subprocess.run" with "pip uninstall [package-name]" and that's all. You can run your project ✔

@Jhomar1158-ux Hey stranger, thanks a lot for that I had troubles with virtual environment and pip having error when installing. Your answer is the only thing that work after countless hours of reading doc and trying to pinpoint the error.

**Comment by OhamsEmeka** [comment]
> **(SOLVED)** I had the same Error **AttributeError: 'list' object has no attribute 'read'** in Django, I uninstalled a package called "subprocess.run" with "pip uninstall [package-name]" and that's all. You can run your project ✔

bro you are the best thank you for leaving this here, after countless hours of trying to fix that error. You are the best. God bless you
