### ISSUE TITLE
Display Samples doesn't work properly

### ISSUE THREAD

**Issue by eyildiz-ugoe** [matterport/Mask_RCNN#952]
The following piece of code taken from the inspection file: 

```
# Load and display random samples
image_ids = np.random.choice(dataset.image_ids, 4)
for image_id in image_ids:
    image = dataset.load_image(image_id)
    mask, class_ids = dataset.load_mask(image_id)
    visualize.display_top_masks(image, mask, class_ids, dataset.class_names)
```

for me results with nonsensical classification of my data:

![1](https://user-images.githubusercontent.com/35396058/45821521-bbdc9f00-bce9-11e8-95ff-dfe0e2c1a331.png)

I did specify 4 classes, yet there only 2 of them appear. On top of that, although the annotations had the same name (screw), their colors are different (look at the screw masks, having different color each). And I have no idea about the last two coloumn at all, like why are they even there if there isn't anything to show. And BG (background) is definitely messed up since it shows other components, like it makes no sense.

This is how I added my classes:

```
        # Add classes.
        self.add_class("components", 1, "screw")
        self.add_class("components", 2, "motor_contacts")
        self.add_class("components", 3, "head_contacts")
        self.add_class("components", 4, "pcb")
```
and it already outputs 5 classes when I print the number of classes. So it's not here which is messed up.

But anyway, there is something which is definitely wrong with this. 

Did someone experience the same?

**Comment by eyildiz-ugoe** [comment]
This part of the code has to be extended and more classes have to be added:

        class_ids = np.zeros([len(info["polygons"])])
        # In the components dataset, pictures are labeled with name 'screw' and 'lid' representing arm and ring.
        for i, p in enumerate(class_names):
            # "name" is the attributes name decided when labeling, etc. 'region_attributes': {name:'a'}
            if p['name'] == 'screw':
                class_ids[i] = 1
            elif p['name'] == 'lid':
                class_ids[i] = 2
                # assert code here to extend to other labels

**Comment by manaswakchaure** [comment]
I am getting following error can you help me out

IndexError                                Traceback (most recent call last)
/tmp/ipykernel_15359/1218656515.py in <module>
      4     image = dataset.load_image(image_id)
      5     mask, class_ids = dataset.load_mask(image_id)
----> 6     visualize.display_top_masks(image, mask, class_ids, dataset.class_names)

~/project/onion_leat_model_train/mrcnn/visualize.py in display_top_masks(image, mask, class_ids, class_names, limit)
    299         m = np.sum(m * np.arange(1, m.shape[-1] + 1), -1)
    300         to_display.append(m)
--> 301         titles.append(class_names[class_id] if class_id != -1 else "-")
    302     display_images(to_display, titles=titles, cols=limit + 1, cmap="Blues_r")
    303 

IndexError: list index out of range
