### ISSUE TITLE
Can not import COCO

### ISSUE THREAD

**Issue by rajubuet24** [matterport/Mask_RCNN#953]
My platform is windows 10. python 3.6

I tried the following steps: 1) cloned: "git clone https://github.com/cocodataset/cocoapi.git". 2) converted python to to 3 by typing this: "2to3 . -w" 3) then in the terminal typed "python setup.py install"

Now I am having error like this:

C:\VS2017\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\mk5n2\AppData\Local\Continuum\anaconda3\envs\tf_keras_env\lib\site-packages\numpy\core\include -I../common -IC:\Users\mk5n2\AppData\Local\Continuum\anaconda3\envs\tf_keras_env\include -IC:\Users\mk5n2\AppData\Local\Continuum\anaconda3\envs\tf_keras_env\include -IC:\VS2017\VC\Tools\MSVC\14.15.26726\ATLMFC\include -IC:\VS2017\VC\Tools\MSVC\14.15.26726\include "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.6\Release../common/maskApi.obj -Wno-cpp -Wno-unused-function -std=c99 cl : Command line error D8021 : invalid numeric argument '/Wno-cpp' error: command 'C:\VS2017\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe' failed with exit status 2

what shoud I do?

**Comment by waleedka** [comment]
This works for me:
```
pip3 install git+https://github.com/waleedka/coco.git#subdirectory=PythonAPI
```

**Comment by rajubuet24** [comment]
Thanks. My problem has been solved. I followed the steps provided by Mark in the following link:
https://github.com/markjay4k/Mask-RCNN-series/blob/master/Mask_RCNN%20Install%20Instructions.ipynb
