### ISSUE TITLE
Do we need both instance masks and bounding boxes?

### ISSUE THREAD

**Issue by amin07** [matterport/Mask_RCNN#955]
I have a set of images and png masks of each image. Interested in only one class. When I create tfrecord, should I provide both bounding box and masks? or only mask will be enough?

**Comment by fastlater** [comment]
Mask RCNN works slightly different than other projects that probably you worked before. Here, you only need the original images + masks per image.
How to load the masks? Well, each user has a different dataset so it is slightly different case by case.

**Comment by amin07** [comment]
Thanks
