### ISSUE TITLE
Error while training the balloon.py file from the command line

### ISSUE THREAD

**Issue by aakashkodes** [matterport/Mask_RCNN#979]
![image](https://user-images.githubusercontent.com/41433168/46067395-07260000-c177-11e8-9752-f836cd8bc18d.png)

While I am trying to implement the balloon model, I couldn't train the balloon.py file.
I always get this error  "FileNotFoundError: [Errno 2] No such file or directory: '/path/to/balloon/dataset\\train\\via_region_data.json'".
I have the balloon dataset stored in the root directory of the project.
Can someone please help me out with this issue.

**Comment by aakashkodes** [comment]
I fixed it. Realized that one should give the own path containing the  data-set instead of the default one. My bad.

**Comment by flit86** [comment]
@aakashkodes hi. i have the same error. can you help me? 
how you fixed it?
many thx

**Comment by xiaobaiaaaaa** [comment]
> @aakashkodes hi. i have the same error. can you help me? how you fixed it? many thx

Click on this error, and then add your path
