### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by eyildiz-ugoe** [matterport/Mask_RCNN#982]
If you have 11 classes, you get the following error when you want to visualize:

```
Traceback (most recent call last):
  File "detection.py", line 49, in <module>
    class_names, p['scores'], colors=colors, real_time=True)
  File "/usr/local/lib/python3.5/dist-packages/mask_rcnn-2.1-py3.5.egg/mrcnn/visualize.py", line 136, in display_instances
IndexError: list index out of range
```

Here is how I  try to visualize in the code:

```
    images_path = os.path.join(PREDICTION_DATA_PATH, '*.jpg')
     files = glob.glob(images_path)
     images = []
     counter = 0
     for f1 in files:
         img = cv2.imread(f1)
         predictions = model.detect([img], verbose=1)  # We are replicating the same image to fill up the batch_size
         p = predictions[0]
         output = visualize.display_instances(img, p['rois'], p['masks'], p['class_ids'],
                                     class_names, p['scores'], colors=colors, real_time=True)
         cv2.imwrite(os.path.join(OUTPUT_PATH , str(counter) + '.jpg'), output)
         counter += 1
         k = cv2.waitKey(10)
         if k & 0xFF == ord('q'):
             break
     cv2.destroyAllWindows()

```

and here is the function in which the error is occurring:

```
def display_instances(image, boxes, masks, class_ids, class_names,
                      scores=None, title="",
                      figsize=(16, 16), ax=None,
                      show_mask=True, show_bbox=True,
                      colors=None, captions=None):
    """
    boxes: [num_instance, (y1, x1, y2, x2, class_id)] in image coordinates.
    masks: [height, width, num_instances]
    class_ids: [num_instances]
    class_names: list of class names of the dataset
    scores: (optional) confidence scores for each box
    title: (optional) Figure title
    show_mask, show_bbox: To show masks and bounding boxes or not
    figsize: (optional) the size of the image
    colors: (optional) An array or colors to use with each object
    captions: (optional) A list of strings to use as captions for each object
    """
    # Number of instances
    N = boxes.shape[0]
    if not N:
        print("\n*** No instances to display *** \n")
    else:
        assert boxes.shape[0] == masks.shape[-1] == class_ids.shape[0]

    # If no axis is passed, create one and automatically call show()
    auto_show = False
    if not ax:
        _, ax = plt.subplots(1, figsize=figsize)
        auto_show = True

    # Generate random colors
    colors = colors or random_colors(N)

    # Show area outside image boundaries.
    height, width = image.shape[:2]
    ax.set_ylim(height + 10, -10)
    ax.set_xlim(-10, width + 10)
    ax.axis('off')
    ax.set_title(title)

    masked_image = image.astype(np.uint32).copy()
    for i in range(N):
        color = colors[i]

        # Bounding box
        if not np.any(boxes[i]):
            # Skip this instance. Has no bbox. Likely lost in image cropping.
            continue
        y1, x1, y2, x2 = boxes[i]
        if show_bbox:
            p = patches.Rectangle((x1, y1), x2 - x1, y2 - y1, linewidth=2,
                                alpha=0.7, linestyle="dashed",
                                edgecolor=color, facecolor='none')
            ax.add_patch(p)

        # Label
        if not captions:
            class_id = class_ids[i]
            score = scores[i] if scores is not None else None
            label = class_names[class_id]
            x = random.randint(x1, (x1 + x2) // 2)
            caption = "{} {:.3f}".format(label, score) if score else label
        else:
            caption = captions[i]
        ax.text(x1, y1 + 8, caption,
                color='w', size=11, backgroundcolor="none")

        # Mask
        mask = masks[:, :, i]
        if show_mask:
            masked_image = apply_mask(masked_image, mask, color)

        # Mask Polygon
        # Pad to ensure proper polygons for masks that touch image edges.
        padded_mask = np.zeros(
            (mask.shape[0] + 2, mask.shape[1] + 2), dtype=np.uint8)
        padded_mask[1:-1, 1:-1] = mask
        contours = find_contours(padded_mask, 0.5)
        for verts in contours:
            # Subtract the padding and flip (y, x) to (x, y)
            verts = np.fliplr(verts) - 1
            p = Polygon(verts, facecolor="none", edgecolor=color)
            ax.add_patch(p)
    ax.imshow(masked_image.astype(np.uint8))
    if auto_show:
        plt.show()
```

**Comment by keineahnung2345** [comment]
How do you set `colors ` before you call `visualize.display_instances `?

**Comment by eyildiz-ugoe** [comment]
I don't set anything, this is the code that is officially released by the authors.

**Comment by eyildiz-ugoe** [comment]
Setting it to `colors=None` solves the problem for now. Don't know why though.

**Comment by nooriahmed** [comment]
I am also facing the same issue of IndexError: list index out of range, I have two classes with background
the Mask_load function is given here as follows, my dataset contains grayscale images. i am seeking help. please correct me, Regards
def load_mask(self, imageID):
		# grab the image info and derive the full annotation path
		# file path
		info = self.image_info[imageID]
		filename = info["id"].split(".")[0]
		#print(filename)
		annotPath = os.path.sep.join([MASKS_PATH,
			"{}_mask.png".format(filename)])
		print(annotPath)
		# load the annotation mask and resize it, *making sure* to
		# use nearest neighbor interpolation
		annotMask = cv2.imread(annotPath)
		annotMask = cv2.split(annotMask)[0]
		#print(annotPath)
		#print(annotMask)
		annotMask = imutils.resize(annotMask, width=self.width,
			inter=cv2.INTER_NEAREST)
		annotMask[annotMask > 0] = 1

		# determine the number of unique class labels in the mask
		classIDs = np.unique(annotMask)

		# the class ID with value '0' is actually the background
		# which we should ignore and remove from the unique set of
		# class identifiers
		classIDs = np.delete(classIDs, [0])

		# allocate memory for our [height, width, num_instances]
		# array where each "instance" effectively has its own
		# "channel" -- since there is only one lesion per image we
		# know the number of instances is equal to 1
		masks = np.zeros((annotMask.shape[0], annotMask.shape[1], 1),
			dtype="uint8")

		# loop over the class IDs
		for (i, classID) in enumerate(classIDs):
			# construct a mask for *only* the current label
			classMask = np.zeros(annotMask.shape, dtype="uint8")
			classMask[annotMask == classID] = 1

			# store the class mask in the masks array
			masks[:, :, i] = classMask

		# return the mask array and class IDs
		return (masks.astype("bool"), classIDs.astype("int32"))

**Comment by angyee** [comment]
share the inference file for same

**Comment by geobowen** [comment]
I solved it by adding 'BG' to the class_names
`class_names = ['BG','yourclass', 'yourclass', 'yourclass']`
check the explanation through this link
[https://stackoverflow.com/questions/50229639/list-index-out-of-range-in-visualize-cv2-py](url)
it says that the problem is it needs a class at index 0 for the background, and your class new defined classes start at index 1 onwards.

**Comment by YashRunwal** [comment]
@pullulation I did that and I am still getting that error

**Comment by er1czz** [comment]
For anyone encounter this error while using detectron2 (latest implementation of Mask RCNN)

This error can be addressed by a proper configuration setting.
You can mandate the number of class by `cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3` (for example, 3 classes)

Then map the corresponding class name as follows
```
md = MetadataCatalog.get(cfg.DATASETS.TEST[0])
md.set(thing_classes=["class0", "class1",  "class2" ])
```
