### ISSUE TITLE
talk about drivable area segmentation with mask-rcnn

### ISSUE THREAD

**Issue by pandamax** [matterport/Mask_RCNN#983]
Here is the experimental result about drivable area segmentation with mask-rcnn, the test frame rate is 3-4 , I would like to ask about any good implementation of network acceleration.

Test Video:
```
https://youtu.be/S0Rkgh652UU
https://youtu.be/iXNGM1gDyH8
https://youtu.be/Ab0yaGYZO9I
```

**Comment by waleedka** [comment]
Nice work! What dataset did you use for training? 

To speed up the inference, you can probably try one of these ideas:
- Smaller input images. Drivable area should be easy to detect even on low resolution
- Eliminate small anchors since you probably don't need to detect small drivable areas

**Comment by pandamax** [comment]
Thanks a lot  for your comments. Yep,  I have adopted the second method that you suggested.And now I try to combine mask-rcnn and mobileNet or shuffleNet. In the drivable area segmentation task, I guess that the image's rgb three-channel input information is very redundant, so maybe it is enough to use grayscale information as input.In the follow-up improvement experiment, your suggestions will be considered and adopted. yeah, the  dataset I use is from [http://bdd-data.berkeley.edu/](url).

**Comment by zhangbaoj** [comment]
Could you send your dataset to me? I also do the drivable eara. But I failed to change the BDD100K to the format like COCO. My e-mail is 1154843512@qq.com. Thank you very much.

**Comment by nvnnghia** [comment]
@zhangbaoj  check this out: https://github.com/eric612/BDD100k-toolkit
