### ISSUE TITLE
InvalidArgumentError (see above for traceback): Incompatible shapes: [6,8,8,256] vs. [6,7,7,256]

### ISSUE THREAD

**Issue by a6225301** [matterport/Mask_RCNN#992]
![image](https://user-images.githubusercontent.com/22911232/46281783-32a75100-c5a2-11e8-8361-bb03a49c887b.png)

Hello, when i train the model on my own model, i came across this issue,  and the detailed configuration is as below, can anyone help?  ps: keras (2.1.5)   tensorflow (1.4.0)
![image](https://user-images.githubusercontent.com/22911232/46282003-f9231580-c5a2-11e8-9277-811e36ce8237.png)

**Comment by SmritiBahuguna** [comment]
Hi @a6225301
Were you able to fix this?

**Comment by a6225301** [comment]
@SmritiBahuguna not yet

**Comment by keineahnung2345** [comment]
IMAGE_MIN_DIM and IMAGE_MIN_DIM should be multiple of 64. 
Ref: https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/config.py#L106.

**Comment by a6225301** [comment]
Hi，thank you for the responses. I reinstall my coding environment based on the Readme, and the model has been worked well. I think this problem is caused by the packages' versions.
